### ISSUE TITLE
Mapy

### ISSUE THREAD

**Issue by wawryk** [lmsgit/lms#1017]
Nie działąją mi filtry na mapie (ten plus w prawym górnym rogu), dokładnie chpodzi o ?m=netdevmap

![image](https://cloud.githubusercontent.com/assets/15612188/20710941/454620dc-b63d-11e6-9b99-f74418b1099b.png)

**Comment by kosaa** [comment]
sprawdzilem na windowsie i linuxie na chrome i mozilli - wszystko ok, a w logach brak informacji o bledach

Masz coś w logach?

**Comment by wawryk** [comment]
Wybaczcie, pośpieszyłem się. Coś u mnie w operze tylko.
Zamykam
