### ISSUE TITLE
Zakładka "konto klienta" na karcie klienta brak datatables

### ISSUE THREAD

**Issue by wawryk** [lmsgit/lms#1026]
Mam dosyć nietypowy błąd, na karcie klienta nie załadowało mi się datatables ale nigdzie w logach nie widzę błędów.
Korzystam z aktualnego stable, wszystko wykonane zgodnie z instrukcją ;) 

![image](https://cloud.githubusercontent.com/assets/15612188/21010958/2f17493a-bd4f-11e6-9aca-0f8780a5704e.png)

a tutaj karta innego klienta: 
![image](https://cloud.githubusercontent.com/assets/15612188/21011025/8d359fc6-bd4f-11e6-9d7a-bd30f0c85fef.png)

dokładnie to chodzi o to że ładują mi się wszystkie płatności klienta naraz i to trwa dość długo

**Comment by chilek** [comment]
To już było na liście mailingowej lms plus. Poszukaj pod kątem phpui.datatables_max_records (domyślnie 300).

**Comment by wawryk** [comment]
Dzięki za szybką pomoc
