### ISSUE TITLE
Czy potrzebujemy szablony dla "Issues" i "Pull requests"?

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#1041]
Helping people contribute to your project:
- [Creating an issue template for your repository](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)
- [Creating a pull request template for your repository](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

Przykład wykorzystania: https://github.com/librenms/librenms

**Comment by interduo** [comment]
Fajne!

**Comment by kosaa** [comment]
Issue template - TAK!
