### ISSUE TITLE
Font-awesome lub inna opcja do celem zastąpienia obecnych ikonek

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#1042]
Kolejne podjeście do zastąpienia obecnych szkaradnych ikonek jednolitymi ikonkami font-awesome lub inną alternatywą.

Co o tym myślicie?

**Comment by interduo** [comment]
Tak! jest dużo fajnych projektów na githubie z UI/UX. Inne też przegladałeś?

**Comment by kosaa** [comment]
trzeba zrobic warstwe posrednia pomiedzy wyswietlaniem a konkretną ikoną (font awesome lub png), aby bez zmiany szablonów LMS mozna bylo podmieniac cale zestawy ikon

potrzeba zrobic zestaw klas CSS ktore beda sie odwolywac do konkretnych wywolan np. font awesome

wiem ze jest na to zielone swiatlo

**Comment by chilek** [comment]
@kyob: już o tym pisaliśmy. Jak najbardziej tak, ale podobnie jak dla ikon menu głównego (co się sprawdziło i nikt nie narzekał!)

**Comment by chilek** [comment]
Migracja jest już dość zaawansowana. Systematycznie rezygnujemy ze starych ikonek w postaci obrazków.
