### ISSUE TITLE
Smarty: Unable to load template 'extendsall:header.html'

### ISSUE THREAD

**Issue by prezesk** [lmsgit/lms#1044]
Witam,
Nowa instalacja centos7. Repozytorium pobrane z github.
Podczas pierwszego uruchomienia brak error 500 brak Panelu do zalogowania 
W error logu pojawia się: 
 PHP Fatal error:  Uncaught  --> Smarty: Unable to load template 'extendsall:header.html' <-- \n  thrown in /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 185.
Podczas instalacji smarty instalują się w wersji 3.1.31 
Jakieś pomysły co mogę źle robić?

**Comment by prezesk** [comment]
Jakies pomysly? Czy ktos kozysta z centos dla lms? czy debian jest docelowym systemem?

**Comment by prezeskk** [comment]
Ja używam Slackware i problemów nie ma. Może czegoś brakuje w instalacji?

**Comment by ciapol** [comment]
Composer update zrobiłeś z poziomu głównego katalogu LMS?29 sty 2017 11:56 Krzysztof Kulesza <notifications@github.com> napisał(a):Ja używam Slackware i problemów nie ma. Może czegoś brakuje w instalacji?

**Comment by prezesk** [comment]
Zrobiłem na nowo clona z git.  git clone https://github.com/lmsgit/lms.git
uruchomiłem: composer update ze ściągniętego katalogu.
Dostałem:
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 14 installs, 0 updates, 0 removals
  - Installing phine/exception (1.0.0) Loading from cache
  - Installing phine/observer (2.0.0) Loading from cache
  - Installing components/normalize.css (3.0.3) Loading from cache
  - Installing smarty/smarty (v3.1.31) Loading from cache
  - Installing rospdf/pdf-php (0.12.22) Loading from cache
  - Installing xdan/datetimepicker (2.5.4) Loading from cache
  - Installing phpmailer/phpmailer (v5.2.22) Loading from cache
  - Installing tecnickcom/tcpdf (6.2.12) Loading from cache
  - Installing spipu/html2pdf (v4.6.1) Loading from cache
  - Installing components/jquery (3.1.1) Loading from cache
  - Installing components/jqueryui (1.12.1) Loading from cache
  - Installing datatables/datatables (1.10.13) Loading from cache
  - Installing setasign/fpdi (1.6.1) Loading from cache
  - Installing setasign/fpdi-tcpdf (1.6.1) Loading from cache
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Google XOAUTH2 authentication)
spipu/html2pdf suggests installing fagundes/zff-html2pdf (zff-html2pdf module ~0.1.1, if you need to integrate HTML2PDF with Zend Framework 2 (zf2))
setasign/fpdi suggests installing setasign/fpdf (FPDI will extend this class but as it is also possible to use "tecnickcom/tcpdf" as an alternative there's no fixed dependency configured.)
setasign/fpdi suggests installing setasign/fpdi-fpdf (Use this package to automatically evaluate dependencies to FPDF.)
Package phine/exception is abandoned, you should avoid using it. No replacement was suggested.
Package phine/observer is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
> sed -i -e 's/class HTML2PDF_myPdf extends TCPDF/class HTML2PDF_myPdf extends LMSTCPDF/' vendor/spipu/html2pdf/_class/myPdf.class.php
> sed -i -e 's/\(\s\+\)register_shutdown_function/\1\/\/register_shutdown_function/' vendor/tecnickcom/tcpdf/tcpdf.php
> cp -f lib/ezpdf/fonts/arial* vendor/rospdf/pdf-php/src/fonts

nie mam pomysłu gdzie szukać błędu. Jedyne co udało mi się znaleźć w logu od http error i jest to to co wrzuciłem powyżej. Są jeszcze jakieś miejsca gdzie należy szukać błędu czego systemowi brakuje co jest nie tak?
