### ISSUE TITLE
lms-sendinvoices.php

### ISSUE THREAD

**Issue by Pinki18** [lmsgit/lms#1045]
Po uruchomieniu lms-sendinvoices.php wiadomości wysyłane są przez konto ustawione w konfiguracji w sekcji [mail]. To co jest ustawione w sekcji [sendinvoices] jest ignorowane. Problem dotyczy tylko ustawień konta pocztowego, inne ustawienia wydają się być poprawnie przekazywane.

LMS 1.11-git (najnowsza wersjia)
DB: 2016122100
Wersja MySQL: 5.5.53-0+deb7u1-log
Wersja PHP: 5.4.45-0+deb7u6
Wersja Smarty: 3.1.31

**Comment by chilek** [comment]
Nieaktualne.
