### ISSUE TITLE
lms-notify.php => "Mailer Error: Message body empty"

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#1046]
```bash
lms-notify.php -t warnings
```
**Wynik:**
[mail/warnings] JAN KOWALSKI  (4322): test@alfa-system.pl
string(32) "Mailer Error: Message body empty"

Coś nie działa czy czegoś mi brakuje?

Testuje na lmsgit/master wersja sprzed 5 minut.

**Comment by chilek** [comment]
pewnie miałeś puste mail_body dla danego typu powiadomień.
