### ISSUE TITLE
LMSHtmlDocument.php => Cannot modify header information 

### ISSUE THREAD

**Issue by alkar1** [lmsgit/lms#1049]
Warning: Cannot modify header information - headers already sent in /var/www/lms/lib/LMSDocuments/LMSHtmlDocument.php on line 52 ( i w linii 54 ).
Objaw po wybraniu Finanse -> Rejestr Kasowy - > Drukuj ( na dole wykazu dokumentów).
Drukowanie pojedynczego dokumentu poprzez ikonę po prawej stronie bez problemu.
Konfiguracja -> Lms UI -> [receipts]  standardowa.
LMS 011120 , Debian 8.2

**Comment by interduo** [comment]
Nie potwierdzam - problem jaki widzę jedyny to to że można kliknąć drukuj w przypadku niewybranego dokumentu - w wyniku czego otrzymujemy pustą stronę.

**Comment by chilek** [comment]
Zapewne nieaktualne.
