### ISSUE TITLE
problem z postgres.2017013100.php

### ISSUE THREAD

**Issue by wawryk** [lmsgit/lms#1083]
Wystąpiły błędy w obsłudze bazy danych!
Zapytanie: INSERT INTO addresses (city, city_id, street, street_id, house, flat) VALUES ('Bohaterów Starówki Warszawskiej 11/20',null,'81-466 Gdynia',null,null,null)
Błąd: ERROR: value too long for type character varying(32)
Zapytanie: SELECT currval('addresses_id_seq')
Błąd: ERROR: current transaction is aborted, commands ignored until end of transaction block
Zapytanie: INSERT INTO customer_addresses (customer_id, address_id, type) VALUES ('5736',NULL,2)
Błąd: ERROR: current transaction is aborted, commands ignored until end of transaction block
Zapytanie: UPDATE nodes SET address_id = NULL WHERE id = '11273';
Błąd: ERROR: current transaction is aborted, commands ignored until end of transaction block
Zapytanie: INSERT INTO addresses (city, city_id, street, street_id, house, flat) VALUES ('Al. Zwycięstwa 96/98',null,'81-451 Gdynia',null,null,null)
Błąd: ERROR: current transaction is aborted, commands ignored until end of transaction block
Zapytanie: SELECT currval('addresses_id_seq')

dzisiaj pobrana nowa wersja z lmsgit

**Comment by chilek** [comment]
Czyżby to był efekt "dobrych zmian" i związanej z tym zmiany nazw ulic? :dagger:

Na poważnie: przypisuję @kosaa do zgłoszenia.

**Comment by wawryk** [comment]
Jest to lekki bug, przydało by się wyrzucic jakiś alert o braku terytu.
Problem u mnie polegał na tym że w kilku urzadzeniach ktos wpisal adres z palca ...
zamykam
