### ISSUE TITLE
mysql.2017031600.php

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#1107]
Napotkano błędy w bazie danych!
Zapytanie: CREATE VIEW vaddresses AS SELECT *, city_id as location_city, street_id as location_street, house as location_house, flat as location_flat, ( trim(both ' ' from CONCAT((CASE WHEN zip is not null AND char_length(zip) > 0 THEN CONCAT(zip, ' ') ELSE '' END), (CASE WHEN city is not null AND char_length(city) > 0 THEN CASE WHEN street is not null AND char_length(street) > 0 THEN CONCAT(city, ', ', street) ELSE city END ELSE CASE WHEN street is not null AND char_length(street) > 0 THEN street ELSE '' END END), (CASE WHEN house is not null THEN CASE WHEN flat is not null THEN CONCAT(' ', house, '/', flat) ELSE CONCAT(' ', house) END ELSE CASE WHEN flat is not null THEN CONCAT(' ', flat) ELSE '' END END ))) AS location FROM addresses;
Błąd: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS location FROM addresses' at line 19

Gdzieś jeszcze jest błąd.

**Comment by interduo** [comment]
https://github.com/chilek/lms-plus/commit/1fab4447e2283c4882795bda40b70beae3e535a8

Mam nadzieję rozwiązuje problem.

**Comment by interduo** [comment]
Po wczorajszym git pull

Nadal występują błędy w bazie danych:

2017031600
Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac, a.city_id as location_city, a.street_id as location_street, a.house as location_house, a.flat as location_flat, a.location FROM nodes n LEFT JOIN (SELECT nodeid, array_to_string(array_agg(mac), ',') AS mac FROM macs GROUP BY nodeid) m ON (n.id = m.nodeid) LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0
Błąd: View's SELECT contains a subquery in the FROM clause


20170314
Napotkano błędy w bazie danych!
Zapytanie: CREATE VIEW vaddresses AS SELECT *, city_id as location_city, street_id as location_street, house as location_house, flat as location_flat, ( trim(both ' ' from CONCAT((CASE WHEN zip is not null AND char_length(zip) > 0 THEN CONCAT(zip, ' ') ELSE '' END), (CASE WHEN city is not null AND char_length(city) > 0 THEN CASE WHEN street is not null AND char_length(street) > 0 THEN CONCAT(city, ', ', street) ELSE city END ELSE CASE WHEN street is not null AND char_length(street) > 0 THEN street ELSE '' END END), (CASE WHEN house is not null THEN CASE WHEN flat is not null THEN CONCAT(' ', house, '/', flat) ELSE CONCAT(' ', house) END ELSE CASE WHEN flat is not null THEN CONCAT(' ', flat) ELSE '' END END ))) AS location FROM addresses;
Błąd: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS location FROM addresses' at line 19
Zapytanie: CREATE VIEW customerview AS SELECT c.*, a1.country_id as countryid, a1.zip as zip, a1.city as city, a1.street as street, a1.house as building, a1.flat as apartment, a2.country_id as post_countryid, a2.zip as post_zip, a2.city as post_city, a2.street as post_street, a2.house as post_building, a2.flat as post_apartment, a2.name as post_name, a1.location as address, a2.location as post_address FROM customers c JOIN customer_addresses ca1 ON c.id = ca1.customer_id AND ca1.type = 1 LEFT JOIN vaddresses a1 ON ca1.address_id = a1.id LEFT JOIN customer_addresses ca2 ON c.id = ca2.customer_id AND ca2.type = 0 LEFT JOIN vaddresses a2 ON ca2.address_id = a2.id WHERE NOT EXISTS ( SELECT 1 FROM customerassignments a JOIN excludedgroups e ON (a.customergroupid = e.customergroupid) WHERE e.userid = lms_current_user() AND a.customerid = c.id) AND c.type < 2;
Błąd: Table 'lmsdb.vaddresses' doesn't exist
Zapytanie: CREATE VIEW contractorview AS SELECT c.*, a1.country_id as countryid, a1.zip as zip, a1.city as city, a1.street as street, a1.house as building, a1.flat as apartment, a2.country_id as post_countryid, a2.zip as post_zip, a2.city as post_city, a2.street as post_street, a2.house as post_building, a2.flat as post_apartment, a2.name as post_name, a1.location as address, a2.location as post_address FROM customers c JOIN customer_addresses ca1 ON c.id = ca1.customer_id AND ca1.type = 1 LEFT JOIN vaddresses a1 ON ca1.address_id = a1.id LEFT JOIN customer_addresses ca2 ON c.id = ca2.customer_id AND ca2.type = 0 LEFT JOIN vaddresses a2 ON ca2.address_id = a2.id WHERE c.type = 2;
Błąd: Table 'lmsdb.vaddresses' doesn't exist
Zapytanie: CREATE VIEW customeraddressview AS SELECT c.*, a1.country_id as countryid, a1.zip as zip, a1.city as city, a1.street as street, a1.house as building, a1.flat as apartment, a2.country_id as post_countryid, a2.zip as post_zip, a1.city as post_city, a2.street as post_street, a2.house as post_building, a2.flat as post_apartment, a2.name as post_name, a1.location as address, a2.location as post_address FROM customers c JOIN customer_addresses ca1 ON c.id = ca1.customer_id AND ca1.type = 1 LEFT JOIN vaddresses a1 ON ca1.address_id = a1.id LEFT JOIN customer_addresses ca2 ON c.id = ca2.customer_id AND ca2.type = 0 LEFT JOIN vaddresses a2 ON ca2.address_id = a2.id WHERE c.type < 2;
Błąd: Table 'lmsdb.vaddresses' doesn't exist
Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac, a.city_id as location_city, a.street_id as location_street, a.house as location_house, a.flat as location_flat, a.location FROM nodes n LEFT JOIN vnodes_mac m ON (n.id = m.nodeid) LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0;
Błąd: Table 'lmsdb.vaddresses' doesn't exist
Zapytanie: CREATE VIEW vmacs AS SELECT n.*, m.mac, m.id AS macid, a.city_id as location_city, a.street_id as location_street, a.house as location_building, a.flat as location_flat, a.location FROM nodes n JOIN macs m ON (n.id = m.nodeid) LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0;
Błąd: Table 'lmsdb.vaddresses' doesn't exist
Zapytanie: CREATE VIEW vnetworks AS SELECT h.name AS hostname, ne.*, no.ownerid, a.city_id as location_city, a.street_id as location_street, a.house as location_house, a.flat as location_flat, no.chkmac, CONCAT(inet_ntoa(ne.address), '/', mask2prefix(inet_aton(ne.mask))) AS ip, no.id AS nodeid, a.location FROM nodes no LEFT JOIN networks ne ON (ne.id = no.netid) LEFT JOIN hosts h ON (h.id = ne.hostid) LEFT JOIN vaddresses a ON no.address_id = a.id WHERE no.ipaddr = 0 AND no.ipaddr_pub = 0;
Błąd: Table 'lmsdb.vaddresses' doesn't exist

**Comment by chilek** [comment]
Na pewno 06aabc6 w części pomoże. Daj znać na czym teraz biedny mysql wywala się ;-)

**Comment by interduo** [comment]
```
Napotkano błędy w bazie danych!
Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac, a.city_id as location_city, a.street_id as location_street, a.house as location_house, a.flat as location_flat, a.location FROM nodes n LEFT JOIN (SELECT nodeid, array_to_string(array_agg(mac), ',') AS mac FROM macs GROUP BY nodeid) m ON (n.id = m.nodeid) LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0
Błąd: View's SELECT contains a subquery in the FROM clause






Napotkano błędy w bazie danych!
Zapytanie: DROP VIEW customerview, contractorview, customeraddressview, vmacs, vnetworks, vnodes, vaddresses, vdivisions
Błąd: Unknown table 'vnodes'
Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac, a.city_id as location_city, a.street_id as location_street, a.house as location_house, a.flat as location_flat, a.location FROM nodes n LEFT JOIN (SELECT nodeid, array_to_string(array_agg(mac), ',') AS mac FROM macs GROUP BY nodeid) m ON (n.id = m.nodeid) LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0
Błąd: View's SELECT contains a subquery in the FROM clause
```

Zostały tylko te dwa.

**Comment by chilek** [comment]
To 56b8ecd chyba rozwiąże te problemy.

**Comment by interduo** [comment]
Czysto! :)
