### ISSUE TITLE
modules/divisionadd.php

### ISSUE THREAD

**Issue by prezesk** [lmsgit/lms#1111]
Cześć,
Dokonano zmian w pliku modules/divisionadd.php ale nie ma dwóch nowych pól w bazie. rbe oraz rbename dodałem sobie ale nie wiem jakie to pola powinny być.

**Comment by chilek** [comment]
Podane pola są w bazie danych:
https://github.com/lmsgit/lms/blob/master/doc/lms.pgsql#L471-L472
