### ISSUE TITLE
Język polski

### ISSUE THREAD

**Issue by prezesk** [lmsgit/lms#1112]
Cześć,
W aktualnej wersji z git. W konfiguracji phpui wpisuje w lang = pl oraz w lms.ini tez dopisałem i nadal mam w wersji angielskiej. W chrome oraz firefox. Dodatkowo zauważyłem że jak uruchomię w IE to jest język polski ale za to cała strona się rozjeżdżą i nie da się tam pracować. Widok zgodności też nie pomaga. W edge działa poprawnie i jest po polsku :)
system windows 10 64bit.

**Comment by kosaa** [comment]
czysciles moze historie i zapamietane w pamieci przegladarki strony?

**Comment by prezesk** [comment]
Tak robiłem nic się nie zmieniało. Dodatkowo uruchomiałem w trybie incognito i tam też nic się nie zmieniało.

**Comment by kosaa** [comment]
a jaki masz język systemowy? przestawiłem u siebie na angielski i mam to samo co u Ciebie tj. pomimo zmiennej lang=pl mam angielski

**Comment by prezesk** [comment]
Na windows 10 64 bit chrome i firefox w najnowszej wersji pokazuje język angielki chodź w systemie wszystko jest na polski region polska itd. 
![_20170327_145707](https://cloud.githubusercontent.com/assets/24987736/24587554/25babcfe-17b9-11e7-9bf2-ab5a1466f7b6.JPG)
Na telefonie andorid 7 ten sam problem pokazuje en zamiast pl

**Comment by prezesk** [comment]
Po długich poszukiwaniach ustaliłem że winę ponosi przeglądarka chrome w ustawieniach znalazłem że są dwa dodatkowe języki dodane aczkolwiek polski był jako główny nie ma tam możliwości przestawienia kolejności ale usunięcie obcych języków i ponowne dodanie spowodowało że lms zaczął gadać po polsku ;)
![image](https://cloud.githubusercontent.com/assets/24987736/25329986/41f7f5e0-28de-11e7-9389-f4ee4a9ad985.png)

**Comment by kosaa** [comment]
ten sam efekt mam na mozilli, obstawiam, że to nie wina chroma

**Comment by chilek** [comment]
@prezesk: a nie masz tam w tym oknie co wstawiłeś możliwości zmiany kolejności języków techniką drag&drop? U mnie w Chrome 58 x86_64 Linux jak najbardziej to działa tą metodą.

**Comment by prezesk** [comment]
Faktycznie działa taka zamiana. I to powoduje zamianę języka w LMS chodź w systemie jest język polski to w Chrome pojawia się po angielsku dopiero zmiana kolejności w samym Chrome zmienia język działania LMS. Dziękuje za pomoc.
