### ISSUE TITLE
update 1.11.21 -> LMS 1.11-git

### ISSUE THREAD

**Issue by reqntar** [lmsgit/lms#1121]
Mam problem z wykonaniem update. Wszystko fajnie działa, ale nie chce mi przenieść komputerów klientów. Szukałem w bazie tabeli z kompami, nie znalazłem. Próbowałem także dodać testową maszynę, po zapisie wyświetliła mi się pusta lista, nowego wpisu nie było. Logi czyste. Jakieś sugestie jak mam sobie z tym poradzić?

**Comment by interduo** [comment]
MySQL czy Postgres? 
Przerabiałem podobny schemat zerknij po podmianie plików na stronę główną i wklej błędy ze skryptow zmieniających strukturę bazy danych.

**Comment by reqntar** [comment]
MySQL. Błędy:
`Zapytanie: ALTER TABLE nodes ADD location varchar(255) DEFAULT NULL
Błąd: Duplicate column name 'location'
Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac FROM nodes n LEFT JOIN vnodes_mac m ON (n.id = m.nodeid); 
Błąd: Duplicate column name 'mac'
Zapytanie: DROP VIEW vnodes
Błąd: Unknown table 'vnodes'
Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac FROM nodes n LEFT JOIN vnodes_mac m ON (n.id = m.nodeid)
Błąd: Duplicate column name 'mac'
Zapytanie: CREATE VIEW vmacs AS SELECT n.*, m.mac, m.id AS macid FROM nodes n JOIN macs m ON (n.id = m.nodeid)
Błąd: Duplicate column name 'mac'`
`Zapytanie: DROP VIEW vnodes
Błąd: Unknown table 'vnodes'
Zapytanie: DROP VIEW vmacs
Błąd: Unknown table 'vmacs'
Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac FROM nodes n LEFT JOIN vnodes_mac m ON (n.id = m.nodeid) WHERE n.ipaddr <> 0 AND n.ipaddr_pub <> 0 
Błąd: Duplicate column name 'mac'
Zapytanie: CREATE VIEW vmacs AS SELECT n.*, m.mac, m.id AS macid FROM nodes n JOIN macs m ON (n.id = m.nodeid) WHERE n.ipaddr <> 0 AND n.ipaddr_pub <> 0 
Błąd: Duplicate column name 'mac'`
`Zapytanie: CREATE VIEW vmacs AS SELECT n.*, m.mac, m.id AS macid, a.city_id as location_city, a.street_id as location_street, a.house as location_building, a.flat as location_flat, ( trim(both ' ' from CASE WHEN a.city is not null AND char_length(city) > 0 THEN CASE WHEN a.street is not null AND char_length(street) > 0 THEN a.city || ', ' || a.street ELSE a.street END ELSE CASE WHEN a.street is not null AND char_length(street) > 0 THEN a.street ELSE '' END END || CASE WHEN a.house is not null THEN CASE WHEN a.flat is not null THEN ' ' || a.house || '/' || a.flat ELSE ' ' || a.house END ELSE CASE WHEN a.flat is not null THEN ' ' || a.flat ELSE '' END END )) AS location FROM nodes n JOIN macs m ON (n.id = m.nodeid) LEFT JOIN addresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0;
Błąd: Duplicate column name 'mac'
Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac, a.city_id as location_city, a.street_id as location_street, a.house as location_house, a.flat as location_flat, ( trim(both ' ' from CASE WHEN a.city is not null AND char_length(city) > 0 THEN CASE WHEN a.street is not null AND char_length(street) > 0 THEN a.city || ', ' || a.street ELSE a.street END ELSE CASE WHEN a.street is not null AND char_length(street) > 0 THEN a.street ELSE '' END END || CASE WHEN a.house is not null THEN CASE WHEN a.flat is not null THEN ' ' || a.house || '/' || a.flat ELSE ' ' || a.house END ELSE CASE WHEN a.flat is not null THEN ' ' || a.flat ELSE '' END END )) AS location FROM nodes n LEFT JOIN vnodes_mac m ON (n.id = m.nodeid) LEFT JOIN addresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0;
Błąd: Duplicate column name 'mac'`
`Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac, a.city_id as location_city, a.street_id as location_street, a.house as location_house, a.flat as location_flat, ( trim(both ' ' from CONCAT( CASE WHEN a.city is not null AND char_length(city) > 0 THEN CASE WHEN a.street is not null AND char_length(street) > 0 THEN CONCAT(a.city, ', ', a.street) ELSE a.street END ELSE CASE WHEN a.street is not null AND char_length(street) > 0 THEN a.street ELSE '' END END, CASE WHEN a.house is not null THEN CASE WHEN a.flat is not null THEN CONCAT(' ', a.house, '/', a.flat) ELSE CONCAT(' ', a.house) END ELSE CASE WHEN a.flat is not null THEN CONCAT(' ', a.flat) ELSE '' END END) )) AS location FROM nodes n LEFT JOIN vnodes_mac m ON (n.id = m.nodeid) LEFT JOIN addresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0;
Błąd: Duplicate column name 'mac'
Zapytanie: CREATE VIEW vmacs AS SELECT n.*, m.mac, m.id AS macid, a.city_id as location_city, a.street_id as location_street, a.house as location_building, a.flat as location_flat, ( trim(both ' ' from CONCAT( CASE WHEN a.city is not null AND char_length(city) > 0 THEN CASE WHEN a.street is not null AND char_length(street) > 0 THEN CONCAT(a.city, ', ', a.street) ELSE a.street END ELSE CASE WHEN a.street is not null AND char_length(street) > 0 THEN a.street ELSE '' END END, CASE WHEN a.house is not null THEN CASE WHEN a.flat is not null THEN CONCAT(' ', a.house, '/', a.flat) ELSE CONCAT(' ', a.house) END ELSE CASE WHEN a.flat is not null THEN CONCAT(' ', a.flat) ELSE '' END END) )) AS location FROM nodes n JOIN macs m ON (n.id = m.nodeid) LEFT JOIN addresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0;
Błąd: Duplicate column name 'mac'`
`Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac, a.city_id as location_city, a.street_id as location_street, a.house as location_house, a.flat as location_flat, a.location FROM nodes n LEFT JOIN vnodes_mac m ON (n.id = m.nodeid) LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0; 
Błąd: Duplicate column name 'mac'
Zapytanie: CREATE VIEW vmacs AS SELECT n.*, m.mac, m.id AS macid, a.city_id as location_city, a.street_id as location_street, a.house as location_building, a.flat as location_flat, a.location FROM nodes n JOIN macs m ON (n.id = m.nodeid) LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0; 
Błąd: Duplicate column name 'mac'`
`Zapytanie: ALTER TABLE events ADD CONSTRAINT 'event_ticketid_rttickets_id_fk' FOREIGN KEY (ticketid) REFERENCES rttickets (id) ON DELETE SET NULL ON UPDATE CASCADE
Błąd: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''event_ticketid_rttickets_id_fk' FOREIGN KEY (ticketid) REFERENCES rttickets (id' at line 1`
`Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac, a.city_id as location_city, a.street_id as location_street, a.house as location_house, a.flat as location_flat, a.location FROM nodes n LEFT JOIN vnodes_mac m ON (n.id = m.nodeid) LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0; 
Błąd: Duplicate column name 'mac'
Zapytanie: CREATE VIEW vmacs AS SELECT n.*, m.mac, m.id AS macid, a.city_id as location_city, a.street_id as location_street, a.house as location_building, a.flat as location_flat, a.location FROM nodes n JOIN macs m ON (n.id = m.nodeid) LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0; 
Błąd: Duplicate column name 'mac'`
`Zapytanie: DROP TABLE imessengers
Błąd: Unknown table 'imessengers'`
`Zapytanie: DROP VIEW customerview, contractorview, customeraddressview, vmacs, vnetworks, vnodes, vaddresses
Błąd: Unknown table 'vmacs,vnodes'
Zapytanie: CREATE VIEW vmacs AS SELECT n.*, m.mac, m.id AS macid, a.city_id as location_city, a.street_id as location_street, a.location, a.house as location_building, a.flat as location_flat FROM nodes n JOIN macs m ON (n.id = m.nodeid) LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0 
Błąd: Duplicate column name 'mac'
Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac, a.city_id as location_city, a.street_id as location_street, a.house as location_house, a.flat as location_flat, a.location FROM nodes n LEFT JOIN vnodes_mac m ON m.nodeid = n.id LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0 
Błąd: Duplicate column name 'mac'`
`Zapytanie: DROP VIEW customerview, contractorview, customeraddressview, vmacs, vnetworks, vnodes, vaddresses, vdivisions
Błąd: Unknown table 'vmacs,vnodes'
Zapytanie: CREATE VIEW vmacs AS SELECT n.*, m.mac, m.id AS macid, a.city_id as location_city, a.street_id as location_street, a.location, a.house as location_building, a.flat as location_flat FROM nodes n JOIN macs m ON (n.id = m.nodeid) LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0 
Błąd: Duplicate column name 'mac'
Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac, a.city_id as location_city, a.street_id as location_street, a.house as location_house, a.flat as location_flat, a.location FROM nodes n LEFT JOIN vnodes_mac m ON m.nodeid = n.id LEFT JOIN vaddresses a ON n.address_id = a.id WHERE n.ipaddr <> 0 OR n.ipaddr_pub <> 0 
Błąd: Duplicate column name '`

Niektóre kilka razy się powtarzały, starałem się nie wklejać duplikatów.

**Comment by interduo** [comment]
Czy na pewno używasz wersji git?

**Comment by reqntar** [comment]
Wersja sprzed aktualizacji nie, a ta po była z git.

**Comment by interduo** [comment]
Jeśli masz zapisane te błędy to wklej pierwszy bo reszta to pochodne.

**Comment by reqntar** [comment]
`Zapytanie: ALTER TABLE nodes ADD location varchar(255) DEFAULT NULL
Błąd: Duplicate column name 'location'
Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac FROM nodes n LEFT JOIN vnodes_mac m ON (n.id = m.nodeid); 
Błąd: Duplicate column name 'mac'
Zapytanie: DROP VIEW vnodes
Błąd: Unknown table 'vnodes'
Zapytanie: CREATE VIEW vnodes AS SELECT n.*, m.mac FROM nodes n LEFT JOIN vnodes_mac m ON (n.id = m.nodeid)
Błąd: Duplicate column name 'mac'
Zapytanie: CREATE VIEW vmacs AS SELECT n.*, m.mac, m.id AS macid FROM nodes n JOIN macs m ON (n.id = m.nodeid)
Błąd: Duplicate column name 'mac'`

**Comment by interduo** [comment]
DROP VIEW mac; 
CREATE VIEW mac (zrób zgodnie ze schematem w doc\lms.mysql) 

Ten błąd został załatany też z nim się bujałem.
Do zamknięcia.

**Comment by chilek** [comment]
Proponuję update do bieżącego master. Zawsze w przypadku problemów można poczekać parę dni i zaktualizować.
