### ISSUE TITLE
Netdevmap: brak popupa z info o danym linku.

### ISSUE THREAD

**Issue by zlyZwierz** [lmsgit/lms#1123]
Po najechaniu kursorem na link pomiędzy urządzeniami nie wyświetla się popup z informacją o technologii, szybkości typie połaczenia.

Testowane na demku.

Chciałem zrobić użytek z tego popupa, ale sam tego chyba nie naprawię :(

W konsoli JS mam: 
TypeError: features[0] is undefined  map.js:755:1

**Comment by cybernetwmw** [comment]
Dobra, jetę hakerę ;) (works for me.)

diff --git a/img/map.js b/img/map.js
index 3f606ff27..e4b39abfe 100644
--- a/img/map.js
+++ b/img/map.js
@@ -260,8 +260,8 @@ function findFeaturesIntersection(selectFeature, feature, featureLonLat)
                for (var j in layer.features) {
                        var currentFeature = layer.features[j];
                        // position feature is not needed - we detect it by nullified style
-                       if (currentFeature.style != null)
-                               continue;
+                       //if (currentFeature.style != null)
+                       //      continue;
                        if (currentFeature.getVisibility() && currentFeature.onScreen()) {
                                var currentLonLat = new OpenLayers.LonLat(
                                        currentFeature.geometry.x, currentFeature.geometry.y);
@@ -273,7 +273,7 @@ function findFeaturesIntersection(selectFeature, feature, featureLonLat)
                }
        }
        // position feature is not needed - we detect it by nullified style
-       if (!features.length && feature.style == null)
+       //if (!features.length && feature.style == null)
                features.push(feature);
        return features;
 }

**Comment by zlyZwierz** [comment]
Przepraszam, może ten diff lepiej będzie wyglądał.
U mnie popupy zaczęły się wyświetlać, nie wiem na ile "koszerny" jest ten fix.

`diff --git a/img/map.js b/img/map.js
index 3f606ff27..e4b39abfe 100644
--- a/img/map.js
+++ b/img/map.js
@@ -260,8 +260,8 @@ function findFeaturesIntersection(selectFeature, feature, featureLonLat)
                for (var j in layer.features) {
                        var currentFeature = layer.features[j];
                        // position feature is not needed - we detect it by nullified style
-                       if (currentFeature.style != null)
-                               continue;
+                       //if (currentFeature.style != null)
+                       //      continue;
                        if (currentFeature.getVisibility() && currentFeature.onScreen()) {
                                var currentLonLat = new OpenLayers.LonLat(
                                        currentFeature.geometry.x, currentFeature.geometry.y);
@@ -273,7 +273,7 @@ function findFeaturesIntersection(selectFeature, feature, featureLonLat)
                }
        }
        // position feature is not needed - we detect it by nullified style
-       if (!features.length && feature.style == null)
+       //if (!features.length && feature.style == null)
                features.push(feature);
        return features;
 }
`

**Comment by chilek** [comment]
Commit https://github.com/lmsgit/lms/commit/1da446cccbc2d119dca2daa35416906b1e097468 rozwijązuje problem z błędem js po kliknięciu na połączenie.
Jak dokładnie uzyskać problem, który opisujesz?

**Comment by chilek** [comment]
@zlyZwierz: Twoja poprawka powoduje, że przez przypadek zaczęły działać chmurki z informacją o właściwościach połączenia, ale będzie generować błędy js w innych sytuacjach.
Commit https://github.com/lmsgit/lms/commit/ff99342cf94c20387fe9ae3d0b73723d2e7252a5 wprowadza poprawkę do wersji rozwojowej, która powoduje poprawne ignorowanie ikonki wskazanego punktu na mapie przy wyświetlaniu chmurek z informacjami o obiektach mapy.
