### ISSUE TITLE
Bład w funkcji SendMail w LMS.class.php

### ISSUE THREAD

**Issue by alkar1** [lmsgit/lms#1132]
Jeśli jest używany backend phpmailer ,  i serwer pocztowy ma AuthType różne od  CRAM-MD5
to wyskakuje błąd autentykacji.

Zamiast
$this->mail_object->SMTPAuth  = (!$auth ? ConfigHelper::getConfig('mail.smtp_auth_type', true) : $auth);
powinno być
$this->mail_object->AuthType = (!$auth ? ConfigHelper::getConfig('mail.smtp_auth_type', true) : $auth);
i zmienna $this->mail_object->SMTPAuth  = true;

Zgodnie z: [http://phpmailer.github.io/PHPMailer/classes/PHPMailer.html#property_AuthType](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.html#property_AuthType)

**Comment by chilek** [comment]
@alkar1 niestety to co podałeś do wyeliminowanie jednego problemu, a wprowadzenie na to miejsce innego.
SMTPAuth powinno być traktowane odrębnie, a AuthType odrębnie.
Commit https://github.com/lmsgit/lms/commit/971d9fb1be0d1929076831bf241281a82584d812
wprowadza zasadę, że jeśli jest smtp_auth jest wartością logiczną to taką wartość przyjmuje SMTPAuth. W przeciwnym wypadku SMTPAuth=true, AuthType=$smtp_auth.
Przy okazji mail.smtp_secure zaczynamy obsługiwać w ten sposób, że jeśli jest false to wyłączamy automatyczne załączanie STARTTLS, tj. SMTPAutoTLS = false.

**Comment by alkar1** [comment]
Ok, 
czyli jeśli ktoś ustawi  mail.smtp_auth_type na true to phpmailer będzie szyfrował hasło do CRAM-MD5 ,
a jeśli  na PLAIN  to wyśle hasło otwartym tekstem.

**Comment by chilek** [comment]
Jeśli mail.smtp_auth_type=true to SMTPAuth=true oraz AuthType domyślne (czyli puste), a wtedy:
https://github.com/PHPMailer/PHPMailer/blob/master/class.smtp.php#L415-L427
czyli automatyczne rozpoznanie sposobu uwierzytelniania w kolejności jak widać tam w kodzie.

**Comment by chilek** [comment]
Jeśli smtp_auth_type='PLAIN' to oczywiście SMTPAuth=true i AuthType='PLAIN'.
