### ISSUE TITLE
Aktualizacja z 1.11.13 do 1.11.21 i Fatal error: cannot connect to database!

### ISSUE THREAD

**Issue by milo-23** [lmsgit/lms#1135]
Witam,

Mam postawionego Debiana 6 z LMS 1.11.13 podczas próby aktualizacji do najnowszej z git podnosiłem co chciał aż pojawił mi się komunikat że nie można połączyć się z bazą danych.

Log z Apache2:
[Sun May 07 01:41:08 2017] [error] [client 78.88.xx.xx] PHP Warning:  Unknown config variable "type" in section "database"! in /var/www/index.php on line 94
[Sun May 07 01:42:24 2017] [error] [client 78.88.xx.xx] PHP Warning:  Unknown config variable "type" in section "database"! in /var/www/userpanel/index.php on line 98

Baza jest, ponieważ przez phpmyadmin loguje się do niej...
Ewentualnie jak podnosiłem wersje PHP to pytał się mnie czy zostawić chyba php.ini czy nadpisać nowszą.
Pomoże ktoś?

**Comment by interduo** [comment]
Nie wykasowałeś czegoś z konfiga? 

Zerknij tutaj i użyj tego pliku
https://github.com/lmsgit/lms/blob/master/sample/lms.ini#L94

**Comment by milo-23** [comment]
Dziękuje za odpowiedz.

Komunikat o nieznanym "type" jest 2 razy dlatego że sprawdzałem czy wyświetli mi się userpanel jeżeli nie mogę zalogować się do samego LMS-a.

Podczas aktualizacji skopiowałem i rozpakowałem cały katalog z LMS-em do www i nic tam nie zmieniam a pojawia się ten błąd, co ciekawsze jak zejdę do wersji 1.11.13 wszystko działa, jak pobiorę wypakuje do katalogu www wersję inetLMS po nadaniu uprawnień też wszystko działa.

Ma ktoś inny pomysł w czym problem?

**Comment by interduo** [comment]
Po poprawieniu konfiga co w logach?

**Comment by milo-23** [comment]
Nie pomogło, ale pomyślałem sobie że raz jeszcze wypakuje 1.11.21 i teraz tak się zastanawiam że ten composer może być winny:

root@inter:/var/www# composer install
`PHP` Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20100525/suhosin.so' - /usr                                                                                                           /lib/php5/20100525/suhosin.so: cannot open shared object file: No such file or directory in Unknown                                                                                                            on line 0
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 12 installs, 0 updates, 0 removals
  - Installing phine/exception (1.0.0): Loading from cache
  - Installing phine/observer (2.0.0): Loading from cache
  - Installing components/normalize.css (3.0.3): Downloading (100%)
  - Installing smarty/smarty (v3.1.30): Downloading (100%)
  - Installing xdan/datetimepicker (2.5.4): Downloading (100%)
  - Installing phpmailer/phpmailer (v5.2.23): Downloading (100%)
  - Installing tecnickcom/tcpdf (6.2.12): Loading from cache
  - Installing spipu/html2pdf (v4.6.1): Downloading (100%)
  - Installing rospdf/pdf-php (0.12.32): Downloading (100%)
  - Installing components/jquery (3.2.1): Downloading (100%)
  - Installing components/jqueryui (1.12.1): Downloading (100%)
  - Installing datatables/datatables (1.10.15): Downloading (100%)
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Google                                                                                                                                on)
spipu/html2pdf suggests installing fagundes/zff-html2pdf (zff-html2pdf module ~0                                                                                                                                integrate HTML2PDF with Zend Framework 2 (zf2))
Package phine/exception is abandoned, you should avoid using it. No replacement
Package phine/observer is abandoned, you should avoid using it. No replacement w
Writing lock file
Generating autoload files
> sed -i -e 's/class HTML2PDF_myPdf extends TCPDF/class HTML2PDF_myPdf extends L                                                                                                                               pu/html2pdf/_class/myPdf.class.php
> sed -i -e 's/\(\s\+\)register_shutdown_function/\1\/\/register_shutdown_functi                                                                                                                               om/tcpdf/tcpdf.php
> cp -f lib/ezpdf/fonts/arial* `vendor/rospdf/pdf-php/src/fonts`

root@inter:/var/www# composer install / composer update
`PHP` Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20100525/suhosin.so' - /usr/lib/php5/20100525/suhosin.so: cannot open shared object file: No such file or directory in Unknown on line 0
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Invalid argument / composer update. Use "composer require / composer update" instead to add packages to your `composer.json.`

**Comment by maciejhpl** [comment]
jaka wersja php ? w php7 nie ma mysql
```
Warning This extension was deprecated in PHP 5.5.0, and it was removed in PHP 7.0.0. Instead, the MySQLi or PDO_MySQL extension should be used. See also MySQL: choosing an API guide. Alternatives to this function include:
```
w lms.ini ustaw 
```
[database]
type = mysqli
```

**Comment by interduo** [comment]
Poradziłeś sobie z tym?

**Comment by interduo** [comment]
composer update zrobiłeś?

**Comment by futszak** [comment]
w kolejności po rozpakowaniu LMS-a w katalogu:

wget https://getcomposer.org/download/1.5.2/composer.phar
php composer.phar install
# potem zgodnie z instrukcją na stronie
mkdir /var/www/lms/img/xajax_js/deferred
chown -R 33:33 /var/www/lms/img/xajax_js/deferred
chmod -R 755 /var/www/lms/img/xajax_js/deferred

poza ściągnięciem najnowszej wersji php composera trzeba go jeszcze update-ować ?

**Comment by interduo** [comment]
Ja u siebie gdzieś w skrypcie mam:
composer self-update
composer update

i działa od wieków ;)

**Comment by interduo** [comment]
Może uprawnienia na katalog lub plik konfiguracyjny lms.ini?

**Comment by interduo** [comment]
W funkcję loadConfig wrzuć: print_r($raw_config); die(); na sam początek i będzie wiadomo co jest nie tak.

**Comment by futszak** [comment]
wyrzuca według mnie config ściąga prawidłowo:

Array ( [database] => Array ( [type] => mysqli [host] => localhost [user] => lms [password] => l*********d [database] => lms ) [directories] => Array ( ) )

**Comment by interduo** [comment]
ścieżki w lms.ini ?

**Comment by futszak** [comment]
powpisywałem, pojawia mi się w logach od apache-a taki komunikat:

[Mon Oct 09 13:59:14.442958 2017] [:error] [pid 18348] [client 78.11.208.117:33980] PHP Warning:  Invalid argument supplied for foreach() in /var/www/lms/lib/LMSConfig/IniConfigParser.php on line 49
[Mon Oct 09 13:59:14.443114 2017] [:error] [pid 18348] [client 78.11.208.117:33980] PHP Warning:  Invalid argument supplied for foreach() in /var/www/lms/lib/LMSConfig/IniConfigParser.php on line 49
[Mon Oct 09 13:59:14.443202 2017] [:error] [pid 18348] [client 78.11.208.117:33980] PHP Warning:  Invalid argument supplied for foreach() in /var/www/lms/lib/LMSConfig/IniConfigParser.php on line 49
[Mon Oct 09 13:59:14.443265 2017] [:error] [pid 18348] [client 78.11.208.117:33980] PHP Warning:  Invalid argument supplied for foreach() in /var/www/lms/lib/LMSConfig/IniConfigParser.php on line 49
[Mon Oct 09 13:59:14.443324 2017] [:error] [pid 18348] [client 78.11.208.117:33980] PHP Warning:  Invalid argument supplied for foreach() in /var/www/lms/lib/LMSConfig/IniConfigParser.php on line 49
[Mon Oct 09 13:59:14.443440 2017] [:error] [pid 18348] [client 78.11.208.117:33980] PHP Warning:  Unknown config variable "type" in section "database"! in /var/www/lms/index.php on line 94

**Comment by interduo** [comment]
coś masz skopsane w konfigu lms.ini moim zdaniem lub nie masz paczki IniConfig w php

**Comment by interduo** [comment]
Postaw na czystej wirtualce zgodnie z instrukcją wszystko a potem podmień bazę ;)

**Comment by futszak** [comment]
zrobiłem jak radziłeś, czysty debian z iso, specjalnie pod LMS-a, czysta baza, $raw_config wygląda tak:

Array ( [database] => Array ( [type] => mysqli [host] => localhost [user] => lms [password] => l*****e [database] => lms ) [directories] => Array ( [sys_dir] => /var/www/html/ [lib_dir] => /var/www/html/lib/ [backup_dir] => /var/backup/lms/ [doc_dir] => /var/www/documents/ [smarty_compile_dir] => /var/smarty/compile/lms [smarty_templates_dir] => /var/www/html/templates ) )

a w logach się wywala tak:

[Tue Oct 10 11:13:58.074668 2017] [:error] [pid 14684] [client 78.11.208.117:57116] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to ConfigLoader::parseRawConfig() must be of the type array, null given, called in /var/www/html/lib/LMSConfig/ConfigLoader.php on line 53 and defined in /var/www/html/lib/LMSConfig/ConfigLoader.php:107\nStack trace:\n#0 /var/www/html/lib/LMSConfig/ConfigLoader.php(53): ConfigLoader->parseRawConfig(NULL, Array)\n#1 /var/www/html/lib/LMSConfig/LMSConfig.php(100): ConfigLoader->loadConfig(Array)\n#2 /var/www/html/lib/LMSConfig/LMSConfig.php(192): LMSConfig::getUiConfig(Array)\n#3 /var/www/html/lib/LMSConfig/LMSConfig.php(152): LMSConfig::mergeConfigs(Array)\n#4 /var/www/html/lib/LMSConfig/ConfigHelper.php(82): LMSConfig::getConfig()\n#5 /var/www/html/index.php(129): ConfigHelper::checkConfig('phpui.force_ssl')\n#6 {main}\n  thrown in /var/www/html/lib/LMSConfig/ConfigLoader.php on line 107

od rana z tym walcze, od procedury do procedury, od pliku do pliku i nie potrafię znaleźć problemu :( Cały czas ten sam błąd :(

Jak zainstalować paczke IniConfig w php ?

**Comment by interduo** [comment]
Skrobnij do mnie na FB lub maila to Ci pomogę.

**Comment by futszak** [comment]
dziękuję za pomoc, udało się. problemem był brak zawartości bazy danych, którą trzeba było ręcznie zaimportować, a sam LMS nie informuje o tym fakcie, w przeciwieństwie do innych systemów jak np. wordpress, który przy pierwszym uruchomieniu tworzy potrzebną strukturę danych

**Comment by interduo** [comment]
@chilek to jest do zamknięcia.
