### ISSUE TITLE
Nowa instalacja z git - formularz division nie przekazuje danych do bazy + teryt

### ISSUE THREAD

**Issue by mnastalek** [lmsgit/lms#1136]
Hej witam! 

Zainstalowałem sobie dla testów nową wersję LMS z gita, instalacja przebiegła sprawnie jednak nie mogę z panelu Konfiguracja -> Firmy (oddziały) dodać nowej firmy. Po kliknięciu na zapisz nie wyskakuje żaden błąd po prostu pojawia się brak firm. Dodałem sobie z bazy i wyświetla ok jednak edycja tych danych z poziomu LMS nie działa (nie aktualizuje). 

Jakieś koncepcje na rozwiązanie problemu? 

teryt nieaktualne ;)

**Comment by interduo** [comment]
Stestowałem na najnowszej wersji - mi działa poprawnie. Co Ci wyrzuca apache2 w error_logu ?

**Comment by interduo** [comment]
Rozumiem że mówimy o formularzu:
https://lms/?m=divisionadd, tak?

**Comment by mnastalek** [comment]
Tak, brak pol w bazie. -------- Wiadomość oryginalna --------Temat: Re: [lmsgit/lms] Nowa instalacja z git - formularz division nie przekazuje danych do bazy + teryt (#1136)Od: Interduo Do: lmsgit/lms DW: mnastalek ,Author Rozumiem że mówimy o formularzu:
https://lms/?m=divisionadd, tak?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lmsgit/lms","title":"lmsgit/lms","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lmsgit/lms"}},"updates":{"snippets":[{"icon":"PERSON","message":"@interduo in #1136: Rozumiem że mówimy o formularzu:\r\nhttps://lms/?m=divisionadd, tak?"}],"action":{"name":"View Issue","url":"https://github.com/lmsgit/lms/issues/1136#issuecomment-300708349"}}}

**Comment by mnastalek** [comment]
Jest wiecej zgloszen tego typu-------- Wiadomość oryginalna --------Temat: Re: [lmsgit/lms] Nowa instalacja z git - formularz division nie przekazuje danych do bazy + teryt (#1136)Od: Interduo Do: lmsgit/lms DW: mnastalek ,Author Stestowałem na najnowszej wersji - mi działa poprawnie. Co Ci wyrzuca apache2 w error_logu ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lmsgit/lms","title":"lmsgit/lms","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lmsgit/lms"}},"updates":{"snippets":[{"icon":"PERSON","message":"@interduo in #1136: Stestowałem na najnowszej wersji - mi działa poprawnie. Co Ci wyrzuca apache2 w error_logu ?"}],"action":{"name":"View Issue","url":"https://github.com/lmsgit/lms/issues/1136#issuecomment-300708235"}}}

**Comment by mnastalek** [comment]
Tak wygląda na brak pól w bazie. Widziałem drugie zgłoszenie tego typu. Został stary schemat bazy przy instalacji - z przed ostatniej aktualizacji.

**Comment by mnastalek** [comment]
Wiecie, że to nadal nie działa? Testowane dzisiaj. 

Nowa instalacja, nie wywala żadnych błędów. Włącza się ui, tworzy strukturę bazy i pól w bazie dalej brakuje. Nie da się dodać oddziału z UI.

**Comment by mnastalek** [comment]
Oto struktura stworzona przez nową instalację (zarówno z git jak i z ostatniej paczki): 
CREATE TABLE `divisions` (
  `id` int(11) NOT NULL,
  `shortname` varchar(255) NOT NULL DEFAULT '',
  `name` text NOT NULL,
  `ten` varchar(16) NOT NULL DEFAULT '',
  `regon` varchar(255) NOT NULL DEFAULT '',
  `account` varchar(48) NOT NULL DEFAULT '',
  `inv_header` text NOT NULL,
  `inv_footer` text NOT NULL,
  `inv_author` text NOT NULL,
  `inv_cplace` text NOT NULL,
  `inv_paytime` smallint(6) DEFAULT NULL,
  `inv_paytype` smallint(6) DEFAULT NULL,
  `description` text NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `tax_office_code` varchar(8) DEFAULT NULL,
  `address_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


Brakuje w strukturze: 
division[rbename]
division[rbe]


Pozdrawiam ;)

**Comment by chilek** [comment]
Poprawione w gałęzi 'master' oraz LMS+ 1.11.22.1.
