### ISSUE TITLE
Kontakt z Tomasz Chiliński

### ISSUE THREAD

**Issue by milo-23** [lmsgit/lms#1140]
Witam,

Dzwonię, na nr podany na stronie ale nikt nie odbiera, wysyłałem smsa też cisza, napisałem e-mail zwróciło że nie dostarczono. Ktoś coś wie co się dzieje z Panem Tomaszem? A może to już koniec LMS Plus?

**Comment by chilek** [comment]
Zgłoszenie niezwiązane z projektem LMS.
