### ISSUE TITLE
Faktura - znikające dane sprzedawcy przy edycji i zły adres doręczenia

### ISSUE THREAD

**Issue by Skyspirit9** [lmsgit/lms#1142]
Przy automatycznym generowaniu faktur poprzez bin/lms-payments.php wszystkie dane są poprawne prócz adresu wysyłki, gdzie w adresie ulica, numer, kod pocztowy są poprawnie pobierane z adresu korespondencyjnego, a z kolei miasto pobiera z adresu klienta. I na przykład pojawiają się kruczki typu "44-200 Warszawa" w adresie doręczenia. 

Drugą ważniejszą sprawą jest to ,że gdy faktury są wygenerowane automatycznie mają poprawne dane sprzedawcy. Zaś gdy edytujemy fakturę dane sprzedawcy 'znikają', znikają także z tablicy documents, (mimo że poprzednio były) Podobnie jest w tworzeniu faktury ręcznie, gdzie także nie ma danych sprzedawcy.
A przy automatycznym generowaniu są...
Problem jest dziwny i już sami sobie nie radzimy
lms-1121git z dnia 2017-05-25

**Comment by prezesk** [comment]
Mam dokładnie taki sam problem. Gdy generuje fakturę ręcznie brakuje na niej Dane sprzedawcy i numer konta bankowego oraz stopki. Podczas generowania faktur przez lms-payments.php dane te pobierają się poprawnie z danych oddziału oraz numer konta z danych klienta. 

Dodatkowo mam jeszcze problem że w adresie klienta na fakturze pojawia się podwójnie kod pocztowy i miasto. Wygląda to tak:

Klient przykładowy
00-000 Miasto, ulica 123/1
00-000 Miasto 

wersja LMS:
LMS 1.11-git
DB: 2017032000

**Comment by chilek** [comment]
Commit de4a7c5 rozwiązuje problem.
