### ISSUE TITLE
lms-teryt

### ISSUE THREAD

**Issue by mnastalek** [lmsgit/lms#1143]
Nowa instalacja lms, clone z git. 

lms@lms.pl~/web/lms2$ php /var/www/lms/web/lms_git/bin/lms-teryt.php -f
lms-teryt.php
(C) 2001-2017 LMS Developers
Using file /etc/lms/lms.ini as config.
Downloading TERYT files...
Error: Downloaded files: 0. Three expected.

[teryt]
unzip_binary = /usr/bin/unzip
dir = /var/lib/teryt

Ktoś wie co tam nie działa? Jakieś zmiany na stronie gus?

**Comment by chilek** [comment]
Ano - potwierdzam GUS coś zmienił :(

**Comment by chilek** [comment]
Poszła adaptacja do nowego panelu www pobierania plików ZIP/XML z bazami TERYT.
Prośba o testy.

**Comment by mnastalek** [comment]
```
Downloading TERYT files...
PHP Warning:  curl_close() expects parameter 1 to be resource, null given in /var/www/lms/web/lms_git/bin/lms-teryt.php on line 294
PHP Stack trace:
PHP   1. {main}() /var/www/lms/web/lms_git/bin/lms-teryt.php:0
PHP   2. curl_close() /var/www/lms/web/lms_git/bin/lms-teryt.php:294
Unzipping TERYT files...
Downloading https://form.teleinfrastruktura.gov.pl/help-files/baza_punktow_adresowych_2016.zip file...
PHP Warning:  fopen() expects parameter 4 to be resource, null given in /home/lms/web/lms2/bin/lms-teryt.php on line 325
PHP Stack trace:
PHP   1. {main}() /var/www/lms/web/lms_git/bin/lms-teryt.php:0
PHP   2. fopen() /var/www/lms/web/lms_git/bin/lms-teryt.php:325
Unzipping baza_punktow_adresowych_2016.zip file...
```

Wypluło warny ale zadziałało i wygląda na to, że działa ok ;)
