### ISSUE TITLE
Advanced Search Plugin - zaawansowane wyszukiwanie

### ISSUE THREAD

**Issue by kosaa** [lmsgit/lms#1145]
Witam
Ukończyłem właśnie wtyczke do dynamicznego wyszukiwania klientów (i nie tylko) w LMS. Głównym założeniem było pozwolić użytkownikom na wyszukiwanie klientów w oparciu o wiele warunków. Pewne rzeczy są jeszcze do poprawy, ale to co zostało zrobione nadaje się do pokazania. Zapraszam do testowania.

link z istniejącą instalacją:
http://demo.lms.org.pl/?m=as_advancedsearch

git repo:
https://github.com/kosaa/LMS_AdvancedSearchPlugin

**Comment by kolabor** [comment]
Jak to można przetestować bez odpowiednich praw na demo.lms.org.pl? 😢

**Comment by interduo** [comment]
Bardzo fajne! :))))
Fajnie by było gdyby była zakładka faktury oraz dokumenty klienta.

**Comment by kosaa** [comment]
@Ostrymiecz
> Jak to można przetestować bez odpowiednich praw na demo.lms.org.pl? :cry:

zobacze wieczorem co jest nie tak z tymi uprawnieniami - faktycznie logujac sie na demo wywala blad uprawnien

@interduo
>Fajnie by było gdyby była zakładka faktury oraz dokumenty klienta.

wtyczka byla pisana pod katem latwej rozbudowy o nowe kategorie wyszukiwan

min. jakich kryteriow bys potrzebowal ?

**Comment by interduo** [comment]
Lista Faktur:
- nie mogę wylistować faktur z dwóch grup klientów.
- nie mogę wylistować faktur z dwóch planów numeracyjnych.
- nie mogę wylistować faktur utworzonych przez więcej niż 1 użytkownika.

Customersearch:
- nie mogę wylistować klientów z kilku sieci.

**Comment by chilek** [comment]
@kosaa Przejrzałem trochę kod - wygląda na to, że nie ma czegoś takiego jak klasy opisujące ogólny mechanizm działania składnika filtru, np. lista wyboru, lista multiwyboru, wartość z wyborem operatora, itp.
Więc pewnie przy dodawaniu każdego nowego składnika filtru trzeba będzie implementować na nowo mechanikę działania takiego składnika. Czy się mylę?

**Comment by chilek** [comment]
@kosaa 

> zobacze wieczorem co jest nie tak z tymi uprawnieniami - faktycznie logujac sie na demo wywala blad uprawnien

http://demo.lms.org.pl/?m=userinfo&id=1
- użytkownik **admin** (domyślny logujący się) ma uprawnienia tylko do odczytu oraz do dziennika transakcji.
Można ewentualnie dodać we wtyczce obsługę uprawnienia dostępu do _zaawansowanego wyszukiwania_ i nadać to uprawnienie dla **admin**.

**Comment by kosaa** [comment]
| @kosaa Przejrzałem trochę kod - wygląda na to, że nie ma czegoś takiego jak klasy opisujące ogólny mechanizm działania składnika filtru, np. lista wyboru, lista multiwyboru, wartość z wyborem operatora, itp.
Więc pewnie przy dodawaniu każdego nowego składnika filtru trzeba będzie implementować na nowo mechanikę działania takiego składnika. Czy się mylę?

nie mam pojecia, wydaje mi sie, ze na chwile obecna trzyma sie to wszystko kupy, zobaczymy jak wyjdzie podczas utrzymywania wtyczki

**Comment by chilek** [comment]
@kosaa: a wiesz o co mi chodziło?

**Comment by Ostrymiecz** [comment]
@kosaa 
I jak z tymi prawami? Chciałbym zobaczyć wtyczkę.

**Comment by kosaa** [comment]
> @kosaa: a wiesz o co mi chodziło?

wydaje mi sie, ze rozumiem ;P

>@kosaa
I jak z tymi prawami? Chciałbym zobaczyć wtyczkę.

juz zrobione, dodalem uprawnienia
https://github.com/kosaa/LMS_AdvancedSearchPlugin/commit/ae4fd81818efcdf055a8aa9734c6f47baccf9c30

**Comment by interduo** [comment]
To chyba nie powinno było się zamknąć....

**Comment by chilek** [comment]
Raczej powinno, bo @kosaa nie pracuje już dla projektu.
