### ISSUE TITLE
Po zapisaniu edytowanej faktury otwiera się kolejna lista faktur

### ISSUE THREAD

**Issue by prezesk** [lmsgit/lms#1146]
Cześć,
Po zakończeniu edycji faktury z panelu lista faktur po kliknięciu zapisz i drukuj w nowym oknie otwiera się kolejna lista faktur a nie poprawiona faktura.

**Comment by chilek** [comment]
Poprawka poszła do rozwojowej (gałąź 'master') oraz do stabilnych linii 1.11.22.x, 1.11.21.x i 1.11.20.x.
