### ISSUE TITLE
Faktura - Błąd w adresie do wysłki

### ISSUE THREAD

**Issue by Skyspirit9** [lmsgit/lms#1147]
W adresie do wysyłki klientowi pojawia się miasto z adresu siedziby klienta, zamiast z adresu korespondencyjnego. 
Wygląda to tak
Ma być:
44-200 Rybnik
A jest:
44-200 Skoczów

**Comment by chilek** [comment]
Już poprawione w wersji z gałęzi 'master' oraz w stabilnej wersji LMS+ 1.11.22.1.
