### ISSUE TITLE
lms-teryt

### ISSUE THREAD

**Issue by mnastalek** [lmsgit/lms#1148]
Hej ;) 

lms-teryt pobiera listę plików ale nie ładuje ich do bazy: 
`root@lms.xyz.pl:var/web/lms$ php bin/lms-teryt.php -f -l 12
lms-teryt.php
(C) 2001-2017 LMS Developers
Using file /etc/lms/lms.ini as config.
Downloading TERYT files...
Unzipping TERYT files...
Unzipping baza_punktow_adresowych_2016.zip file...
root@lms.xyz.pl:var/web/lms$ php bin/lms-teryt.php -u
lms-teryt.php
(C) 2001-2017 LMS Developers
Using file /etc/lms/lms.ini as config.
Creating TERC cache
Parsing TERC.xml
Loaded 1000
Loaded 2000
Loaded 3000
Loaded 4000
Loaded 4153
TERC inserted/updated/deleted = 0/0/0
Creating SIMC cache
Parsing SIMC.xml
.
.
.tutaj sobie parsuje
.
.
SIMC inserted/updated/deleted = 0/0/0
ULIC inserted/updated/deleted = 0/0/0

`

Pozdrawiam

**Comment by chilek** [comment]
Poprawka:
https://github.com/lmsgit/lms/commit/a1c730f9c1688b963807449fadea40e2419dfbaa
