### ISSUE TITLE
stawka podatkowa "odwrócone opodatkowanie"

### ISSUE THREAD

**Issue by wawryk** [lmsgit/lms#1171]
Po rozmowie z Tomkiem, zakładam taki temat.
Chodzi o to, że potrzebuję takiej stawki i trzeba by było wprowadzić ją do LMS.
Czy ktoś z osób korzystających z systemu też ma takie potrzeby ? 

W moim przypadku, głównym problemem jest sprzedaż złomu elektronicznego, które podlega odwróconemu opodatkowaniu.
Dostawa towarów oraz świadczenie usług, dla których podatnikiem jest nabywca zgodnie z art 17 ust. 1 pkt 7 lub 8 ustawy (wypełnia dostawca).
Samo dodanie napisu "Odwrócone opodatkowanie" na fv nie jest problemem jako takim. Większy problem pojawia się w momencie definiowania stawki podatkowej i późniejszym generowaniu jpk, gdzie taka fakturą w tym momencie ląduje w niewłaściwej kolumnie.

**Comment by chilek** [comment]
@wawryk: czy "oo" dotyczy każdych stawek bazowych VAT oddzielnie?

**Comment by wawryk** [comment]
@chilek 
uwielbiam wypowiedzi księgowych dlatego pozwolę sobie zacytować znowu :D 
"
Stawka potocznie zwana "oo" oznacza odwrotne obciążenie. Jest to sposób rozliczenia VAT poprzez nabywcę usługi polegającą na naliczeniu VAT i odliczeniu VAT praktycznie w tym samym momencie. Może zatem dotyczyć wszystkich stawek VAT "bazowych" czyli 23, 8, 5, 0 procent. 

W przypadku złomu odwrotne obciążenie na fakturze sprzedaży oznacza, że Pani która bierze złom musi naliczyć i odliczyć VAT, a nie MAXNET. Więc MAXNET wystawia im fakturę z OO oznaczającą, iż oni są zobowiązani do dokonania tego rozrachunku i zapłaty MAXNET kwoty netto. MAXNET nie nalicza VAT należnego w przypadku złomu, tj nie płaci go do US.
"
Czyli odpowiadając na twoje pytanie, to tak dotyczy każdej ze stawek bazowych oddzielnie.

**Comment by chilek** [comment]
Załóżmy, że dodajemy dodatkowo wszystkie stawki oddzielnie z nową flagą "oo" (choć nie wiem czy to dobry kierunek).
Następnie wystawiamy fakturę, która jedną pozycję ma na 8% oo, a drugą pozycję na 23% oo.
1. Czy w podsumowaniu stawek na fakturze pokazujemy obydwie stawki 8% oo i 23% oo oddzielnie?
2. Jak rozkładamy kwoty netto 8% oo i 23% oo w rejestrze sprzedaży?
3. Jak rozkładamy kwoty netto 8% oo i 23% oo w w JPK VAT i FAKTURY?
4. Czy pojedyncza faktura może mieć część pozycji oo, a część normalnych?

Zastanawia mnie czy lepiej flagę "oo" umieścić w stawkach podatkowych, a może w fakturach, czy może w pozycjach faktur...

Co na to @interduo ? ;-)

**Comment by interduo** [comment]
Niestety nie orientuje się jak to z OO bo nie miałem okazji jeszcze okazji wystawiać faktur z OO ... ale już niedługo ;-)

**Comment by chilek** [comment]
Mój znajomy, zaufany księgowy jest na urlopie - jego też o to dokładnie zapytam jak wróci.

**Comment by chilek** [comment]
Dobra - jestem po rozmowie - w ogólnym przypadku faktura może mieć mieszane pozycje tzn. część z oo, a część normalnie, więc umieszczenie flagi oo w fakturze jako takiej nie ma sensu. Zostają dwa możliwe warianty: flaga oo w stawkach VAT i flaga oo w pozycjach faktur.

@wawryk: czy w JPK_VAT sprzedaż oo umieszczamy dla danej pozycji w kolumnie K31 i **NIE** uwzględniamy już jej jednocześnie w kolumnach K12-K20?

**Comment by chilek** [comment]
@wawryk: czy podsumowanie kwot w rozbiciu na stawki dla faktury zawierającej pozycje oo odbywa się jedynie w rozbiciu na stawki VAT (bez rozpatrywania oo), czy raczej trzeba traktować stawki oo jako oddzielne stawki, a co za tym idzie tworzyć oddzielne pozycje tabeli podsumowującej?

**Comment by wawryk** [comment]
muszą być oddzielne pozyscje podsumowujące dla oo
wydaje mi się że najlepszym rozwiązaniem jest utworzenie nowej stawki podatkowej w lms o nazwie oo:
![image](https://user-images.githubusercontent.com/15612188/28364735-148ab444-6c86-11e7-868c-45b1f26c3652.png)

co do kolumny w jpk_vat to tak jak napisałeś, robimy to w K_31 i nigdzie więcej wtedy już to nie występuje

**Comment by chilek** [comment]
A czy to nie jest tak, że na fakturze VAT pozycja z oo i tak musi być podana z obowiązującą nabywcę stawką VAT?

**Comment by wawryk** [comment]
Firma wystawiająca fv z oo nie podaje stawki vat.
Tutaj już nabywca musi się rozliczyć zgodnie z prawem co do opodatkowania artykułu ktory kupuje

**Comment by chilek** [comment]
Powyższy commit dodaje do obsługi stawek podatkowych flagę odwróconego obciążenia.
Wkrótce odpowiadająca zmiana w JPK-VAT.

**Comment by chilek** [comment]
@wawryk: testuj.

**Comment by wawryk** [comment]
@chilek 
Dziękuję, wygląda wszystko ok.
Pytanie czy wrzucisz to teraz do stable ? czy narazie nie ?

**Comment by chilek** [comment]
W dniu 20.07.2017 11:23, Maciej Wawryk napisał(a):
> @chilek [1]
> Dziękuję, wygląda wszystko ok.
> Pytanie czy wrzucisz to teraz do stable ? czy narazie nie ?

To zmienia schemat bazy danych więc nie, ale możesz użyć cherry-pick 
trzech commitów
pamiętając o tym, żeby aktualizacje schematu zaraz po cherry-pickach 
zmienić z 2017071900
na 201705120400 (najlepiej przez git mv - potem git będzie Ci pamiętał, 
że już te aktualizacje
pobrałeś i nie pobierze ich ponownie z nazwami 2017071900).

**Comment by wawryk** [comment]
Dzięki za podpowiedź.
Wszystko działa ;)
