### ISSUE TITLE
adresy klienta

### ISSUE THREAD

**Issue by wawryk** [lmsgit/lms#1175]
mamy teraz te pinezki na karcie klienta, gdzie jest możliwość dodania wielu adresów co jest bardzo fajne, ale nie wyszukuje mi tych adresow w quick search 
Ktoś może potwierdzic ? 
bo nie widzę żadnych błedów w logach

**Comment by frychlich** [comment]
wyszukuje jak jest wpisana sama nazwa ulicy, dopisanie nr budynku zwraca puste wyniki

**Comment by wawryk** [comment]
a po samej ulicy to nie wyszukuje głównego adresu ?

**Comment by chilek** [comment]
Prawdopodobnie obydwaj używacie MySQL i stąd problemy.
Sprawdziłem przed chwilą na działającej produkcyjnie wersji rozwojowej - działa wyszukiwanie wg samej ulicy jak również wg ulicy i budynku.
Prawdopodobnie w następnej wersji LMS+ oficjalny support zostanie ograniczony do PostgreSQL, a w jeszcze następnej oficjalny instalator systemu razem z LMS+. Chodzi o to, żeby wsparcie było sensowne, bo przy obecnym rozwiązaniu marnotrawiony jest czas wszystkich na wynajdywanie koła na nowo po raz tysięczny.

**Comment by frychlich** [comment]
Cóż takiego złego jest w mysql/mariadb, że programiści nie potrafią napisać poprawnego kodu pod obie bazy danych?

**Comment by chilek** [comment]
@frychlich: widzę, że lubisz dyskusje akademickie... Było już takich dyskusji w internecie miliony...
Z drugiej strony: dlaczego administrator nie potrafi uruchomić środowiska PostgreSQL? Cóż w nim takiego trudnego?

**Comment by frychlich** [comment]
@chilek bo nikt nie widzi powodu aby z 10 aplikacji dla tylko jeden zmieniać bazę, bo jedna aplikacja ma kod tylko pod psql

**Comment by chilek** [comment]
Dorzuć jeszcze perconę i inne wynalazki...

**Comment by wawryk** [comment]
@chilek 
Akurat u mnie wersja stable na psql ;)

**Comment by chilek** [comment]
@wawryk: a co konkretnie nie działa? Wyszukiwanie w adresach głównych czy innych?
Dodawanie wszelkich możliwych wyszukiwań powoduje, że trudno szuka się czegoś po niewielkiej liczbie znaków.

**Comment by wawryk** [comment]
w quicksearch jak wyszukuje po adresie to adres główny (ten przy domku na karcie klienta) wyszukuje prawidłowo, ale nie działa wyszukiwanie po adresach dodatkowych (tych z pinezkami na karcie klienta)

**Comment by interduo** [comment]
`@chilek bo nikt nie widzi powodu aby z 10 aplikacji dla tylko jeden zmieniać bazę, bo jedna aplikacja ma kod tylko pod psql`

To ja może dołoże coś od siebie. Silnik silnikiem - mysql dopóki nie zyska pełnej transakcyjności to będzie z nim problem. Jeśli trzymasz 10 aplikacji na jednej wirtualce i na jednej bazie to moim zdaniem prosisz się o problemy - prędzej czy później (tak wiem, że się tak da).

Ja jestem za tym, żeby porzucić wsparcie dla jednego z silników. Według mnie lepszy jest postgres.

**Comment by frychlich** [comment]
@interduo dla mnie aplikacja to nawet prosty skrypt, gdzie ktoś klika że klient przyszedł, nie widzę powodu aby dla takich prostych rzeczy stawiać osobnych wirtualek i dla każdej osobnej bazy danych

**Comment by chilek** [comment]
@frychlich: a po co stawiasz linuksa jak można również na windowsie - miałbyś jeszcze mniej wirtualek (czy też fizycznych serwerów) MySQL na windows działa, PHP również ;-)

@interduo mysql będzie wspierany, ale nieoficjalnie bez priorytetu przy poprawkach.

**Comment by frychlich** [comment]
@chilek z takiego samego powodu dla którego "wdepłem" w lms-plus

**Comment by wawryk** [comment]
Fajnie, że znowu się zastanawiamy na tym czy wspierać mysql czy nie, ale to nie wnosi nic do tego czy quicksearch na pgsql działa wszystkim prawidłowo

Napiszę raz jeszcze,
jak klient ma dodanych np. 5 różnych lokalizacji to quicksearch u mnie wyszukuje tylko tej jednej głównej, a inne pomija
ktoś coś ?

**Comment by chilek** [comment]
"Napiszę raz jeszcze,
jak klient ma dodanych np. 5 różnych lokalizacji to quicksearch u mnie wyszukuje tylko tej jednej głównej, a inne pomija
ktoś coś ?"
Prawidłowo - tak było wcześniej jak adresy były przypisane do komputerów. Wyszukiwanie w jednym polu wszystkiego co przyjdzie do głowy spowodowałoby, że pole szybkiego wyszukiwania stałoby się nieużywalne.

**Comment by interduo** [comment]
To może zrobić oddzielną szukajkę dla adresów klienta i oddzielną dla imię/nazwisko/telefon ? Od czasu gdy szukajki chowają się jest na prawdę dużo miejsca.

Moim zdaniem przydałaby się możliwość wyszukiwania po wszystkich lokalizacjach bo często klienci podają adresy placówek zamiast adresów rejestrowych.

**Comment by wawryk** [comment]
@interduo 
moim zdaniem bardzo dobry pomysł

**Comment by chilek** [comment]
> Od czasu gdy szukajki chowają się jest na prawdę dużo miejsca.

"Szukajki" już nie chowają, a jedynie nieco zmniejszają rozmiar. Tylko w stabilnej 1.11.21.x chowały się całkowicie co dla mnie bardzo podobało się, ale było to dość kontrowersyjne w odniesieniu do wielu osób i wrócić podobny wygląd w ostatniej stabilnej.

**Comment by wawryk** [comment]
niestety coś nie działa tak jak powinno (miałem urlop i dopiero teraz testuje);
![image](https://user-images.githubusercontent.com/15612188/29110857-682a216c-7ce8-11e7-8daa-a6819effc536.png)

**Comment by wawryk** [comment]
@chilek testowałeś to wczesniej ?

**Comment by wawryk** [comment]
już wiem, czego zabrakło ;) 
w kilku przypadkach mam zaznaczony domyslny adres lokalizacyjny i tych mi nie wyszukiwało, poprawiłem i jest ok
dzięki ;)
