### ISSUE TITLE
Różne limity długości nazwy grupy dla klientów i komputerów

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#1182]
Można ujednolicić limity długości nazw grup dla klientów i komputerów.

Obecnie długość nazwy grupy dla:
- komputerów to 32 znaki
- klienci to 256 znaki

Sprawdzałem dziś po synchronizacji z repo LMSGIT branch master.

**Comment by chilek** [comment]
@kyob: coś chyba źle szukam  - w pełnym schemacie pgsql i mysql obydwie nazwy są ograniczone do varchar(256). Możesz mi wskazać miejsce w którym znalazłeś ograniczenie do 32 znaków?

**Comment by kyob** [comment]
@chilek Tak grupy klientow to limi 256 znaków, ale grupy komputerów "/?m=nodegroupadd" to nie mogę wpisać więcej niż 32 znaki.
![fireshot capture 18 - ___ lms _nowa grupa ___ - http___192 168 12 2__m nodegroupadd](https://user-images.githubusercontent.com/689112/29211226-19483758-7e98-11e7-8d13-5b2212a6edb5.png)
