### ISSUE TITLE
Informacje dodatkowe do Węzła sieciowego

### ISSUE THREAD

**Issue by frychlich** [lmsgit/lms#1186]
Przydatne byłoby pole tekstowe (tak jak przy urządzeniach sieciowych, komputerach klienta) do węzła sieciowego, w którym można by było zapisać dodatkowe informację przydatne na serwisantów na temat danego węzła, np: jak przyłączony prąd, ewentualnie dodanie pliku z obrazkiem (np: skrzynki z bezpiecznikami i opis który bezpiecznik jest do skrzynki, itp)

**Comment by interduo** [comment]
To już jest w masterze. 
Kiedyś tam dorobiłem - pole notatka.

**Comment by frychlich** [comment]
Pole notatka - super, czekam aż wejdzie do stable.

Przypinanie zgłoszenia RT - dobry ruch, w prosty sposób będzie można weryfikować awaryjność danego węzła.

**Comment by interduo** [comment]
Chyba bardziej, jak wyjdzie kolejne stable.

**Comment by interduo** [comment]
Wdrożone. Możesz sobie wrzucać. Dodatkowo wrzuciłem pola 
"Kontakt administracyjny" i "Ostatni przegląd".

**Comment by interduo** [comment]
Proszę o zamknięcie bo ja nie mogę.

**Comment by interduo** [comment]
Wdrożone. Możesz sobie wrzucać. Dodatkowo wrzuciłem pola 
"Kontakt administracyjny" i "Ostatni przegląd". 
Proszę o zamknięcie bo ja nie mogę.

**Comment by frychlich** [comment]
> Wiadomość napisana przez Interduo <notifications@github.com> w dniu 07.10.2017, o godz. 11:18:
> 
> Wdrożone. Możesz sobie wrzucać. Dodatkowo wrzuciłem pola
> "Kontakt administracyjny" i "Ostatni przegląd".
> Proszę o zamknięcie bo ja nie mogę.
> 
gr8, dzięki
— 

D.Wesołowski
wesoly@klu.pl

**Comment by interduo** [comment]
@chilek proszę zamknij to zgłoszenie.
