### ISSUE TITLE
Powiadomienia - help desk

### ISSUE THREAD

**Issue by Pinki18** [lmsgit/lms#1191]
Mam LMS Plus z okolic maja.
DB: 2017051201

W systemie mam użytkownika, który jest wyłączony.
Był kiedyś przypisany do kolejki w helpdesk.

Zauważyłem, że jak robię zgłoszenie to wysyłane jest do niego powiadomienie o zgłoszeniu.

Oczywiście w konfiguracji kolejki już go odznaczyłem, ale jak ktoś ma dużo użytkowników to wygodniej by było gdyby wyłączenie użytkownika powodowało również zaprzestanie wszystkich akcji z nim związanych jak np. wysyłanie powiadomienia.

**Comment by chilek** [comment]
@Pinki18 przy okazji - zaktualizuj LMS+ do bieżącej wersji z obecnej gałęzi 'stable'. Schemat bazy danych powinien podbić się do **2017051203**.

**Comment by Pinki18** [comment]
Mam Twoja ofertę i czekam na dogodny moment żeby zrobić wszystko o czym pisałem.
