### ISSUE TITLE
10.1.26-MariaDB-0+deb9u1 i LMS 1.11.22 - błędy i nie działający system

### ISSUE THREAD

**Issue by futszak** [lmsgit/lms#1192]
Debian 9 wymusza zamiast mysql-a - MariaDB ale jak bym nie importował bazy (z pliku czy copy-paste) to i tak sypie błędami

ERROR 1071 (42000) at line 240 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 366 in file: 'lms.mysql': Can't create table `lms`.`addresses` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 391 in file: 'lms.mysql': Can't create table `lms`.`customer_addresses` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 406 in file: 'lms.mysql': Can't create table `lms`.`documents` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 461 in file: 'lms.mysql': Can't create table `lms`.`documentcontents` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 477 in file: 'lms.mysql': Can't create table `lms`.`documentattachments` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 494 in file: 'lms.mysql': Can't create table `lms`.`receiptcontents` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 509 in file: 'lms.mysql': Can't create table `lms`.`invoicecontents` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 529 in file: 'lms.mysql': Can't create table `lms`.`debitnotecontents` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 544 in file: 'lms.mysql': Can't create table `lms`.`assignments` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 661 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 675 in file: 'lms.mysql': Can't create table `lms`.`networks` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 703 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 731 in file: 'lms.mysql': Can't create table `lms`.`invprojects` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 744 in file: 'lms.mysql': Can't create table `lms`.`netnodes` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 772 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1071 (42000) at line 784 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 798 in file: 'lms.mysql': Can't create table `lms`.`netdevices` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 836 in file: 'lms.mysql': Can't create table `lms`.`netradiosectors` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 859 in file: 'lms.mysql': Can't create table `lms`.`nodes` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 907 in file: 'lms.mysql': Can't create table `lms`.`nodelocks` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 921 in file: 'lms.mysql': Can't create table `lms`.`macs` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 934 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 959 in file: 'lms.mysql': Can't create table `lms`.`nodeassignments` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 974 in file: 'lms.mysql': Can't create table `lms`.`voipaccounts` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 1071 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 1125 in file: 'lms.mysql': Can't create table `lms`.`voip_cdr` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 1212 in file: 'lms.mysql': Can't create table `lms`.`voip_number_assignments` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 1225 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 1237 in file: 'lms.mysql': Can't create table `lms`.`tariffassignments` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 1252 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1071 (42000) at line 1267 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 1287 in file: 'lms.mysql': Can't create table `lms`.`promotionassignments` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 1361 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 1373 in file: 'lms.mysql': Can't create table `lms`.`customerassignments` (errno: 150 "Foreign key constraint is incorrectly formed
ERROR 1005 (HY000) at line 1426 in file: 'lms.mysql': Can't create table `lms`.`netlinks` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 1449 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 1471 in file: 'lms.mysql': Can't create table `lms`.`rttickets` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 1506 in file: 'lms.mysql': Can't create table `lms`.`rtmessages` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 1533 in file: 'lms.mysql': Can't create table `lms`.`rtrights` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 1548 in file: 'lms.mysql': Can't create table `lms`.`rtattachments` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 1560 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 1573 in file: 'lms.mysql': Can't create table `lms`.`rtcategoryusers` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 1587 in file: 'lms.mysql': Can't create table `lms`.`rtticketcategories` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 1601 in file: 'lms.mysql': Can't create table `lms`.`rtqueuecategories` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 1614 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1071 (42000) at line 1645 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 1665 in file: 'lms.mysql': Can't create table `lms`.`records` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1005 (HY000) at line 1687 in file: 'lms.mysql': Can't create table `lms`.`domainmetadata` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 1713 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1071 (42000) at line 1725 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1071 (42000) at line 1828 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 1843 in file: 'lms.mysql': Can't create table `lms`.`cashimport` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1071 (42000) at line 1828 in file: 'lms.mysql': Specified key was too long; max key length is 767 bytes
ERROR 1005 (HY000) at line 1843 in file: 'lms.mysql': Can't create table `lms`.`cashimport` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR 1146 (42S02) at line 2187 in file: 'lms.mysql': Table 'lms.nodes' doesn't exist
ERROR 1146 (42S02) at line 2194 in file: 'lms.mysql': Table 'lms.macs' doesn't exist
ERROR 1146 (42S02) at line 2198 in file: 'lms.mysql': Table 'lms.addresses' doesn't exist
ERROR 1146 (42S02) at line 2225 in file: 'lms.mysql': Table 'lms.divisions' doesn't exist
ERROR 1146 (42S02) at line 2231 in file: 'lms.mysql': Table 'lms.nodes' doesn't exist
ERROR 1146 (42S02) at line 2241 in file: 'lms.mysql': Table 'lms.assignments' doesn't exist
ERROR 1146 (42S02) at line 2248 in file: 'lms.mysql': Table 'lms.nodes' doesn't exist
ERROR 1146 (42S02) at line 2269 in file: 'lms.mysql': Table 'lms.nodes' doesn't exist
ERROR 1146 (42S02) at line 2285 in file: 'lms.mysql': Table 'lms.vnodes' doesn't exist
ERROR 1146 (42S02) at line 2293 in file: 'lms.mysql': Table 'lms.assignments' doesn't exist
ERROR 1146 (42S02) at line 2312 in file: 'lms.mysql': Table 'lms.nodes' doesn't exist
ERROR 1146 (42S02) at line 2336 in file: 'lms.mysql': Table 'lms.nodes' doesn't exist

wersja bazy ściagnięta pół godziny temu z github-a, więc przynajmiej teoretycznie uwzględnia najnowsze poprawki o których ktoś pisał.
 Efekt zaimportowania bazy w ten sposób jest taki, że strona startowa się wprawdzie ładuje, ale nie można dodać użytkownika, a na dole jest komunikat:

Zapytanie: SELECT keyvalue FROM dbinfo WHERE keytype = 'dbversion'
Błąd: Table 'lms.dbinfo' doesn't exist

Jakieś sugestie ?
Jeśli chodzi o Postgres-a to po 2 godzinach boksowania się z prawami dostępu poddałem się :(

**Comment by interduo** [comment]
Ja uciekam z MySQL'a do postgresa w niedługim czasie. 
Jeśli chodzi o odpalenie praw na postgresie zerknij w pg_hba.conf

Mój wygląda np. tak:
# cat pg_hba.conf
# PostgreSQL Client Authentication Configuration File
# ===================================================
#local  all     postgres        peer
local   all     all     trust
host    all     all     127.0.0.1/32    password

# psql -U postgres
psql (9.6.4)
Wpisz "help" by uzyskać pomoc.

**Comment by chilek** [comment]
Proponuję testować na bieżącej wersji z LMS. Numerowane wersje LMS nie są wspierane w żadnym zakresie.
