### ISSUE TITLE
[Karta klienta] Znika kontakt, jeśli zaznaczymy tylko "powiadomienia"

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#1196]
Sprawdzałem z MySQL oraz PostgreSQL.

Scenariusz:

Krok 1 edytuje klienta:
![1](https://user-images.githubusercontent.com/689112/31720282-6614adf6-b416-11e7-8746-fa812e2f75c6.png)

Krok 2 zaznaczam tylko **powiadomienia**:
![2](https://user-images.githubusercontent.com/689112/31720313-81dc15ce-b416-11e7-8155-75e8da86d681.png)

Krok 3 zapisuje i kontakt znika. W bazie istnieje z **type = 32**, ale nie wyświetla na karcie.
![3](https://user-images.githubusercontent.com/689112/31720366-b40e890a-b416-11e7-8762-ee48949f4ff2.png)

**Comment by chilek** [comment]
Poprawione w master i stable,stable-1.11.21 LMS+
