### ISSUE TITLE
Brak pola channelid w ewx_stm_channels

### ISSUE THREAD

**Issue by prezeskk** [lmsgit/lms#1198]
https://github.com/lmsgit/lms/blob/eb5388e59eb2b761969fdffe402d39a1d9e1b64f/lib/upgradedb/mysql.2017101600.php#L29

Nie powinno tu byc **ewx_stm_nodes** zamiast **ewx_stm_channels** ?

**Comment by chilek** [comment]
Jeśli tak jest w pgsql to i tak samo powinno być w mysql.
3dadf6655
