### ISSUE TITLE
Dodawanie nowej taryfy

### ISSUE THREAD

**Issue by noyo-pl** [lmsgit/lms#1199]
```
Wersja LMS: | 1.11-git (2017-10-23T22:25:45+02:00)
Wersja LMSDB: | 1.11-git
Wersja MySQL: | 10.1.21-MariaDB-1~wheezy
Wersja PHP: | 5.4.45-0+deb7u7
Wersja Smarty: | 3.1.31
```

Przy dodawaniu nowej taryfy, ale nie mając dodanej żadnej stawki podatkowej, nie krzyczy o błedzie tylko przechodzi do listy taryf bez zapisana taryfy.

**Comment by chilek** [comment]
Sprawdź z bieżącą wersją master. Zmienia się z dnia na dzień ;-)
