### ISSUE TITLE
DELETE FROM cash ?

### ISSUE THREAD

**Issue by prezeskk** [lmsgit/lms#1200]
https://github.com/lmsgit/lms/blob/7afc258eca28830cd74edf710bf446a36c7a7a4c/lib/upgradedb/mysql.2017101202.php#L233

Czy ta linia powinna tak wyglądać? Jeśli mamy puste `$ids = $this->GetCol("SELECT id FROM cashimport");` to usuwa całą historie wpłat!

Czy nie powinna wyglądać tak?
```
$ids = $this->GetCol("SELECT id FROM cashimport");
if (empty($ids)) {
    $this->Execute("UPDATE cash SET importid = NULL");
} else {
    $sql_ids = implode(',', $ids);
    $this->Execute("UPDATE cash SET importid = NULL WHERE importid NOT IN (" . $sql_ids . ")");
}
```

**Comment by chilek** [comment]
Jest źle, a to co proponujesz też nie będzie dobrze.
Cel tego był taki, żeby usuwać wszystkie rekordy cash, które mają importid wskazujący na nieistniejące rekordy cashimport. Zaraz to trochę poprawię. Dziękuję za wnikliwą analizę Panie Prezesie!

**Comment by chilek** [comment]
12955af72cf0eddb05c592ac21fe4b1c8eacae37
