### ISSUE TITLE
Umowa z LMS - jeden klient, różne pakiety/lokalizacje

### ISSUE THREAD

**Issue by zetorzeszow** [lmsgit/lms#1202]
Hej,
jest możliwość aby wygenerować umowę z poziomu LMS zawierającą podstawowe dane klienta + dodatkowo dane instalacji?

Mam tu na myśli przypadek w którym na jednego klienta podpisane są dwie odrębne umowy na świadczenie usług w 2ch różnych lokalizacjach.
np.
Dane podstawowe: Jan Nowak, 00-000 Warszawa ul. Kwiatowa 1/2
Dane dodatkowe (każde na osobnej umowie)
- Pakiet 10Mbit - Adres instalacji 11-111 Gdańsk, ul. Pomorska 20/22
- Pakiet 30Mbit - Adres instalacji 22-222 Poznań, ul. Lubelska 30/33

**Comment by interduo** [comment]
Plugin contract-promo z projektu LMSplus to umożliwia.  Goły LMS nie. 
https://github.com/lmsgit/lms/wiki/Informacje-o-projekcie-LMS-Plus

**Comment by zetorzeszow** [comment]
Dzięki, właśnie odpalam plusa. Powiedz mi prosze jak wygląda  jeszcze sytuacja z generowaniem protokołów odnośnie urządzeń?

**Comment by zetorzeszow** [comment]
A druga kwestia, rozbicie FV per lokalizacje?
Domyślnie  jeżeli FV jest wystawiana 1go dla każdej lokalizacji to wychodzi jako jedna.
Co w przypadku gdy klient chce mieć każdą lokalizacje na osobnej FV?

**Comment by interduo** [comment]
Klep na listę pytania.
W zobowiązaniu możesz zaznaczyć "oddzielna faktura".
