### ISSUE TITLE
Błąd przy dodawaniu użytkownika

### ISSUE THREAD

**Issue by Grejeru** [lmsgit/lms#1211]
Zainstalowałem LMS z gita wg instrukcji na stronie (świeża instalacja).
Przy robieniu `source doc/lms.mysql` wyskoczyło kilka błędów, które przy okazji mają wpływ na dodawanie klienta

Błędy przy source:
```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '------------------------------------------------------

CREATE TABLE liabiliti' at line 1
ERROR 1005 (HY000): Can't create table 'lms.assignments' (errno: 150)
ERROR 1005 (HY000): Can't create table 'lms.voip_number_assignments' (errno: 150)

ERROR 1005 (HY000): Can't create table 'lms.nodeassignments' (errno: 150)

ERROR 1146 (42S02): Table 'lms.assignments' doesn't exist
ERROR 1146 (42S02): Table 'lms.nodeassignments' doesn't exist
ERROR 1146 (42S02): Table 'lms.vnodetariffs_tariffs' doesn't exist

ERROR 1146 (42S02): Table 'lms.assignments' doesn't exist
ERROR 1146 (42S02): Table 'lms.vnodetariffs_tariffs' doesn't exist
```

Do tego spora część Queries zawiera warningi.

Błąd przy dodawaniu klienta (klient dodany pomyślnie pomimo tego):

```
Wystąpiły błędy w obsłudze bazy danych!
Zapytanie: SELECT a.id AS id, a.tariffid, a.customerid, a.period, a.at, a.suspended, a.invoice, a.settlement, a.datefrom, a.dateto, a.pdiscount, a.vdiscount, a.attribute, a.liabilityid, t.uprate, t.upceil, t.downceil, t.downrate, t.type AS tarifftype, (CASE WHEN t.value IS NULL THEN l.value ELSE t.value END) AS value, (CASE WHEN t.name IS NULL THEN l.name ELSE t.name END) AS name, d.number AS docnumber, d.type AS doctype, d.cdate, np.template FROM assignments a LEFT JOIN tariffs t ON (a.tariffid = t.id) LEFT JOIN liabilities l ON (a.liabilityid = l.id) LEFT JOIN documents d ON d.id = a.docid LEFT JOIN numberplans np ON np.id = d.numberplanid WHERE a.customerid=1 AND a.commited = 1 AND (a.dateto > 1510441200 OR a.dateto = 0) AND (a.at >= 1510441200 OR a.at < 531) ORDER BY a.datefrom, t.name, value
Błąd: Table 'lms.assignments' doesn't exist
```

**Comment by interduo** [comment]
Z tego co się orientuje Twórca niechętnie wspiera MySQL. Zapewne używasz MariaDB ?
Jeśli to możliwe spróbuj postawić postgresql lub jeśli Ci zależy obligatoryjnie na MySQL mocno to wersję z gałęzi stabilnej.

**Comment by Grejeru** [comment]
@interduo zacząłem od wersji stabilnej, niestety jest tam też bug z brakującymi polami w bazie danych przez co nie można dodać żadnej firmy, poprawka jest w niewypuszczonej wersji 1.11.22.1 oraz w masterze... Jak widać ogólnie LMS jest aktualnie nieużywalny dla tych co chcą go teraz ściągnąć i zainstalować.

**Comment by interduo** [comment]
Proponuję spróbować na postgresie, sam instalowałem niedawno na testowej instancji i nie miałem problemów o których piszesz.

**Comment by Grejeru** [comment]
@interduo nie chce mi się stawiać specjalnie postgresa zanim nie zdecyduję czy chcę używać.
Co zabawne klient dodany, ale już wylistowanie go nie jest możliwe, znalazłem sobie obejście, bo po dodaniu komputera i przypisania klientowi mogę wrócić do widoku klienta, bo nie działa zarówno wyszukiwanie, jak i listowanie klientów.

**Comment by interduo** [comment]
Jak chcesz się pobawić to na https://demo.lms.org.pl admin/test masz też wystawione demo.

**Comment by Grejeru** [comment]
@interduo widziałem, ale w kilku miejscach było permission denied ;-)

**Comment by interduo** [comment]
To może przeklej sobie brakujące pola z postgresa lub Cofnij się gitem na przykład o trzy tygodnie. (?)

**Comment by chilek** [comment]
Codziennie a nocy są wykonywane automatyczne testy schematów mysql i pgsql i obecna wersja w master LMS-a przechodzi je bez problemów.

**Comment by Grejeru** [comment]
@chilek dwukrotnie dropowałem bazę i zakładałem wg instrukcji w dokumentacji instalacyjnej, za każdym razem te same błędy.

```
[root@gniotek] 22:17:59
(master) /srv/www/lms # git branch
* master
[root@gniotek] 22:18:04
(master) /srv/www/lms # git pull
Already up-to-date.
[root@gniotek] 22:19:11
(master) /srv/www/lms # mysql -V
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
```

**Comment by chilek** [comment]
@Grejeru proponuję podbić mysql do co najmniej 5.5, a najlepiej od razu mariadb.
5.1.73 to staroć pozbawiona wsparcia bezpieczeństwa przez producenta.

**Comment by Grejeru** [comment]
@chilek później zerknę czy jest różnica na wyższej wersji MySQL/MariaDB, bo tak jak dla Postgresa, tak dla Marii nie mam potrzeby stawiać na moment w środowisku domowym kolejnej bazki ;-)

**Comment by chilek** [comment]
@Grejeru testy poprawności (automatyczne) wykonywane są na 10.1.26-MariaDB.

**Comment by Grejeru** [comment]
@chilek to postaram się znaleźć w tygodniu czas na instalację Marii i zobaczyć czy to pomoże.

**Comment by chilek** [comment]
Powyższy commit naprawia błędny komentarz z perspektywy MySQL 5.1.

**Comment by interduo** [comment]
@Grejeru tak btw widzę, że grupowicze SysOp/DevOps wszędzie są :-))))

**Comment by Grejeru** [comment]
@interduo ano są, ale co się dziwić, akurat soft mocno zbieżny z tematyką grupy ;-)
