### ISSUE TITLE
Zły warunek w MultiExecute 

### ISSUE THREAD

**Issue by MKaciuba** [lmsgit/lms#1217]
https://github.com/lmsgit/lms/blob/2c4f7692fd35100f7aa5502d5d0c4d4dc7966db0/lib/LMSDB_common.class.php#L161
LMSDB_driver_mysqli._driver_multi_execute zwraca true jeśli wystąpi błąd i false w przeciwnym przypadku. Tutaj warunek jest zanegowany co skutkuje wyświetleniem komunikatu o błędzie, którego nie ma.

**Comment by chilek** [comment]
@MKaciuba rzuć proszę okiem czy powyższy commit rozwiązuje problem? TRUE - będzie oznaczać ok, FALSE - błąd sql.

**Comment by MKaciuba** [comment]
Wygląda że będzie ok ale nie sprawdzałem jak jest w driverze postgresa.

**Comment by chilek** [comment]
Driver pgsql przekazuje wywołanie _driver_multi_execute od razu do _driver_execute:
https://github.com/lmsgit/lms/blob/master/lib/LMSDB_driver_postgres.class.php#L182-L186
więc nic tu się nie zmieniło.
