### ISSUE TITLE
Export sprzedaży błedy w stawkach vat 

### ISSUE THREAD

**Issue by alkar1** [lmsgit/lms#1218]
W związku z uruchomieniem TV , pojawiła się u nas w sprzedaży stawka 8%.
Od tego czasu w eksporcie kwoty netto,vat 23% eksportuja się jako 8% a kwoty 8% jako 23%.
Fragment exportcfg.php:
`$inv_record[0] = '%I|%TYPE|%NUMBER|%DATE|%DATE|%DEADLINE|';
$inv_record[1] = '%CID|%CUSTOMER|%ADDRESS|%ZIP|%CITY|%TEN|';
$inv_record[2] = '%NETTO3|';//stawka 3 to jest 0%
$inv_record[3] = '%NETTO2|%VAT2|';//stawka 2 to jest 7%
$inv_record[4] = '%NETTO4|%VAT4|';//stawka 4 to jest 8%
$inv_record[5] = '%NETTO1|%VAT1|';//stawka 1 to jest 22%
$inv_record[6] = '%NETTO5|%VAT5|';//stawka 5 to jest 23%
$inv_record[7] = '%VALUE';`

Wg. mnie w export.php zamiast:
`				$v = 0;
				$netto_v = 0;
				$tax_v = 0;

				foreach($rectax as $id => $tax)
				{
					$v++;
					$line = str_replace('%VATP'.$v, form_num($taxes[$id]['value']), $line);
					$line = str_replace('%TAXED'.$v, form_num($taxes[$id]['taxed']), $line);
					$line = str_replace('%VAT'.$v, form_num($tax['tax']), $line);
					$line = str_replace('%NETTO'.$v, form_num($tax['val']), $line);

					$netto_v += $tax['val'];
					$tax_v += $tax['tax'];
				}

				for($x=$v+1; $x<=8; $x++)
				{
					$line = str_replace('%VATP'.$x, '0.00', $line);
					$line = str_replace('%VAT'.$x, '0.00', $line);
					$line = str_replace('%NETTO'.$x, '0.00', $line);
					$line = str_replace('%TAXED'.$x, '0.00', $line);
				}
`
powinno być :
`				$netto_v = 0;
				$tax_v = 0;

				foreach($rectax as $id => $tax)
				{
					$line = str_replace('%VATP'.$id, form_num($taxes[$id]['value']), $line);
					$line = str_replace('%TAXED'.$id, form_num($taxes[$id]['taxed']), $line);
					$line = str_replace('%VAT'.$id, form_num($tax['tax']), $line);
					$line = str_replace('%NETTO'.$id, form_num($tax['val']), $line);

					$netto_v += $tax['val'];
					$tax_v += $tax['tax'];
				}

				for($x=1; $x<=8; $x++)
				{
					$line = str_replace('%VATP'.$x, '0.00', $line);
					$line = str_replace('%VAT'.$x, '0.00', $line);
					$line = str_replace('%NETTO'.$x, '0.00', $line);
					$line = str_replace('%TAXED'.$x, '0.00', $line);
				}
`

**Comment by chilek** [comment]
Proponowane przez Ciebie rozwiązanie załatwi sprawę pewnie tylko u Ciebie. U innych zmieni obecny problem na inny ;-)
