### ISSUE TITLE
lmsd - payments nie generuje faktur dla klientów bez przypisanego kraju.

### ISSUE THREAD

**Issue by darton** [lmsgit/lms#1220]
Wersja LMS: | 1.11-git
Wersja LMSDB: | 2017112200
Wersja MySQL: | 5.5.56-MariaDB
Wersja PHP: | 5.4.16
Wersja Smarty: | 3.1.31

lmsd - payments nie generuje faktur dla klientów bez przypisanego kraju.

Po przypisaniu kraju problem znika.

p.s.
Możliwe że przyczyną jest to, że kolumna country_id tabeli addresses, ma zadeklarowaną wartość domyślną jako NULL, co powoduje, że nie zwracana jest żadna wartość. Gdyby nie miała zadeklarowanej żadnej wartości domyślnej zwracany byłby pusty ciąg ' ', co pozwoliłoby uniknąć problemu i nie wymagało dodatkowych nakładów pracy po stronie oprogramowania do obsłużenia sytuacji braku przypisania kraju.

**Comment by chilek** [comment]
lmsd nie jest wspieranym rozwiązaniem. Przesiądź się na lms-payments.php.

**Comment by darton** [comment]
Ups ... coś mi umknęło :-). Może by zrobić folder np legacy dla tych nie wspieranych rozwiązań i tam je przenieść ?

**Comment by darton** [comment]
A tu jest winowajca :-) https://github.com/lmsgit/lms/commit/7929cde5644ddf20df27917c3ee6a662b744cc9d#diff-f281b88087d60d5242075112da44869d

Byłem pewny że to działało jeszcze parę miesięcy temu :-).

**Comment by chilek** [comment]
Ale 0 też będzie źle, bo 0 będzie błędem niespełnionego ograniczenia wynikającego z klucza obcego
(być może MySQL dopuszcza takie bzdury).

**Comment by darton** [comment]
Tak 0 bedzie źłe. Ale to było nawiązanie do tego że tak jak pisałem wcześniej, dawniej domyślna wartość kolumny country_id tabeli addresses była nieustawiona (podobnie jak nie jest ustawiona domyślna wartość  dla kolumny o nazwie "ten") co powodowało że lmsd generował wtedy pusty ciąg czyli ' ' i zapewniało poprawność składni INSERTU.
Po ustawieniu domyślnej wartości kolumny country_id  na NULL, lmsd nie generuje żadnej wartości co powoduje błąd przy insercie wynikający z błędnej składni INSERTU.  
Przywrócenie więc poprzedniego stanu czyli braku wartości domyślnej dla komuny country_id tabeli addresses rozwiąże problem dla lmsd, bo i tak może to być obsłużone programowo w lms-payments.php

**Comment by chilek** [comment]
Jeśli już lepiej poprawić w daemon/payments. Z drugiej strony nie wiem po co kurczowo trzymać się czegoś co jest przestarzałe.

**Comment by darton** [comment]
Raczej chodzi o to żeby przypadkowo, w jakiejś trywialnej sprawie nie psuć tego co działa. 
Z drugiej strony chyba nie ma gotowego narzędzia, które pozwoliłoby odwzorować pełną funkcjonalność lmsd w prosty sposób. Chyba że znowu coś przeoczyłem. I jest jakiś gotowy lms-agent.php
który odpalany w cronie odwali za niego robotę. 

Bo jeśli już porzucać lmsd, to trzeba być coś dać kompletnego w zamian, i w konsekwencji usunąć obsługę nie wspieranego rozwiązania z gui.

**Comment by chilek** [comment]
> Bo jeśli już porzucać lmsd, to trzeba być coś dać kompletnego w zamian, i w konsekwencji usunąć obsługę nie wspieranego rozwiązania z gui.

A przygotujesz coś kompletnego?

**Comment by chilek** [comment]
Daemon to zbyteczna redundancja kodu i wywarzanie otwarty drzwi - jedyne do czego jest on jeszcze używalny to EtherWerX.

**Comment by darton** [comment]
Do tej pory tak samo myślałem o zbieraninie skryptów perl/php, które próbowały odtworzyć to co potrafi lmsd.

**Comment by darton** [comment]
Ale faktem jest, że co jak co. ale wystawianie faktur według zobowiązań okresowych powinno być integralną częścią LMS-a, gotowe do pracy od razu. Tak by po instalacji LMS-a  faktury do zobowiązań okresowych od razu się wystawiały. Dlatego przydałoby się coś takiego jak nazwijmy to roboczo lms-scheduler.php,, który byłby uruchamiany przez crona co minutę. I bo byłoby jedyne co byłoby konieczne by LMS i jego moduły/pluginy php potrafiły wykonywać okresowo zadania.  Domyślnie od razu sterowałby pracą np lms-payments.php. Wtedy lmsd mółby przejść na zasłużoną emeryturę. A ktoś używa jeszcze etherwerxa w dzisiejszych czasach ?
