### ISSUE TITLE
Występuje błąd gdy podczas korzystania z pola wyszukaj klienta, po wpisaniu frazy wciśnie się enter.

### ISSUE THREAD

**Issue by darton** [lmsgit/lms#1221]
Wersja LMS: | 1.11-git
Wersja LMSDB: | 2017112200
Wersja MySQL: | 5.5.56-MariaDB
Wersja PHP: | 5.4.16
Wersja Smarty: | 3.1.31

Wystąpiły błędy w obsłudze bazy danych!
Zapytanie: SELECT c.id AS id, CONCAT(UPPER(lastname), ' ', c.name) AS customername, status, full_address, address, zip, city, countryid, countries.name AS country, cc.email, ccp.phone, ten, ssn, c.info AS info, extid, message, c.divisionid, c.paytime AS paytime, COALESCE(b.value, 0) AS balance, COALESCE(t.value, 0) AS tariffvalue, s.account, s.warncount, s.online, (CASE WHEN s.account = s.acsum THEN 1 WHEN s.acsum > 0 THEN 2 ELSE 0 END) AS nodeac, (CASE WHEN s.warncount = s.warnsum THEN 1 WHEN s.warnsum > 0 THEN 2 ELSE 0 END) AS nodewarn FROM customerview c LEFT JOIN (SELECT customerid, (GROUP_CONCAT(contact SEPARATOR ',')) AS email FROM customercontacts WHERE (type & 8 > 0) GROUP BY customerid) cc ON cc.customerid = c.id LEFT JOIN (SELECT customerid, (GROUP_CONCAT(contact SEPARATOR ',')) AS phone FROM customercontacts WHERE (type & 5 > 0) GROUP BY customerid) ccp ON ccp.customerid = c.id LEFT JOIN countries ON (c.countryid = countries.id) LEFT JOIN (SELECT SUM(value) AS value, customerid FROM cash GROUP BY customerid ) b ON (b.customerid = c.id) LEFT JOIN (SELECT a.customerid, SUM((CASE a.suspended WHEN 0 THEN (((100 - a.pdiscount) * (CASE WHEN t.value IS null THEN l.value ELSE t.value END) / 100) - a.vdiscount) ELSE ((((100 - a.pdiscount) * (CASE WHEN t.value IS null THEN l.value ELSE t.value END) / 100) - a.vdiscount) * 0 / 100) END) * (CASE t.period WHEN 3 THEN 1 WHEN 5 THEN 1/12.0 WHEN 7 THEN 1/6.0 WHEN 4 THEN 1/3.0 ELSE (CASE a.period WHEN 3 THEN 1 WHEN 5 THEN 1/12.0 WHEN 7 THEN 1/6.0 WHEN 4 THEN 1/3.0 ELSE 0 END) END) ) AS value FROM assignments a LEFT JOIN tariffs t ON (t.id = a.tariffid) LEFT JOIN liabilities l ON (l.id = a.liabilityid AND a.period != 0) WHERE a.commited = 1 AND a.datefrom <= UNIX_TIMESTAMP() AND (a.dateto > UNIX_TIMESTAMP() OR a.dateto = 0) GROUP BY a.customerid ) t ON (t.customerid = c.id) LEFT JOIN (SELECT ownerid, SUM(access) AS acsum, COUNT(access) AS account, SUM(warning) AS warnsum, COUNT(warning) AS warncount, (CASE WHEN MAX(lastonline) > UNIX_TIMESTAMP() - 600 THEN 1 ELSE 0 END) AS online FROM nodes WHERE ownerid > 0 AND ipaddr <> 0 GROUP BY ownerid ) s ON (s.ownerid = c.id) WHERE c.deleted = 0 AND (CONCAT(UPPER(c.lastname), ' ', UPPER(c.name)) LIKE UPPER('%aaaaaa%') OR (UPPER(address) LIKE UPPER('%aaaaaa%') OR UPPER(post_address) LIKE UPPER('%aaaaaa%') OR EXISTS (SELECT 1 FROM customer_addresses ca JOIN vaddresses va ON va.id = ca.address_id AND ca.customer_id = c.id WHERE UPPER(va.address) LIKE UPPER('%aaaaaa%'))) OR (UPPER(zip) LIKE UPPER('%aaaaaa%') OR UPPER(post_zip) LIKE UPPER('%aaaaaa%') OR EXISTS (SELECT 1 FROM customer_addresses ca JOIN vaddresses va ON va.id = ca.address_id AND ca.customer_id = c.id WHERE UPPER(va.zip) LIKE UPPER('%aaaaaa%'))) OR (UPPER(city) LIKE UPPER('%aaaaaa%') OR UPPER(post_city) LIKE UPPER('%aaaaaa%') OR EXISTS (SELECT 1 FROM customer_addresses ca JOIN vaddresses va ON va.id = ca.address_id AND ca.customer_id = c.id WHERE UPPER(va.city) LIKE UPPER('%aaaaaa%'))) OR EXISTS (SELECT 1 FROM customercontacts WHERE customerid = c.id AND customercontacts.type & 8 = 8 AND contact LIKE '%aaaaaa%')) ORDER BY customername asc
Błąd: Unknown column 'c.id' in 'on clause'

**Comment by chilek** [comment]
Wchodzę na:
http://demo.lms.org.pl/?m=customersearch
wpisuję w nazwa/nazwisko klienta literkę a i wciskam ENTER.
Opisywany problem nie występuje.

**Comment by darton** [comment]
Może tu jest problem.
Robiłem kilka niezależnych instalacji lms z cvs a potem wrzucałem bazę z paroma tysiącami klientów/komputerów i po wpisaniu kilku znaków np  aaaaa i szybkim naciśnięciu enter zanim js zdążył wykonać kwerendę sql  problem występował za każdym razem. Bez naciskania enter'a (ręcznego wywołania przeładowania) problemu nie ma.

**Comment by darton** [comment]
Przed chwilą zrobiłem czystą instalację LMS na virtualce, z czterem testowymi użytkownikami. W polu wyszukiwania użytkownika wpisałem szybko aaaaa i nacisnąłem enter. Problem występuje w sposób powtarzalny.

**Comment by interduo** [comment]
U nas ten problem na MySQL występuje sporadycznie i nie potrafimy go odwzorować.

**Comment by darton** [comment]
Możliwe, że MariaDB oraz  MySQL  w wersji 5.5.x jest bardziej restrykcyjne w kwestiach przestrzegania norm ANSI  w składni zapytań.  I trzeba będzie dostosować zapytanie.

**Comment by chilek** [comment]
> Możliwe, że MariaDB oraz MySQL w wersji 5.5.x jest bardziej restrykcyjne w kwestiach przestrzegania norm ANSI w składni zapytań. I trzeba będzie dostosować zapytanie.

To co udało się dostosować zapytanie do norm ISO? ;-)

Rozłożenie zapytania na czynniki pierwsze używają eleganckiego formatowania SQL:
```sql
SELECT c.id AS id, CONCAT(UPPER(lastname), ' ', c.name) AS customername, status,
	full_address, address, zip, city, countryid, countries.name AS country,
	cc.email, ccp.phone, ten, ssn, c.info AS info, extid, message, c.divisionid,
	c.paytime AS paytime, COALESCE(b.value, 0) AS balance, COALESCE(t.value, 0) AS tariffvalue,
	s.account, s.warncount, s.online,
	(CASE WHEN s.account = s.acsum THEN 1 WHEN s.acsum > 0 THEN 2 ELSE 0 END) AS nodeac,
	(CASE WHEN s.warncount = s.warnsum THEN 1 WHEN s.warnsum > 0 THEN 2 ELSE 0 END) AS nodewarn
FROM customerview c
LEFT JOIN (
	SELECT customerid, (GROUP_CONCAT(contact SEPARATOR ',')) AS email
	FROM customercontacts
	WHERE (type & 8 > 0)
	GROUP BY customerid
) cc ON cc.customerid = c.id
LEFT JOIN (SELECT customerid, (GROUP_CONCAT(contact SEPARATOR ',')) AS phone
	FROM customercontacts
	WHERE (type & 5 > 0)
	GROUP BY customerid
) ccp ON ccp.customerid = c.id
LEFT JOIN countries ON (c.countryid = countries.id)
LEFT JOIN (
	SELECT SUM(value) AS value, customerid
	FROM cash GROUP BY customerid
) b ON (b.customerid = c.id)
LEFT JOIN (SELECT a.customerid,
	SUM((CASE a.suspended WHEN 0 THEN (((100 - a.pdiscount) * (CASE WHEN t.value IS null THEN l.value ELSE t.value END) / 100) - a.vdiscount)
		ELSE ((((100 - a.pdiscount) * (CASE WHEN t.value IS null THEN l.value ELSE t.value END) / 100) - a.vdiscount) * 0 / 100) END)
		* (CASE t.period WHEN 3 THEN 1 WHEN 5 THEN 1/12.0 WHEN 7 THEN 1/6.0 WHEN 4 THEN 1/3.0 ELSE (CASE a.period WHEN 3 THEN 1 WHEN 5 THEN 1/12.0 WHEN 7 THEN 1/6.0 WHEN 4 THEN 1/3.0 ELSE 0 END) END) ) AS value
	FROM assignments a
	LEFT JOIN tariffs t ON (t.id = a.tariffid)
	LEFT JOIN liabilities l ON (l.id = a.liabilityid AND a.period != 0)
	WHERE a.commited = 1 AND a.datefrom <= UNIX_TIMESTAMP()
		AND (a.dateto > UNIX_TIMESTAMP() OR a.dateto = 0)
	GROUP BY a.customerid
) t ON (t.customerid = c.id)
LEFT JOIN (
	SELECT ownerid, SUM(access) AS acsum, COUNT(access) AS account,
		SUM(warning) AS warnsum, COUNT(warning) AS warncount,
		(CASE WHEN MAX(lastonline) > UNIX_TIMESTAMP() - 600 THEN 1 ELSE 0 END) AS online
	FROM nodes
	WHERE ownerid > 0 AND ipaddr <> 0
	GROUP BY ownerid
) s ON (s.ownerid = c.id)
WHERE c.deleted = 0
	AND (CONCAT(UPPER(c.lastname), ' ', UPPER(c.name)) LIKE UPPER('%aaaaaa%')
		OR (UPPER(address) LIKE UPPER('%aaaaaa%')
			OR UPPER(post_address) LIKE UPPER('%aaaaaa%')
			OR EXISTS (
				SELECT 1 FROM customer_addresses ca
				JOIN vaddresses va ON va.id = ca.address_id AND ca.customer_id = c.id
				WHERE UPPER(va.address) LIKE UPPER('%aaaaaa%')
			)
		)
		OR (UPPER(zip) LIKE UPPER('%aaaaaa%')
			OR UPPER(post_zip) LIKE UPPER('%aaaaaa%')
			OR EXISTS (
				SELECT 1 FROM customer_addresses ca
				JOIN vaddresses va ON va.id = ca.address_id AND ca.customer_id = c.id
				WHERE UPPER(va.zip) LIKE UPPER('%aaaaaa%')
			)
		)
		OR (UPPER(city) LIKE UPPER('%aaaaaa%')
			OR UPPER(post_city) LIKE UPPER('%aaaaaa%')
			OR EXISTS (
				SELECT 1 FROM customer_addresses ca
				JOIN vaddresses va ON va.id = ca.address_id AND ca.customer_id = c.id
				WHERE UPPER(va.city) LIKE UPPER('%aaaaaa%')
			)
		)
		OR EXISTS (
			SELECT 1 FROM customercontacts
			WHERE customerid = c.id AND customercontacts.type & 8 = 8
				AND contact LIKE '%aaaaaa%'
		)
	)
ORDER BY customername asc;
```
Problem w MySQL/MariaDB/PerconaDB powodują podzapytania w **OR EXISTS**, który używają tabeli **c**...

**Comment by chilek** [comment]
Proszę o weryfikację poprawki:
https://github.com/lmsgit/lms/pull/1224

**Comment by krzysztofpuchala** [comment]
U mnie ok, po zastosowaniu poprawki.

**Comment by chilek** [comment]
@krzysztofpuchala dzięki za informację zwrotną. Pytanie czy pokazuje sensowną listę klientów.

**Comment by krzysztofpuchala** [comment]
Raczej tak, poszukałem po adresach i imionach ilość wyników wydaje się być poprawna.
