### ISSUE TITLE
Nowa instalacja z git - brak możliwości tworzenia kopii zapasowych z panelu + błąd divisionadd (znowu) 

### ISSUE THREAD

**Issue by mnastalek** [lmsgit/lms#1225]
Nie działa backup bazy z panelu, nie wywala żadnych błędów. Po prostu backup się nie tworzy.  
Nie da się dodać firmy (divisionadd, formularz znika bez błędów wracamy do Brak firm w bazie danych.) 

Pozdrawiam

**Comment by interduo** [comment]
Zerknij w loga postgresa/mysql i apache2. 
Włącz wyświetlanie błędów w php.

**Comment by chilek** [comment]
> Nie działa backup bazy z panelu, nie wywala żadnych błędów. Po prostu backup się nie tworzy.

Być może brak backup_dir w lms.ini.
