### ISSUE TITLE
JPK_VAT 3

### ISSUE THREAD

**Issue by noyo-pl** [lmsgit/lms#1228]
Witam
Chyba nie zmodyfikowaliście lmsa pod wersje 3 JPK_VAT, czy się mylę?

**Comment by noyo-pl** [comment]
Niestety poświęciłem noc i dopisałem JPK_VAT v3. Troche tych zmian jest, ale i troche uproszczeń.

**Comment by chilek** [comment]
Brawo. Wersja JPK-VAT v3 jest dostępna w ramach LMS+. Za jakiś czas będzie dostępna w LMS.
Dlaczego tak? Bo użytkownicy finansują rozwój i funkcje w LMS+ i byłoby nie fair udostępniać to natychmiast dla wszystkich.

**Comment by noyo-pl** [comment]
Tak się domyślałem. Ale i tak fajnie, że v2 była to mogłem oprzeć się na niej.
