### ISSUE TITLE
Problem z migracją do najnowszego LMSa

### ISSUE THREAD

**Issue by wrkilu** [lmsgit/lms#1229]
Hej,
Mam wersję 1.11.13 Dira (1.1069/1.32) i teraz chciałbym ją zmigrować do najnowszej (z JPK) jednak występuje problem z niekompatybilnościa bazy MySQL. Po wgraniu starej czy odpaleniu na starej od razu wyskuje dużo błedów po otwarciu panelu i już nie mam pomysłu jak to rozwiązać. Czy ktoś z Was miałby na to jakiś sposób ? Podejrzewam że takich ludzi jak ja będzie mnóstwo i to większy problem a nie tylko mój.

**Comment by interduo** [comment]
Przejdź na postgresql przed upgrade. Ja updateowałem jakoś w maju LMS ze schematu z 2013 roku.
Ciężko było ale jest to wykonalne :-)

**Comment by wrkilu** [comment]
Hmm, a czy jest gdzieś opis jak skonwertować te bazy ? Poza tym co dalej ? Gdy będe miał obecną wersję w Postgresie - jak wtedy podpiąć ją do najnowszej wersji LMSa żeby to łyknął i nie było błedów ?

**Comment by interduo** [comment]
Oj chyba będzie lepiej skoro o to pytasz zlecić to komuś kto już ma doświadczenie w tym temacie.
Dużo masz swoich zmian w kodzie?

**Comment by wrkilu** [comment]
Żadnych, to oryginalny LMS

**Comment by wrkilu** [comment]
A czy ktoś inny nie miałby pomysłu jak sobie poradzić z Mysql ? Czy trzeba aż migrować się do Postgresa ?

**Comment by interduo** [comment]
composer update zrobiłeś i wyczyściłeś templates_c ?

**Comment by wrkilu** [comment]
Nie, jak to zrobić ?

**Comment by interduo** [comment]
z cli:
```
composer update;
rm templates_c/*
```

**Comment by wrkilu** [comment]
Ok, zacznijmy od początku:
- tworze pustą bazę Mysql
- wgrywam stary dump
- robię powyższe 
tak ? czy to wystarczy ?

**Comment by interduo** [comment]
Nie.

Procedura w skrócie:
1. Robisz klona produkcyjnego LMS.
2. Update plików.
3. Composer update; 
4. rm templates_c/*
5. Uruchamiasz z cli devel/upgradedb.php.

**Comment by wrkilu** [comment]
Nie rozumiem tylko punktu 2., w sensie czy powinienem nadpisać klona LMSa nowym LMSem ? czy jakiegoś rsynca zrobić ?

**Comment by interduo** [comment]
Już Ci tłumaczę.
Ja mam wszystkie aplikację pokonteneryzowane. Robiąc klona mam na myśli klona całego systemu - tak żeby upgrade nie dostarczył Ci siwych włosów :)

Update plików mam na myśli pobranie całego nowego repozytorium za pomocą polecenia:
`git clone https://github.com/lmsgit/lms.git`

**Comment by wrkilu** [comment]
ja to zrobię na tym samym systemie tylko w innym folderze i bazie. Zatem:
- klon obecnego LMSa do nowego folderu
- git clone https://github.com/lmsgit/lms.git do tego samego folderu
- punkty 3,4,5
tak ?

**Comment by interduo** [comment]
Pamiętaj o zróbieniu kopię bazy danych "w razie W".

**Comment by wrkilu** [comment]
Produkcji nie dotykam także luz. Dam znać jak mi poszło. Dzięki na razie

**Comment by wrkilu** [comment]
W punkcie 5. w folderze nowego LMSa uruchamiam:
# php devel/upgradedb.php
i dostaje błąd:
Composer autoload not found. Run 'composer install' command from LMS directory and try again. More informations at https://getcomposer.org/
Przy czym wczesniej w tym folderze już robiłem composer install i update więc co jest nie tak ?

**Comment by wrkilu** [comment]
Z tym sobie już poradziłem, musiałem ustawić zmienną sys_dir w lms.ini.
Teraz niestety mam kolejny błąd który mówi że mam na serwerze za niską wersję Smarty gdyż wymagana jest min. 3.1. Zainstalowałem zatem najnowszą z .deb (3.1.2) ale niestety wciąż jest ten błąd (w innej przeglądarce też sprawdzałem - to nie jest cache). Jak zatem najlepiej zainstalować mu ta najnowszą wersję żeby ją zobaczył ?

**Comment by wrkilu** [comment]
Pliku devel/smarty_install.sh w obecnej wersji nie ma

**Comment by wrkilu** [comment]
ok , z tym też sobie poradziłem, zgodnie z logami widze ze należało wrzucić źródła nowego Smarta do vendor/smarty.

Strona w końcu się odpaliła i niestety dalej wyrzuca błędy Mysql:
Error: FUNCTION zadmin_lmsjpk.lms_current_user does not exist
Error: Table 'zadmin_lmsjpk.vusers' doesn't exist
albo
Query: CREATE VIEW vnodes AS SELECT n.*, m.mac FROM nodes n LEFT JOIN vnodes_mac m ON (n.id = m.nodeid)
Error: Table 'vnodes' already exists

Czyli wykonałem te wszystkie punkty z powyżej tak jak mówiłeś i niestety kompatybilności baz dalej nie ma. 

Kurde, wiem że to jest open source ze nikt Was nie zmusza do pisania tego softu jak i mnie do korzystania ale czy Wy developerzy pomyśleliście pisząc nowe wersje o tej podstawowej sprawie jaką jest kompatybilność wsteczna ??

**Comment by interduo** [comment]
1. devel/smarty_install.sh nie używaj
Załaduj composerem wszystkie zależności za pomocą:
composer self-update
composer clean
composer update

Composer pobierze Ci odpowiednie wersje bibliotek. Nie musisz nic kombinować.

2. To trochę trudny temat z tą kompatybilnością. Na pewno nie jest tak jak Ci się wydaje. Poprzeglądaj commity to może domyślisz się o co mi chodzi. Nikt pewnych rzeczy nie zrobi za Ciebie - chyba, że wsparcie komercyjne/płatne.

**Comment by wrkilu** [comment]
Podaj mi pls namiar na wsparcie komercyjne. Najprawdopodbniej z tego skorzystamy.

**Comment by chilek** [comment]
@wrkilu http://lms-plus.org

**Comment by chilek** [comment]
@wrkilu no i warto przed aktualizacją przemigrować z MySQL do PostgreSQL (jeśli jeszcze używasz na MySQL). Dla subskrybentów LMS+ dostępny jest w wiki skrypt automatyzujący migrację danych.

**Comment by darton** [comment]
Może taki skrypt automatyzujący migrację z MySQL do PostgreSQL dobrze by było upublicznić.
Im więcej użytkowników migruje do PostgreSQL i im szybciej się to stanie tym lepiej.
Wtedy po jakimś czasie można by porzucić wsparcie LMS dla baz z rodziny MySQL i byłoby mniej pracy z rozwijaniem LMS. Niektóre sprawy trzeba lekko stymulować aby zaczęły się dziać lub działy szybciej oddając część swojej pracy za darmo.

Poddaję Tobie to pod rozwagę jako autorowi :-)  .

**Comment by chilek** [comment]
> Poddaję Tobie to pod rozwagę jako autorowi :-) .

W drugą stronę stymulacja też jest wskazana :D

**Comment by JohnyByk** [comment]
Witam.

Też mam problem z updatem do najnowszej wersji (posiadam LMS 1.11.13 Dira). Postawiłem obok najnowszą wersję i śmiga, ale jak podepnę starą bazę to pojawiają się problemy. Oczywiste dla mnie jest to, że struktura bazy jest niekompatybilna. Przez chwilę przez myśl przeszło mi dostosowanie struktury starej bazy na piechotę i już nawet zacząłem, ale liczę że może da się to jakoś po ludzku zrobić. 

Jak uruchamiam 
devel/upgradedb.php to dostaję zwrotkę.
PHP Fatal error:  Using $this when not in object context in /var/www/lms/devel/upgradedb.php on line 24

Może ktoś nakieruje jak się do tego zabrać. Na piechotę na razie mam marne efekty. Sam lms się odpala bez błędów, w podsumowaniu nawet widzę listę klientów i wartość zadłużenia. Nie widzę klientów w liście klientów, nie widzę faktur itp. Mogę za to dodać klientów do grupy (tam są widoczni). Wiem, że to wszystko kwestia struktury, ale powoli idzie mi ogarnianie tego dlatego szukam bardziej humanitarnego rozwiązania :).

Dziękuję za ewentualne sugestie.

**Comment by JohnyByk** [comment]
Dzięki.
Faktycznie to był problem. Pobrałem najnowszą wersję LMS'a. Wszystko zainstalowałem i skonfigurowałem na nowo. 

Niestety jedna rzecz nie do końca działa. Klienci i faktury (listy) zgadzają się z zawartością starego LMS'a natomiast jest problem w podsumowaniem.

Nowy LMS pokazuje 1618 podłączonych klientów (powinno być 657 i tylu jest ja wejdę w listę klientów). Tak samo wartość zadłużenia w podsumowaniu jest prawie 3 razy większa (ilość zadłużonych jest poprawna). Czy widok vnodes może mieć z tym coś wspólnego.

Jedyny błąd bazy jaki widzę (jeszcze nie doszedłem co go boli) to:
Zapytanie: SELECT COUNT(CASE WHEN access=1 THEN 1 END) AS connected, COUNT(CASE WHEN access=0 THEN 1 END) AS disconnected, COUNT(CASE WHEN UNIX_TIMESTAMP()-lastonline < '600' THEN 1 END) AS online, COUNT(CASE WHEN location_city IS NULL THEN 1 END) AS withoutterryt, COUNT(CASE WHEN netdev IS NULL THEN 1 END) AS withoutnetdev, COUNT(CASE WHEN warning = 1 THEN 1 END) AS withwarning FROM vnodes JOIN customerview c ON c.id = ownerid WHERE ownerid IS NOT NULL
Błąd: Table 'lms.vnodes' doesn't exist

Myślicie, że to jest problem braku widoku vnodes? Staram się go zaimportować, ale chyba brakuje mi jakiejś kolumny, pewnie gdzieś przy upgrade bazy jakaś kolumna się nie dodała? A może błędne podsumowanie względem poszczególnych widoków to jakiś inny problem. Gdzie byście tego szukali.

Pozdrawiam

**Comment by chilek** [comment]
Tak - brakuje widoku vnodes.

**Comment by JohnyByk** [comment]
Udało mi się stworzyć widok. Niestety problem z sumami nadal pozostaje. To znaczy - na podsumowaniach dotyczących zaległości i podłączonych klientów są błędy (za duże wartości) natomiast na liście (przynajmniej klientów już jest OK).

Tutaj jest obrazek, który wszystko pokazuje, wydaje się że jest czytelny i najlepiej oddaje problem:
[https://ibb.co/bwho0x](https://ibb.co/bwho0x)

Zgaduję, że LMS nie wyświetla podsumowań na żywca zliczając rekordy w bazie, a jeśli nie to jest do tego jakiś widok czy może cache? Może ma ktoś pomysł jak spróbować to naprawić. Jak ręcznie poprawiałem sobie bazę to akurat podsumowanie miałem poprawne, ale za to nie działało dużo innych rzeczy i jak najbardziej sposób automatycznej aktualizacji bazy jest lepszy, ale coś trochę za dużo chyba zrobił i chciałbym to naprawić :)

Pozdrawiam
