### ISSUE TITLE
Nie można dodać zobowiązań ze schematu promocji

### ISSUE THREAD

**Issue by seba11** [lmsgit/lms#1234]
Zobowiązania nie dodają się do klienta korzystając ze schematu promocji.

Przykładowy INSERT SQL przy próbie dodania:
```
INSERT INTO assignments
    (tariffid, customerid, period, at, invoice, separatedocument, settlement, numberplanid, paytype, datefrom, dateto, pdiscount, vdiscount, attribute, liabilityid, recipient_address_id, docid, commited)
    VALUES (-2, '216', '3', '1', '0', 0, 0, NULL, NULL, 1519254000, 0, '0', '0', NULL, NULL, NULL, NULL, 1)
```
kończy się błędem
```
#1452 - Cannot add or update a child row: a foreign key constraint fails (`lms`.`assignments`, CONSTRAINT `assignments_tariffid_fkey` FOREIGN KEY (`tariffid`) REFERENCES `tariffs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
```

**Comment by chilek** [comment]
Widać, że mysql - same problemy z nim ludzie mają.

Za mało informacji podajesz - jaka wersja, itp... itd....

**Comment by seba11** [comment]
Dokładnie, używam mysql. Moduł customerassignmentadd próbuje dodać do bazy nie istniejącą taryfę id: -2. Sam schemat promocji udaje się dodać bez problemów.

Tak wygląda log z dziennika transakcji:

` zobowiązanie: dodanie 								assignmentid: 0, customerid: 216, tariffid: -2 								16: , 3: , at: 1, attribute: , commited: 1, datefrom:  2018.02.22, dateto: 0, docid: , invoice: nie, paytype: domyślny,  pdiscount: 0, period: miesięcznie, recipient_address_id: ,  separatedocument: 0, settlement: 0, vdiscount: 0`



Ostatni commit: | https://github.com/lmsgit/lms/commit/71ce0b53e4779101e335bb7b9f2fa138e0cd91be
-- | --
Wersja LMSDB: | 2018020800
Wersja MySQL: | 5.1.73-1
Wersja PHP: | 5.4.45-1~dotdeb+6.1
Wersja Smarty: | 3.1.31

**Comment by seba11** [comment]
@chilek Przeanalizowałem temat. Błąd jest na froncie w \templates\default\customer\customerassignmenthelper.html:87
Jeśli taryfa jest w schemacie oznaczona jako wymagana to checkbox z inputem taryfy będzie disabled, co automatycznie powoduje, że przeglądarka nie wysyła  POSTem. Wystarczy usunąć disabled w konsoli przeglądarki, żeby wszystko zadziałało właściwie.

**Comment by chilek** [comment]
@seba11 to chyba efekt literówki. Zobacz czy:
https://github.com/lmsgit/lms/pull/1236
nie rozwiąże Twojego  problemu. Po aktualizacji warto wymusić przeładowanie wszystkich plików js w przeglądarce.

**Comment by seba11** [comment]
Potwierdzam rozwiązanie problemu.
Dzięki za współpracę 👍
