### ISSUE TITLE
Can not add a division

### ISSUE THREAD

**Issue by tessicz** [lmsgit/lms#1235]
Hello, adding a new division does not work. The error is in LMSDivisionManager where array $args contains telecomnumber but missing in SQL.

Excuse my English is a google translator

**Comment by chilek** [comment]
@tessicz you had and you still have:
https://github.com/lmsgit/lms/blob/master/doc/lms.pgsql#L204
https://github.com/lmsgit/lms/blob/master/doc/lms.mysql#L334
and in db schema updates:
https://github.com/lmsgit/lms/blob/master/lib/upgradedb/postgres.2018020800.php
https://github.com/lmsgit/lms/blob/master/lib/upgradedb/mysql.2018020800.php

**Comment by tessicz** [comment]
The database version is 2018022500. The problem is not in the database but in an SQL query that contains a parameter less than $ arg

`$args = array(
			'name'            => $division['name'],
			'shortname'       => $division['shortname'],
			'ten'             => $division['ten'],
			'regon'           => $division['regon'],
			'rbe'             => $division['rbe'],
			'rbename'         => $division['rbename'] ? $division['rbename'] : '',
			**'telecomnumber'   => $division['telecomnumber'] ? $division['telecomnumber'] : '',**
			'account'         => $division['account'],
			'inv_header'      => $division['inv_header'],
			'inv_footer'      => $division['inv_footer'],
			'inv_author'      => $division['inv_author'],
			'inv_cplace'      => $division['inv_cplace'],
			'inv_paytime'     => $division['inv_paytime'],
			'inv_paytype'     => $division['inv_paytype'] ? $division['inv_paytype'] : null,
			'description'     => $division['description'],
			'tax_office_code' => $division['tax_office_code'],
			'address_id'      => ($address_id >= 0 ? $address_id : null)
		);`

and the telecomnumber is missing in the SQL query

`$this->db->Execute('INSERT INTO divisions (name, shortname,
			ten, regon, rbe, rbename, account, inv_header, inv_footer, inv_author,
			inv_cplace, inv_paytime, inv_paytype, description, tax_office_code, address_id)
			VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array_values($args));`

**Comment by chilek** [comment]
Thanks, above commit should fix it. Check it, please and write back if it is ok.
