### ISSUE TITLE
psr-2

### ISSUE THREAD

**Issue by maciejlew** [lmsgit/lms#1244]
Zamierzam przygotować PR z poprawkami pod PSR-2. W tym temacie możemy to omówić.

**Comment by chilek** [comment]
Nie ma takiej potrzeby - już jest prawie wszystko gotowe - łącznie z integracją z Travisem.
Zostało poczekać do momentu 0 (tuż przed wydaniem nowej stabilnej 1.11.24.x) i:
1. Zrobić phpcbf na wszystkich plikach *.php (z pominięciem zewnętrznych).
2. Odkomentować phpcs w .travis.yml.

Z drugiej strony jeśli chciałbyś pomóc to może byś był zainteresowany zrobieniem tego samego dla *.js?
Znalazłem już narzędzia do tego: jshint i jscs. Puściłem do master .jshintignore i .jshintrc oraz parę plików zmodyfikowałem pod kątem zgodności z jshint, ale trochę jeszcze zostało.

**Comment by maciejlew** [comment]
Chciałem to zrobić iteracyjnie. Przygotowałem PR z standardem kodowania ograniczonym tylko do sprawdzania wcięć #1245. Trzeba to zrobić ostrożnie bo nie mamy żadnych testów automatycznych (na pewno trzeba uważać na pliki z wymieszanym php i js bo np. phpcbf może zmienić składnie "if else" tak że przestanie być zgodna ze standardami js).

**Comment by chilek** [comment]
> bo np. phpcbf może zmienić składnie "if else" tak że przestanie być zgodna ze standardami js).

Czy phpcbf nie widzi kontekstu kodu JS jako tekstu w PHP? Moim zdaniem nie powinno ruszać czegoś co jest tekstem w perspektywy PHP. Chyba, że to o coś innego chodzi?

**Comment by maciejlew** [comment]
Przetestowałem to i rzeczywiście w najnowszych wersjach z gałęzi 2 i 3 działa. Nie było tematu ;)

**Comment by chilek** [comment]
@maciejlew 
1. Nie wiesz czy można w composer.json tworzyć zależności kaskadowe, tzn. takie w których jakaś biblioteka jest instalowana w wersji X, gdy jest PHP <= 5.4 i w wersji Y, gdy jest PHP >= 5.5?
2. composer ma domyślne --dev - żeby nie wrzucały się zależności developerskie trzeba:
```sh
composer update --no-dev
```
Nie wiesz czy da się zmusić composera przez composer.json, żeby domyślnie było --no-dev?
Pytam, ponieważ w środowiskach produkcyjnych trochę nie bardzo wrzucać zależności developerskie.

**Comment by maciejlew** [comment]
ad 1. W przypadku PHPCS można chyba zaryzykować i zrobić * - wydaje mi się że composer powinien wtedy wybrać najlepszą pasującą do wersji PHP wersję zależności. Można tak zrobić, bo kod LMS nie zależy od PHPCS. W przypadku innych zależności może być już tak, że zmiany w nowej wersji zewnętrznej biblioteki mogą być niekompatybilne z kodem LMS. Wtedy bezpieczniej będzie używać ^.

ad 2. Nie wiem czy da się zrobić domyślnie --no-dev, ale też nie wydaje mi się to potrzebne. Na Travis'ie masz środowisko testowe, odbudowywane za każdym razem, bezpieczne i w sumie niezagrożone ewentualnymi problememi z paczkami z require-dev. A problem z dodaniem flagi --no-dev można przerzucić na użytkowników produkcyjnych LMS, np. wspominając o tym w dokumentacji.

**Comment by maciejlew** [comment]
ad 2. Można też zakomitować composer.lock i napisać żeby używać
`composer install` zamiast `composer update`.

**Comment by maciejlew** [comment]
ad 2. I można też wykorzystać usługę https://dependabot.com/ która sprawdzi czy są nowe wersje zależnośc, przygotuje PR, a Travis sprawdzi czy nadal wszystko działa (albo przynajmniej to co będzie pokryte testami).

**Comment by chilek** [comment]
> np. wspominając o tym w dokumentacji.

Której prawie nikt nie czyta :)

**Comment by chilek** [comment]
> W przypadku PHPCS można chyba zaryzykować i zrobić * - wydaje mi się że composer powinien wtedy wybrać najlepszą pasującą do wersji PHP wersję zależności. Można tak zrobić, bo kod LMS nie zależy od PHPCS. 

To co - puścisz zmiany w PR?

**Comment by chilek** [comment]
Ostatnie zmiany z dzisiaj czynią LMS prawie zgodny z PSR-2 - trzeba było pominąć parę drobiazgów, które warto będzie brać pod uwagę w przyszłości.
