### ISSUE TITLE
Porzucenie wsparcia dla starszych wersji PHP

### ISSUE THREAD

**Issue by maciejlew** [lmsgit/lms#1248]
Co o tym myślicie? Wiązałoby się to pewnie z wydaniem kolejnej wersji (2.0?).

Tu mamy taki fajny wykres (pewnie znacie): http://php.net/supported-versions.php

**Comment by chilek** [comment]
A propos wspieranych wersji PHP:

RHEL/CentOS 6 wspierane do 30 listopada 2020:
php-5.3.3-49.el6.x86_64
RHEL/CentOS 7 wspierane do 30 czerwca 2024:
php-5.4.16-43.el7_4.1.x86_64

Do tego dorzuć Debiana, Ubuntu i spójrz jakie tam są wersje PHP wspierane.

**Comment by nicraMarcin** [comment]
No, tym tokiem rozumowania w LMS dluuuugo nie zobaczymy deklaracji `[]` :(

Już ze dwa lata temu jak była dyskusja odnośnie przepisania LMS pod frameworka ale ucichła szybko jak powstała. Już nikomu nie chcę się pisać płaskiego kodu pozatym zgodnego na 10 lat wstecz. Więc mamy ma co Tomek pozwala i w jakim kierunku chce rozwijać projekt. Jak widać z commitow to Tomek wrzuca coś "nowego" a reszta poprawia przecinki bo cos nie działa.

Ja jestem za znaczącym pójściem do przodu bym mógł w wolnej chwili pisać coś pod lms a tak sam piszę sobie taki podobny system jak LMS z tym że na S4 + Angular5 na froncie. Idzie to mozolnie wlasnie z braku czasu.

**Comment by interduo** [comment]
Tylko jedna drobna sprawa - to wymaga nakładów finansowych. 

@nicraMarcin jak to widzisz?

**Comment by nicraMarcin** [comment]
Ja od siebie mogę robić w ramach "edukacji"

**Comment by chilek** [comment]
Hehe już setki razy takie propozycje i pomysły były... Skończy się na tym, że super nowoczesny nowy system nigdy nie osiągnie możliwości 1.11.x i w efekcie nikt nie będzie używał z dotychczasowych użytkowników.

**Comment by nicraMarcin** [comment]
@chilek tu się z Tobą nie zgodzę, że nowy system nigdy nie osiagnie użyteczności obecnego LMS. Śmiem twierdzić, że wiele rzeczy da się i łatwiej i szybciej zrobic w Symfony choćby komendy czy cron. Nie potrzeba powtarzać kodu jak obecnie w /bin bo to załatwiają wlaśnie Comands. 
A czy i kiedy nowy projekt przerośnie obecny LMS zależy od deweloperów piszacych linie. 

Kwestia czy będą używać też prosta. Jak będzie zrobiony prosty interfejs do migracji danych, będzie działał lepiej i ładniej wyglądał to będą. 

Jeśli będzie to Symfony na api z Angularem na froncie to się piszę do kodowania. By ładnie i nowocześnie front wyglądał proponuje material design.

**Comment by chilek** [comment]
@nicraMarcin: przepraszam, że napiszę to wprost - masz bardzo studenckie podejście. Użyjesz Symfony i Angular, a kto potem będzie w stanie dopisywać do tego kod - mocno ograniczysz tym samym zakres osób podsyłających swoje modyfikacje. Wiele lat zajmuję się utrzymaniem LMS - nie mam nic przeciwko temu co piszesz, ale mam też doświadczenie i pragmatyczne podejście. Poza tym zauważ, że to co piszesz od kilku postów brzmi bardzo pretensjonalnie i założenie się, że nie tylko ja mam taki odbiór. Z drugiej strony w świecie open source obowiązuje zasada: jak uważasz, że coś można zrobić lepiej to proszę to zrób i podziel się tym.

**Comment by chilek** [comment]
> Ja od siebie mogę robić w ramach "edukacji"

To brzmi jak chęć zrobienia projektu na studia, a potem projekt się skończy i temat olejesz, a ktoś będzie musiał to utrzymywać. Ludzi z takim podejściem było już wielu...

**Comment by nicraMarcin** [comment]
@chilek trochę przesadzasz, że mam jakieś pretensje. Użycie frameworka po pierwsze przyśpiesza pracę a po drugie wprowadza jakąś systematyke. Chcę rozdzielić front od backendu wlaśnie po to by oddzielic dane i to się z nimi dzieje od widoku. Wówczas każdy może napisać coś swojego na froncie, czy to js, html czy apka na telefon pozostawiając całą funkcjonalność core.
I nie jest to żaden projekt na studia typu zrób i zalicz by była  jasność .

Wspomniałeś o świecie opensource. Tak , robie sobie coś w stylu lms, mam zrobione już core ale przez normalny tok pracy, swoje jakieś dorobki do LMSa i jescze kilka czynników w pracy nie dotykalem tego kodu ponad pół roku. Jako front robię z wykorzystaniem fuse2, ale z braku czasu samemu sie zejdzie :/

**Comment by nicraMarcin** [comment]
Nie twierdzę, że LMS jest zły, wprost przeciwnie ogólnie jest to kawał dobrej roboty, ale LMS powstawał 15 lat temu i to 15 lat widać w "nowym" kodzie, który ludzie podsyłają by być "na czasie" z kodem. Wystarczy zerknąć w pierwszy lepszy templejt, strukturę strony w tabelach robiło się właśnie 15 lat temu o znacznikach htmlowych pisanych wielkimi literami nie wspomnę. namespace w PHP są już z 10 lat, no może mniej. ale nie o to chodzi. Dopisując, poprawiając coś w obecnym LMS, fakt, wystarczy podstawowa wiedza PHP ale czy mimo to LMS jest lepszy, ile osób defakto wrzuca coś treściwego, 2, 3? i to też z naciskiem na 1, po pozostali od "wielkiego dzwonu". 
Gdzy LMS startował miał ilu developerów? a teraz jest ilu? jeden @chilek wrzucający swoje poprawki, które wychodzą z LMS+ i jeszcze kilka osób wrzucających "przecinki". @chilek czemu tylko Ty zostałeś "na polu bitwy"?

Użycie jakiegoś frameworka "wymusza" w pewnym sensie na developerach "bycie na czasie", jest pewną gwarancją aktualności kodu, nawet jego semantyki. 

Nie upieram się by to było Symfony i Angular, zaproponowałem to bo przy tych frameworkach mogę wesprzeć i tyle.  Proszę @chilek nie doszukuj się tu drugiego dna bo go nie ma.

Wracając do wspomnianego świata OpenSource. Jeśli zbierze się grupka entuzjastów owszem, zawsze mogą zrobić coś lepiej jeśli uważają, że się da. Jeśli ktoś robi sam to na pewno nie będzie tego robił OpenSourceowo bo to jego prywatny czas i jego wola. Dowodem na to jest np. LMS+ :)
@chilek Tak patrząc trochę z boku, to masz nie złe zaplecze betatesterów Twojego kodu :) pewnie tylko dla tego jeszcze chce Ci się bawić w LMS :) 

Ale dyskusja zeszła na inne tory.
Wracając do wątku @maciejlew ja jestem za.

**Comment by chilek** [comment]
> Ale dyskusja zeszła na inne tory.

No właśnie, a kto zaczął odejście "na inne tory"?

> Wracając do wątku @maciejlew ja jestem za.

Wiesz, że taki jak ty było już co najmniej dziesiątki. Zwykle kończyło się to tak, że nie mieli czasu, ale doradzać owszem czas zawsze znajdywali. Bez sensu - robi się z dyskusja akademicka, a póki co nic nie zrobiłeś i nic nie możesz pokazać działającego, ale już chcesz decydować co będzie dalej... Miałeś okazji się sprawdzić przy okazji wtyczki Novitus - jak tylko pojawiło się coś do poprawienia do wy***eś dupę i tyle. Masz dzięki temu spokój, ale rusz chłopie głową i wyobraź sobie, że to tak nie działa w projekcie.

**Comment by chilek** [comment]
>  @chilek czemu tylko Ty zostałeś "na polu bitwy"?

Zapytaj ich - przekonasz się, że Twoje podejrzenia są błędne.

**Comment by nicraMarcin** [comment]
No i zostałem wywołany do tablicy. obiecuję, że ostatni raz by móc odpowiedzieć i już nie będę szukał okazji na _doradztwo_

> jak tylko pojawiło się coś do poprawienia do wy***eś dupę

Tu się z Tobą nie zgodzę i to jest Twoja interpretacja. Sam widziałeś, że chciałem by być zgodnym wstecz, zacząłem poprawiać deklaracje tablic na stary sposób a tu jeszcze ma być zgodne do 5.3 bo ta wersja jest wspierana wspierana przez centosa do 2020r. Czyli jednym słowem mam, że tak powiem kolokwialnie, cofać się do tyłu? Nie, pisałem kod pod nowy PHP, jeśli 7.0 można nazwać nowym. 


> już chcesz decydować co będzie dalej

Jeśli chodzi o LMS to daleko mi do decydowania i nawet bym nie śmiał. Jedyne co mogę to tylko zaproponować i wspomóc w tym co mogę. 

> Zapytaj ich - przekonasz się, że Twoje podejrzenia są błędne.

Czemu Ty wszędzie doszukujesz się ataku na swoja osobę? Trochę dystansu by się przydało. Rozumiem, 15 lat to jak własne prawie dorosłe dziecko :)

**Comment by chilek** [comment]
> Czemu Ty wszędzie doszukujesz się ataku na swoja osobę? 

Nie doszukuję się ataku na swoją osobę. Chcę wyraźnie podkreślić jaki mam odbiór tego co piszesz - klepiesz w klawiaturę i na 99% nic z tego nie będzie. Ot tak sobie poklepiesz jak większość "konsultantów". Takie jest moje odczucie. Z mojej strony koniec tematu, bo nie spodziewam się, że dojdę do jakichś sensownych wniosków dalej wymieniając komentarze z Tobą. Jak chcesz czymś "zabłyszczeć" to pokaż własną robotę do której nikt nie będzie miał zastrzeżeń - tylko tyle i aż tyle. Tak wiem, że Ci się nie chce, a znajdziesz 120 tłumaczeń dlaczego jest lepiej jak Ci się nie chce ...

**Comment by maciejlew** [comment]
> RHEL/CentOS 6 wspierane do 30 listopada 2020:
> php-5.3.3-49.el6.x86_64
> RHEL/CentOS 7 wspierane do 30 czerwca 2024:
> php-5.4.16-43.el7_4.1.x86_64

To chyba nie oznacza że autorzy RHEL będa sami łatać dziury w porzuconych wersjach PHP? I mam nadzieję, że nie oznacza też, że na tych dystrybucjach nie da się zainstalować nowszej wersji PHP?

Trzeba sobie zadać kilka pytań:
1. czy ktoś jeszcze używa LMS + PHP 5.3? - być może jakaś grupa osób
2. czy ten ktoś będzie robił aktualizację LMS? - mniej osób niż punkt wyżej
3. czy Ci którzy będą robić aktualizacje będą mieli problemy z podniesieniem wersji PHP? - jeszcze mniej osób niż punkt wyżej
4. czy to jest gałąź rozowjowa czy utrzymaniowa? - wydaje mi się że rozwojowa
5. czy w takim razie powinniśmy się przejmować punktami 1-3? - moim zdaniem nie

Co do 1-3 to wiem, że to trudno powiedzieć jaka jest ta bazowa grupa - nie mamy żadnych danych. Być może wcale jej nie ma i jest to w ogóle walka z wiatrakami.

**Comment by darton** [comment]
Nie ma problemu z podniesieniem wersji php do 7 na Centos6 i Centos 7.
Niezbędne pakiety są w repozytoriach EPEL oraz Remi da tych dystrybucji  i
proces jest stosunkowo prosty.

Do zbierania statystyk odnośnie wersji oprogramowania  (za zgodą
użytkowników) można by wykorzystać moduł rejestracji LMS ( w każdym razie
nowych)
Dla obecnych może zrobić jakąś ankietę online (limesourvey ?) , niech
powisi z miesiąc może  będzie w miarę reprezentatywna.


W dniu 28 kwietnia 2018 09:09 użytkownik Maciej Lew <
notifications@github.com> napisał:

**Comment by chilek** [comment]
> @maciejlew To chyba nie oznacza że autorzy RHEL będa sami łatać dziury w porzuconych wersjach PHP? I mam nadzieję, że nie oznacza też, że na tych dystrybucjach nie da się zainstalować nowszej wersji PHP?

Dokładnie to oznacza - i już sporo poprawek błędów zostało wstecznie-przeniesionych.

> @darton: Do zbierania statystyk odnośnie wersji oprogramowania  (za zgodą
użytkowników) można by wykorzystać moduł rejestracji LMS ( w każdym razie
nowych)
> Dla obecnych może zrobić jakąś ankietę online (limesourvey ?) , niech
powisi z miesiąc może  będzie w miarę reprezentatywna.

To co - już implementujesz czy raczej świadczysz usługi konsultingu przymusowego? ;-)

> @darton: Nie ma problemu z podniesieniem wersji php do 7 na Centos6 i Centos 7.
Niezbędne pakiety są w repozytoriach EPEL oraz Remi da tych dystrybucji  i
proces jest stosunkowo prosty.

Od kiedy to dystrybucja remi jest uważana za składnicę stabilnych pakietów?
EPEL jest całkiem ok tylko pamiętaj, że paczki PHP z EPEL mogą nie posiadać tych wszystkich zabezpieczeń co posiadają oficjalne paczki RHEL, a tym samym CentOS.

Jeśli już lepiej użyć paczek z PHP 5.6 i PHP 7 z RedHat Software Collections.

**Comment by chilek** [comment]
> czy ktoś jeszcze używa LMS + PHP 5.3? - być może jakaś grupa osób

Tak - są instalacje na RHEL/CentOS 6. Niedługo w sumie będzie można zalecić migrację do RHEL/CentOS 7 użytkownikom szóstki. To co prawda podniesie dostępne PHP do 5.4.

> czy to jest gałąź rozowjowa czy utrzymaniowa? - wydaje mi się że rozwojowa

"To" tzn. chodzi Ci o master? Jeśli tak to master jest stałą gałęzią rozwojową na bazie której co ok 6-9 miesięcy wychodzą wersje numerowane stanowiące bazę do gałęzi stabilnych utrzymywanych przez ok. 1-1,5 roku.

Ogólnie można zastanowić się nad podniesieniem wymogów do PHP 5.6, a nawet 7, ale trzeba zbadać rozsądne ścieżki aktualizacji w każdej z często używanych dystrybucji tj. Debian, CentOS, Ubuntu (inne?).

**Comment by chilek** [comment]
Wygląda na to, że LMS 25 i tym samym LMS+ 25.x będzie już wymagał PHP 5.6. Od teraz w repozytorium LMS gałęzi master akceptowany jest kod zgodny z PHP 5.6 i wyżej. Tyle, że same poprawki będą i tak w ramach LMS+ przenoszone do 
zgodności z PHP 5.3.

**Comment by interduo** [comment]
Aktualizacja PHP w Debianie to kilka poleceń aptem nawet dla dystrybucji oldstable. Wystarczy dodać repozytorium backports i puścić aktualizację. 

W Ubuntu podobnie, idzie gładko.

**Comment by chilek** [comment]
To jak tak łatwo idzie to dlaczego do razu w dystrybucji takiej aktualizacji nie ma? Zastanawiało to Ciebie?

**Comment by interduo** [comment]
> To jak tak łatwo idzie to dlaczego do razu w dystrybucji takiej aktualizacji nie ma?

Jeszcze raz napiszę - jest repozytorium backports. To jest oficjalne repozytorium.

> Zastanawiało to Ciebie?

Nie muszę się nad tym zastanawiać ponieważ założenia dystrybucji Debiana są dokładne opisane. To jest po to byś wiedział czego się spodziewać.

**Comment by chilek** [comment]
> Jeszcze raz napiszę - jest repozytorium backports. To jest oficjalne repozytorium.

Developerskie pakiety i testowane też są oficjalnymi repozytoriami. Nie myl pojęć - chodzi o stabilność i przetestowanie w wielu warunkach. Backports jest z założenia tak stabilne jak stable?

**Comment by interduo** [comment]
@chilek zamykają Ci się zgłoszenia automatycznie commitami - mniemam że nie chciałeś tego zrobić.

**Comment by chilek** [comment]
Pewnie ID tego zgłoszenia jest takie same jak w projekcie LMS+.

**Comment by chilek** [comment]
Obecnie wymaga już PHP 7.1.
