### ISSUE TITLE
MySQL >= 5.7 and MariaDB >=10.2 : Daemon compile problem with 

### ISSUE THREAD

**Issue by tudor2k3** [lmsgit/lms#1250]
Hello,

     MySQL >= 5.7 and MariaDB >=10.2 have replaced libmysqlclient with Connector/C. See: https://mariadb.com/kb/en/library/changes-improvements-in-mariadb-102/

**Comment by chilek** [comment]
What is your problem?

**Comment by chilek** [comment]
No answer for long time - so expiring issue.
