### ISSUE TITLE
Hasło do faktur

### ISSUE THREAD

**Issue by prezesk** [lmsgit/lms#1251]
Witam,
Po ostaniach aktualizacjach podczas drukowania faktury pojawia się monit o hasło. Jakie to hasło i jak je się ustawia?  
Znalazłem że jest parametr phpui.document_password dodany przez @chilek Ale nie wiem jak z tego skorzystać. Proszę o pomoc jak to ma działać.

**Comment by prezesk** [comment]
Po kilkukrotnym błędnie wypisany haśle w chromie wreszcie pojawia się faktura. Czy tylko ja mam z tym problem?

**Comment by prezesk** [comment]
Ok mam wrzuconą najnowszą wersje master. W jaki sposób powinienem szukać gdzie powstaje błąd? Jak się cofnąłem kilka wersji do tyłu git reset --hard 054afe1 to faktury mi działają. Jakie powinien podjąć kroki aby znaleźć gdzie jest błąd i pomóc go naprawić?

**Comment by interduo** [comment]
Przeczyść cache w przeglądarce.
Wyczyść templates_c.
Composer update

Na początek.

**Comment by interduo** [comment]
Potem zobacz co ta zmienna oznacza w wiki jest opis.

**Comment by chilek** [comment]
Podpowiedź z LMS+ wiki:

## invoices.disable_protection

**Typ:** Wartość logiczna.

**Wartość domyślna:** _false_

**Opis:** Wpływa na status zabezpieczeń faktur TCPDF przed edycją, modyfikowaniem, kopiowaniem zawartości.

**Dostępność:** od 1.11.20
