### ISSUE TITLE
Arbitrary File Read

### ISSUE THREAD

**Issue by ProDigySML** [lmsgit/lms#1271]
# The Issue
An attacker can arbitrarily read files (which the user running the web application has permission to read) using unsanitised user input passed to the `fopen` PHP function

# Where the Issue Occurred
An attacker can control the file path for reading a file using the variable assignment below:
https://github.com/lmsgit/lms/blob/1dddbab05fcbedcd4ec02ba8e1d1aa3bc384d202/modules/dbview.php#L49

The above variable is passed to the line below, where the `fopen` function is being used to read the file:
https://github.com/lmsgit/lms/blob/1dddbab05fcbedcd4ec02ba8e1d1aa3bc384d202/modules/dbview.php#L32

As displayed above, `.sql` is appended to the file name, however this can be bypassed (in some versions of PHP) using a null byte terminator (%00)

**Comment by chilek** [comment]
@ProDigySML thanks for info. It has been fixed by the above commit. Also has been ported to private LMS+ stable branches.
