### ISSUE TITLE
Userpanel nie wyświetla strony

### ISSUE THREAD

**Issue by nooa85** [lmsgit/lms#1323]
Witam,
zainstalowałem LMSa z GIT, sam LMS uruchamia się poprawnie nie ma żadnych błędów, po uruchomieniu userpanelu wyświetla się pusta strona. Jest to nowa instalacja z pustą bazą danych.

Log z apache:
PHP Fatal error:  Uncaught  --> Smarty: Unable to load template 'file:jquery.html' in 'login.html' <-- \n  thrown in /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 185

**Comment by nooa85** [comment]
Tak robiłem.

**Comment by interduo** [comment]
pokaż lms.ini

**Comment by interduo** [comment]
Skróć go do:

```
[database]
type = mysql
database = lms
host = localhost
user = lms
password = 1234

[directories]
sys_dir = /var/www/html/lms/
```

**Comment by nooa85** [comment]
Nie pomogło. Dalej ten sam błąd.

**Comment by interduo** [comment]
SOA#1

Chyba faktycznie warto byloby udostępnić plik z playbookiem do jakiegoś ansible lub template do wirtualki lxc.

**Comment by interduo** [comment]
Może masz coś z uprawnieniami zrypane? Wywal cały folder lms i zrób git clone od nowa. Potem composer self-update; composer update;

**Comment by nooa85** [comment]
Jeżeli zostawię katalog userpanel w katalogu lms to działa wszystko poprawnie. Jeżeli przerzucę katalog userpanel do katalogu nadrzędnego wówczas pokazuje się pusta strona. Oczywiście zmieniam ścieżkę w lms.ini

**Comment by chilek** [comment]
Z komunikatu błędu z pierwszego posta wynika, że dowiązanie symboliczne jquery.html z katalogu templates w userpanel nie ma właściwego powiązania z pliki templates/default/jquery.html z katalogu z instalacją LMS. Wystarczy poprawić to dowiązanie symboliczne, żeby wskazywało na fizyczny plik.

**Comment by nooa85** [comment]
dzięki pomogło.
