### ISSUE TITLE
Fatal error: cannot connect to database!

### ISSUE THREAD

**Issue by kolorek1** [lmsgit/lms#1402]
Hej, nie mogę uruchomić lmsa, problem leży tutaj:
"PHP Warning:  Unknown config variable "type" in section "database"! in /var/www/html/lms/index.php on line 94"
typ mysql jest ustawiony jako mysqli ponieważ działa na php 7.0. Proszę o jakieś porady

**Comment by interduo** [comment]
Pokaż lms.ini całe

**Comment by chilek** [comment]
@interduo: Nie doczekasz się odpowiedzi pewnie - chłop miał pewnie inwencję twórczą przez 5 minut :D

**Comment by interduo** [comment]
Dobry zwyczaj nakazuje zamknąć swoje issue jeśli stwierdziliśmy że jest niezasadne. Może po prostu był offline od ostatniej wiadomości?

**Comment by chilek** [comment]
> Dobry zwyczaj nakazuje zamknąć swoje issue jeśli stwierdziliśmy że jest niezasadne

1. Ten temat poruszany już był wiele razy.
2. Dobry zwyczaj nakazuje również kontynuować dyskusję w wątku, a zobacz ile tu takich wątków, że ktoś zaczął, a potem zapomniał.
