### ISSUE TITLE
Na fakturze za bieżacy okres niepełny błędna data zakończenia

### ISSUE THREAD

**Issue by alkar1** [lmsgit/lms#1405]
Jeśli tworzę nowe zobowiązanie z naliczaniem miesięcznym i wyrównaniem niepełnego  okresu w okresie biezącym, pierwsza faktura wystawiawia się z opisem okresu np. 25.09.2018-24.10.2018 zamiast 25.09.2018-30.09.2018.
Natomiast kwota liczona jest Ok.

**Comment by chilek** [comment]
To po prostu zależy od ustawień payments.comment i payments.settlement_comment.

**Comment by alkar1** [comment]
No Ok , ale w parametrach %period  (aligned,forward) nie ma takiego okresu.

**Comment by chilek** [comment]
O jakim ustawieniu piszesz? Od tego zacznijmy...

**Comment by alkar1** [comment]
W payments.comment ustawiam treść opisu na faturze , defaultowo tam jest "Tariff %tariff - %attribute subscription for period %period" . 
Ale jesli zmienię %period na %aligned_period albo %forward_periods albo %forward_aligned_periods to też nie ma prawidłowego zakresu dat.

**Comment by alkar1** [comment]
Dodam tylko, że przy wyrównaniu okresu niepełnego w przyszłym okresie wszystko jest jak nalezy.

**Comment by chilek** [comment]
payments.comment nie ma wpływu na zobowiązania wyrównawcze.

**Comment by chilek** [comment]
Polecam użycie symbolu %backward_aligned_periods dla ustawienia payments.settlement_comment.
