### ISSUE TITLE
Warning w PHP w formularzu rtticketedit

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#1407]
```
[Tue Oct  2 09:30:32 2018] PHP Warning:  Use of undefined constant ul - assumed 'ul' (this will throw an Error in a future version of PHP) in /var/www/html/lms/lib/LMSManagers/LMSHelpdeskManager.php on line 555
[Tue Oct  2 09:30:32 2018] PHP Stack trace:
[Tue Oct  2 09:30:32 2018] PHP   1. {main}() /var/www/html/lms/index.php:0
[Tue Oct  2 09:30:32 2018] PHP   2. include() /var/www/html/lms/index.php:343
[Tue Oct  2 09:30:32 2018] PHP   3. LMS->GetEventsByTicketId($id = *uninitialized*) /var/www/html/lms/modules/rtticketview.php:91
[Tue Oct  2 09:30:32 2018] PHP   4. LMSHelpdeskManager->GetEventsByTicketId($id = *uninitialized*) /var/www/html/lms/lib/LMS.class.php:2550
```

**Comment by chilek** [comment]
Widzę, że moduł rtticketview. Przy jakich danych wejściowych przekazanych GET-em udało CI się to uzyskać?

**Comment by interduo** [comment]
rtticketview:
http://lms/?m=rtqueueview&persistent-filter=-1

`[Tue Oct  2 10:34:48 2018] 172.20.2.42:54780 [200]: /?m=rtqueueview&persistent-filter=-1&action=delete&api=1
[Tue Oct  2 10:34:48 2018] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/lms/templates_c/5a2c3c3dae61a15d8ce1aba8174c4609c3ee9ec7_1.extendsall.rtqueueview.html.php on line 1804
[Tue Oct  2 10:34:48 2018] PHP Stack trace:
[Tue Oct  2 10:34:48 2018] PHP   1. {main}() /var/www/html/lms/index.php:0
[Tue Oct  2 10:34:48 2018] PHP   2. include() /var/www/html/lms/index.php:343
[Tue Oct  2 10:34:48 2018] PHP   3. LMSSmarty->display($template = *uninitialized*, $cache_id = *uninitialized*, $compile_id = *uninitialized*, $parent = *uninitialized*) /var/www/html/lms/modules/rtqueueview.php:268
[Tue Oct  2 10:34:48 2018] PHP   4. LMSSmarty->display($template = *uninitialized*, $cache_id = *uninitialized*, $compile_id = *uninitialized*, $parent = *uninitialized*) /var/www/html/lms/lib/LMSSmarty.php:43
[Tue Oct  2 10:34:48 2018] PHP   5. LMSSmarty->_execute($template = *uninitialized*, $cache_id = *uninitialized*, $compile_id = *uninitialized*, $parent = *uninitialized*, $function = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:134
[Tue Oct  2 10:34:48 2018] PHP   6. Smarty_Internal_Template->render($no_output_filter = *uninitialized*, $display = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:232
[Tue Oct  2 10:34:48 2018] PHP   7. Smarty_Template_Compiled->render($_template = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:216
[Tue Oct  2 10:34:48 2018] PHP   8. Smarty_Template_Compiled->getRenderedTemplateCode($_template = *uninitialized*, $unifunc = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:114
[Tue Oct  2 10:34:48 2018] PHP   9. content_5bb31e9164d086_05040835($_smarty_tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Tue Oct  2 10:34:48 2018] PHP  10. Smarty_Internal_Template->_subTemplateRender($template = *uninitialized*, $cache_id = *uninitialized*, $compile_id = *uninitialized*, $caching = *uninitialized*, $cache_lifetime = *uninitialized*, $data = *uninitialized*, $scope = *uninitialized*, $forceTplCache = *uninitialized*, $uid = *uninitialized*, $content_func = *uninitialized*) /var/www/html/lms/templates_c/5a2c3c3dae61a15d8ce1aba8174c4609c3ee9ec7_1.extendsall.rtqueueview.html.php:148
[Tue Oct  2 10:34:48 2018] PHP  11. Smarty_Template_Compiled->getRenderedTemplateCode($_template = *uninitialized*, $unifunc = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:376
[Tue Oct  2 10:34:48 2018] PHP  12. content_5bb31e90cef406_44342933($_smarty_tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Tue Oct  2 10:34:48 2018] PHP  13. Smarty_Internal_Runtime_Inheritance->endChild($tpl = *uninitialized*, $template = *uninitialized*, $uid = *uninitialized*, $func = *uninitialized*) /var/www/html/lms/templates_c/5a2c3c3dae61a15d8ce1aba8174c4609c3ee9ec7_1.extendsall.rtqueueview.html.php:2162
[Tue Oct  2 10:34:48 2018] PHP  14. Smarty_Internal_Template->_subTemplateRender($template = *uninitialized*, $cache_id = *uninitialized*, $compile_id = *uninitialized*, $caching = *uninitialized*, $cache_lifetime = *uninitialized*, $data = *uninitialized*, $scope = *uninitialized*, $forceTplCache = *uninitialized*, $uid = *uninitialized*, $content_func = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:125
[Tue Oct  2 10:34:48 2018] PHP  15. Smarty_Template_Compiled->getRenderedTemplateCode($_template = *uninitialized*, $unifunc = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:376
[Tue Oct  2 10:34:48 2018] PHP  16. content_5bb31e90cf3694_14643045($_smarty_tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Tue Oct  2 10:34:48 2018] PHP  17. Smarty_Internal_Template->_subTemplateRender($template = *uninitialized*, $cache_id = *uninitialized*, $compile_id = *uninitialized*, $caching = *uninitialized*, $cache_lifetime = *uninitialized*, $data = *uninitialized*, $scope = *uninitialized*, $forceTplCache = *uninitialized*, $uid = *uninitialized*, $content_func = *uninitialized*) /var/www/html/lms/templates_c/5a2c3c3dae61a15d8ce1aba8174c4609c3ee9ec7_1.extendsall.rtqueueview.html.php:1338
[Tue Oct  2 10:34:48 2018] PHP  18. Smarty_Template_Compiled->getRenderedTemplateCode($_template = *uninitialized*, $unifunc = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:376
[Tue Oct  2 10:34:48 2018] PHP  19. content_5bb31e90cf6110_07816604($_smarty_tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Tue Oct  2 10:34:48 2018] PHP  20. Smarty_Internal_Template->_subTemplateRender($template = *uninitialized*, $cache_id = *uninitialized*, $compile_id = *uninitialized*, $caching = *uninitialized*, $cache_lifetime = *uninitialized*, $data = *uninitialized*, $scope = *uninitialized*, $forceTplCache = *uninitialized*, $uid = *uninitialized*, $content_func = *uninitialized*) /var/www/html/lms/templates_c/5a2c3c3dae61a15d8ce1aba8174c4609c3ee9ec7_1.extendsall.rtqueueview.html.php:1329
[Tue Oct  2 10:34:48 2018] PHP  21. Smarty_Template_Compiled->getRenderedTemplateCode($_template = *uninitialized*, $unifunc = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:376
[Tue Oct  2 10:34:48 2018] PHP  22. content_5bb31e90cf8e44_19649271($_smarty_tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Tue Oct  2 10:34:48 2018] PHP  23. Smarty_Internal_Template->_subTemplateRender($template = *uninitialized*, $cache_id = *uninitialized*, $compile_id = *uninitialized*, $caching = *uninitialized*, $cache_lifetime = *uninitialized*, $data = *uninitialized*, $scope = *uninitialized*, $forceTplCache = *uninitialized*, $uid = *uninitialized*, $content_func = *uninitialized*) /var/www/html/lms/templates_c/5a2c3c3dae61a15d8ce1aba8174c4609c3ee9ec7_1.extendsall.rtqueueview.html.php:1224
[Tue Oct  2 10:34:48 2018] PHP  24. Smarty_Template_Compiled->getRenderedTemplateCode($_template = *uninitialized*, $unifunc = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:376
[Tue Oct  2 10:34:48 2018] PHP  25. content_5bb31e90cfb5f6_45987804($_smarty_tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Tue Oct  2 10:34:48 2018] PHP  26. Smarty_Internal_Runtime_Inheritance->instanceBlock($tpl = *uninitialized*, $className = *uninitialized*, $name = *uninitialized*, $tplIndex = *uninitialized*) /var/www/html/lms/templates_c/5a2c3c3dae61a15d8ce1aba8174c4609c3ee9ec7_1.extendsall.rtqueueview.html.php:1093
[Tue Oct  2 10:34:48 2018] PHP  27. Smarty_Internal_Runtime_Inheritance->process($tpl = *uninitialized*, $block = *uninitialized*, $parent = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:156
[Tue Oct  2 10:34:48 2018] PHP  28. Smarty_Internal_Runtime_Inheritance->callBlock($block = *uninitialized*, $tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:184
[Tue Oct  2 10:34:48 2018] PHP  29. Block_10817656805bb31e90dc5026_35294911->callBlock($_smarty_tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:248
[Tue Oct  2 10:34:48 2018] PHP  30. Smarty_Internal_Runtime_Inheritance->instanceBlock($tpl = *uninitialized*, $className = *uninitialized*, $name = *uninitialized*, $tplIndex = *uninitialized*) /var/www/html/lms/templates_c/5a2c3c3dae61a15d8ce1aba8174c4609c3ee9ec7_1.extendsall.rtqueueview.html.php:1211
[Tue Oct  2 10:34:48 2018] PHP  31. Smarty_Internal_Runtime_Inheritance->process($tpl = *uninitialized*, $block = *uninitialized*, $parent = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:156
[Tue Oct  2 10:34:48 2018] PHP  32. Smarty_Internal_Runtime_Inheritance->process($tpl = *uninitialized*, $block = *uninitialized*, $parent = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:186
[Tue Oct  2 10:34:48 2018] PHP  33. Smarty_Internal_Runtime_Inheritance->callBlock($block = *uninitialized*, $tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:184
[Tue Oct  2 10:34:48 2018] PHP  34. Block_16948457165bb31e9109bb69_56564657->callBlock($_smarty_tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:248
[Tue Oct  2 10:34:48 2018] PHP  35. Smarty_Internal_Template->_subTemplateRender($template = *uninitialized*, $cache_id = *uninitialized*, $compile_id = *uninitialized*, $caching = *uninitialized*, $cache_lifetime = *uninitialized*, $data = *uninitialized*, $scope = *uninitialized*, $forceTplCache = *uninitialized*, $uid = *uninitialized*, $content_func = *uninitialized*) /var/www/html/lms/templates_c/5a2c3c3dae61a15d8ce1aba8174c4609c3ee9ec7_1.extendsall.rtqueueview.html.php:2241
[Tue Oct  2 10:34:48 2018] PHP  36. Smarty_Template_Compiled->getRenderedTemplateCode($_template = *uninitialized*, $unifunc = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:376
[Tue Oct  2 10:34:48 2018] PHP  37. content_5bb31e912bed17_16663665($_smarty_tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Tue Oct  2 10:34:48 2018] PHP  38. Smarty_Internal_Template->_subTemplateRender($template = *uninitialized*, $cache_id = *uninitialized*, $compile_id = *uninitialized*, $caching = *uninitialized*, $cache_lifetime = *uninitialized*, $data = *uninitialized*, $scope = *uninitialized*, $forceTplCache = *uninitialized*, $uid = *uninitialized*, $content_func = *uninitialized*) /var/www/html/lms/templates_c/5a2c3c3dae61a15d8ce1aba8174c4609c3ee9ec7_1.extendsall.rtqueueview.html.php:1876
[Tue Oct  2 10:34:48 2018] PHP  39. Smarty_Template_Compiled->getRenderedTemplateCode($_template = *uninitialized*, $unifunc = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:376
[Tue Oct  2 10:34:48 2018] PHP  40. content_5bb31e912c1360_67332458($_smarty_tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Tue Oct  2 10:34:48 2018] PHP  41. Smarty_Internal_Runtime_Inheritance->instanceBlock($tpl = *uninitialized*, $className = *uninitialized*, $name = *uninitialized*, $tplIndex = *uninitialized*) /var/www/html/lms/templates_c/5a2c3c3dae61a15d8ce1aba8174c4609c3ee9ec7_1.extendsall.rtqueueview.html.php:1766
[Tue Oct  2 10:34:48 2018] PHP  42. Smarty_Internal_Runtime_Inheritance->process($tpl = *uninitialized*, $block = *uninitialized*, $parent = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:156
[Tue Oct  2 10:34:48 2018] PHP  43. Smarty_Internal_Runtime_Inheritance->callBlock($block = *uninitialized*, $tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:184
[Tue Oct  2 10:34:48 2018] PHP  44. Block_14044057015bb31e912c4461_79928245->callBlock($_smarty_tpl = *uninitialized*) /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:248
`

I jeszcze:

http://lms/?m=rtqueuelist

`[Tue Oct  2 10:32:32 2018] PHP Warning:  array_merge(): Argument #1 is not an array in /var/www/html/lms/lib/LMSManagers/LMSHelpdeskManager.php on line 593
[Tue Oct  2 10:32:32 2018] PHP Stack trace:
[Tue Oct  2 10:32:32 2018] PHP   1. {main}() /var/www/html/lms/index.php:0
[Tue Oct  2 10:32:32 2018] PHP   2. include() /var/www/html/lms/index.php:343
[Tue Oct  2 10:32:32 2018] PHP   3. LMS->GetQueueList($params = *uninitialized*) /var/www/html/lms/modules/rtqueuelist.php:36
[Tue Oct  2 10:32:32 2018] PHP   4. LMSHelpdeskManager->GetQueueList($params = *uninitialized*) /var/www/html/lms/lib/LMS.class.php:1512
[Tue Oct  2 10:32:32 2018] PHP   5. LMSHelpdeskManager->GetQueueStats($id = *uninitialized*) /var/www/html/lms/lib/LMSManagers/LMSHelpdeskManager.php:497
[Tue Oct  2 10:32:32 2018] PHP   6. array_merge(*uninitialized*, *uninitialized*) /var/www/html/lms/lib/LMSManagers/LMSHelpdeskManager.php:593
[Tue Oct  2 10:32:32 2018] 172.20.2.42:54474 [200]: /?m=rtqueuelist`

**Comment by chilek** [comment]
Testuj teraz. Ciekawe czy któryś warning jeszcze zostanie.

**Comment by interduo** [comment]
Zrobiłem rm temaplates_c/*; git fetch origin; git pull origin master;

```
[Tue Oct  2 11:06:44 2018] PHP Warning:  array_merge(): Argument #1 is not an array in /var/www/html/lms/lib/LMSManagers/LMSHelpdeskManager.php on line 594
[Tue Oct  2 11:06:44 2018] PHP Stack trace:
[Tue Oct  2 11:06:44 2018] PHP   1. {main}() /var/www/html/lms/index.php:0
[Tue Oct  2 11:06:44 2018] PHP   2. include() /var/www/html/lms/index.php:343
[Tue Oct  2 11:06:44 2018] PHP   3. LMS->GetQueueList($params = *uninitialized*) /var/www/html/lms/modules/rtqueuelist.php:36
[Tue Oct  2 11:06:44 2018] PHP   4. LMSHelpdeskManager->GetQueueList($params = *uninitialized*) /var/www/html/lms/lib/LMS.class.php:1512
[Tue Oct  2 11:06:44 2018] PHP   5. LMSHelpdeskManager->GetQueueStats($id = *uninitialized*) /var/www/html/lms/lib/LMSManagers/LMSHelpdeskManager.php:497
[Tue Oct  2 11:06:44 2018] PHP   6. array_merge(*uninitialized*, *uninitialized*) /var/www/html/lms/lib/LMSManagers/LMSHelpdeskManager.php:594
```

**Comment by interduo** [comment]
W rtqueueview nadal:

`[Tue Oct  2 11:12:32 2018] PHP Warning:  Use of undefined constant ul - assumed 'ul' (this will throw an Error in a future version of PHP) in /var/www/html/lms/lib/LMSManagers/LMSHelpdeskManager.php on line 555
[Tue Oct  2 11:12:32 2018] PHP Stack trace:
[Tue Oct  2 11:12:32 2018] PHP   1. {main}() /var/www/html/lms/index.php:0
[Tue Oct  2 11:12:32 2018] PHP   2. include() /var/www/html/lms/index.php:343
[Tue Oct  2 11:12:32 2018] PHP   3. LMS->GetEventsByTicketId($id = *uninitialized*) /var/www/html/lms/modules/rtticketview.php:91
[Tue Oct  2 11:12:32 2018] PHP   4. LMSHelpdeskManager->GetEventsByTicketId($id = *uninitialized*) /var/www/html/lms/lib/LMS.class.php:2550`

**Comment by chilek** [comment]
Sam piszesz kod, który generuje takie ostrzeżenia :D

**Comment by chilek** [comment]
Zapamiętaj - już od wielu wersji nie używamy indeksów tabel zapisywanych jako stałe.

**Comment by interduo** [comment]
Zrobiłem ponownie:
rm templates_c/*; git fetch origin; git pull origin master; service apache2 restart;

Błąd w rtticketview niewystępuje. 
Błąd w rtqueuelist tak.

**Comment by chilek** [comment]
> Błąd w rtqueuelist tak.

Jaki dokładnie?
To nie błąd - to ostrzeżenie.

**Comment by interduo** [comment]
Tak racja - ostrzeżenie.

```
[Tue Oct  2 11:29:44 2018] PHP Warning:  array_merge(): Argument #1 is not an array in /var/www/html/lms/lib/LMSManagers/LMSHelpdeskManager.php on line 594
[Tue Oct  2 11:29:44 2018] PHP Stack trace:
[Tue Oct  2 11:29:44 2018] PHP   1. {main}() /var/www/html/lms/index.php:0
[Tue Oct  2 11:29:44 2018] PHP   2. include() /var/www/html/lms/index.php:343
[Tue Oct  2 11:29:44 2018] PHP   3. LMS->GetQueueList($params = *uninitialized*) /var/www/html/lms/modules/rtqueuelist.php:36
[Tue Oct  2 11:29:44 2018] PHP   4. LMSHelpdeskManager->GetQueueList($params = *uninitialized*) /var/www/html/lms/lib/LMS.class.php:1512
[Tue Oct  2 11:29:44 2018] PHP   5. LMSHelpdeskManager->GetQueueStats($id = *uninitialized*) /var/www/html/lms/lib/LMSManagers/LMSHelpdeskManager.php:497
[Tue Oct  2 11:29:44 2018] PHP   6. array_merge(*uninitialized*, *uninitialized*) /var/www/html/lms/lib/LMSManagers/LMSHelpdeskManager.php:594
```

**Comment by chilek** [comment]
Przy jakich parametrach to wywołanie?

**Comment by interduo** [comment]
Przy braku. 
Nawet klikałem w śmietniczek.

**Comment by chilek** [comment]
Poprawione.

**Comment by interduo** [comment]
Czysto w logu. Dzięki.

**Comment by chilek** [comment]
Jeszcze jedna optymalizacja - powyższy commit - jak nie ma zgłoszeń w kolejce to nie będzie w ogóle drugie zapytanie się wykonywać, bo po co?

**Comment by chilek** [comment]
Poszła poprawka.

**Comment by chilek** [comment]
Poprawione.

**Comment by interduo** [comment]
Jeszcze tutaj:

```
[Thu Oct  4 19:20:11 2018] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/lms/lib/LMSManagers/LMSNetDevManager.php on line 634
[Thu Oct  4 19:20:11 2018] PHP Stack trace:
[Thu Oct  4 19:20:11 2018] PHP   1. {main}() /var/www/html/lms/index.php:0
[Thu Oct  4 19:20:11 2018] PHP   2. include() /var/www/html/lms/index.php:343
[Thu Oct  4 19:20:11 2018] PHP   3. include() /var/www/html/lms/modules/customerinfo.php:59
[Thu Oct  4 19:20:11 2018] PHP   4. LMS->GetNetDevList() /var/www/html/lms/modules/customer.inc.php:84
[Thu Oct  4 19:20:11 2018] PHP   5. LMSNetDevManager->GetNetDevList() /var/www/html/lms/lib/LMS.class.php:1358
```

**Comment by chilek** [comment]
W dniu 04.10.2018 19:21, Interduo napisał(a):
> Jeszcze tutaj:
> 
> [Thu Oct  4 19:20:11 2018] PHP Warning:  count(): Parameter must be an
> array or an object that implements Countable in
> /var/www/html/lms/lib/LMSManagers/LMSNetDevManager.php on line 634
> [Thu Oct  4 19:20:11 2018] PHP Stack trace:
> [Thu Oct  4 19:20:11 2018] PHP   1. {main}()
> /var/www/html/lms/index.php:0
> [Thu Oct  4 19:20:11 2018] PHP   2. include()
> /var/www/html/lms/index.php:343
> [Thu Oct  4 19:20:11 2018] PHP   3. include()
> /var/www/html/lms/modules/customerinfo.php:59
> [Thu Oct  4 19:20:11 2018] PHP   4. LMS->GetNetDevList()
> /var/www/html/lms/modules/customer.inc.php:84
> [Thu Oct  4 19:20:11 2018] PHP   5. LMSNetDevManager->GetNetDevList()
> /var/www/html/lms/lib/LMS.class.php:1358

Poprawione.

**Comment by interduo** [comment]
```[Mon Oct  8 23:50:12 2018] PHP Notice:  cycle: missing 'values' parameter in /var/www/html/lms/vendor/smarty/smarty/libs/plugins/function.cycle.php on line 53
[Mon Oct  8 23:50:12 2018] PHP Stack trace:
[Mon Oct  8 23:50:12 2018] PHP   1. {main}() /var/www/html/lms/index.php:0
[Mon Oct  8 23:50:12 2018] PHP   2. include() /var/www/html/lms/index.php:343
[Mon Oct  8 23:50:12 2018] PHP   3. LMSSmarty->display() /var/www/html/lms/modules/userlist.php:32
[Mon Oct  8 23:50:12 2018] PHP   4. LMSSmarty->display() /var/www/html/lms/lib/LMSSmarty.php:43
[Mon Oct  8 23:50:12 2018] PHP   5. LMSSmarty->_execute() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:134
[Mon Oct  8 23:50:12 2018] PHP   6. Smarty_Internal_Template->render() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:232
[Mon Oct  8 23:50:12 2018] PHP   7. Smarty_Template_Compiled->render() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:216
[Mon Oct  8 23:50:12 2018] PHP   8. Smarty_Template_Compiled->getRenderedTemplateCode() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:114
[Mon Oct  8 23:50:12 2018] PHP   9. content_5bbbd1143a5d90_90812619() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Mon Oct  8 23:50:12 2018] PHP  10. Smarty_Internal_Template->_subTemplateRender() /var/www/html/lms/templates_c/44bd0fe278ed33ae88cd4fda58b534c1dfc2f2b1_1.extendsall.userlist.html.php:116
[Mon Oct  8 23:50:12 2018] PHP  11. Smarty_Template_Compiled->getRenderedTemplateCode() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:376
[Mon Oct  8 23:50:12 2018] PHP  12. content_5bbbd114251681_13838373() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Mon Oct  8 23:50:12 2018] PHP  13. Smarty_Internal_Runtime_Inheritance->endChild() /var/www/html/lms/templates_c/44bd0fe278ed33ae88cd4fda58b534c1dfc2f2b1_1.extendsall.userlist.html.php:1323
[Mon Oct  8 23:50:12 2018] PHP  14. Smarty_Internal_Template->_subTemplateRender() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:125
[Mon Oct  8 23:50:12 2018] PHP  15. Smarty_Template_Compiled->getRenderedTemplateCode() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:376
[Mon Oct  8 23:50:12 2018] PHP  16. content_5bbbd114252e88_74443868() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Mon Oct  8 23:50:12 2018] PHP  17. Smarty_Internal_Template->_subTemplateRender() /var/www/html/lms/templates_c/44bd0fe278ed33ae88cd4fda58b534c1dfc2f2b1_1.extendsall.userlist.html.php:1306
[Mon Oct  8 23:50:12 2018] PHP  18. Smarty_Template_Compiled->getRenderedTemplateCode() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:376
[Mon Oct  8 23:50:12 2018] PHP  19. content_5bbbd114253e78_65180406() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Mon Oct  8 23:50:12 2018] PHP  20. Smarty_Internal_Template->_subTemplateRender() /var/www/html/lms/templates_c/44bd0fe278ed33ae88cd4fda58b534c1dfc2f2b1_1.extendsall.userlist.html.php:1297
[Mon Oct  8 23:50:12 2018] PHP  21. Smarty_Template_Compiled->getRenderedTemplateCode() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:376
[Mon Oct  8 23:50:12 2018] PHP  22. content_5bbbd1142550b7_44163238() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Mon Oct  8 23:50:12 2018] PHP  23. Smarty_Internal_Template->_subTemplateRender() /var/www/html/lms/templates_c/44bd0fe278ed33ae88cd4fda58b534c1dfc2f2b1_1.extendsall.userlist.html.php:1193
[Mon Oct  8 23:50:12 2018] PHP  24. Smarty_Template_Compiled->getRenderedTemplateCode() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:376
[Mon Oct  8 23:50:12 2018] PHP  25. content_5bbbd114256046_33368331() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123
[Mon Oct  8 23:50:12 2018] PHP  26. Smarty_Internal_Runtime_Inheritance->instanceBlock() /var/www/html/lms/templates_c/44bd0fe278ed33ae88cd4fda58b534c1dfc2f2b1_1.extendsall.userlist.html.php:1068
[Mon Oct  8 23:50:12 2018] PHP  27. Smarty_Internal_Runtime_Inheritance->process() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:156
[Mon Oct  8 23:50:12 2018] PHP  28. Smarty_Internal_Runtime_Inheritance->callBlock() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:184
[Mon Oct  8 23:50:12 2018] PHP  29. Block_957115655bbbd1142a4c29_00771654->callBlock() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:248
[Mon Oct  8 23:50:12 2018] PHP  30. Smarty_Internal_Runtime_Inheritance->instanceBlock() /var/www/html/lms/templates_c/44bd0fe278ed33ae88cd4fda58b534c1dfc2f2b1_1.extendsall.userlist.html.php:1180
[Mon Oct  8 23:50:12 2018] PHP  31. Smarty_Internal_Runtime_Inheritance->process() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:156
[Mon Oct  8 23:50:12 2018] PHP  32. Smarty_Internal_Runtime_Inheritance->process() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:186
[Mon Oct  8 23:50:12 2018] PHP  33. Smarty_Internal_Runtime_Inheritance->callBlock() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:184
[Mon Oct  8 23:50:12 2018] PHP  34. Block_13441586675bbbd1143742a0_42356763->callBlock() /var/www/html/lms/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php:248
[Mon Oct  8 23:50:12 2018] PHP  35. smarty_function_cycle() /var/www/html/lms/templates_c/44bd0fe278ed33ae88cd4fda58b534c1dfc2f2b1_1.extendsall.userlist.html.php:1408
[Mon Oct  8 23:50:12 2018] PHP  36. trigger_error() /var/www/html/lms/vendor/smarty/smarty/libs/plugins/function.cycle.php:53```

To jeszcze jeden.

**Comment by chilek** [comment]
Wygląda na to, że tam {cycle} w ogóle nie było potrzebne.
