### ISSUE TITLE
Undefined function easter_date()

### ISSUE THREAD

**Issue by seba11** [lmsgit/lms#1424]
`Fatal error: Call to undefined function easter_date() in lms/lib/locale/pl/system.php on line 142`

Szukając w plikach repozytorium nie znalazłem definicji funkcji easter_date().

**Comment by chilek** [comment]
Drugi rezultat z google po wpisaniu: _debian php easter_date_:
https://stackoverflow.com/questions/5297894/fatal-error-call-to-undefined-function-easter-date
