### ISSUE TITLE
Terminarz po update

### ISSUE THREAD

**Issue by milekz** [lmsgit/lms#1446]
Witam, zauważyłem mały problem z Terminarzem , mianowicie po wykonaniu upgradeu z LMS -2 lata miałem pustą listę. 

Do poprawnego wyswietlania eventów musiałem popełnić

update events set date =  extract(epoch from  substr((TIMESTAMP 'epoch' + date  * INTERVAL '1 second')::text,0,11)::date ) ; 

Czyli, poprawiłem daty eventow z danego dnia na godzine 00:00:00  ( w przeciwnym razie mam pusty szablon )

linia 38 w eventlistbox.html " {if $eventlist[eventlist].date == $daylist[daylist]} "  - tutaj leży problem lub miałem niefart

**Comment by interduo** [comment]
https://github.com/lmsgit/lms/pull/1447

Zerknij czy to nie jest powiązane z Twoim zgłoszeniem.

**Comment by interduo** [comment]
To już nie jest aktualne.
