### ISSUE TITLE
LMS frontend

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#145]
Chciałem trochę odświeżyć frontend, ale według mnie szkoda czasu na grzebanie w obecnym dość archaicznym kodzie. Chcę przerobić aktualny kod na coś zgodnego z HTML5. Teraz pytania, który kierunek obrać:

1. Grzebanie w istniejącym szablonie z katalogu **templates** - jeden szablon dla wszystkich?

2. Stworzenie nowych template np. **templates/nazwa_szablonu**, wtedy każdy z poziomu np. **lms.ini** mógłby aktywować odpowiedni szablon według uznania?

Domyślnie: templates/default
Nowe szablony: templates/nazwa_szablonu

Inne pomysły?

**Comment by nicraMarcin** [comment]
Witam,
czy będzie jakaś możliwość udosępnienia tego?

**Comment by interduo** [comment]
Świetnie to wygląda. 
Kyob, podzielisz się z nami?

**Comment by kyob** [comment]
Tak postaram się wrzucić gałąź z szablonem na moim repo. Jak wrzucę dam znać.
Niestety z braku czasu szablon nie został ukończony. Tutaj muszę przyznać rację @chilek, że utrzymywanie równoległe dwóch szablonów w dłuższej perspektywie jest kłopotliwe.

**Comment by kyob** [comment]
Wersja developerska używacie na własną odpowiedzialność :)
https://github.com/kyob/lms/tree/twbs-template

**Comment by kyob** [comment]
Pacjent #145 zmarł. Nowy obiekt badań otrzymał nr https://github.com/lmsgit/lms/issues/776
