### ISSUE TITLE
Szablon planu numeracyjnego.

### ISSUE THREAD

**Issue by toplek** [lmsgit/lms#1451]
Dzień dobry,

w najnowszej wersji LMSa pojawił mi się problem z planami numeracyjnymi.
Mam utworzony domyślny szablon, który wygląda następująco:
` %N/%Y/SPG-SP`

Do powyższego szablonu przypisany jest jeden z oddziałów firmy. Problem pojawia się przy wystawianiu faktury dla klienta przypisanego do ww. oddziału. Zamiast powyższego szablonu na fakturze pojawia się numer faktury z domyślnego szablonu LMSa:
`7/LMS/2019`

W poprzedniej wersji ten problem nie występował. Czy można prosić o wsparcie w tej sprawie?

--Informacje o LMS:
Wersja LMS: | 1.11-git
Wersja LMSDB: | 2018121300
Wersja PostgreSQL: | 9.4.15
Wersja PHP: | 7.0.19-1
Wersja Smarty: | 3.1.33

Z góry dziękuję i pozdrawiam.

**Comment by chilek** [comment]
Witam,

zalecam aktualizację do bieżącej wersji LMS+, albo (jeśli są Państwo subskrybentem) do bieżącej serii wydań LMS+ 1.11.23.x utrzymywanych na bieżąco w gałęzi **stable** projektu LMS+.

Pozdrawiam.

**Comment by toplek** [comment]
Dzień dobry,

niestety po zaktualizowaniu LMS+ do poniższej (najnowszej?) wersji problem nadal występuje:

Wersja LMS: | 1.11-git
Wersja LMSDB: | 2019013100

Czy coś innego może być przyczyną problemu?

**Comment by chilek** [comment]
To nie jest LMS+ - używasz LMS. LMS+ obecnie wydanie stable ma schemat bazy danych **2018022606**.

**Comment by chilek** [comment]
LMS+ to nie jest to samo co LMS. LMS+ to prywatne wydania utrzymywane w ramach projektu w gałęziach stable* i numerowane obecnie jako 1.11.23.1, 1.11.23.2, 1.11.23.3, itd. LMS+ bazuje na publicznych wydaniach numerowanych - ostatnie publiczne to 1.11.23.

**Comment by toplek** [comment]
Racja, była to wersja LMS, pogubiłem się w gałęziach - błąd w sztuce. W każdym razie po aktualizacji do LMS+ efekt jest ten sam:

![lms1](https://user-images.githubusercontent.com/18083324/53639475-a3be6380-3c29-11e9-892c-d6b6b91a901f.png)
Wystawiam fakturę:
![lms2](https://user-images.githubusercontent.com/18083324/53639476-a456fa00-3c29-11e9-9bb8-fd29049bde88.png)
Pozycję na numer faktury pozostawiam pustą, dodaję pozycję faktury, zapisz i oto co wychodzi:
![lms3](https://user-images.githubusercontent.com/18083324/53639478-a456fa00-3c29-11e9-91ba-648a1a655cdc.png)

Jestem niemalże pewien że coś źle robię, ale nie widzę żadnych innych opcji, które miałyby coś zmieniać. Poprzednia wersja: DB:2016033100 działa bez problemu...

**Comment by chilek** [comment]
Czy jesteś w stanie odwzorować dokładnie ten problem na:
https://stable.lms.org.pl
(jeśli nie masz tam jeszcze konta podaj swój email - prześlę na niego login i hasło do logowania
do tego systemu).

**Comment by toplek** [comment]
Konta jeszcze nie mam, bardzo proszę o utworzenie, podaję adres e-mail:
toplek (małpa) polok.pl

**Comment by toplek** [comment]
Dziękuję za przesłanie dostępu, udało się przetestować. Wniosek jest taki:
Każdy plan numeracyjny, którego id jest >0 działa w porządku. W momencie gdy jego id=0, wtedy brany jest pod uwagę domyślny plan numeracyjny LMSa, czyli np. 1/LMS/2019. Poniżej utworzyłem kilka planów numeracyjnych, z czego działają wszystkie oprócz pierwszego. 

![image](https://user-images.githubusercontent.com/18083324/53644542-21d53700-3c37-11e9-9776-82bb62f2e863.png)

Usuwam więc plan numeracyjny o id=0 i problem już nie występuje. 
Dziękuję za pomoc. Pozdrawiam.

**Comment by chilek** [comment]
@toplek jak Ci udało się zrobić plan numeracyjny o ID równym 0? :)

**Comment by toplek** [comment]
Właśnie też się nad tym zastanawiam :D Problem rozwiązany, zamykam wątek.
