### ISSUE TITLE
lms-teryt.php -b = PHP Warning and loop

### ISSUE THREAD

**Issue by cyberavis** [lmsgit/lms#1476]
https://github.com/lmsgit/lms/blob/bf016634dc6859eec4146bc1a947ba7422477607/bin/lms-teryt.php#L1240

```
PHP Warning:  Division by zero in /usr/sbin/lms-teryt.php on line 1240
PHP Warning:  feof() expects parameter 1 to be resource, boolean given in /usr/sbin/lms-teryt.php on line 1130
PHP Warning:  fread() expects parameter 1 to be resource, boolean given in /usr/sbin/lms-teryt.php on line 1131
```

I się zapętla.
Przy okazji można zrobić update linii 239 i 230 na:
```
define('BUILDING_BASE_ZIP_NAME', 'baza_punktow_adresowych_2018.zip');
define('BUILDING_BASE_ZIP_URL', 'https://form.teleinfrastruktura.gov.pl/help-files/baza_punktow_adresowych_2018.zip');
```

**Comment by chilek** [comment]
https://github.com/lmsgit/lms/commit/945fc24bfa60de8b12cc344e80186694ec44cdbc

Baza budynków uaktualniona i pewnie pobieranie nieaktualnej bazy było przyczyną problemów.
SIIS musiał jakoś niedawno uaktualnić bazę budynków, bo jak spoglądałem jakiś czas temu to nadal była z zeszłego roku.
