### ISSUE TITLE
LMS & PHP7

### ISSUE THREAD

**Issue by DariusEvs** [lmsgit/lms#1500]
Hi,

we need to run tje LMS with php7, is it possible, because when we run the command the error apear:

root@lms:/var/www/lms# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)

  [ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

what is the matter ???

root@lms:/var/www/lms# php -v
PHP 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7 (cli) (built: May 31 2019 11:27:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7, Copyright (c) 1999-2018, by Zend Technologies

**Comment by maciejlew** [comment]
https://www.php.net/manual/en/migration73.incompatible.php

There must be a switch that use continue statement somewhere in the code.

W dniu 05.06.2019 o 21:55, DariusEvs pisze:

**Comment by DariusEvs** [comment]
Can anyone tell me which version of php I must to use  with lms plus that it function fully and correctly ?

**Comment by chilek** [comment]
What output the following cli command show you:

```bash
composer info
composer -V
```

Have you tried:

```bash
composer selfupdate
```

?

**Comment by DariusEvs** [comment]
root@lms:/var/www/lms# composer selfupdate
Do not run Composer as root/super user! See https://getcomposer.org/root for details


  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "selfupdate" is not defined.


root@lms:/var/www/lms# composer info
Do not run Composer as root/super user! See https://getcomposer.org/root for details
root@lms:/var/www/lms# composer -V
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.2.2 2016-11-03 17:43:15

**Comment by chilek** [comment]
You use to high PHP version according to installed composer package.
Try to upgrade composer manually or also from backports.

**Comment by DariusEvs** [comment]
Thanks it working, but now I have another problem, when I import the database the error apear:
root@lms:~# mysql -u lms -p lms < /home/darius/lms-2019-06-06.sql
Enter password:
ERROR 1305 (42000) at line 4982: FUNCTION lms.lms_current_user does not exist

and when I ry to connect with my old credentials it say that bad login name or password, how I can to reset old users and create new user ?

**Comment by chilek** [comment]
Does /home/darius/lms-2019-06-06.sql file contains you own, custom mysql dump?
If it does it looks like something is missed in this dump. You have `lms_current_user` usage in dump, but it's not defined in this dump.

**Comment by DariusEvs** [comment]
I create new database lms on new host and try to import the database structure
root@lms:/var/www/lms# mysql -u lms -p lms < /var/www/lms/doc/lms.mysql
Enter password:
ERROR 1050 (42S01) at line 191: Table 'vusers' already exists

what is the matter ?
