### ISSUE TITLE
Howto get the division address

### ISSUE THREAD

**Issue by DariusEvs** [lmsgit/lms#1509]
Hi,

we make my own invoice.pdf and I don't know how I can the division address, all other I can get for example
$y = $y - $this->backend->text_align_left($x, $y , $font_size, "PVM kodas: " . $this->data['division_ten']);
but how I can to get value the division address, city or etc... ???? Pls help :)

**Comment by chilek** [comment]
TCPDF: https://github.com/lmsgit/lms/blob/master/lib/LMSDocuments/LMSTcpdfInvoice.php#L498
The same variable is defined for EZPDF and HTML invoices.
