### ISSUE TITLE
regon on ezpdfinvoice

### ISSUE THREAD

**Issue by DariusEvs** [lmsgit/lms#1510]
$y=$y-$this->backend->text_align_left($x, $y, $font_size, "Įmonės / asmens kodas " . $this->data['regon'] . $this->data['ssn']); 

why the $this->data['regon']  is empty, on customer form the field is filled ...
what is the $this->data structure ? can I change it ?

**Comment by chilek** [comment]
Insert:
```php
print_r($invoice);
```
before:
https://github.com/lmsgit/lms/blob/master/modules/invoice.php#L34
line and you will see all variable which you can use in invoice generation code.

**Comment by DariusEvs** [comment]
Hi,

but we need the company code on invoice pdf, how we can to add it ?

**Comment by chilek** [comment]
Have you tried what I wrote above? ;-)

**Comment by DariusEvs** [comment]
yes, but I can't find the cutomer regon field :( the "ten" field exist , the "ssn" exist, but "regon" field no

**Comment by chilek** [comment]
Customer REGON is not copied to documents table during invoice issue.
You can insert:
```sql
c.regon
```
somewhere in place:
https://github.com/lmsgit/lms/blob/master/lib/LMSManagers/LMSFinanceManager.php#L1864

**Comment by DariusEvs** [comment]
super, thank you, So how I can to get the invoice period on title the invoice, but not on detailed lines ?

**Comment by chilek** [comment]
What do you mean by **invoice period**?

**Comment by DariusEvs** [comment]
I write on lms.ini
[payments]
comment		= %tariff už %current_month
paytype		= 3
deadline	= 30

but the %current_month I need to print only once on top of the infoice. see atach.
![Period](https://user-images.githubusercontent.com/44641324/60438298-08f68580-9c19-11e9-92dd-8dd1ad2cb150.jpg)
