### ISSUE TITLE
Problem z $LMS->NodeSetU

### ISSUE THREAD

**Issue by MKaciuba** [lmsgit/lms#1511]
Do wtyczki BillTech został zgłoszony błąd https://github.com/BillTechPL/lms-billtech-plugin/issues/19.
```
Zapytanie: INSERT INTO logmessagedata (logmessageid, name, value) VALUES('35064', ‘warning’, )
Bład: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 2
```

Wiem, że istnieje już dyskusja na ten temat tutaj: https://github.com/chilek/lms-plus/issues/774#issuecomment-509189568 ale niestety nie mam dostępu do lms-plus, dlatego zgłaszam tutaj, żeby kontynuować dyskusję.

Błąd zaczął się pojawiać po aktualizacji do nowej wersji LMS. Udało się zawęzić przyczynę do wywołania `$LMS->NodeSetU`.

@interduo pisze:
> "Błąd z początku zgłoszenia może wskazywać, że wykonywane są czynności na dzienniku zdarzeń np. bez rozpoczęcia wcześniej transakcji dziennika. Rozpoczęcie transakcji wykonuje się przez:
>
> $SYSLOG->NewTransaction(... nazwa tekstowa transakcji ...);
> Może to tego właśnie brakuje?"
>
> "Być może najpierw będzie jeszcze potrzebne:
> $SYSLOG = SYSLOG::getInstance();"

Widzę, że błąd polega na złej składni zapytania SQL, co wynika z braku wartości dla `value` przy insercie do logmessagedata. Czytam https://github.com/lmsgit/lms/blob/ca96cba2a3379d6377655bf5d3668af0a09d2985/lib/SYSLOG.class.php#L289-L321 i nie bardzo widzę, jak stworzenie nowej transakcji w syslogu miałoby tu pomóc. Być może czegoś nie rozumiem, @chilek mógłbyś rozjaśnić?

**Comment by chilek** [comment]
Ahh zapomniałem o tym:
```php
         if (empty($this->transid)) { 
             $this->DB->Execute('INSERT INTO logtransactions (time, userid, module) 
 				VALUES(?NOW?, ?, ?)', array($this->userid, $this->module)); 
             $this->transid = $this->DB->GetLastInsertID('logtransactions'); 
         } 
```
To i tak utworzy nową transakcję jeśli takowej jeszcze nie było.
Ważne, żeby błąd był powtarzalny - wtedy zapewne da się zweryfikować przyczynę.

**Comment by interduo** [comment]
Tak, jest powtarzalny - występuje za każdym razem po wpłynięciu płatności kiedy wtyczka billtech uruchamia swój kod który korzysta z tej funkcji. Efekt jest widoczny tylko i wyłącznie w pierwszej załadowanej stronie www (lms lub userpanel) dlatego poprzednio wydawało się nam, że to występuje losowo.

**Comment by interduo** [comment]
Commit https://github.com/lmsgit/lms/commit/31a1dcd6cca942e6a3bc7b82547821143e3b3d6e rozwiązuje problem. Proszę o zamknięcie zgłoszenia.
