### ISSUE TITLE
Bug in Helpdesk

### ISSUE THREAD

**Issue by DariusEvs** [lmsgit/lms#1512]
Hi,

LMS versija: | 25-git (2019-06-06T20:10:53+02:00)
-- | --
LMSDB versija: | 2019060300
MySQL versija: | 5.5.5-10.1.38-MariaDB-0+deb9u1
Versija PHP: | 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7
Versija Smarty: | 3.1.33

when I insert new record it inserted twice ....

**Comment by interduo** [comment]
Do You have newest version of LMS?

**Comment by chilek** [comment]
This bug has been already fixed after 2019-06-06T20:10:53+02:00.

**Comment by DariusEvs** [comment]
can I fix only this problem without new installation ? maybe with diff ?

**Comment by chilek** [comment]
Better update using git-update if you've made local copy using git-clone earlier. Many fixes came after 2019-06-06.

**Comment by DariusEvs** [comment]
Hi chilek,

pls help to upgrade our version of LMS to newwest ...
root@lms:/var/www/lms# git pull
fatal: Not a git repository (or any of the parent directories): .git

**Comment by chilek** [comment]
the message above means that you create installation directory without git toolkit and thus it's not git repository.

**Comment by DariusEvs** [comment]
Can I get the lms plus version ? then I try to install it with git tool ...

**Comment by chilek** [comment]
LMS+ and its repository is accessible only to project subscribers - for now most from Poland, but single from Lithuania (do you know Artur of Etanetas ;-))?

**Comment by DariusEvs** [comment]
Yes of corse :) we come from the same association LIPTA, did the lms plus have more features than not plus version ?

**Comment by DariusEvs** [comment]
Problems with helpdesk different users, what is the matter ?
1) I create the user with rights (see atachments)
![user-rights](https://user-images.githubusercontent.com/44641324/62119126-93d5a900-b2c7-11e9-984a-d55fc0372a56.jpg)
2) when I login with this users logins I can't see the helpdesk info on first screen
![dariuskl user login no helpdesk on first screen](https://user-images.githubusercontent.com/44641324/62119242-cda6af80-b2c7-11e9-916b-81d297cf5941.jpg)
3) I login with my account with all rights and I create new ticket
![queue list](https://user-images.githubusercontent.com/44641324/62119352-08a8e300-b2c8-11e9-8a2e-5a7a6ad4d834.jpg)
![new-ticket-from DariusE](https://user-images.githubusercontent.com/44641324/62119391-1d857680-b2c8-11e9-91d8-97b48da444df.jpg)
![queue list with new ticket from DariusE](https://user-images.githubusercontent.com/44641324/62119406-270ede80-b2c8-11e9-8492-2a9de923ec33.jpg)
4) then I login with dariuskl account
![dariuskl no tickets on queue](https://user-images.githubusercontent.com/44641324/62119460-4c9be800-b2c8-11e9-9e3c-9c4d60b74d90.jpg)
when I remove the Fault filter then I see all tickets
![remove fault filter then view all tickets](https://user-images.githubusercontent.com/44641324/62119499-663d2f80-b2c8-11e9-8f27-60bccbdab12d.jpg)
5) when I try to edit the ticket, the not enought rigts error apear
![dariuskl try to edit ticket](https://user-images.githubusercontent.com/44641324/62119561-8967df00-b2c8-11e9-8f49-2d4deb609b9b.jpg)

Pls help with the problem....

**Comment by interduo** [comment]
Do You have granted permission to 'default' category?

**Comment by DariusEvs** [comment]
What do you mean ? where I can to do that ?

**Comment by DariusEvs** [comment]
I found and set the user to the default category and all work fine.  Please explain to me what category it applies to

**Comment by interduo** [comment]
It's like a hashtag for tickets. 
There are many possibilities to use that how to use that (filtering, permissions, stats).

**Comment by DariusEvs** [comment]
Can I get the ZTE GPON module ? How much it cost ?

**Comment by chilek** [comment]
@DariusEvs For price quoting write down to biuro@chilan.com
