### ISSUE TITLE
?m=documentadd szablon z własnymi polami i javascript

### ISSUE THREAD

**Issue by gxw** [lmsgit/lms#1513]
Witam, 
Jestem nowy w LMS, więc proszę o wyrozumiałość

Przy tworzeniu nowego dokumentu (typ np. umowa), po wybraniu szablonu pojawia się zawartość pliku plugin.html z dodatkowymi polami. Jeżeli do pliku (plugin.html) dodam jakiś javascript **nie działa**, zapewne dlatego iż pobrany html wrzucany jest poprzez coś takiego document.getElementById(‘plugin’).innerHTML = html, a w takim wypadku tagi <script> nie zadziałają.

Jednakże, jeżeli zaznaczę opcję _Wyświetl ten formularz ponownie po dodaniu dokumentu_ i zapiszę (zostanie stworzony dokument), nastąpi wysłanie danych POST i przeładowanie strony, automatycznie pojawi się wybrany szablon, z polami z plugin.html i javascript **działa**.

Czy jest jakakolwiek możliwość, aby javascript umieszczony w plugin.html działał od razu po każdej zmianie szablonu? Czy może jest inny sposób, aby to zrobić?

Z góry dzięki za info

**Comment by chilek** [comment]
Użyj np. plugin.js w ramach pluginu dla szablonu dokumentu.
