### ISSUE TITLE
passwd

### ISSUE THREAD

**Issue by vladimirha** [lmsgit/lms#1514]
Hello, at line 1034 of LMSCustomerManager.php need change passwd to n.passwd.

**Comment by chilek** [comment]
Why?

**Comment by vladimirha** [comment]
It throw mysql error for me.

**Comment by chilek** [comment]
@vladimirha could you insert detailed mysql error message here?

**Comment by vladimirha** [comment]
On url /?m=customerinfo&id=
Database errors occurred!

Query: SELECT n.id, n.name, mac, ipaddr, inet_ntoa(ipaddr) AS ip, nd.name as netdev_name, ipaddr_pub, n.authtype, inet_ntoa(ipaddr_pub) AS ip_pub, passwd, access, warning, info, n.ownerid, lastonline, n.location, n.address_id, (SELECT COUNT(*) FROM nodegroupassignments WHERE nodeid = n.id) AS gcount, n.netid, net.name AS netname FROM vnodes n JOIN networks net ON net.id = n.netid LEFT JOIN netdevices nd ON n.netdev = nd.id WHERE n.ownerid = 1940 ORDER BY n.name ASC
Error: Column 'passwd' in field list is ambiguous

**Comment by chilek** [comment]
Yes there's `passwd` field in vnodes view:
https://github.com/lmsgit/lms/blob/master/doc/lms.mysql#L1337-L1388
but I can't see `passwd` field in netdevices table:
https://github.com/lmsgit/lms/blob/master/doc/lms.mysql#L1269-L1306
What does:
```sql
DESCRIBE netdevices;
```
in mysql console show you?
Maybe u use locally modified db schema?

**Comment by vladimirha** [comment]
We use LMS from 2012, once upgrade in 2016 and just now.
Over the years, there has certainly been something modified.

+--------------------+---------------------+------+-----+---------+----------------+
| Field              | Type                | Null | Key | Default | Extra          |
+--------------------+---------------------+------+-----+---------+----------------+
| id                 | int(11)             | NO   | PRI | NULL    | auto_increment |
| name               | varchar(32)         | NO   |     |         |                |
| description        | text                | NO   |     | NULL    |                |
| producer           | varchar(64)         | NO   |     |         |                |
| model              | varchar(128)        | NO   |     |         |                |
| serialnumber       | varchar(32)         | NO   |     |         |                |
| ports              | int(11)             | NO   |     | 0       |                |
| purchasetime       | int(11)             | NO   |     | 0       |                |
| guaranteeperiod    | tinyint(3) unsigned | YES  |     | 0       |                |
| shortname          | varchar(32)         | NO   |     |         |                |
| nastype            | int(11)             | NO   |     | 0       |                |
| clients            | int(11)             | NO   |     | 0       |                |
| secret             | varchar(60)         | NO   |     |         |                |
| community          | varchar(50)         | NO   |     |         |                |
| channelid          | int(11)             | YES  | MUL | NULL    |                |
| x                  | int(11)             | YES  |     | NULL    |                |
| y                  | int(11)             | YES  |     | NULL    |                |
| sektor             | int(11)             | YES  |     | NULL    |                |
| longitude          | decimal(10,6)       | YES  |     | NULL    |                |
| latitude           | decimal(10,6)       | YES  |     | NULL    |                |
| monit_nastype      | int(11)             | NO   |     | 0       |                |
| monit_login        | varchar(60)         | NO   |     |         |                |
| monit_passwd       | varchar(60)         | NO   |     |         |                |
| monit_port         | varchar(5)          | YES  |     | NULL    |                |
| networknodeid      | int(10) unsigned    | NO   |     | 0       |                |
| server             | varchar(64)         | NO   |     |         |                |
| coaport            | varchar(5)          | YES  |     | NULL    |                |
| devtype            | tinyint(1)          | NO   |     | 1       |                |
| managed            | tinyint(1)          | NO   |     | 1       |                |
| sharing            | tinyint(1)          | NO   |     | 0       |                |
| modular            | tinyint(1)          | NO   |     | 0       |                |
| backbone_layer     | tinyint(1)          | NO   |     | 0       |                |
| distribution_layer | tinyint(1)          | NO   |     | 1       |                |
| access_layer       | tinyint(1)          | NO   |     | 1       |                |
| typeofdevice       | int(10) unsigned    | NO   |     | 0       |                |
| netdevicemodelid   | int(11)             | YES  | MUL | NULL    |                |
| invprojectid       | int(11)             | YES  | MUL | NULL    |                |
| status             | tinyint(1)          | YES  |     | 0       |                |
| login              | varchar(128)        | YES  |     | NULL    |                |
| passwd             | varchar(128)        | YES  |     | NULL    |                |
| ibgp               | bigint(20)          | NO   |     | 0       |                |
| ebgp               | bigint(20)          | NO   |     | 0       |                |
| netnodeid          | int(11)             | YES  | MUL | NULL    |                |
| ownerid            | int(11)             | YES  | MUL | NULL    |                |
| address_id         | int(11)             | YES  | MUL | NULL    |                |
+--------------------+---------------------+------+-----+---------+----------------+
45 rows in set (0.00 sec)

**Comment by vladimirha** [comment]
Anyway, in query is (short way) "SELECT  **passw** FROM vnodes **n** JOIN".
Correct me if I am wrong but if passwd be n.passwd then will not be doubt in which table should be passwd.

**Comment by chilek** [comment]
> Anyway, in query is (short way) "SELECT passw FROM vnodes n JOIN". Correct me if I am wrong but if passwd be n.passwd then will not be doubt in which table should be passwd.

Correct.

Basing on database netdevices table schema I assume that you don't use LMS, but some clone,  maybe inetlms?

**Comment by vladimirha** [comment]
If i remember well yea, we did try inetlms some years ago.
