### ISSUE TITLE
[adescom plugin] Błędna numeracji pozycji na fv

### ISSUE THREAD

**Issue by sparbelon** [lmsgit/lms#1521]
Moduł adescom(aktualny commit lms(24.5) i plugin adescom) dubluje itemid, poniżej przykład:
+-------+--------+-----------+-----------+-----------+-------+--------+---------+-------+-------------------------------------------------------+----------+
| docid | itemid | value     | pdiscount | vdiscount | taxid | prodid | content | count | description                                           | tariffid |
+-------+--------+-----------+-----------+-----------+-------+--------+---------+-------+-------------------------------------------------------+----------+
| 28342 |      1 | 399.00000 |      0.00 |    400.50 |     1 |        | szt.    | 1.000 | SYMETRYK 30 za 08/2019                                |       44 |
| 28342 |      2 | 149.00000 |      0.00 |      1.00 |     1 |        | szt.    | 1.000 | Abonament telefoniczny za 08/2019                     |      244 |
| 28342 |      3 |  34.44000 |      0.00 |      0.00 |     1 |        | szt.    | 1.000 | Abonament za numer                                    |     NULL |
| 28342 |      4 |  12.30000 |      0.00 |      0.00 |     1 |        | szt.    | 1.000 | Zewnętrzny adres IP                                   |     NULL |
| 28342 |      5 |   1.23000 |      0.00 |      0.00 |     1 |        | szt.    | 1.000 | Usługa Wirtulanej Centrali CENTREX                    |     NULL |
| 28342 |      2 |   1.80000 |      0.00 |      0.00 |     1 |        | szt.    | 1.000 | Połączenia telefoniczne poza abonamentem za 07/2019   |       -3 |
+-------+--------+-----------+-----------+-----------+-------+--------+---------+-------+-------------------------------------------------------+----------+
6 rows in set (0.00 sec)

Zdarzają się też kombinacje 1,2,3,4,9 gdzie 9 to pozycja "Połączenia telefoniczne poza abonamentem za 07/2019"

**Comment by chilek** [comment]
Plugin Adescom nie jest wspierany w ramach projektu LMS. Proszę o wprowadzenie zgłoszenia z poziomu systemu github.com przeznaczonego projektowi LMS+:
https://github.com/chilek/lms-plus/issues/
Od razu wpisując zgłoszenie w LMS+ proponuję dokładnie opisać w jaki sposób generowane są faktury oraz skąd pobrana jest wtyczka **adescom**.

**Comment by chilek** [comment]
Obsłużone w ramach systemu zgłoszeń LMS+.
