### ISSUE TITLE
Network devices list

### ISSUE THREAD

**Issue by DariusEvs** [lmsgit/lms#1524]
Hi,

Since we rent some equipment, some are purchased by the customer, so we need information in the contract as to what equipment is rented so that we can recover it at the end of the service. So I try to solve this place through an investment project so I can isolate the state of the equipment. But I am missing the list of equipment for sale date in field filtering. Is it possible to solve this situation in some other way?
![1](https://user-images.githubusercontent.com/44641324/62272401-a96fdd80-b443-11e9-82cc-cb243bf058ab.jpg)
![2](https://user-images.githubusercontent.com/44641324/62272409-ad9bfb00-b443-11e9-812a-9ad1973bb46d.jpg)

**Comment by chilek** [comment]
Warehouse plugin from LMS+ project allows to mark all network devices transfer by warehouse documents.
