### ISSUE TITLE
Userpanel updateuserform - Brak weryfikacji poprawności adresu e-mail.

### ISSUE THREAD

**Issue by seba11** [lmsgit/lms#1528]
Można zapisać błędny adres e-mail w sytuacji gdy klient ma możliwość edycji danych  kontaktowych z poziomu userpanel-a. 
Prosta zmiana typu selektora input z text na email nie zdaje egazminu, ponieważ formularz wysyłany jest za pomocą JS.

**Comment by chilek** [comment]
Na którym temacie graficznym robisz testy? default, old czy bclean?
