### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by DariusEvs** [lmsgit/lms#1531]
Hello,

I want to translate the several comboboxes in node section, but I can't find it 
![lms-translate-1](https://user-images.githubusercontent.com/44641324/62853731-df3f7c80-bcf5-11e9-97e8-3ee258d6c43a.jpg)
![lms-translate-2](https://user-images.githubusercontent.com/44641324/62853737-e2d30380-bcf5-11e9-933b-4dd6cd36046e.jpg)

in strings.php.

**Comment by interduo** [comment]
You need to add that to strings.php.

**Comment by DariusEvs** [comment]
but I cant't to find it in strings.php, for example I search the komin and not found this string in strings.php ...

**Comment by interduo** [comment]
Change internet browser language to English. 
Are those words changes to English now?

**Comment by DariusEvs** [comment]
No ...
![lms-translate-3](https://user-images.githubusercontent.com/44641324/62863363-40287e00-bd11-11e9-889c-7e0f4dd24950.jpg)

**Comment by interduo** [comment]
Ups, this is hardcoded in `definitsions.php` and should be done in better way.
