### ISSUE TITLE
Sortowanie listy użytkowników

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#1532]
Czy tylko ja mam problem z nienaturalnym sortowaniem użytkowników na liście wyboru?

Według mojej logiki powinno być **sortowanie według nazwiska**, a obecnie jest według loginu.

Czy ktoś zgłasza sprzeciw na zmianę sortowania według nazwiska? :)

**Comment by interduo** [comment]
W którym miejscu?

**Comment by kyob** [comment]
Np. terminarz i helpdesk.

**Comment by interduo** [comment]
Jeśli chodzi o formularz userlist to ja mam per login.
Jeśli chodzi o selekty/multiselekty to ja mam per login.

Fakt - mogłoby być per nazwisko.

**Comment by chilek** [comment]
https://demo.lms.org.pl/?m=rtticketadd
właściciel i weryfikator wg nazwiska posortowane! Były i nadal są.
Używana metoda pobierająca użytkowników: https://github.com/lmsgit/lms/blob/master/lib/LMSManagers/LMSUserManager.php#L84-L89

Dla eventadd faktycznie wg loginu. W wersji rozwojowej zmienimy tu również na nazwisko i imię.

**Comment by kyob** [comment]
Zaproponowana poprawka poprawiła sortowanie, ale został jeszcze jedne szkopuł. 

Mianowicie kolejność jest **IMIĘ NAZWISKO**, a sugerowane rozwiązanie to **NAZWISKO IMIĘ** :)

**Comment by chilek** [comment]
Zrobione powyższym commitem w paru istotnych miejscach. W niektórych już było najpierw nazwisko, a potem imię.
