### ISSUE TITLE
Dublowanie wpisów w plikach lokalizacyjnych strings.php

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#1534]
Przeglądając dziś plik [strings.php](https://github.com/lmsgit/lms/blob/master/userpanel/lib/locale/pl/strings.php#L40-L43) uderzyło mnie wielokrotne tłumaczenie słowa **błąd**

Moim zdaniem powinno być jedno tłumaczenie, a forma prezentacji ustalana indywidualnie na poziomie szablonu smarty.

Ktoś potwierdzi mój tok myślenia czy mam sobie darować ewentualnego PR?

**Comment by chilek** [comment]
W każdym języku może być inny szyk - nie można założyć bezpiecznie, że `{trans("Error")}:` jest równoważne `{trans("Error:")}`. W języku hebrajskim pisze się przecież od prawej do lewej ;-)

**Comment by kyob** [comment]
Jest w [strings.php](https://github.com/lmsgit/lms/blob/master/userpanel/lib/locale/pl/strings.php#L40-L43) 

Proponuje zastąpić to:
`$_LANG['Error'] = 'Błąd';`

Potem w szablonach smarty:

- chcę dwukropek to robię `{trans("Error")}:`
- chcę nawias klamrowy to robię `[ {trans("Error")} ]`
- chcę wykrzyknik to robię `{trans("Error")}!`

Np. potrzebuje [label z auth type bez dwukropka](https://github.com/chilek/lms-plus/blob/master/lib/definitions.php#L845) co w takim wypadku powinienem zrobić?

- dodać kolejną nową pozycję w definitions.php => ` 'label_bez_dwukropka' => trans('Customer ID'), ` i analogicznie nową pozycję w strings.php
- usuwać ostatni znak w PHP
- usunąć ostatni znak w smarty
- zmienić 'label' => trans('Customer ID:'), ` na 'label' => trans('Customer ID'), ` i w szablonach smarty tam, gdzie jest wymagany dwukropek tam go dodaje

**Comment by chilek** [comment]
> hmm to jak rozwiązać ten przykład z label auth_type?

Trzeba chyba dopiero na to znaleźć rozwiązanie...
