### ISSUE TITLE
Karta klienta: Niepoprawne wyświetlanie taryfy przy komputerze

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#1546]
**Informacja o kliencie => karta komputery klienta** pokazuje ostatnią taryfę, a powinno pokazywać aktualnie obowiązującą dla danego komputera.

Testowane na bieżącym stable oraz na [demo.lms.org.pl](https://demo.lms.org.pl/?m=customerinfo&id=15#50)

**Comment by chilek** [comment]
Może być tak jak teraz po poprawce?

**Comment by kyob** [comment]
Bomba :)

**Comment by kyob** [comment]
PS: Mogę prosić o link do poprawki - chciałem zrobić cherry-pick :)

**Comment by kyob** [comment]
Sam sobie odpowiadam: https://github.com/lmsgit/lms/commit/2cdf8f5761870b21cb202c934175281a47a795a6
