### ISSUE TITLE
UX: Utrudnienie przy wyborze daty dla wydarzeń

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#1547]
Np. na stronie https://demo.lms.org.pl/?m=eventadd okienko z wyborem daty zdarzenia pojawia się  po kliknięciu w malutką i nieintuicyjna ikonkę zamiast po kliknięciu w pole typu INPUT. Problem dotyczy wszystkich pól, gdzie wprowadzamy datę i godzinę.

Nasz BOK jednogłośnie stwierdził, że wybór daty zdarzenia powinien być poprzez klikniecie w pole input, gdzie wpisywana jest data i godzina.

Czy takie zachowanie jest celowe czy to jest bug?

**Comment by chilek** [comment]
Takie działanie jest celowe - parę osób zgłaszało, że irytujące jest wyświetlanie tego kalendarza, gdy chcemy datę wpisać ręcznie.

**Comment by kyob** [comment]
Ile osób tyle opinii. U nas niestety takie zachowanie nie sprawdza się.

Dla potomnych poprawka dla mojego zgłoszenia:
[lms-improve-ux-datepicker-toggle.diff.txt](https://github.com/lmsgit/lms/files/3524753/lms-improve-ux-datepicker-toggle.diff.txt)

**Comment by chilek** [comment]
@kyob: masz rację - stąd mój commit powyżej - zmienia i datetimepicker i datepicker zależenie od ustawienia `phpui.open_calendar_on_input_click`, które zaraz udokumentuję w LMS+ wiki.
Same zgłoszenia w ramach suportu LMS+ piszesz w github LMS+. PR-y natomiast muszą iść przez publiczne github LMS (z powodu ograniczeń usługi komercyjnej github).

**Comment by chilek** [comment]
https://github.com/chilek/lms-plus/wiki/Zmienne-konfiguracyjne-LMS-Plus-phpui#phpuiopen_calendar_on_input_click
