### ISSUE TITLE
LMS message add

### ISSUE THREAD

**Issue by DariusEvs** [lmsgit/lms#1554]
Hi,

I can't to send the mail message to customer from LMS, what is the matter ?
I set the all parameters in [mail] section on lms.ini file:
[mail]
smtp_username = user_name
smtp_password = passw

and set the all params in user interface [mail] section
![image](https://user-images.githubusercontent.com/44641324/63680518-8ba45700-c7fc-11e9-831e-5c1bf9be827d.png)

When I send the customer message the mail to the debug_email arrive, but to the customers mail not.
What I do bad ?

**Comment by chilek** [comment]
Checks logs in your smtp server. Maybe customer emails are from external domains relating to your smtp server.
