### ISSUE TITLE
customerinfo structure in contract document template

### ISSUE THREAD

**Issue by DariusEvs** [lmsgit/lms#1570]
hi,

what is the data structure in contract document template ? we need the customer telephone info and e-mail on contract document ... how I can to access that info ?

**Comment by DariusEvs** [comment]
Please answer to me .... We need to make the contract document :(

**Comment by interduo** [comment]
Just print all variables from document....

**Comment by DariusEvs** [comment]
I insert the code 
<?php>
print_r({$customerinfo});
?>
into html file, but I not see anything ...

**Comment by interduo** [comment]
`$arr = get_defined_vars();`
or 
{$var|@var_dump}

**Comment by DariusEvs** [comment]
<?php
	var_dump({$customerinfo});
?>
but the list is empty, I don't understand what is wrong ..

**Comment by DariusEvs** [comment]
Pls help how I can to print the customer telephone number on contract document, when the structure look like this 
["phones"]=> array(1) { [0]=> array(5) { ["phone"]=> string(11) "370111222" ["contact"]=> string(11) "370111222" ?

**Comment by interduo** [comment]
use print_r instead of print or smarty `|@debug_print_var`
