### ISSUE TITLE
Grupowanie taryf

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#158]
W przypadku, gdy taryf jest kilkadziesiąt lub więcej robi się chaos.

Pomysły:
1) grupowanie tagami
2) przedrostkiem
3) w formie katalogów

Co o tym myślicie?

**Comment by kyob** [comment]
Jestem w trakcie pisania. Jak skończę wrzucę na tapetę do weryfikacji.

**Comment by chilek** [comment]
Czekam ;-) Masz wolne mocne przerobowe, żeby coś robić na zlecenie do LMS/ LMS Plus?

**Comment by kyob** [comment]
Tak i nie. Zależy od zlecenia. Im zlecenie bardzie zbieżne z naszymi potrzebami tym więcej czasu będę mógł wygospodarować :)

**Comment by kyob** [comment]
Feature zrobiony: https://github.com/lmsgit/lms/commit/f5b2a3c7fa56e667455ae66e5fcf67b72b113498
