### ISSUE TITLE
Podatność XSS

### ISSUE THREAD

**Issue by zwirek-pl** [lmsgit/lms#1584]
Witam,
w wersji LMS 1.11-git, której używa mój dostawca występuje podatność XSS.
https://lms.domena.pl/userpanel/?m=<script>alert(123)</script>
https://lms.domena.pl/userpanel/?m=<script>alert(document.cookie)</script>

Czy w najnowszej wersji też występuje ta podatność ?
Pozdrawiam
ZwireK

**Comment by chilek** [comment]
Witam,

bardzo dziękuję za zgłoszenie problemu, który został rozwiązany powyższym commitem.
Poprawka oprócz wersji rozwojowej (gałąź `master`) weszła również do LMS+ 24.x i 1.11.23.x.

Pozdrawiam!
