### ISSUE TITLE
Błąd java - usuwanie historii

### ISSUE THREAD

**Issue by cyberavis** [lmsgit/lms#1586]
Przy próbie usunięcia wpisu z "Historia operacji" (po wciśnięciu usuń, a przed potwierdzeniem) powstaje jakiś błąd java po czym w przeglądarce wyświetla się jedynie "false", a w pasku adresu "javascript:DeleteMarked();"

openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-suse-lp151.3.6.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.4+11-suse-lp151.3.6.1-x8664, mixed mode)

**Comment by chilek** [comment]
Ta jasne OpenJDK ;-) LMS nie używa Javy, tylko JavaScript działającej po stronie przeglądarki. Poza tym przetestowałem na demo.lms.org.pl - błąd nie występuje.

**Comment by cyberavis** [comment]
No dobra, Java czy JavaScript (niby wiem, że to nie to samo) - ale błąd
powstaje z tym, że jedynie w Firefox 60.8.0.ESR for openSUSE Leap (tak
dla ścisłości).

W dniu 21.10.2019 o 16:48, Tomasz Chiliński pisze:

**Comment by chilek** [comment]
U mnie w Firefox 69.x też nie działało. Poprawione powyższym commitem.
