### ISSUE TITLE
Sieć IP bez określania hosta

### ISSUE THREAD

**Issue by dyzajash** [lmsgit/lms#1602]
Dzień dobry,
w LMS 1.11.21 była możliwość dodania sieci IP bez określania hosta. Czy w nowej wersji jest możliwość zdjęcia tego wymogu za pomocą jakiejś flagi / opcji? Czy wymagana jest modyfikacja kodu źródłowego?

**Comment by interduo** [comment]
A nie możesz sobie dodać hosta "bezhosta" ?;)

**Comment by dyzajash** [comment]
Jakby to przeszło z operatorami to tematu by nie było :). Czyli jak rozumiem, jedyna możliwość aby przywrócić "starą funkcjonalność" to modyfikacja kodu źródłowego.

Aby nie tworzyć nowego issue pozwolę sobie zadać jeszcze jedno pytanie: jaka jest wasza polityka odnośnie releasów? Obecnie mam wgrany na serwer release 24, który jak się okazuje ma kilka bugów naprawionych na obecnym masterze. Czy branch "master" jest u was branchem stabilnym? Czy należy czekać na nowy release aby nadawało się to na użytek produkcyjny?

**Comment by chilek** [comment]
> Aby nie tworzyć nowego issue pozwolę sobie zadać jeszcze jedno pytanie: jaka jest wasza polityka odnośnie releasów? Obecnie mam wgrany na serwer release 24, który jak się okazuje ma kilka bugów naprawionych na obecnym masterze. Czy branch "master" jest u was branchem stabilnym? Czy należy czekać na nowy release aby nadawało się to na użytek produkcyjny?

LMS 24 ma akttualizacje w ramach LMS+ serii wydań 24.x dostępnych wyłącznie dla uczestników projektu LMS+ (http://lms-plus.org). Zresztą w LMS+ utrzymywane jest obecnie 1.11.23.x i 24.x, a za jakieś 1-2 miesiące pojawi się 25.x po czym po 1-2 miesiącach zniknie wsparcie do 1.11.23.x.

**Comment by dyzajash** [comment]
Dziękuję za odpowiedź.
