### ISSUE TITLE
Invoices

### ISSUE THREAD

**Issue by DariusEvs** [lmsgit/lms#1607]
Hi,

Can I generate the invoice date on the last day of the month, but not only 28day of month ?

**Comment by chilek** [comment]
Upgrade your LMS to current master branch - there is a checkbox which allows to setup assignment with last day of month issue.

**Comment by DariusEvs** [comment]
It's a fine, but I made some changes to own LMS :( and when I update it ir overwrite it :( How I can to solve this problem in the future ?

**Comment by interduo** [comment]
use git

**Comment by DariusEvs** [comment]
does with git it not overwrites my changes ?

**Comment by interduo** [comment]
1. always commit your changes
2. update your repo only using git fetch origin; git pull origin master
It works :)

**Comment by DariusEvs** [comment]
I try to view this change on your https://stable.lms.org.pl/ but I don't found it ...

**Comment by interduo** [comment]
so try demo.lms.org.pl

**Comment by DariusEvs** [comment]
what's the login credentials ?

**Comment by interduo** [comment]
https://www.lms.org.pl/demo.php

**Comment by DariusEvs** [comment]
I can't login with user: admin and passw: test credentials :(

**Comment by DariusEvs** [comment]
>>always commit your changes
>>update your repo only using git fetch origin; git pull origin master
>>It works :)

how I can to commit my changes of LMS ?

**Comment by interduo** [comment]
dude learn a basics od git and don't ask that simple things
