### ISSUE TITLE
Zdublowane nadplaty

### ISSUE THREAD

**Issue by jakrzy** [lmsgit/lms#1610]
W podsumowaniu Zaleglosci/Nadplaty `m=customerlist&s=&o=balance,desc` kwota nadpłaty jest dwukrotnie wyższa.

DB: 2020011402

**Comment by chilek** [comment]
Sprawdziłem na demo - opisywany problem nie występuje. Testujesz na pgsql czy mysql?

Jak wyglądają wyniki zapytań:
```sql
SELECT COUNT(*) FROM customers;
SELECT COUNT(*) FROM customerbalances;
```
?

**Comment by jakrzy** [comment]
mysql -V
mysql  Ver 15.1 Distrib 10.1.43-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

SELECT COUNT(*) FROM customers;
count(*) 42
SELECT COUNT(*) FROM customerbalances;
Count(*) 3

Problem zauwazylem po aktualizacji z  LMS24

**Comment by chilek** [comment]
> mysql Ver 15.1 Distrib 10.1.43-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Dla LMS i LMS+ zawsze mocno zalecanym silnikiem był (i jest) PostgreSQL. Nie chodzi o to, żeby teraz wyliczać wady i zalety jednego czy drugiego silnika, a o fakt, że LMS i LMS+ są znacznie mocniej testowane i optymalizowane do PostgreSQL. Przede wszystkim aktualizacje schematu bazy danych są w PostgreSQL w pełni transakcyjne, a na MySQL niestety nie.

Odnośnie Twojej odpowiedzi - poproszę jeszcze o:
```sql
SELECT * FROM customerbalances;
```
Żadnych danych tym zapytaniem nie ujawnisz - zapytanie zwróci listę "zbuforowanych" sald bieżących klientów. Jestem ciekaw czy gdzieś na tym poziomie nie ma błędów.

**Comment by jakrzy** [comment]
Prosze bardzo;

customerid | balance |  
-- | -- | --
32 | 880.00
32 | 880.00
32 | 880.00

**Comment by chilek** [comment]
@jakrzy z tego powyżej wynika problem - rekord salda dla jednego klienta trzymany jest 3-krotnie.

**Comment by chilek** [comment]
Przy okazji mamy testera ostatnich aktualizacji schematu i zmian w zakresie MySQL :)

**Comment by chilek** [comment]
Proponuję jeszcze dodać klientowi o id `32` kilka wpłat (do doda rekordy w cash) i zobaczyć jak wtedy zachowa się tabela `customerbalances`.

**Comment by chilek** [comment]
Na naszym środowisku testowym na MySQL (przed chwilą takowe przygotowałem) dokonałem obciążenia klienta, a następnie wpłaty klienta i rekord w `customerbalances` jest tylko 1:
MariaDB> SELECT * FROM customerbalances;
+------------+---------+
| customerid | balance |
+------------+---------+
|          1 |   -4.00 |
+------------+---------+
1 row in set (0.00 sec)

**Comment by jakrzy** [comment]
Dodalem klientowi id 32 zobowiazanie: 100zl , tabela customerbalances wyglada nastepujaca;

customerid | balance |  
-- | -- | --
32 | 780.00
32 | 780.00
32 | 780.00

Wartość jest powielana 3 krotnie. Nadpłata powinna wynieść 780zl , a obecnie w '?m=customerlist&s=&o=balance,desc' pokazuje 2340zl (3x780=2340)

Co ciekawe wystawiajac innemu klientowi zobowiazanie, wpis w customerbalances jest poprawny ( jeden rekord dla klienta)

customerid | balance |  
-- | -- | --
32 | 780.00
32 | 780.00
32 | 780.00
15 | -100.00

Wyglada na to że cos poszlo nie tak przy aktualizacji z LMS24..?

**Comment by jakrzy** [comment]
Jeszcze jako ciekawostkę dodam, ze po przywróceniu bazy z przed zmian, o które mnie prosiłeś ( wystawienie zobowiązania dla klienta id 32 i dodaniu zobowiązania dla klienta id 15 j.w.) dodał się kolejny rekord w customerbalances jak ponizej;

customerid | balance |  
-- | -- | --
32 | 880.00
32 | 880.00
32 | 880.00
32 | 880.00

**Comment by chilek** [comment]
@jakrzy zrób:
```sql
DELETE FROM customerbalances WHERE customerid = 32;
```
a następnie wprowadź temu klientowi jakąś wpłatę i od razu usuń.

**Comment by chilek** [comment]
> Jeszcze jako ciekawostkę dodam, ze po przywróceniu bazy z przed zmian, o które mnie prosiłeś ( wystawienie zobowiązania dla klienta id 32 i dodaniu zobowiązania dla klienta id 15 j.w.) dodał się kolejny rekord w customerbalances jak ponizej;

@jakrzy spróbuj wyłączyć globalnie wszystkie TRIGGER-y przy odtwarzaniu bazy z backupu (na czas odtwarzania)?

**Comment by chilek** [comment]
Ewentualnie (jeśli tymczasowe wyłączenie TRIGGER-ów w MySQL nie będzie możliwe) można jeszcze skasować je przez zapytaniami wstawiającym dane (zwykle `INSERT INTO ...`), a utworzyć je dopiero na końcu.

**Comment by chilek** [comment]
Artykuł:
https://www.percona.com/blog/2013/02/11/unexpected-problem-with-triggers-and-mysqldump/
może być przy tym pomocny.

**Comment by chilek** [comment]
@jakrzy jeszcze mam 2 pytania:
1. Jak dokładnie robisz backup swojej bazy?
2. Jak dokładnie odtwarzasz bazę z backupu?

**Comment by jakrzy** [comment]
Po wykasowaniu rekordu 'DELETE FROM customerbalances WHERE customerid = 32;'  zrobieniu wplaty i usunieciu tej wplaty z poziomu lms-a, wyglada ze jest OK, tabela customerbalances;

customerid | balance |  
-- | -- | --
32 | 880.00

Backup bazy i odtworzenie kopi bazy robie z poziomu LMS-a (Administracja->Kopie zapasowe)

**Comment by jakrzy** [comment]
I kolejna ciekawostka; przywracajac poprzednia kopie bazy danych z poziomu LMS-a, znow dodal sie kolejny rekord w customer balances;

customerid | balance |  
-- | -- | --
32 | 880.00
32 | 880.00
32 | 880.00
32 | 880.00
32 | 880.00

byly 4 rekordy, w poprzedniej kopi, teraz po odtworzeniu tej kopi jest 5.

**Comment by chilek** [comment]
@jakrzy Zrób co następuje:
1. Skasuj wszystkie rekordy z `customerbalances`:
```sql
DELETE FROM customerbalances;
```
2. Uaktualnij swojego LMS o poprawkę:
https://github.com/lmsgit/lms/commit/87198cdfcd909f1f0f38e210bea97b61cf20d9ef
3. Wykonaj zapytanie:
```sql
	INSERT INTO customerbalances (customerid, balance)
		(SELECT customerid, SUM(value * currencyvalue) AS balance FROM cash WHERE 
                         customerid IS NOT NULL GROUP BY customerid);
```
4. Wykonaj nowy-testowy zrzut sql z poziomu LMS.
5. Spróbuj załadować zrzut z punktu 4 na nowo do bazy danych.
6. Sprawdź czy nie masz duplikatów sald w `customerbalances`:
```sql
SELECT COUNT(*), customerid FROM customerbalances
GROUP BY customerid HAVING COUNT(*) > 1;
```

**Comment by jakrzy** [comment]
Wyglada na to ze jest OK,
duplikatow nie ma po odtworzeniu kopi, a zapytanie 'SELECT COUNT(*), customerid FROM customerbalances
GROUP BY customerid HAVING COUNT(*) > 1;'
Zwraca pusty wynik.

Dzieki, pozdrawiam

**Comment by chilek** [comment]
Ja również dziękuję za dobry _feedback_.
