### ISSUE TITLE
Customer list type

### ISSUE THREAD

**Issue by tudor2k3** [lmsgit/lms#1616]
Hello,

     Is there any way to print the customer list in a specific format (csv, xls, pdf)? The csv template exists, but i don't know how to set the option to use it.

                 Thank you.

**Comment by interduo** [comment]
Use: customers --> Raport or get that list SQL Query.

**Comment by tudor2k3** [comment]
Yes, that works as html. I was wondering about exporting as csv or xls. 

În 10.02.2020 09:10, Interduo a scris:

> Use: customers --> Raport or get that list SQL Query. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/lmsgit/lms/issues/1616?email_source=notifications&amp;email_token=AD5KGSQAGAQWLVNKP7SNIY3RCD4UTA5CNFSM4KSIWGTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELHORDI#issuecomment-583985293
[2]
