### ISSUE TITLE
Szablony wiadomości w helpdesku

### ISSUE THREAD

**Issue by bestgo** [lmsgit/lms#1624]
Mam propozycję aby wprowadzić szablony wiadomości z modułu "wiadomości" do modułu "helpdesk". Wydaje mi się, że byłoby to pomocne przy odpowiadaniu na zgłoszenia szczególnie w przypadku jakichś większych awarii.

**Comment by interduo** [comment]
Jest już :)

**Comment by bestgo** [comment]
W masterze czy nowym stable?

**Comment by interduo** [comment]
branch:master

**Comment by bestgo** [comment]
Ok. Dzięki za info.
