### ISSUE TITLE
zmienna $balance i 12 miejsc po przecinku.

### ISSUE THREAD

**Issue by jakrzy** [lmsgit/lms#1631]
Zmienna $balance uzywana do wysylania powiadomien sms/mail przedstawia liczby z 12 miejscami po przecinku.
Dla przykladu wartosc 2zl przedstawiana jest w wiadomosci wyslanej jako 2.000000000000zl

**Comment by chilek** [comment]
@jakrzy o który element aplikacji chodzi? lms-notify.php? messageadd? Coś innego?

**Comment by jakrzy** [comment]
Wysyłanie wiadomości i maili z przypomnieniem bezpośrednio z LMS-a (Wiadomosci-> Nowa wiadomosc SMS/e-mail)

**Comment by chilek** [comment]
@jakrzy Zobacz czy powyższa poprawka pomaga?

**Comment by jakrzy** [comment]
Jest OK,
Dzieki.
