### ISSUE TITLE
Klienci "zombie"

### ISSUE THREAD

**Issue by cyberavis** [lmsgit/lms#1633]
Upgrade z wersji bazy danych DB: 2019101000 do obecnej (DB: 2020031000) przywrócił wszystkich usuniętych klientów.

**Comment by chilek** [comment]
To nie możliwe, bo:
```
# grep -r delete lib/upgradedb/{postgres,mysql}.{20191[0-2]*,2020*}.php
lib/upgradedb/mysql.2019121800.php:    CREATE TRIGGER cash_customerbalances_delete_trigger AFTER DELETE ON cash
lib/upgradedb/mysql.2020011000.php:$this->Execute("DROP TRIGGER cash_customerbalances_delete_trigger");
lib/upgradedb/mysql.2020011000.php:    CREATE TRIGGER cash_customerbalances_delete_trigger AFTER DELETE ON cash
lib/upgradedb/mysql.2020011401.php:$this->Execute("DROP TRIGGER cash_customerbalances_delete_trigger");
lib/upgradedb/mysql.2020011401.php:    CREATE TRIGGER cash_customerbalances_delete_trigger AFTER DELETE ON cash

```
czyli nie widać nic co by zmieniało dla klientów deleted z `1` na `0'.
Raczej podejrzewam jakiś lokalny problem.

**Comment by cyberavis** [comment]
Tam stało się coś innego. W bazie jest on nadal jako usunięty, (1) ale w
LMS wyświetlają się kontakty usunięte w momencie wybrania "wszyscy".
Chyba, że tak teraz ma być.

-- 
Pozdrawiam,
Cyberavis

W dniu 22.03.2020 o 13:33, Tomasz Chiliński pisze:

**Comment by chilek** [comment]
Raczej tak ma być, ale teraz za to można wybrać filtr "istniejący".
