### ISSUE TITLE
Wiadomosci SMS - blad 105 smscenter...

### ISSUE THREAD

**Issue by jakrzy** [lmsgit/lms#1634]
Wysylajac masowe wiadomosci SMS np. dla zadluzonych i korzystajac z szablonu wiadomosci ktory wczesniej byl utworzony, SMS-y sa wysylane.
Problem jest z utworzeniem nowego szablonu wiadomosci SMS, lub proby wyslania dowolnego SMS-a do klienta z poziomu wiadomosci LMS-a ( zarowno w wiadomosciach masowych jak i dla pojedynczego klienta)
Kazdorazowo wystepuje błąd (Smscenter error 105. Please contact smscenter administrator)

**Comment by chilek** [comment]
Przed chwilą testowałem na jednym z produkcyjnie używanych systemów wykorzystujących bieżącą wersję LMS. Co prawda tam sms.service=smstools, ale to tylko nie powinno być istotne. W formularzu nowej wiadomości zaznaczyłem, że ma utworzyć się nowy szablon wiadomości i tak się stało. Wiadomość SMS-owa doszła, a szablon wiadomości utworzył się. Zatem nie potwierdzam problemu, a wątpię, żeby był zależny od typu dostawcy usług sms-owych.

**Comment by jakrzy** [comment]
Hmmm...
Próbowałem wysłać text 155 znaków ( bez polskich liter) i wywala błąd 105, ponowiłem próby i zauważyłem ze nie można wysłać z LMS-a dłuższego texu niż 150 znaków, chociaż w specyfikacji max jest 160 znaków, a dłuższy Text jest rozdzielany na dwa SMS-y. 
https://smscenter.pl/specyfikacja_mt.pdf

Jeżeli tak ma być, ze nie można wysłać dłuższego Textu z LMS-a niż 150 znaków to proszę o zamkniecie tematu.

**Comment by chilek** [comment]
https://github.com/lmsgit/lms/blob/d01883b3db17324c17d4a27347b0db540a51dae4/lib/LMS.class.php#L2639-L2640

Proponuję temu ustawieniu nadać wartość `concat` (zgodnie z tym co piszą w dokumentacji pod podanym linkiem powinno pozwolić na wysyłanie wiadomości dzielonej na kilka sms-ów).

**Comment by chilek** [comment]
Nie to wskazałem - obsługa typu wiadomości SMS realizowana jest tu:
https://github.com/lmsgit/lms/blob/d01883b3db17324c17d4a27347b0db540a51dae4/lib/LMS.class.php#L2630-L2637

Zgodnie z dokumentacją:
https://www.smscenter.pl/specyfikacja_mt.pdf
strona 2 dla `sms` max. długość to 160 znaków, a dla `sms_concat` to max. 459 znaków.
Przynajmniej teoretycznie.

**Comment by chilek** [comment]
Powyższy commit dodaje obsługę SMS-ów UNICODE dla smscenter.pl

**Comment by jakrzy** [comment]
Dzieki,
Dziala super, dochodza wiadomosci SMS nawet dluzsze niz 160 znakow. W jednej wiadomosci SMS dochodzi 201 znakow, powyzej tej wartosci komunikat "Zbyt długa wiadomość SMS!"

**Comment by chilek** [comment]
Proponuję ustawić **sms.transliterate_message** na `true`. Wtedy zaczną dochodzić nawet do 459 znaków i będzie mniej smsów fizycznych to generowało.
