### ISSUE TITLE
po aktualizacji: TCPDF ERROR: Could not include font definition file: arial

### ISSUE THREAD

**Issue by jakrzy** [lmsgit/lms#1648]
Po aktualizacji do najnowszej wersji LMS (wyczyszczenie /templates_c + git pull + composer update), nie mozna wygenerowac rejestru sprzedazy ( LMS->Rejestr Sprzedazy-> Okres 1.03.2020-31.03.2020)
Komunikat Bledu:
TCPDF ERROR: Could not include font definition file: arial

**Comment by chilek** [comment]
Sprawdzisz czy commit 9c41aac30 rozwiązuje problem?

**Comment by chilek** [comment]
W dniu 01.04.2020 11:39, jakrzy napisał(a):
> Po aktualizacji do najnowszej wersji LMS (wyczyszczenie /templates_c +
> git pull + composer update), nie mozna wygenerowac rejestru sprzedazy
> ( LMS->Rejestr Sprzedazy-> Okres 1.03.2020-31.03.2020)
> Komunikat Bledu:
> TCPDF ERROR: Could not include font definition file: arial

Przeszliśmy na czcionki prawdziwie UTF-8 i o wolnej licencji 
"LiberationSans".

**Comment by jakrzy** [comment]
Niestety poprawka nie rozwiazuje problemu; TCPDF ERROR: Could not include font definition file: arial

**Comment by chilek** [comment]
To było za mało - poszła kolejna poprawka.

**Comment by jakrzy** [comment]
Teraz jest OK,
Dzieki.

**Comment by jakrzy** [comment]
Hmm... nie do konca jest OK,
formatowanie strony w PDF-ie nie jest w formacie A4, obaw jest taki iż tabele z rejestru sprzedaży są do polowy strony A4 na wydruku.

**Comment by chilek** [comment]
No ale na to czcionka nie ma wpływu.

**Comment by jakrzy** [comment]
Jest tylko 25 pozycji na stronie a reszta strony pusta...
