### ISSUE TITLE
patern in cachimportcfg.php

### ISSUE THREAD

**Issue by DariusEvs** [lmsgit/lms#1656]
Hi,

in my cachimportcfg.php now I find the patern:
'pattern' => "/^([^ ]+);(.*)[\s;]+([^ ]+);([^ ]+);(.*)/",
but it works with csv file with separator ";", but I need that it work with tab symbol, how I must to change the patern ?

**Comment by interduo** [comment]
You need to search PHP documentation for regular expression match & prag_match.

For example:
https://stackoverflow.com/questions/1917034/php-preg-match-tab-separated
https://www.poftut.com/regex-space-whitespace-tab-usage-examples/

There is a lot more in google.
