### ISSUE TITLE
Nieaktualna migracja schematu bazy danych

### ISSUE THREAD

**Issue by MKaciuba** [lmsgit/lms#1667]
https://github.com/lmsgit/lms/blob/752f5e5daf6abe9ad3f8132659e3ab5d63979efb/lib/LMSManagers/LMSFinanceManager.php#L4527-L4529

W powyższym insercie widać odwołanie m.in. do kolumny `taxcategory`, której nie ma w migracji schematu bazy danych:

https://github.com/lmsgit/lms/blob/f434735ee3f143a0830852bc9167b418a4ab0f3f/doc/lms.pgsql#L905-L920

Gdzie można zdobyć aktualną migrację?

**Comment by chilek** [comment]
Witam, dzięki za info. To błąd w plikach z pełną wersją schematu.
O ile dobrze widzę - przyrostowe aktualizacje schematu były dotąd ok.
Poprawka: https://github.com/lmsgit/lms/commit/331e21367d848cb3664f79a4d97ec202ef6d157c

**Comment by MKaciuba** [comment]
Super, zadziałało, dzięki :)
