### ISSUE TITLE
Nie można się zalogować na konto demo LMS

### ISSUE THREAD

**Issue by kosaa** [lmsgit/lms#1670]
**Wstępna weryfikacja**
Wpisane zostało hasło oraz login podany przed wejściem na stronę https://demo.lms.org.pl/.

**Opis błędu**
Login lub hasło podane na stronie nie działa.

**Odtworzenie problemu**
Kroki odtwarzające błędne zachowanie:
1. Przejdź do https://demo.lms.org.pl/
2. Wpisz login: admin, hasło: test
3. Wyświetlony zostanie błąd o błędnym loginie lub haśle.

**Oczekiwane zachowanie**
Dane do konta demo będą poprawne

**Zrzuty ekranu**
n/a

**Środowisko - prosimy o uzupełnienie następującej informacji:**
 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36

**Comment by chilek** [comment]
Witaj, dodałem przed chwilą w cron na serwerze automatycznie ustawianie co nocy hasła na `test`.
Wykonałem również procedurę doraźnie. Powinna być już możliwość zalogowania na konto `admin`.

**Comment by kosaa** [comment]
potwierdzam, działa
