### ISSUE TITLE
Znaki tytułu okna przekazywane do okna dialogowego są zastępowane encjami HTML

### ISSUE THREAD

**Issue by kosaa** [lmsgit/lms#1671]
**Opis błędu**
Tytuł okna `<!dialog>Alert` 

**Odtworzenie problemu**
Kroki odtwarzające błędne zachowanie:
1. Ustaw język angielski
2. Otwórz konsolę
3. wklej kod:
```
alertDialog($t('Your session is near to expiration! Click "OK" if you want to prevent logout.'))
```

**Oczekiwane zachowanie**
Tytuł okna będzie miał wartość `Alert`

**Zrzuty ekranu**
<img width="390" alt="Zrzut ekranu 2020-05-1 o 15 47 17" src="https://user-images.githubusercontent.com/17165619/80809975-1f67c780-8bc3-11ea-8dc7-ac005323a513.png">

**Środowisko - prosimy o uzupełnienie następującej informacji:**
 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36

**Comment by kosaa** [comment]
https://github.com/lmsgit/lms/pull/1672

**Comment by chilek** [comment]
Dziękuję za poprawkę. Okazuje się, że jquery-ui title traktuje jako tekst, a nie html.

**Comment by chilek** [comment]
@kosaa co tam u Ciebie? Widzę, że chyba już na Maka przeskoczyłeś? Jaki model?

**Comment by kosaa** [comment]
Od wyjazdu cały czas pracuję w Warszawie, i pomyślałem, że zobaczę co tam w LMS słychać.

Laptop Model MacBook Pro (16-inch, 2019)

p.s.
jeszcze cały czas leci 404 Request URL: https://demo.lms.org.pl/js/jqueryui/ui/minified/i18n/datepicker-en.js

**Comment by chilek** [comment]
Znam temat, ale niestety to jest zaszyte chyba w jquery-ui ładowanie nawet angielskiej wersji, która przecież nie jest potrzebna... Przynajmniej nigdzie w kodzie nie ładujemy jawnie.
