### ISSUE TITLE
korekta faktury

### ISSUE THREAD

**Issue by nooa85** [lmsgit/lms#1673]
Witam,
podczas dodawania korekty otrzymuję komunikat "Fatal error: couldn't get quote for currency!"
Wersja LMSa 25-git, przy wersji 24 nie było tego problemu.
Z czym może być ten problem związany?

**Comment by darton** [comment]
Potwierdzam, u mnie też ten błąd wystąpił w czasie testów.

Wersja LMS: | 25-git
-- | --
Wersja LMSDB: | 2020042701
Wersja MySQL: | 5.5.65-MariaDB
Wersja PHP: | 7.3.17
Wersja Smarty: | 3.1.33

**Comment by chilek** [comment]
Przed chwilą u siebie na bieżącej wersji z GIT.

LMS: 25-git
LMSDB: 2020050400
PHP: 7.3.17
Paczki zainstalowane przez composer:
```
alexei/sprintf.js                     1.1.1   
ccampbell/mousetrap                   1.6.5   
components/jquery                     3.4.1    jQuery JavaScript Library
components/jqueryui                   1.12.1   jQuery UI is a curated set of user interface interactions, effects, widgets, and themes built on top of the jQuery JavaScript Library. Whether ...
components/normalize.css              3.0.3    Normalize.css is a customisable CSS file that makes browsers render all elements more consistently and in line with modern standards.
composer/installers                   v1.9.0   A multi-framework Composer library installer
datatables/datatables                 1.10.20  DataTables is a plug-in for the jQuery Javascript library. It is a highly flexible tool, based upon the foundations of progressive enhancement,...
drmonty/datatables-responsive         2.2.1    Responsive extension for DataTables, providing support for complex tables on all device screen sizes
erusev/parsedown                      1.7.4    Parser for Markdown.
fortawesome/font-awesome              5.13.0  
gusapi/gusapi                         3.3.2    Gus Api Library for PHP
harvesthq/chosen                      v1.8.7   Chosen is a JavaScript plugin that makes select boxes user-friendly. It is currently available in both jQuery and Prototype flavors.
html2text/html2text                   4.3.1    Converts HTML to formatted plain text
ivkremer/jquery-simple-combobox       1.1.29  
oomphinc/composer-installers-extender v1.1.2   Extend the composer/installers plugin to accept any arbitrary package type.
paragonie/constant_time_encoding      v2.3.0   Constant-time Implementations of RFC 4648 Encoding (Base-64, Base-32, Base-16)
paragonie/random_compat               v9.99.99 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
pear/console_getopt                   v1.4.3   More info available on: http://pear.php.net/package/Console_Getopt
pear/mail                             v1.4.1   Class that provides multiple interfaces for sending emails.
pear/pear-core-minimal                v1.10.10 Minimal set of PEAR core files to be used as composer dependency
pear/pear_exception                   v1.0.1   The PEAR Exception base class.
phine/exception                       1.0.0    A PHP library for improving the use of exceptions.
phine/observer                        2.0.0    A PHP library that implements the observer pattern.
phpmailer/phpmailer                   v6.1.5   PHPMailer is a full-featured email creation and transfer class for PHP
pragmarx/google2fa                    v6.1.3   A One Time Password Authentication package, compatible with Google Authenticator.
rospdf/pdf-php                        0.12.62  The R&OS Pdf class supports the creation of PDF documents without any adiditional modules or extensions.
setasign/fpdi                         v2.3.3   FPDI is a collection of PHP classes facilitating developers to read pages from existing PDF documents and use them as templates in FPDF. Becaus...
setasign/fpdi-tcpdf                   v2.2.0   Kind of metadata package for dependencies of the latest versions of FPDI and TCPDF.
smarty/smarty                         v3.1.33  Smarty - the compiling PHP template engine
spipu/html2pdf                        v4.6.1   HTML2PDF is a HTML to PDF converter written in PHP5 (it uses TCPDF). OFFICIAL PACKAGE
symfony/polyfill-php56                v1.15.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-util                 v1.15.0  Symfony utilities for portability of PHP codes
tecnickcom/tc-lib-barcode             1.15.20  PHP library to generate linear and bidimensional barcodes
tecnickcom/tc-lib-color               1.12.15  PHP library to manipulate various color representations
tecnickcom/tcpdf                      6.2.21   TCPDF is a PHP class for generating PDF documents and barcodes.
tinymce/tinymce                       4.9.10   Web based JavaScript HTML WYSIWYG editor control.
westonganger/input-autogrow           1.1.1   
xdan/datetimepicker                   2.5.20  
zenorocha/clipboardjs                 v2.0.6   Modern copy to clipboard. No Flash. Just 3kb gzipped https://clipboardjs.com
```

i nie potwierdzam problemu - faktura wystawiła się prawidłowo.

Rozumiem, że w zgłoszeniu chodzi jedynie o to, żeby sprawdzić u kogo ten komunikat wyskakuje, a u kogo nie, a kroki, które trzeba wykonać, żeby odtworzyć problem są nieistotne? ;-)

**Comment by nooa85** [comment]
Konkretnie chodzi o korektę faktury. W jaki sposób bym nie chciał wystawić korekty pokazuje mi się ten sam błąd czy to wchodząc przez klienci -> lista -> klient -> konto klienta -> następnie klucz przy fakturze -> poprawiam naciskam zapisz wyświetla się komunikat z pierwszego postu.  To samo jest jak wchodzę w finanse -> lista faktur i klikam klucz. Na każdym kliencie jest to samo. 


Wersja LMS: | 25-git
Wersja LMSDB: | 2020040600
Wersja MySQL: | 5.5.5-10.3.22-MariaDB-0+deb10u1
Wersja PHP: | 7.3.14-1~deb10u1
Wersja Smarty: | 3.1.33

Paczki zainstalowane przez composer:
alexei/sprintf.js                     1.1.1
ccampbell/mousetrap                   1.6.5
components/jquery                     3.4.1    jQuery JavaScript Library
components/jqueryui                   1.12.1   jQuery UI is a curated set o...
components/normalize.css              3.0.3    Normalize.css is a customisa...
composer/installers                   v1.9.0   A multi-framework Composer l...
datatables/datatables                 1.10.20  DataTables is a plug-in for ...
doctrine/instantiator                 1.3.0    A small, lightweight utility...
drmonty/datatables-responsive         2.2.1    Responsive extension for Dat...
erusev/parsedown                      1.7.4    Parser for Markdown.
fortawesome/font-awesome              5.13.0
gusapi/gusapi                         3.3.2    Gus Api Library for PHP
harvesthq/chosen                      v1.8.7   Chosen is a JavaScript plugi...
html2text/html2text                   4.2.1    Converts HTML to formatted p...
ivkremer/jquery-simple-combobox       1.1.29
oomphinc/composer-installers-extender v1.1.2   Extend the composer/installe...
paragonie/constant_time_encoding      v2.3.0   Constant-time Implementation...
paragonie/random_compat               v9.99.99 PHP 5.x polyfill for random_...
pear/console_getopt                   v1.4.3   More info available on: http...
pear/mail                             v1.4.1   Class that provides multiple...
pear/pear-core-minimal                v1.10.10 Minimal set of PEAR core fil...
pear/pear_exception                   v1.0.1   The PEAR Exception base class.
phine/exception                       1.0.0    A PHP library for improving ...
phine/observer                        2.0.0    A PHP library that implement...
phpdocumentor/reflection-common       2.0.0    Common reflection classes us...
phpdocumentor/reflection-docblock     5.1.0    With this component, a libra...
phpdocumentor/type-resolver           1.1.0    A PSR-5 based resolver of Cl...
phpmailer/phpmailer                   v6.1.5   PHPMailer is a full-featured...
phpspec/prophecy                      v1.10.3  Highly opinionated mocking f...
phpunit/php-code-coverage             2.2.4    Library that provides collec...
phpunit/php-file-iterator             1.4.5    FilterIterator implementatio...
phpunit/php-text-template             1.2.1    Simple template engine.
phpunit/php-timer                     1.0.9    Utility class for timing
phpunit/php-token-stream              1.4.12   Wrapper around PHP's tokeniz...
phpunit/phpunit                       4.8.36   The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          2.3.8    Mock Object library for PHPUnit
pragmarx/google2fa                    v6.1.3   A One Time Password Authenti...
rospdf/pdf-php                        0.12.61  The R&OS Pdf class supports ...
sebastian/comparator                  1.2.4    Provides the functionality t...
sebastian/diff                        1.4.3    Diff implementation
sebastian/environment                 1.3.8    Provides functionality to ha...
sebastian/exporter                    1.2.2    Provides the functionality t...
sebastian/global-state                1.1.1    Snapshotting of global state
sebastian/recursion-context           1.0.5    Provides functionality to re...
sebastian/version                     1.0.6    Library that helps with mana...
setasign/fpdi                         v2.3.2   FPDI is a collection of PHP ...
setasign/fpdi-tcpdf                   v2.2.0   Kind of metadata package for...
smarty/smarty                         v3.1.33  Smarty - the compiling PHP t...
spipu/html2pdf                        v4.6.1   HTML2PDF is a HTML to PDF co...
squizlabs/php_codesniffer             3.5.4    PHP_CodeSniffer tokenizes PH...
symfony/polyfill-ctype                v1.15.0  Symfony polyfill for ctype f...
symfony/polyfill-php56                v1.15.0  Symfony polyfill backporting...
symfony/polyfill-util                 v1.15.0  Symfony utilities for portab...
symfony/yaml                          v3.4.39  Symfony Yaml Component
tecnickcom/tc-lib-barcode             1.15.4   PHP library to generate line...
tecnickcom/tc-lib-color               1.12.15  PHP library to manipulate va...
tecnickcom/tcpdf                      6.2.21   TCPDF is a PHP class for gen...
tinymce/tinymce                       4.9.9    Web based JavaScript HTML WY...
webmozart/assert                      1.7.0    Assertions to validate metho...
westonganger/input-autogrow           1.1.1
xdan/datetimepicker                   2.5.20
zenorocha/clipboardjs                 v2.0.6   Modern copy to clipboard. No...

**Comment by darton** [comment]
Problem nie dotyczy faktury tylko korekty faktury.

**Comment by chilek** [comment]
> Problem nie dotyczy faktury tylko korekty faktury.

Napisałem `faktura` mając na myśli `korektę`, która oczywiście u mnie wstawia się bez problemu.

U mnie formularz nowej korekty faktury wygląda tuż przed przesłaniem do serwera jak poniżej:
![Zrzut ekranu z 2020-05-05 21-56-27](https://user-images.githubusercontent.com/1457437/81110080-57507100-8f1b-11ea-9cb1-a25eb25932c3.png)
No i oczywiście błędu nie ma - tak jak wcześniej.

**Comment by chilek** [comment]
Btw. używacie MySQL/MariaDB i prosicie się o problemy - całkiem możliwe, że jakaś aktualizacja schematu nie do końca zadziałała i np. pole identyfikatora waluty w kilku tabelach nie ustawiło się. Będzie prawdopodobnie wiadomo jak prześlecie zrzuty ekranu formularza tuż przed przesłaniem do serwera www.

**Comment by darton** [comment]
W tabeli cash faktycznie było trochę pozycji NULL zamiast waluty PLN. Ustawienie właściwej waluty 
nie rozwiązało problemu. Szukam dalej.

**Comment by nooa85** [comment]
@darto nakierowałeś mnie na rozwiązanie problemu 👍  zmieniłem wszystkie wpisy z null na pln w cash i documents. Teraz korekty wystawiają się właściwie.

**Comment by darton** [comment]
no u mnie jeszcze nie, też zmieniłem i w jednej i drugiej tabeli , szukam jeszcze jednej tabeli

**Comment by nooa85** [comment]
@darton spróbuj wulogować się UI i zalogować ponownie. U mnie nie zadziałało od razu po zmianie w bazie

**Comment by darton** [comment]
Wyczyściłem templates_c i zadziałało.  Teraz pytanie czy problem rozwiązany czy też jakiś trigger trzeba poprawić.

**Comment by interduo** [comment]
> @darto nakierowałeś mnie na rozwiązanie problemu  zmieniłem wszystkie wpisy z null na pln w cash i documents. Teraz korekty wystawiają się właściwie.

Może tą zmianę trzeba by wrzucić do schematu?

**Comment by chilek** [comment]
> Może tą zmianę trzeba by wrzucić do schematu?

To jest i było w aktualizacji schematu.

Dlaczego koledzy mieli _NULL_ w polach _currency_? Jest kilka możliwości:
1. Generują rekordy finansowe skryptami spoza dystrybucji LMS, które zapewne nie mają obsługi wielu walut.
2. Schemat przy aktualizacji nie w pełni podniósł i w efekcie pola _currency_ z kilku tabel nie ustawiły się na takie jak lokalizacja systemu (zmienna **phpui.lang**).

**Comment by chilek** [comment]
> Teraz pytanie czy problem rozwiązany czy też jakiś trigger trzeba poprawić.

Triggera na pewno nie trzeba, ale zwróć uwagę na mój komentarz wcześniej
oraz na zalecenie odnośnie przejścia na PostgreSQL.

**Comment by chilek** [comment]
Panowie, jak tam się mają sprawy? Można zamykać zgłoszenie?

**Comment by nooa85** [comment]
U mnie działa, nie wiem jak u kolegi

**Comment by darton** [comment]
Działać działa. Ale nie znalazłem przyczyny jeszcze.

**Comment by darton** [comment]
Skrypt do przejścia na postgresql jest w LMS+. Nie każdego stać na to.

**Comment by chilek** [comment]
Jako administrator z dużym doświadczeniem na pewno jesteś w stanie sklecić coś samemu do migracji.

**Comment by darton** [comment]
Ale też nie za darmo :-)

**Comment by interduo** [comment]
Nieaktualne.
