### ISSUE TITLE
Obsługa hooków w module welcome

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#1687]
**Czy nowa funkcja jest związana z jakimś problemem? Prosimy opisać.**
Chcę wyświetlać informacje o aktualnych i planowanych wyłączeniach prądu w tauronie na głównej stronie WELCOME.
Wydaje mi się, że potrzebuję do tego obsługę hooków w module welcome.

Potem wykorzystam poniższy fragment do wyświetlenia potrzebnych danych:
```php
		<div id="lms-ui-welcome-extra-panel">
			{block name="extra-panel"}
			{/block}
		</div>
```

**Opisz swoją propozycję rozwiązania**
Zreplikować działanie hooków np. z modułu nodes do welcome.

**Opisz alternatywy, które rozważałeś**
Mam to zrobione jako osobna podstrona, ale wolałbym na głównej.

**Dodatkowy kontekst**
![screenshot-192 168 12 2-2020 06 02-10_19_31](https://user-images.githubusercontent.com/689112/83497356-a0fc8f00-a4ba-11ea-83b7-727739584a90.png)

**Comment by interduo** [comment]
Udostępnij to gdzieś, fajne.

**Comment by chilek** [comment]
Dla każdego modułu istnieje domyślny, niejawny hook:
https://github.com/chilek/lms-plus/blob/1bd3c770057d812d229e3349e8caf508a6d0e6c9/lib/LMSSmarty.php#L53-L56

**Comment by kyob** [comment]
@chilek Dzięki.

**Comment by kyob** [comment]
Potrafię podmienić zawartość bloku "extra-panel" na głównej stronie, ale **nie wiem jak przypisać moje zmienne, aby można było je odczytać w szablonie smarty.**

Próbowałem tak, ale chyba nie tędy droga:
```php
// LMSPowerOutagesPlugin.php
class LMSPowerOutagesPlugin extends LMSPlugin
{
    public function registerHandlers()
    {
            'welcome_before_module_display' => array(
                'class' => 'PowerOutagesHandler',
                'method' => 'welcomePowerOutages'
            )
        );
    }

// PowerOutagesHandler.php
class PowerOutagesHandler
{
    public function welcomePowerOutages(array $hook_data = array())
    {
        $myArray = "https://www.tauron-dystrybucja.pl/iapi/"; // tylko dla przykładu
        $hook_data['welcome']['powerOutages'] = $myArray; // <= to nie działa :)
        return $hook_data;
    }
}

```

**Comment by chilek** [comment]
> Potrafię podmienić zawartość bloku "extra-panel" na głównej
> stronie, ale nie wiem jak przypisać moje zmienne, aby można było je
> odczytać w szablonie smarty.
> 
> Próbowałem tak, ale chyba nie tędy droga:
> 
> // LMSPowerOutagesPlugin.php
> class LMSPowerOutagesPlugin extends LMSPlugin
> {
>     public function registerHandlers()
>     {
>             'welcome_before_module_display' => array(
>                 'class' => 'PowerOutagesHandler',
>                 'method' => 'welcomePowerOutages'
>             )
>         );
>     }
> 
> // PowerOutagesHandler.php
> class PowerOutagesHandler
> {
>     public function welcomePowerOutages(array $hook_data = array())
>     {
>         $myArray = "https://www.tauron-dystrybucja.pl/iapi/"; // tylko
> dla przykładu
>         $hook_data['welcome']['powerOutages'] = $myArray; // <= to nie
> działa :)
>         return $hook_data;
>     }

W $hook_data masz składową 'smarty', a przez nią możesz i czytać 
zdefiniowane
wcześniej zmienne szablonu, jak również modyfikować lub dodawać nowe.

**Comment by kyob** [comment]
Jeżeli to jest poprawne przypisanie `$hook_data['welcome']['powerOutages'] = $myArray;` to szablonie smarty jak zrobię `{debug}` nie widzę tych moich danych.

**Comment by chilek** [comment]
Nie - to przypisanie nie nie robi.
W $hook_data['smarty'] masz pewnie obiekt LMSSmarty i to na nim trzeba wykonywać operacje.

**Comment by kyob** [comment]
Czasem mam problemy z interpretacją błędów.

Trąbi mi, że object != array a ja przypisuje w zaparte array :)

**Comment by interduo** [comment]
@kyob opublikujesz kod z alertami taurona na welcome.page?:)

**Comment by kyob** [comment]
@interduo Link do pluginu: https://github.com/kyob/lms-plugin-power-outages

**Comment by chilek** [comment]
@kyob: kawał fajnej roboty.

**Comment by kyob** [comment]
@chilek Kilka linijek kodu, ale dzięki. Nie wiem sprawa wygląda u innych dostawcach energii.
