### ISSUE TITLE
Zrobić metodę: LMSFinanceManager::isInvoiceEditable() i zaaplikować w formularze invoicedit

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#1696]
Można. Może warto od razu zrobić metodę: LMSFinanceManager::isInvoiceEditable(), która by zwróciła _true_ lub _false_ w sytuacji, gdy dany dokument finansowy jest edytowalny?

_Originally posted by @chilek in https://github.com/lmsgit/lms/pull/1695#issuecomment-638820688_

**Comment by chilek** [comment]
Zaraz dorobię metodę isInvoiceEditable. Zakładam, że faktura jest editable, gdy:
1. Nie jest zamknięta.
2.Nie ma do niej wystawionej korekty.
?

**Comment by interduo** [comment]
Jeszcze:
- Nie jest upubliczniona lub użytkownik ma phpui.published_document_modification
