### ISSUE TITLE
Błąd odtworzenia bazy danych z kopii zapasowej

### ISSUE THREAD

**Issue by cyberavis** [lmsgit/lms#1739]
Odtworzenie bazy danych z kopii zapasowej wypluwa następujące błędy:

`Zapytanie: INSERT INTO customers (id,extid,lastname,name,status,type,ten,ssn,regon,rbe,rbename,icn,info,notes,creationdate,moddate,creatorid,modid,deleted,message,pin,cutoffstop,divisionid,paytime,paytype,documentmemo) VALUES (…) 
Błąd: SQL query parser error: parameter count differs from passed argument count (3 != 0): 
Zapytanie: INSERT INTO nodes (id,name,ipaddr,ipaddr_pub,passwd,ownerid,creationdate,moddate,creatorid,modid,netdev,linktype,linkradiosector,linkspeed,linktechnology,port,access,warning,authtype,chkmac,halfduplex,lastonline,info,nas,longitude,latitude,netid,invprojectid,address_id) VALUES (...) 
Błąd: SQL query parser error: parameter count differs from passed argument count (5 != 0): 
Zapytanie: INSERT INTO rttickets (id,queueid,requestor,requestor_mail,requestor_phone,requestor_userid,subject,state,cause,owner,customerid,creatorid,createtime,resolvetime,source,priority,deleted,deltime,deluserid,address_id,nodeid,netnodeid,netdevid,verifierid,verifier_rtime,deadline,service,type,verifierticketbody,parentid,invprojectid,modtime) VALUES (...) 
Błąd: SQL query parser error: parameter count differs from passed argument count (1 != 0): 
Zapytanie: INSERT INTO rtmessages (id,ticketid,userid,customerid,phonefrom,mailfrom,subject,messageid,inreplyto,replyto,headers,body,createtime,type,deleted,deltime,deluserid) VALUES (...) 
Błąd: SQL query parser error: parameter count differs from passed argument count (63 != 0): 
Zapytanie: INSERT INTO messages (id,subject,body,cdate,type,userid,sender,contenttype) VALUES (...) 
Błąd: SQL query parser error: parameter count differs from passed argument count (4 != 0): `

**Środowisko:**
 - system operacyjny openSUSE Leap 15.1
 - przeglądarka www Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
 - wersja LMS - GIT
 
**Server:**
 - Debian stretch up to date
 - Database Server version<----->10.1.45-MariaDB-0+deb9u1

**Comment by interduo** [comment]
Jak robisz kopię zapasową i jak ją odtwarzacz?

**Comment by cyberavis** [comment]
Kopię robię w GUI LMS - odtwarzam tak samo. Błąd ten zauważyłem po upgrade do GIT z wersji DB: 2019101000 (gdzie działa to poprawnie). Wydaje mi się, że upgrade do wersji 25-stable dawał takie same błędy.

**Comment by chilek** [comment]
Czyżby próba wrzucenia backupu zrobionego starszą wersją do systemu działającego na nowszej wersji?

**Comment by cyberavis** [comment]
Nie. Robiona i odtwarzana w bieżącej wersji.

**Comment by interduo** [comment]
@cyberavis aktualne to?

**Comment by cyberavis** [comment]
W tygodniu sprawdzę z aktualnym git'em i dam znać.

**Comment by cyberavis** [comment]
To samo, a nawet jeszcze gorzej. Podejrzewam, że coś się dzieje z bazą danych przy upgrade z 2019101000, bo przy tej bazie z dedykowanym do tego LMS działa bez problemu. Albo bazę już mam niepełnosprawną i dopiero teraz to wychodzi.

**Comment by interduo** [comment]
@cyberavis masz jak na dłoni wszystko w błędzie gdzie się zrobił śmietniczek. Marsz do bazy i wyszukaj duplikaty. Gdybyś uważał że to błąd w oprogramowaniu otwórz ponownie issue.

**Comment by cyberavis** [comment]
Znalazłem trochę czasu aby znów to pomęczyć i doszedłem do tego, że przyczyną większości wcześniejszych błędów był fakt fakt iż
`CONSTRAINT MariaDB starting with 10.2.1`
stąd błędy w składni.

Obecnie postawiłem wszystko na nowo

Server:
    • Debian 11 up to date 
    • Database Server version: 10.5.12-MariaDB-0+deb11u1 Debian 11
    • wersja LMS - GIT 

I przy obecnym upgrade LMS z wersji DB: 2019101000 do GIT wyrzuca tylko jeden błąd:
```
Zapytanie: ALTER TABLE customerassignments DROP CONSTRAINT customerassignment
Błąd: Cannot drop index 'customerassignment': needed in a foreign key constraint
```

I nie wiem zbytnio o co chodzi – czy ten klucz obcy jest potrzebny, czy nie…?
