### ISSUE TITLE
Nie można zapisać edytowanej faktury

### ISSUE THREAD

**Issue by cyberavis** [lmsgit/lms#1740]
Wybieram klienta, edytuję jedną z faktur, dodaje kolejną pozycję, zapis pozycji, a następnie próba zapisu całości lub „zapisz i drukuj” nie skutkuje zapisem do bazy danych.

**Środowisko:**
 - system operacyjny openSUSE Leap 15.1
 - przeglądarka www Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
 - wersja LMS - GIT
 
**Server:**
 - Debian stretch up to date
 - Database Server version<----->10.1.45-MariaDB-0+deb9u1
 - PHP Version 7.0.33-0+deb9u8

**Comment by interduo** [comment]
@cyberavis u mnie działa, aktualne to?

**Comment by mocakow** [comment]
Z tego co wiem to przy update z git-a  php co najmniej 7.1  (composer potrzebuje) 
Robilem to 3 dni temu.. Może w tym tkwi problem.
U siebie Mam php 7.3. Po "walce" z composerem … poszło.

**Comment by chilek** [comment]
Tak - LMS 26-git potrzebuje PHP 7.1. Daje się co prawda zrobić trochę korekt, żeby działało jeszcze z PHP 5.6, ale potrzeba ich coraz więcej. Biblioteki od których zależymy zaczynają narzucać wymóg PHP 7.1.

**Comment by interduo** [comment]
@cyberavis jeśli aktualne to otwórz.
