### ISSUE TITLE
"Długie" kwoty w e-mailu dla klientów

### ISSUE THREAD

**Issue by cyberavis** [lmsgit/lms#1741]
Zmienna %balance użyta w mail_body dla skryptu lms-sendinvoices.php wyciąga kwotę z 12 miejscami po "przecinku"
Dla przykładu:
`-70.250000000000`

**Środowisko:**
 - system operacyjny openSUSE Leap 15.1
 - przeglądarka www Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
 - wersja LMS - GIT
 
**Server:**
 - Debian stretch up to date
 - Database Server version<----->10.1.45-MariaDB-0+deb9u1
 - PHP Version 7.0.33-0+deb9u8

**Comment by chilek** [comment]
Było i jest już dawno poprawione.

**Comment by cyberavis** [comment]
Rzeczywiście, przepraszam - nie zaktualizowałem skryptów z wersji 25-stable.
