### ISSUE TITLE
Nowy LMS Git 26 - nie można stworzyć pierwszego użytkownika

### ISSUE THREAD

**Issue by hoktaur** [lmsgit/lms#1783]
Jak ciekawostkę stworzyłem sobie nowego LMS 26 z Git
i nie mogę stworzyć pierwszego użytkownika:

![obraz](https://user-images.githubusercontent.com/70721157/92332885-127f4700-f081-11ea-843f-01d72d730721.png)

[Sun Sep 06 20:39:03.652162 2020] [:error] [pid 8019] [client 10.0.35.1:52279] PHP Warning:  array_keys() expects parameter 1 to be array, null given in ....lmsgit/index.php on line 257, referer: ..../?m=useradd

257     $user_divisions_ids = array_keys($user_divisions);

Wiem że to moja wina nie mam firmy wprowadzonej ;)

**Comment by rafalpietraszewicz** [comment]
PR  z poprawką już wysłany (zmiany w commicie 19531e28b613263982ec146fb5deddbea2629810).

**Comment by rafalpietraszewicz** [comment]
> Wiem że to moja wina nie mam firmy wprowadzonej ;)

Zgadza się, nie ma firmy ale to brak odpowiedniego inserta w skrypcie instalującym db.

**Comment by rafalpietraszewicz** [comment]
Wszystkie niezbędne poprawki już trafiły do gałęzi 'master'.
