### ISSUE TITLE
GIT-26 - błędnie naliczany okres abonamentowy oraz problemy z j. polskim na fakturach

### ISSUE THREAD

**Issue by batot1** [lmsgit/lms#1791]
Środowisko:
```
/var/www/html/lms-git26$ env
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_CONNECTION=1.2.3.4. 54256 1.2.3.5 1234
LANG=pl_PL.UTF-8
DISPLAY=localhost:10.0
XDG_SESSION_ID=2391
USER=lms
PWD=/var/www/html/lms-git26
HOME=/home/lms
SSH_CLIENT=1.1.1.1 12345
SSH_TTY=/dev/pts/0
MAIL=/var/mail/lms
TERM=xterm-256color
SHELL=/bin/bash
SHLVL=1
LOGNAME=lms
XDG_RUNTIME_DIR=/run/user/1000
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
OLDPWD=/var/www/html/lms-git26/bin
_=/usr/bin/env

```
Po odpaleniu skryptu 

`$ php ./bin/lms-payments.php -f 2015/06/03`

Faktury mam naliczane od 3-go do 2-go zamiast jak dawniej od 1-go do ostatniego miesiąca. Data wystawienia chce aby była np 3-go.
Wynik skryptu to wygenerowanie faktur z zapisem:
"Tariff Standard FTTH - ulga - subscription for period 2015/06/03 - 2015/07/02 "
Pozostałe wszystkie opisy na fakturze są w języku polskim poza pozycja na fakturze w/w.

1. Zmienne środowiskowe w konsoli PL i w konfiguracji LMS też mam ustawione na PL a mimo wszystko generuje faktury łamaną polszczyzno-agielszyczną.
Jak to naprawić?

2. Dlaczego nalicza od 3-go pomimo że w Tarrif ma ustawione naliczanie miesięczne? Stary LMS Diara przy takich ustawieniach generował fakturę od 1-go do ostatniego miesiąca z datą wystawienia tak jak opcja "-f".
Jak to samo osiągnąć w LMS GIT-26?

    system operacyjny, np. Debian 9.13
    przeglądarka www: Firefox 80.1
    Wersja LMS: | 26-git
    Wersja LMSDB: | 2020083100
    Wersja MySQL: | 5.5.5-10.1.45-MariaDB-0+deb9u1
    Wersja PHP: | 7.0.33-0+deb9u9
    Wersja Smarty: | 3.1.33

**Comment by batot1** [comment]
Ten wątek nie ma nic wsólnego z #1792

**Comment by batot1** [comment]
@hoktaur Wiem że masz czystą bazę, więc czy mogę cię prosić o ustawienie ze 2-3 zobowiązań taryfowych i wygenerowanie faktur skryptem jak wyżej?
Powiedz mi czy u ciebie wszystko będzie w języku polskim.

**Comment by batot1** [comment]
Rozwiązane.
Brak w pliku ./bin/lms-payment.php translacji.
 181 $paytype = ConfigHelper::getConfig('payments.paytype', 2); // TRANSFER
 182 $comment = ConfigHelper::getConfig('payments.comment', "Taryfa %tariff - %attribute abonament za okres %period");
 183 $backward_comment = ConfigHelper::getConfig('payments.backward_comment', $comment);

oryginalnie jest po angielsku a u mnie już linia 182 jest zmodyfikowana i działa poprawnie.
Czy nie powinien opis taryfy być ściągany z pliku lms.ini jak dawniej $comment ?
Bo jak jej nie czyta to taryfy zawsze u każdego będą po angielsku wedle dziwnego założenia autora skryptu (osobiście dla mnie chorego założenia).

**Comment by interduo** [comment]
> Domyślam się, że odchodzicie od nadrzędności ustawień lms.ini.

Pakuj wszystkie ustawienia do DB a w lms.ini zostaw to co potrzebne tylko do połączenia z DB.

> Wynika z tego że użytkownik LMS'a nie będący programistą PHP nie odpali go poprawnie.

Powinieneś zakupić sobie indywidualne skoro masz problemy.

> Program zyskałby na elastyczności bo w końcu nie każdy chce mieć fakturę wystawioną w pierwszym dniu okresu rozliczeniowego.

Odpal lms-payments.php innego dnia i wystawi Ci faktury z tego dnia lub użyj fakedate.
