### ISSUE TITLE
Nieprawidłowe zliczanie parametrów podczas parsowania SQL query

### ISSUE THREAD

**Issue by MKaciuba** [lmsgit/lms#1830]
https://github.com/lmsgit/lms/blob/5dd96dba8e3358967aff76e6902af5df3ed4c816/lib/LMSDB_common.class.php#L546

Przykładowe zapytanie: `insert into foo(bar) values ('foo?bar');` będzie skutkować ostrzeżeniem o nieprawidłowej liczbie parametrów, podczas gdy zapytanie jest składniowo poprawne i nie wymaga żadnych parametrów. Znaki `?` wewnątrz `''` nie powinny być zliczane.

**Comment by chilek** [comment]
@MKaciuba: zamiast podanej konstrukcji użyj zalecanej:
```php
$DB->Execute('INSERT INTO foo (bar) VALUES (?)', array('foo?bar'));
```

**Comment by MKaciuba** [comment]
@chilek Czy w ten sposób można dodać wiele wierszy na raz?

**Comment by chilek** [comment]
Można, np.:
```php
$DB->Execute('INSERT INTO foo (bar) VALUES (?),(?)', array('foo?bar1', 'foo?bar2'));
```
To jest całkiem prymitywna biblioteka ;-)

**Comment by MKaciuba** [comment]
@chilek Ok, ma to sens. Przy zmiennej liczbie wierszy mogę sobie zbudować query z `implode(',', array_fill(0, 10, '()'))`. Zamykam.
