### ISSUE TITLE
GIT26 nie działa userpanel - błąd composera nie ma JSON'a

### ISSUE THREAD

**Issue by batot1** [lmsgit/lms#1833]
Powracam z problemem bo teraz chce wrzucić na nowa maszynę produkcyjną działającą z tym GIT-26 starą wersję bazy LMS z wersji 1.11.13 i nie da się. Mam dokładnie te same błędy co już wcześniej zauważono wątku  #1229 ale też nikt nie powiedział jak rozwiązać problem.
Czyżby tylko wsparcie płatne rozwiązywało problem?

Backup bazy zrobiłem tak:
mysqldump -u username -p lms --single-transaction --quick --lock-tables=false > lms-backup-$(date +%F).sql

Przywracanie bazy z DIARY w LMS GIT-26 działający sprawny z usuniętymi błędami z wersji z repo.

Wszystkie operacje na GIT-26 jako nowym systemie
1. Bazę "lms" usunięto w MariaDB.
2. Utworzono bazę LMS zgodnie z dokumentacją lms.org.pl
3. Próba wgrania metodą:
```
lms@lms:~$ mysql -u lms -p --one-database lms < lms-diara-backup-2020-10-13.sql 
Enter password: 
ERROR 1227 (42000) at line 2515: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
lms@lms:~$ 
```
Dziwne pomimo że wcześnie stożono użytkownika lms z pełnymi prawami dostępu zgodnie z Ad.2. czyli poleceniem:
GRANT ALL ON lms.* TO lms@localhost IDENTIFIED BY 'twoje_hasło';

```
No nic skoro brak uprawnień to lecimy dalej z poziomu roota:
lms@lms:~$ mysql -u root -p --one-database lms < lms-diara-backup-2020-10-13.sql 
Enter password: 
ERROR 1305 (42000) at line 2515: FUNCTION lms.lms_current_user does not exist
```
identycznym błędme pluje php ./devel/upgradedb.php
```
(C) 2001-2019 LMS Developers
Using file /etc/lms/lms.ini as config.
DB schema version bumped to 2017041800
DB schema upgrade errors:

        CREATE VIEW customerview AS
            SELECT c.*,
                a1.country_id as countryid, a1.zip as zip, a1.city as city,
                a1.street as street,a1.house as building, a1.flat as apartment,
                a2.country_id as post_countryid, a2.zip as post_zip,
                a2.city as post_city, a2.street as post_street, a2.name as post_name,
                a2.house as post_building, a2.flat as post_apartment,
                a1.address as address, a1.location AS full_address,
                a2.address as post_address, a2.location AS post_full_address
            FROM customers c
                JOIN customer_addresses ca1 ON c.id = ca1.customer_id AND ca1.type = 1
                LEFT JOIN vaddresses a1 ON ca1.address_id = a1.id
                LEFT JOIN customer_addresses ca2 ON c.id = ca2.customer_id AND ca2.type = 0
                LEFT JOIN vaddresses a2 ON ca2.address_id = a2.id
            WHERE NOT EXISTS (
                SELECT 1 FROM customerassignments a
                JOIN excludedgroups e ON (a.customergroupid = e.customergroupid)
                WHERE e.userid = lms_current_user() AND a.customerid = c.id)
                AND c.type < 2

FUNCTION lms.lms_current_user does not exist
SELECT section, var, value, description FROM uiconfig WHERE disabled = 0 AND userid is null
Unknown column 'userid' in 'where clause'
lms@lms:/var/www/html/lms-git26$ 

```
No i tutaj tak samo jak wątku  #1229 brak rozwiązania.
A może trzeba pozwolić GIT-26 aby poprzez WWW stworzył se tego usera?
też ślepa uliczka bo ktoś celowo wyrzucił funkę:
**"FUNCTION lms.lms_current_user does not exist"**
a LMS nie tworzy pierwszego usera.

Na zakończenie stworzenie pustej bazy w GIT-26:
generuje błąd na stronie www "Could not load database schema!"
```
lms@lms:/var/www/html/lms-git26$ php ./devel/upgradedb.php 
upgradedb.php
(C) 2001-2019 LMS Developers
Using file /etc/lms/lms.ini as config.
DB schema version bumped to 2020083100

```
Rozwiązuje problem i otwiera się okienko z tworzeniem usera pierwszego.
Niestety z nieznanych mi powodów nie da się go stworzyć i za każdym razem LMS odrzuca polecenie ZAPISZ i na nowo okienko tworzenia usera.
Telefon do przyjaciela....
Potwierdza że miał ten sam problem, ponoć błąd w strukturze LMS'a.
Czyżby nadal nie poprawiony?
W logach:
`[Tue Oct 13 13:27:19.150186 2020] [:error] [pid 16755] [client 192.168.1.2:54738] PHP Warning:  array_keys() expects parameter 1 to be array, null given in /var/www/html/lms-git26/index.php on line 257, referer: http://192.168.1.1/lms-git26/?m=logout&is_sure=1
`

Czy ktoś wie jak wgrać bazę z 1.11.13 do GIT26 aby działało?
Zaznaczam nie mam możliwości stworzenia identycznego systemu na testy jak ten który jest na DIARZE i chyba nie o to tutaj chodzi aby zmuszać użytkownika backapu aby wgrywał wersję do identycznej wersji systemu.
Nie wiem czy do końca trafnie wybrałem wątek bo teraz zauważyłem, że dotyczy migracji do wersji 1.11.25 a nie do GIT26. Proszę ew przerzucić lub napisać to przerzucę do wątku GIT-26.

Pokusiłem się na ten czystej bazie z scheme zgodnym bez pierwszego usera bo nie można go stworzyć wgrać  jeszcze raz bazę z 1.11.13:
```
lms@lms:~$ mysql -u root -p --one-database lms < lms-diara-backup-2020-10-13.sql 
Enter password: 
lms@lms:~$ cd /var/www/html/lms-git26/
```
Wow przeszło....

Teraz męczę 100-tki razy php ./devel/upgradedb.php  co wypluwa setki błędów ale idzie dalej...
Przykładowy błąd jeden z setek:
```
lms@lms:/var/www/html/lms-git26$ php ./devel/upgradedb.php 
upgradedb.php
(C) 2001-2019 LMS Developers
Using file /etc/lms/lms.ini as config.
DB schema version bumped to 2020080300
DB schema upgrade errors:

    CREATE TABLE userdivisions (
        id int(11) NOT NULL auto_increment,
        userid int(11) NOT NULL,
        divisionid int(11) NOT NULL,
        PRIMARY KEY (id),
        INDEX userdivisions_userid_idx (userid),
        CONSTRAINT userdivisions_userid_fkey
            FOREIGN KEY (userid) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT userdivisions_divisionid_fkey
            FOREIGN KEY (divisionid) REFERENCES divisions (id) ON DELETE CASCADE ON UPDATE CASCADE,
        UNIQUE KEY userdivisions_userid_divisionid_ukey (userid, divisionid)
    ) ENGINE=InnoDB

Table 'userdivisions' already exists

```
Ale:
```
lms@lms:/var/www/html/lms-git26$ php ./devel/upgradedb.php 
upgradedb.php
(C) 2001-2019 LMS Developers
Using file /etc/lms/lms.ini as config.
DB schema version bumped to 2020083100
lms@lms:/var/www/html/lms-git26$ 

```
Niby osiągnął spoójność.
Niby działa LMS ale czy wszystkie dane prawidłowo przeniósł to tego nie wiem.
Da się to prościej zrobić?

Wejście na:
http://10.60.1.232/lms-git26/userpanel/
powoduje:
_"Composer autoload not found. Run 'composer install' command from LMS directory and try again. More informations at https://getcomposer.org/"_
```
ms@lms:/var/www/html/lms-git26/userpanel$ composer install
Composer could not find a composer.json file in /var/www/html/lms-git26/userpanel
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

```
LMS chodzi a user panel nie chodzi. I co biega z tym composerem?
Wykonanie :
```
lms@lms:/var/www/html/lms-git26/userpanel$ composer install
Composer could not find a composer.json file in /var/www/html/lms-git26/userpanel
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
lms@lms:/var/www/html/lms-git26/userpanel$ cd ..
lms@lms:/var/www/html/lms-git26$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package phine/exception is abandoned, you should avoid using it. No replacement was suggested.
Package phine/observer is abandoned, you should avoid using it. No replacement was suggested.
Package setasign/fpdi-tcpdf is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
> sed -i -e 's/class HTML2PDF_myPdf extends TCPDF/class HTML2PDF_myPdf extends LMSTCPDF/' vendor/spipu/html2pdf/_class/myPdf.class.php
> sed -i -e 's/\(\s\+\)register_shutdown_function/\1\/\/register_shutdown_function/' vendor/tecnickcom/tcpdf/tcpdf.php
> cp -f lib/ezpdf/fonts/arial* vendor/rospdf/pdf-php/src/fonts
lms@lms:/var/www/html/lms-git26$ 

```
Niczego nie zmienia nadal userpanel nie działa.
https://www.youtube.com/watch?v=b4QDxoWlPFw

**Comment by chilek** [comment]
W dniu 13.10.2020 18:49, batot1 napisał(a):
> Powracam z problemem bo teraz chce wrzucić na nowa maszynę
> produkcyjną działającą z tym GIT-26 starą wersję bazy LMS z
> wersji 1.11.13 i nie da się. Mam dokładnie te same błędy co już
> wcześniej zauważono wątku #1229 [1] ale też nikt nie powiedział
> jak rozwiązać problem.
> Czyżby tylko wsparcie płatne rozwiązywało problem?
> 
> Backup bazy zrobiłem tak:
> mysqldump -u username -p lms --single-transaction --quick
> --lock-tables=false > lms-backup-$(date +%F).sql
> 
> Przywracanie bazy z DIARY w LMS GIT-26 działający sprawny z
> usuniętymi błędami z wersji z repo.
> 
> Wszystkie operacje na GIT-26 jako nowym systemie
> 
>  	* Bazę "lms" usunięto w MariaDB.
>  	* Utworzono bazę LMS zgodnie z dokumentacją lms.org.pl
>  	* Próba wgrania metodą:
> 
> lms@lms:~$ mysql -u lms -p --one-database lms <
> lms-diara-backup-2020-10-13.sql
> Enter password:
> ERROR 1227 (42000) at line 2515: Access denied; you need (at least one
> of) the SUPER privilege(s) for this operation
> lms@lms:~$
> 
> Dziwne pomimo że wcześnie stożono użytkownika lms z pełnymi
> prawami dostępu zgodnie z Ad.2. czyli poleceniem:
> GRANT ALL ON lms.* TO lms@localhost IDENTIFIED BY 'twoje_hasło';
> 
> No nic skoro brak uprawnień to lecimy dalej z poziomu roota:
> lms@lms:~$ mysql -u root -p --one-database lms <
> lms-diara-backup-2020-10-13.sql
> Enter password:
> ERROR 1305 (42000) at line 2515: FUNCTION lms.lms_current_user does
> not exist
> 
> identycznym błędme pluje php ./devel/upgradedb.php
> 
> (C) 2001-2019 LMS Developers
> Using file /etc/lms/lms.ini as config.
> DB schema version bumped to 2017041800
> DB schema upgrade errors:
> 
>         CREATE VIEW customerview AS
>             SELECT c.*,
>                 a1.country_id as countryid, a1.zip as zip, a1.city as
> city,
>                 a1.street as street,a1.house as building, a1.flat as
> apartment,
>                 a2.country_id as post_countryid, a2.zip as post_zip,
>                 a2.city as post_city, a2.street as post_street,
> a2.name as post_name,
>                 a2.house as post_building, a2.flat as post_apartment,
>                 a1.address as address, a1.location AS full_address,
>                 a2.address as post_address, a2.location AS
> post_full_address
>             FROM customers c
>                 JOIN customer_addresses ca1 ON c.id = ca1.customer_id
> AND ca1.type = 1
>                 LEFT JOIN vaddresses a1 ON ca1.address_id = a1.id
>                 LEFT JOIN customer_addresses ca2 ON c.id =
> ca2.customer_id AND ca2.type = 0
>                 LEFT JOIN vaddresses a2 ON ca2.address_id = a2.id
>             WHERE NOT EXISTS (
>                 SELECT 1 FROM customerassignments a
>                 JOIN excludedgroups e ON (a.customergroupid =
> e.customergroupid)
>                 WHERE e.userid = lms_current_user() AND a.customerid =
> c.id)
>                 AND c.type < 2
> 
> FUNCTION lms.lms_current_user does not exist
> SELECT section, var, value, description FROM uiconfig WHERE disabled =
> 0 AND userid is null
> Unknown column 'userid' in 'where clause'
> lms@lms:/var/www/html/lms-git26$
> 
> No i tutaj tak samo jak wątku #1229 [1] brak rozwiązania.
> A może trzeba pozwolić GIT-26 aby poprzez WWW stworzył se tego
> usera?
> też ślepa uliczka bo ktoś celowo wyrzucił funkę:
> "FUNCTION lms.lms_current_user does not exist"
> a LMS nie tworzy pierwszego usera.
> 
> Na zakończenie stworzenie pustej bazy w GIT-26:
> generuje błąd na stronie www "Could not load database schema!"
> 
> lms@lms:/var/www/html/lms-git26$ php ./devel/upgradedb.php
> upgradedb.php
> (C) 2001-2019 LMS Developers
> Using file /etc/lms/lms.ini as config.
> DB schema version bumped to 2020083100
> 
> Rozwiązuje problem i otwiera się okienko z tworzeniem usera
> pierwszego.
> Niestety z nieznanych mi powodów nie da się go stworzyć i za
> każdym razem LMS odrzuca polecenie ZAPISZ i na nowo okienko tworzenia
> usera.
> Telefon do przyjaciela....
> Potwierdza że miał ten sam problem, ponoć błąd w strukturze
> LMS'a.
> Czyżby nadal nie poprawiony?
> W logach:
> [Tue Oct 13 13:27:19.150186 2020] [:error] [pid 16755] [client
> 192.168.1.2:54738] PHP Warning: array_keys() expects parameter 1 to be
> array, null given in /var/www/html/lms-git26/index.php on line 257,
> referer: http://192.168.1.1/lms-git26/?m=logout&is_sure=1
> 
> Czy ktoś wie jak wgrać bazę z 1.11.13 do GIT26 aby działało?
> Zaznaczam nie mam możliwości stworzenia identycznego systemu na
> testy jak ten który jest na DIARZE i chyba nie o to tutaj chodzi aby
> zmuszać użytkownika backapu aby wgrywał wersję do identycznej
> wersji systemu.
> Nie wiem czy do końca trafnie wybrałem wątek bo teraz zauważyłem,
> że dotyczy migracji do wersji 1.11.25 a nie do GIT26. Proszę ew
> przerzucić lub napisać to przerzucę do wątku GIT-26.
> 
> Pokusiłem się na ten czystej bazie z scheme zgodnym bez pierwszego
> usera bo nie można go stworzyć wgrać jeszcze raz bazę z 1.11.13:
> 
> lms@lms:~$ mysql -u root -p --one-database lms <
> lms-diara-backup-2020-10-13.sql
> Enter password:
> lms@lms:~$ cd /var/www/html/lms-git26/
> 
> Wow przeszło....
> 
> Teraz męczę 100-tki razy php ./devel/upgradedb.php co wypluwa setki
> błędów ale idzie dalej...
> Przykładowy błąd jeden z setek:
> 
> lms@lms:/var/www/html/lms-git26$ php ./devel/upgradedb.php
> upgradedb.php
> (C) 2001-2019 LMS Developers
> Using file /etc/lms/lms.ini as config.
> DB schema version bumped to 2020080300
> DB schema upgrade errors:
> 
>     CREATE TABLE userdivisions (
>         id int(11) NOT NULL auto_increment,
>         userid int(11) NOT NULL,
>         divisionid int(11) NOT NULL,
>         PRIMARY KEY (id),
>         INDEX userdivisions_userid_idx (userid),
>         CONSTRAINT userdivisions_userid_fkey
>             FOREIGN KEY (userid) REFERENCES users (id) ON DELETE
> CASCADE ON UPDATE CASCADE,
>         CONSTRAINT userdivisions_divisionid_fkey
>             FOREIGN KEY (divisionid) REFERENCES divisions (id) ON
> DELETE CASCADE ON UPDATE CASCADE,
>         UNIQUE KEY userdivisions_userid_divisionid_ukey (userid,
> divisionid)
>     ) ENGINE=InnoDB
> 
> Table 'userdivisions' already exists
> 
> Ale:
> 
> lms@lms:/var/www/html/lms-git26$ php ./devel/upgradedb.php
> upgradedb.php
> (C) 2001-2019 LMS Developers
> Using file /etc/lms/lms.ini as config.
> DB schema version bumped to 2020083100
> lms@lms:/var/www/html/lms-git26$
> 
> Niby osiągnął spoójność.
> Niby działa LMS ale czy wszystkie dane prawidłowo przeniósł to
> tego nie wiem.
> Da się to prościej zrobić?

Jaką spójność? Przecież błąd SQL zapytania typu DDL przy aktualizacji 
schematu w MySQL
powoduje, że i tak wersja schematu jest podbijana, więc w efekcie można 
mieć
złudzenie, że "w końcu poszło", a tak naprawdę cała masa braków jest 
potem w schemacie bazy danych.

> Wejście na:
> http://10.60.1.232/lms-git26/userpanel/
> powoduje:
> _"Composer autoload not found. Run 'composer install' command from LMS
> directory and try again. More informations at
> https://getcomposer.org/"_
> 
> ms@lms:/var/www/html/lms-git26/userpanel$ composer install
> Composer could not find a composer.json file in
> /var/www/html/lms-git26/userpanel
> To initialize a project, please create a composer.json file as
> described in the https://getcomposer.org/ "Getting Started" section
> 
> LMS chodzi a user panel nie chodzi. I co biega z tym composerem?
> 
> Wykonanie :
> 
> lms@lms:/var/www/html/lms-git26/userpanel$ composer install
> Composer could not find a composer.json file in
> /var/www/html/lms-git26/userpanel
> To initialize a project, please create a composer.json file as
> described in the https://getcomposer.org/ "Getting Started" section
> lms@lms:/var/www/html/lms-git26/userpanel$ cd ..
> lms@lms:/var/www/html/lms-git26$ composer install
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Nothing to install or update
> Package phine/exception is abandoned, you should avoid using it. No
> replacement was suggested.
> Package phine/observer is abandoned, you should avoid using it. No
> replacement was suggested.
> Package setasign/fpdi-tcpdf is abandoned, you should avoid using it.
> No replacement was suggested.
> Package phpunit/phpunit-mock-objects is abandoned, you should avoid
> using it. No replacement was suggested.
> Package phpunit/php-token-stream is abandoned, you should avoid using
> it. No replacement was suggested.
> Generating autoload files
>> sed -i -e 's/class HTML2PDF_myPdf extends TCPDF/class HTML2PDF_myPdf
> extends LMSTCPDF/' vendor/spipu/html2pdf/_class/myPdf.class.php
>> sed -i -e
> 's/\(\s\+\)register_shutdown_function/\1\/\/register_shutdown_function/'
> vendor/tecnickcom/tcpdf/tcpdf.php
>> cp -f lib/ezpdf/fonts/arial* vendor/rospdf/pdf-php/src/fonts
> lms@lms:/var/www/html/lms-git26$
> 
> Niczego nie zmienia nadal userpanel nie działa.
> https://www.youtube.com/watch?v=b4QDxoWlPFw

**Comment by batot1** [comment]
Czy w podkatalogu userpanel ma być plik JSON (bo nie ma)?

**Comment by batot1** [comment]
Nieaktualne poradziliśmy już sobie.
Niezły bigos jest w tym userpanelu aby go odpalić.

**Comment by interduo** [comment]
A widziałeś mój instalator dla Debiana w którymś tam katalogu?;)
