### ISSUE TITLE
lms-git26 - (master) brak kompatybiloności z PHP 7.4!

### ISSUE THREAD

**Issue by batot1** [lmsgit/lms#1853]
Gałąź master pobrana z dnia 16.11.2020.
Brak kompatybilności LMS z PHP 7.4
W Debian 10.6 najnowsza wersja PHP 7.4.
Przykład:

```
lms@lms:/var/www/html/lms-git26n/devel$ ./upgradedb.php
upgradedb.php
(C) 2001-2019 LMS Developers
Using file /etc/lms/lms.ini as config.
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/lms-git26/vendor/tecnickcom/tcpdf/tcpdf.php on line 16905
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/lms-git26/vendor/tecnickcom/tcpdf/tcpdf.php on line 16905
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/lms-git26/vendor/tecnickcom/tcpdf/tcpdf.php on line 16908
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/lms-git26/vendor/tecnickcom/tcpdf/include/tcpdf_images.php on line 318
DB schema version bumped to 2020083100
lms@lms:/var/www/html/lms-git26n/devel$ apt info php
Package: php
Version: 2:7.4+79+0~20201020.27+debian10~1.gbp95ec92
Priority: optional
Section: php
Source: php-defaults (79+0~20201020.27+debian10~1.gbp95ec92)
Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
Installed-Size: 13,3 kB
Depends: php7.4
Download-Size: 6 628 B
APT-Manual-Installed: no
APT-Sources: https://packages.sury.org/php buster/main amd64 Packages
Description: server-side, HTML-embedded scripting language (default)
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
 .
 This package is a dependency package, which depends on latest stable
 PHP version (currently 7.4).

N: There is 1 additional record. Please use the '-a' switch to see it
```

Nawet nie odpali się LMS bo nie potrafi zrobić ani ręcznej ani automatycznej aktualizacji struktury bazy.
Z wersją PHP 7.3 działa prawidłowo - przynajmniej odpala się.

**Comment by batot1** [comment]
Na dodatek macie coś pomieszane w gałęzi master bo pobrane przez gita powoduje taki wynik:
MariaDB [lms]> SELECT * from dbinfo;
+----------------------------------+--------------------------------------------------+
| keytype                          | keyvalue                                         |
+----------------------------------+--------------------------------------------------+
| dbversion                        | 2020083100                                       |
| last_check_for_updates_timestamp | 1605520693                                       |
| regdata_hidden                   | 0                                                |

A master pobrany przez plik ZIP'a w dniu dzisiejszym powoduje taki rezultat:
| dbversion                        | 2020111000                                       |
| last_check_for_updates_timestamp | 1605520369                                       |
| unique_installation_id           | 5026fb22351d5b62c071b542b0d91b3605f5617a206cd414 |

Czy oby na pewno plik ZIP to jest to samo z master pobrany przez GIT? Może ktoś to sprawdzić?

**Comment by batot1** [comment]
Oczywiście upgrade przechodzi z PHP 7.3 poprawnie:
```
lms@lms:/var/www/html/lms-git26n/devel$ ./upgradedb.php
upgradedb.php
(C) 2001-2019 LMS Developers
Using file /etc/lms/lms.ini as config.
DB schema version bumped to 2020083100
lms@lms:/var/www/html/lms-git26n/devel$

```
lms-git26n - wersja z gałęzi master pobrana gitem w dniu dzisiejszym. Oczywiście nie opala się strona LMS. Wysypuje się próbie zalogowania użytkownika.
Logi:
[Mon Nov 16 19:23:13.228355 2020] [:error] [pid 914] [client 91.196.56.17:53026] PHP Fatal error:  Uncaught Error: Call to undefined method LMSDivisionManager::setCurrentDivision() in /var/www/html/lms-git26n/index.php:284\nStack trace:\n#0 {main}\n  thrown in /var/www/html/lms-git26n/index.php on line 284, referer: http://10.60.1.232/lms-git26n/

**Comment by batot1** [comment]
A może jest jeszcze inaczej?
O dziwo w katalogu lib/upgradedb są nowsze aktualizacje ale z jakiś powodów nieznanych nie próbuje zaktualizować się struktura.
```
lms@lms:/var/www/html/lms-git26n/lib/upgradedb$ ls -la mysql.202011*
-rw-r--r-- 1 lms lms 1846 lis 16 11:26 mysql.2020110200.php
-rw-r--r-- 1 lms lms  993 lis 16 11:26 mysql.2020110201.php
-rw-r--r-- 1 lms lms 6193 lis 16 11:26 mysql.2020110400.php
-rw-r--r-- 1 lms lms 1165 lis 16 11:26 mysql.2020110600.php
-rw-r--r-- 1 lms lms 1087 lis 16 11:26 mysql.2020111000.php
lms@lms:/var/www/html/lms-git26n/lib/upgradedb$
```

**Comment by batot1** [comment]
No to chyba znamy przyczynę:
```
lms@lms:/var/www/html/lms-git26n/lib/upgradedb$ sudo ./mysql.2020090200.php
[sudo] hasło użytkownika lms:
sudo: ./mysql.2020090200.php: nie znaleziono polecenia
lms@lms:/var/www/html/lms-git26n/lib/upgradedb$ sudo php mysql.2020090200.php
PHP Fatal error:  Uncaught Error: Using $this when not in object context in /var/www/html/lms-git26n/lib/upgradedb/mysql.2020090200.php:24
Stack trace:
#0 {main}
  thrown in /var/www/html/lms-git26n/lib/upgradedb/mysql.2020090200.php on line 24
lms@lms:/var/www/html/lms-git26n/lib/upgradedb$

```

**Comment by zlyZwierz** [comment]
https://pl.wikipedia.org/wiki/Metoda_gumowej_kaczuszki

**Comment by batot1** [comment]
Ok znalazłem przyczynę dlaczego nie chciał za cholerę zrobić się upgrade bazy.
Obecnie:
```
lms@lms:/var/www/html/lms-git26n/devel$ ./upgradedb.php
upgradedb.php
(C) 2001-2019 LMS Developers
Using file /etc/lms/lms.ini as config.
DB schema version bumped to 2020111000
lms@lms:/var/www/html/lms-git26n/devel$

```
Lecz po wejściu do LMS wysypuje błędami:
Wystąpiły błędy w obsłudze bazy danych!

Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND vd.status = 0 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Unknown column 'vd.label' in 'field list'
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Unknown column 'vd.label' in 'field list'
Zapytanie: SELECT DISTINCT c.id AS id, c.lastname, c.name, CONCAT(UPPER(lastname), ' ', c.name) AS customername, c.karma, c.type, c.deleted, status, full_address, post_full_address, c.address, c.zip, c.city, countryid, countries.name AS country, cc.email, ccp.phone, ten, ssn, c.info AS info, extid, message, c.divisionid, c.paytime AS paytime, COALESCE(b.balance, 0) AS balance, COALESCE(t.value, 0) AS tariffvalue, s.account, s.warncount, s.online, (CASE WHEN s.account = s.acsum THEN 1 WHEN s.acsum > 0 THEN 2 ELSE 0 END) AS nodeac, (CASE WHEN s.warncount = s.warnsum THEN 1 WHEN s.warnsum > 0 THEN 2 ELSE 0 END) AS nodewarn FROM customerview c LEFT JOIN (SELECT customerid, (GROUP_CONCAT(contact SEPARATOR ',')) AS email FROM customercontacts WHERE (type & 8 > 0) GROUP BY customerid) cc ON cc.customerid = c.id LEFT JOIN (SELECT customerid, (GROUP_CONCAT(contact SEPARATOR ',')) AS phone FROM customercontacts WHERE (type & 5 > 0) GROUP BY customerid) ccp ON ccp.customerid = c.id LEFT JOIN countries ON (c.countryid = countries.id) LEFT JOIN customerbalances b ON b.customerid = c.id LEFT JOIN ( SELECT a.customerid, SUM( ( CASE a.suspended WHEN 0 THEN (((100 - a.pdiscount) * (CASE WHEN t.value IS null THEN l.value ELSE t.value END) / 100) - a.vdiscount) ELSE ((((100 - a.pdiscount) * (CASE WHEN t.value IS null THEN l.value ELSE t.value END) / 100) - a.vdiscount) * 0 / 100) END ) * ( CASE WHEN a.period <> 0 AND t.period > 0 AND t.period <> a.period THEN ( CASE t.period WHEN 5 THEN 1/12.0 WHEN 7 THEN 1/6.0 WHEN 4 THEN 1/3.0 ELSE 1 END ) ELSE ( CASE a.period WHEN 5 THEN 1/12.0 WHEN 7 THEN 1/6.0 WHEN 4 THEN 1/3.0 WHEN 2 THEN 4.0 WHEN 1 THEN 30.0 ELSE 1 END ) END ) * a.count ) AS value FROM assignments a LEFT JOIN tariffs t ON (t.id = a.tariffid) LEFT JOIN liabilities l ON (l.id = a.liabilityid AND a.period <> 0) WHERE a.commited = 1 AND a.datefrom <= UNIX_TIMESTAMP() AND (a.dateto > UNIX_TIMESTAMP() OR a.dateto = 0) GROUP BY a.customerid ) t ON (t.customerid = c.id) LEFT JOIN (SELECT ownerid, SUM(access) AS acsum, COUNT(access) AS account, SUM(warning) AS warnsum, COUNT(warning) AS warncount, (CASE WHEN MAX(lastonline) > UNIX_TIMESTAMP() - 600 THEN 1 ELSE 0 END) AS online FROM nodes WHERE ownerid > 0 AND ipaddr <> 0 GROUP BY ownerid ) s ON (s.ownerid = c.id) WHERE 1 = 1 AND c.divisionid = 1 ORDER BY customername asc LIMIT 100 OFFSET 0
Błąd: Unknown column 'c.karma' in 'field list'
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Unknown column 'vd.label' in 'field list'

Nie stworzył "vd.label" z jakiegoś powodu.

**Comment by chilek** [comment]
> https://pl.wikipedia.org/wiki/Metoda_gumowej_kaczuszki

:D

Tymczasem kibicujemy @batot1 w wynajdywaniu koła na nowo po raz milionowy.

**Comment by zlyZwierz** [comment]
@batot1 
To się powinno raczej tak robić:
root@test:/var/www/html/lms# mysql -u lms -p lms < doc/lms.mysql 

i dalej: (sprawdzając)

root@test:/var/www/html/lms# mysql -u lms -p lms
Enter password: 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 44
Server version: 10.3.25-MariaDB-0+deb10u1 Debian 10

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [lms]> show tables;
+-----------------------------+
| Tables_in_lms               |
+-----------------------------+
| addresses                   |
| aliasassignments            |
| aliases                     |
| assignments                 |
| cash                        |
(...)
| voip_prefix_groups          |
| voip_prefixes               |
| voip_price_groups           |
| voip_rule_groups            |
| voip_rule_states            |
| voip_rules                  |
| voip_tariffs                |
| voipaccounts                |
| vusers                      |
| zipcodes                    |
+-----------------------------+
160 rows in set (0.001 sec)

potem:

root@test:/var/www/html/lms# apt-get install php-zip php-soap php-xml php-bcmath

potem:

root@test:/var/www/html/lms# composer update --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies
Package operations: 43 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.9.0): Downloading (100%)         
  - Installing oomphinc/composer-installers-extender (2.0.0): Downloading (100%)         
(...)

potem wklejasz w konsoli to,  co wywali lms w przeglądarce:

chown -R 33:33 /var/www/html/lms/templates_c
chmod -R 755 /var/www/html/lms/templates_c
chown -R 33:33 /var/www/html/lms/backups
chmod -R 755 /var/www/html/lms/backups
chown -R 33:33 /var/www/html/lms/documents
chmod -R 755 /var/www/html/lms/documents
mkdir /var/www/html/lms/js/xajax_js/deferred
chown -R 33:33 /var/www/html/lms/js/xajax_js/deferred
chmod -R 755 /var/www/html/lms/js/xajax_js/deferred

i wbijasz  już normalnie.

**Comment by zlyZwierz** [comment]
Cała misja trwała z 5 minut.

**Comment by batot1** [comment]
Tak jak napisałem na czystej bazie działa na istniejącej nie działa. Zwierz czytaj wyżej co napisałem.

**Comment by zlyZwierz** [comment]
> Tak jak napisałem na czystej bazie działa na istniejącej nie działa. Zwierz czytaj wyżej co napisałem.

Nic co napisaeś się nie zgadza.

**Brak kompatybilności LMS z PHP 7.4** - U mnie działa.
**W Debian 10.6 najnowsza wersja PHP 7.4.** - W debku nie ma 7.4 z defaulta.

**Comment by batot1** [comment]
Czyli rozumiem mam taka cudowną wersje PHP 7.4 która nie generuje błędów w kodzie php?
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/lms-git26/vendor/tecnickcom/tcpdf/tcpdf.php on line 16905
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/lms-git26/vendor/tecnickcom/tcpdf/tcpdf.php on line 16905
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/lms-git26/vendor/tecnickcom/tcpdf/tcpdf.php on line 16908
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/lms-git26/vendor/tecnickcom/tcpdf/include/tcpdf_images.php on line 318

**Comment by chilek** [comment]
> PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/lms-git26/vendor/tecnickcom/tcpdf/tcpdf.php on line 16905
> PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/lms-git26/vendor/tecnickcom/tcpdf/tcpdf.php on line 16905
> PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/lms-git26/vendor/tecnickcom/tcpdf/tcpdf.php on line 16908
> PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/lms-git26/vendor/tecnickcom/tcpdf/include/tcpdf_images.php on line 318

No i to - to nie jest składnik LMS-a, a zewnętrzna biblioteka. Poproś Nicolę Assuni, żeby to poprawił.

**Comment by chilek** [comment]
@batot1 nie bież się za robotę w sytuacji, gdy nie potrafisz odróżnić błędu od ostrzeżenia. Do tego nie widzisz, że to ostrzeżenie generowane przez zewnętrzną bibliotekę.

**Comment by chilek** [comment]
@batot1 tu przynajmniej masz na kim się wyżyć, bo Nicola by na 100% zlał Twój mail.

**Comment by batot1** [comment]
> @batot1 nie bież się za robotę w sytuacji, gdy nie potrafisz odróżnić błędu od ostrzeżenia. Do tego nie widzisz, że to ostrzeżenie generowane przez zewnętrzną bibliotekę.
Masz rację

Co nie zmienia faktu, że lms nie działa z powodu braku tablic vd.* pomimo że struktura bazy jest aktualna.

**Comment by zlyZwierz** [comment]
Wydaje Ci się, że rozumiesz co robisz .. i masz rację  - wydaje Ci się.

Próbujesz forsować upgrade schematu bazy na silniku mysql, co jest dosyć wymagające od użytkownika,
bo często kończy się w połowie, ustawiając dbversion a nie czyniąc zmian w tabelach/widokach.

**Comment by zlyZwierz** [comment]
Proponuję przesiadkę na postgresa. Może będzie trochę "dziko" na początku, ale w dłuższym użytkowaniu wypada lepiej.

**Comment by batot1** [comment]
Cały czas się powiela jeden i ten sam błąd u programistów LMS'a.
Testujecie cały czas kod na czystej bazie (wtedy działa) natomiast 99% z nas ma już dane i aktualizuje na bazie a wtedy wychodzą kwiatki tak jak teraz i wszystkie poprzednie znalezione błędy. Zacznijcie testować na bazach dość dobrze wypełnionych danymi a nie pustymi.

**Comment by chilek** [comment]
@batot1 polecam zmianę nicka na @beton, bo do Ciebie niestety jak do betonu...

**Comment by zlyZwierz** [comment]
> Cały czas się powiela jeden i ten sam błąd u programistów LMS'a.
> Testujecie cały czas kod na czystej bazie (wtedy działa) natomiast 99% z nas ma już dane i aktualizuje na bazie a wtedy wychodzą kwiatki tak jak teraz i wszystkie poprzednie znalezione błędy. Zacznijcie testować na bazach dość dobrze wypełnionych danymi a nie pustymi.

Zacznij czytać to, co się do Ciebie pisze.
Jak nie umiesz ogarnąć, to zapłać komuś i miej to z głowy.

**Comment by chilek** [comment]
@zlyZwierz funkcja dawania "bananów" bardzoby się tu przydała :)

**Comment by zlyZwierz** [comment]
Kiedyś to było, zanim człowiek zdał prawko na internet, to nie jednego bana zarobił..

@batot1 - http://rtfm.killfile.pl/

**Comment by batot1** [comment]
>@zlyZwierz
> Zacznij czytać to, co się do Ciebie pisze.

Kolego proponuję faktycznie zacząć czytać co napisałem.
Jeśli ktoś trafi na taką samą sytuację jak u mnie i poczyta co to za rozwiązanie mu proponujecie:

> To się powinno raczej tak robić:
> root@test:/var/www/html/lms# mysql -u lms -p lms < doc/lms.mysql  👎 

no to się ostro ktoś zdziwi zdziwi po zabiegu jaki mu proponujecie kiedy zorientuje się, że baza wyparuje wraz z danymi. 
Po raz 4 ty napisze to samo na czystej bazie działa a na bazie z danymi nie działa bo z jakiegoś powodu nie stworzył w ogóle struktury "vd.*".
Skoro was błędy LMS nie interesują to zakończmy temat, bo nie prowadzi do nikąd.
To było moje ostanie zgłoszenie błędu. Bawcie się sami i testujcie.

**Comment by interduo** [comment]
Pozwólcie, że to zrobię.... ;)

**Comment by batot1** [comment]
Zgłaszam już od grubo ponad 10 lat błędy w rónżych programach Open Source jak Libre Office, Apache Office, Linux kernel. FRR, Mozilla Firefox itd...
Nigdy jednak nie spotkałem się nawet z jednym słowem krytyki ze strony społeczności po dokonaniu zgłoszenia natomiast w Polsce jest zawsze inaczej. Nie dość, że ktoś poświęca swój czas na znalezienie błędu, opisanie go ew znalezienie sposobu załatania problemu to jeszcze spotyka Cię jad ludzi z rodzimego polskiego podwórka.
Panowie - to nie tak działa.

@interduo
Mam nawet dwie działające wersje LMS'a stara poczciwa Diara i GIT26 z okolic października, więc nie rozumiem zupełnie twojej złośliwej uwagi.
Ta wersja prawdopodobnie też ruszy po uzupełnieniu tabeli "vd" (do tego Wy mi niepotrzebni jesteście).
Chciałem Was poinformować o istnieniu problemu, że aktualizacja nie zadziała jak ktoś ma pełna bazę - na czystej działa co napisałem na samym początku.

Pozdrawiam w Pokoju.

**Comment by zlyZwierz** [comment]
No i dostałeś odpowiedź, dlaczego tak się dzieje,
a ponieważ to Twoja instancja bazy a nie nasza - to na Tobie spoczywa jej
odgruzowanie.

MySQL będzie się pier**ł i tyle. O ile na pgsql w razie błędów aktualizacja
się zatrzyma i masz jasno napisane co i jak, o tyle na mysql poleci dalej
aktualizując numer wersji, zostawiając schemat w tyle.

wt., 17 lis 2020 o 09:45 batot1 <notifications@github.com> napisał(a):

**Comment by batot1** [comment]
> No i dostałeś odpowiedź, dlaczego tak się dzieje, a ponieważ to Twoja instancja bazy a nie nasza - to na Tobie spoczywa jej odgruzowanie.

Baza na chwilę obecną nigdy nie była modyfikowana w sensie rozbudowywana poza oryginalną strukturę narzuconą przez LMS.
Tak więc mowa o bazie LMS zbudowanej przez twórców LMS w sensie narzucenia struktury z góry, aktualizowana struktura również poprzez narzucenie z góry wytycznych autorów oprogramowania LMS. Błędy wynikłe w strukturze bazy SQL także są wynikiem działania oprogramowania autorów, więc gdzie tutaj "moja" instalacja skoro wszystko było robione za pomocą programów autorskich wchodzących w skład LMS?

Nie jestem biegły w SQL'u więc nie wypowiem się czy to prawda, że MYSQL jest niedoskonały bo aktualizuje się dalej pomimo błędów.
A czy to nie jest czasami tak, że aktualizacja a w zasadzie sposób aktualizacji struktury w ogóle nie ma funkcji weryfikacji po każdej małej paczce czy wykonała się poprawnie?
Pobieżnie oglądając kod nie spotkałem się nigdzie z kodem odpowiedzialnym za weryfikacje aktualizacji.
Powiem szczerze dotychczas myślałem, że skoro zmieniła się wersja aktualizacji w bazie LMS dbinfo. dbversion i widzę zapis np:
" dbversion                        | 2020111000  "
To mam pewność że aktualizacja powiodła się prawidłowo i struktura zaktualizowała się.
Jeśli update zmieni wersję bazy nawet jak aktualizacja się nie powiedzie poprawnie no to niefajnie łagodnie mówiąc.

A tutaj przyczyna dlaczego tabela label się nie utworzyła:
```
MariaDB [lms]> ALTER TABLE divisions ADD COLUMN label varchar(100) DEFAULT NULL;
ERROR 1118 (42000): Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

```
Kod wyciągnięty z kodu aktualizacji wrzucony ręcznie.

**Comment by zlyZwierz** [comment]
https://mariadb.com/kb/en/troubleshooting-row-size-too-large-errors-with-innodb/

wt., 17 lis 2020 o 15:08 batot1 <notifications@github.com> napisał(a):

**Comment by batot1** [comment]
Też to znalazłem - przebijamy się przez dokumentację....

**Comment by zlyZwierz** [comment]
Spróbuj

[mariadb]
...
innodb_strict_mode=OFF

i potem dopiero upgade.
Docelowo chyba trzeba zmienić page_size w InnoDB na 32k, lub 64k:

https://mariadb.com/kb/en/innodb-system-variables/#innodb_page_size
a potem dopiero zainicjalzować data dir wrzucić bazę z dumpa.

Nie weryfikowałem tego jakoś mocno - potestuj :)

wt., 17 lis 2020 o 15:40 batot1 <notifications@github.com> napisał(a):

**Comment by batot1** [comment]
Ustawienie:
innodb_strict_mode=OFF
pomogło na zasadzie że błędy zniknęły w komunikatach przeglądarki na stronie LMS ale czy przyszłe aktualizacje struktury bazy pójdą gładko nie wiem - czas pokaże.

Podejrzałem wartość u siebie:
```
MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE 'innodb_page_size';
+------------------+-------+
| Variable_name    | Value |
+------------------+-------+
| innodb_page_size | 16384 |
+------------------+-------+
1 row in set (0.001 sec)
MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE 'version';
+---------------+---------------------------+
| Variable_name | Value                     |
+---------------+---------------------------+
| version       | 10.3.23-MariaDB-0+deb10u1 |
+---------------+---------------------------+

```
Na starej diarze z nowym systemem gdzie nie mam problemów mam podobnie:
```
MariaDB [(none)]>  SHOW GLOBAL VARIABLES LIKE 'innodb_page_size';
+------------------+-------+
| Variable_name    | Value |
+------------------+-------+
| innodb_page_size | 16384 |
+------------------+-------+
1 row in set (0.002 sec)

MariaDB [(none)]>  SHOW GLOBAL VARIABLES LIKE 'version';
+---------------+-----------------+
| Variable_name | Value           |
+---------------+-----------------+
| version       | 10.4.12-MariaDB |
+---------------+-----------------+
1 row in set (0.002 sec)
MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE 'innodb_strict_mode';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| innodb_strict_mode | ON    |
+--------------------+-------+
1 row in set (0.002 sec)
```
pewnie przy aktualizacji struktury by się zaczął czepiać dopiero skoro jest ON - zgaduje.

i u kolegi jest tak:
```
MariaDB [lmsgit]> SHOW GLOBAL VARIABLES LIKE 'innodb_page_size';
+------------------+-------+
| Variable_name    | Value |
+------------------+-------+
| innodb_page_size | 16384 |
+------------------+-------+
1 row in set (0.00 sec)
MariaDB [lmsgit]> SHOW GLOBAL VARIABLES LIKE 'innodb_strict_mode';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| innodb_strict_mode | OFF   |
+--------------------+-------+
1 row in set (0.00 sec)

MariaDB [lmsgit]>
```
Ponieważ wszędzie jest innodb_page_size = 16384 więc nic nie zmieniam z tym parametrem.
Jak na razie działa.

Do wersji MariaDB  10.2.2 nie ma problemu a od  10.2.2 domyślnie jest ON więc pewnie dopiero zaczną się zgłaszać problemy po aktualizacji MariaDB bo wysypie się na aktualizacji struktury bazy LMS. Nie wiem jaką Centos ma teraz wersje MaridB.

**Comment by zlyZwierz** [comment]
Tam jest napisane, jak zapobiegać ewentualnym problemom  z InnoDB w
przyszłości.

Docelowo i tak proponuję przejście na postgresa.

śr., 18 lis 2020 o 12:12 batot1 <notifications@github.com> napisał(a):
