### ISSUE TITLE
JPK VAT - pozycje z fv które mają ponad 256 znaków, tag P_7

### ISSUE THREAD

**Issue by sparbelon** [lmsgit/lms#1854]
Witam,
Sytuacja jest następujący księgowe, napisały wypracowania po ponad 300 znaków na fv.
TZnakowyJPK ma max 256.
LMS generuje XML nie patrząc na to ograniczenie  -  wrzuci wszystkie 300 znaków tam gdzie powinno byc max 256 (znacznik P_7)
Przepatrzyłem kilka interpretacji i 1 z nich mówi:
Numery dowodów sprzedaży oraz dowodów zakupu należy ująć w ewidencji w całości, zgodnie z ich oryginalną pisownią do 256 znaków. 

Czy nie byłoby stosowne skrócenie pozycji do 256 znaków podczas generowania jpk ?

**Comment by chilek** [comment]
Na pewno chodzi o JPK-VAT, a nie o JPK-FA?

**Comment by chilek** [comment]
https://github.com/lmsgit/lms/commit/cfb18583a06d75e67c1031f45a5fed732d0f9824
