### ISSUE TITLE
postgresql - wgranie doc/lms.pgsql

### ISSUE THREAD

**Issue by batot1** [lmsgit/lms#1855]
Jeśli to nie miejsce na tego typu pytania to przepraszam nie za bardzo wiem gdzie z tym iść.
Postgresql zainstalowany, baza zainstalowana, użytkownik zainstalowany.

```
postgres=# SELECT * FROM pg_database WHERE datname='lms';
 datname | datdba | encoding | datcollate  |  datctype   | datistemplate | datallowconn | datconnlimit | datlastsysoid | datfrozenxid | datminmxid | dattablespace | datacl 
---------+--------+----------+-------------+-------------+---------------+--------------+--------------+---------------+--------------+------------+---------------+--------
 lms     |  16384 |        6 | pl_PL.UTF-8 | pl_PL.UTF-8 | f             | t            |           -1 |         13100 |          561 |          1 |          1663 | 
(1 wiersz)

postgres=# SELECT * FROM pg_user WHERE usename='lms';
 usename | usesysid | usecreatedb | usesuper | userepl | usebypassrls |  passwd  | valuntil | useconfig 
---------+----------+-------------+----------+---------+--------------+----------+----------+-----------
 lms     |    16384 | f           | f        | f       | f            | ******** |          | 
(1 wiersz)

```
Znalazłem w internecie sposób przez Was wskazany jak wgrywać strukturę bazy z doc:
```
postgres@lms:~$ psql -d lms -U lms -f /var/www/html/lms-git26n/doc/lms.pgsql 
psql: KATASTROFALNY:  Równoległa autoryzacja nie powiodła się dla użytkownika "lms"
postgres@lms:~$

```
w logach:
```
2020-11-20 11:48:38.951 CET [1496] lms@lms DZIENNIK:  dostarczona nazwa użytkownika (lms) i nazwa użytkownika zautoryzowanego (postgres) różnią się
2020-11-20 11:48:38.951 CET [1496] lms@lms KATASTROFALNY:  Równoległa autoryzacja nie powiodła się dla użytkownika "lms"
2020-11-20 11:48:38.951 CET [1496] lms@lms SZCZEGÓŁY:  Połączenie dopasowane do linii 90 pg_hba.conf: "local   all             all                                     peer"

```
Cel był po testować posgresa ale tutaj gogle już nie chce mi pomóc ;-(

**Comment by batot1** [comment]
Lista relacji
 Schemat |               Nazwa                |    Typ    | Właściciel 
---------+------------------------------------+-----------+------------
 public  | addresses                          | tabela    | lms
 public  | addresses_id_seq                   | sekwencja | lms
 public  | aliasassignments                   | tabela    | lms
 public  | aliasassignments_id_seq            | sekwencja | lms
 public  | aliases                            | tabela    | lms
 public  | aliases_id_seq                     | sekwencja | lms
 public  | assignments                        | tabela    | lms
 public  | assignments_id_seq                 | sekwencja | lms
 public  | cash                               | tabela    | lms
 public  | cash_id_seq                        | sekwencja | lms
 public  | cashimport                         | tabela    | lms
 public  | cashimport_id_seq                  | sekwencja | lms
 public  | cashreglog                         | tabela    | lms
 public  | cashreglog_id_seq                  | sekwencja | lms
 public  | cashregs                           | tabela    | lms
 public  | cashregs_id_seq                    | sekwencja | lms
 public  | cashrights                         | tabela    | lms
 public  | cashrights_id_seq                  | sekwencja | lms
 public  | cashsources                        | tabela    | lms
 public  | cashsources_id_seq                 | sekwencja | lms
 public  | comments                           | tabela    | lms
 public  | comments_id_seq                    | sekwencja | lms
 public  | contractorview                     | widok     | lms
 public  | countries                          | tabela    | lms
 public  | countries_id_seq                   | sekwencja | lms
 public  | cryptokeys                         | tabela    | lms
 public  | cryptokeys_id_seq                  | sekwencja | lms
 public  | customer_addresses                 | tabela    | lms
 public  | customer_addresses_id_seq          | sekwencja | lms
 public  | customeraddressview                | widok     | lms
 public  | customerassignments                | tabela    | lms
 public  | customerassignments_id_seq         | sekwencja | lms
 public  | customerbalances                   | tabela    | lms
 public  | customerconsents                   | tabela    | lms
 public  | customerconsentview                | widok     | lms
 public  | customercontacts                   | tabela    | lms
 public  | customercontacts_id_seq            | sekwencja | lms
 public  | customergroups                     | tabela    | lms
 public  | customergroups_id_seq              | sekwencja | lms
 public  | customerkarmalastchanges           | tabela    | lms
 public  | customerkarmalastchanges_id_seq    | sekwencja | lms
 public  | customermailsview                  | widok     | lms
 public  | customernotes                      | tabela    | lms
 public  | customernotes_id_seq               | sekwencja | lms
 public  | customers                          | tabela    | lms
 public  | customers_id_seq                   | sekwencja | lms
 public  | customerview                       | widok     | lms
 public  | daemonconfig                       | tabela    | lms
 public  | daemonconfig_id_seq                | sekwencja | lms
 public  | daemoninstances                    | tabela    | lms
 public  | daemoninstances_id_seq             | sekwencja | lms
 public  | dbinfo                             | tabela    | lms
 public  | debitnotecontents                  | tabela    | lms
 public  | debitnotecontents_id_seq           | sekwencja | lms
 public  | divisions                          | tabela    | lms
public  | docrights                          | tabela    | lms
 public  | docrights_id_seq                   | sekwencja | lms
 public  | documentattachments                | tabela    | lms
 public  | documentattachments_id_seq         | sekwencja | lms
 public  | documentcontents                   | tabela    | lms
 public  | documents                          | tabela    | lms
 public  | documents_id_seq                   | sekwencja | lms
 public  | domainmetadata                     | tabela    | lms
 public  | domainmetadata_id_seq              | sekwencja | lms
 public  | domains                            | tabela    | lms
 public  | domains_id_seq                     | sekwencja | lms
 public  | eventassignments                   | tabela    | lms
 public  | events                             | tabela    | lms
 public  | events_id_seq                      | sekwencja | lms
 public  | ewx_channels                       | tabela    | lms
 public  | ewx_channels_id_seq                | sekwencja | lms
 public  | ewx_pt_config                      | tabela    | lms
 public  | ewx_pt_config_id_seq               | sekwencja | lms
 public  | ewx_stm_channels                   | tabela    | lms
 public  | ewx_stm_channels_id_seq            | sekwencja | lms
 public  | ewx_stm_nodes                      | tabela    | lms
 public  | ewx_stm_nodes_id_seq               | sekwencja | lms
 public  | excludedgroups                     | tabela    | lms
 public  | excludedgroups_id_seq              | sekwencja | lms
 public  | filecontainers                     | tabela    | lms
 public  | filecontainers_id_seq              | sekwencja | lms
 public  | files                              | tabela    | lms
 public  | files_id_seq                       | sekwencja | lms
 public  | hosts                              | tabela    | lms
 public  | hosts_id_seq                       | sekwencja | lms
 public  | invoicecontents                    | tabela    | lms
 public  | invprojects                        | tabela    | lms
 public  | invprojects_id_seq                 | sekwencja | lms
 public  | liabilities                        | tabela    | lms
 public  | liabilities_id_seq                 | sekwencja | lms
 public  | location_boroughs                  | tabela    | lms
 public  | location_boroughs_id_seq           | sekwencja | lms
 public  | location_buildings                 | tabela    | lms
 public  | location_buildings_id_seq          | sekwencja | lms
 public  | location_cities                    | tabela    | lms
 public  | location_cities_id_seq             | sekwencja | lms
 public  | location_city_types                | tabela    | lms
 public  | location_city_types_id_seq         | sekwencja | lms
 public  | location_districts                 | tabela    | lms
 public  | location_districts_id_seq          | sekwencja | lms
 public  | location_states                    | tabela    | lms
 public  | location_states_id_seq             | sekwencja | lms
 public  | location_street_types              | tabela    | lms
 public  | location_street_types_id_seq       | sekwencja | lms
 public  | location_streets                   | tabela    | lms
 public  | location_streets_id_seq            | sekwencja | lms
 public  | logmessagedata                     | tabela    | lms
 public  | logmessagekeys                     | tabela    | lms
 public  | logmessages                        | tabela    | lms
 public  | logmessages_id_seq                 | sekwencja | lms
 public  | logtransactions                    | tabela    | lms
 public  | logtransactions_id_seq             | sekwencja | lms
public  | macs                               | tabela    | lms
 public  | macs_id_seq                        | sekwencja | lms
 public  | managementurls                     | tabela    | lms
 public  | managementurls_id_seq              | sekwencja | lms
 public  | messageitems                       | tabela    | lms
 public  | messageitems_id_seq                | sekwencja | lms
 public  | messages                           | tabela    | lms
 public  | messages_id_seq                    | sekwencja | lms
 public  | nas                                | widok     | lms
 public  | nastypes                           | tabela    | lms
 public  | nastypes_id_seq                    | sekwencja | lms
 public  | netdevicemodels                    | tabela    | lms
 public  | netdevicemodels_id_seq             | sekwencja | lms
 public  | netdeviceproducers                 | tabela    | lms
 public  | netdeviceproducers_id_seq          | sekwencja | lms
 public  | netdevices                         | tabela    | lms
 public  | netdevices_id_seq                  | sekwencja | lms
 public  | netlinks                           | tabela    | lms
 public  | netlinks_id_seq                    | sekwencja | lms
 public  | netnodes                           | tabela    | lms
 public  | netnodes_id_seq                    | sekwencja | lms
 public  | netradiosectors                    | tabela    | lms
 public  | netradiosectors_id_seq             | sekwencja | lms
 public  | networks                           | tabela    | lms
 public  | networks_id_seq                    | sekwencja | lms
 public  | nodeassignments                    | tabela    | lms
 public  | nodeassignments_id_seq             | sekwencja | lms
 public  | nodegroupassignments               | tabela    | lms
 public  | nodegroupassignments_id_seq        | sekwencja | lms
 public  | nodegroups                         | tabela    | lms
 public  | nodegroups_id_seq                  | sekwencja | lms
 public  | nodelocks                          | tabela    | lms
 public  | nodelocks_id_seq                   | sekwencja | lms
 public  | nodes                              | tabela    | lms
 public  | nodes_id_seq                       | sekwencja | lms
 public  | nodesessions                       | tabela    | lms
 public  | nodesessions_id_seq                | sekwencja | lms
 public  | numberplanassignments              | tabela    | lms
 public  | numberplanassignments_id_seq       | sekwencja | lms
 public  | numberplans                        | tabela    | lms
 public  | numberplans_id_seq                 | sekwencja | lms
 public  | passwd                             | tabela    | lms
 public  | passwd_id_seq                      | sekwencja | lms
 public  | passwdhistory                      | tabela    | lms
 public  | passwdhistory_id_seq               | sekwencja | lms
 public  | payments                           | tabela    | lms
 public  | payments_id_seq                    | sekwencja | lms
 public  | pna                                | tabela    | lms
 public  | pna_id_seq                         | sekwencja | lms
 public  | promotionassignments               | tabela    | lms
 public  | promotionassignments_id_seq        | sekwencja | lms
 public  | promotions                         | tabela    | lms
 public  | promotions_id_seq                  | sekwencja | lms
 public  | promotionschemas                   | tabela    | lms
 public  | promotionschemas_id_seq            | sekwencja | lms
 public  | receiptcontents                    | tabela    | lms
 public  | records                            | tabela    | lms
 public  | records_id_seq                     | sekwencja | lms
public  | routednetworks                     | tabela    | lms
 public  | routednetworks_id_seq              | sekwencja | lms
 public  | rtattachments                      | tabela    | lms
 public  | rtcategories                       | tabela    | lms
 public  | rtcategories_id_seq                | sekwencja | lms
 public  | rtcategoryusers                    | tabela    | lms
 public  | rtcategoryusers_id_seq             | sekwencja | lms
 public  | rtmessages                         | tabela    | lms
 public  | rtmessages_id_seq                  | sekwencja | lms
 public  | rtqueuecategories                  | tabela    | lms
 public  | rtqueuecategories_id_seq           | sekwencja | lms
 public  | rtqueues                           | tabela    | lms
 public  | rtqueues_id_seq                    | sekwencja | lms
 public  | rtrights                           | tabela    | lms
 public  | rtrights_id_seq                    | sekwencja | lms
 public  | rttemplatequeues                   | tabela    | lms
 public  | rttemplatequeues_id_seq            | sekwencja | lms
 public  | rttemplatetypes                    | tabela    | lms
 public  | rttemplatetypes_id_seq             | sekwencja | lms
 public  | rtticketcategories                 | tabela    | lms
 public  | rtticketcategories_id_seq          | sekwencja | lms
 public  | rtticketlastview                   | tabela    | lms
 public  | rttickets                          | tabela    | lms
 public  | rttickets_id_seq                   | sekwencja | lms
 public  | sessions                           | tabela    | lms
 public  | sourcefiles                        | tabela    | lms
 public  | sourcefiles_id_seq                 | sekwencja | lms
 public  | states                             | tabela    | lms
 public  | states_id_seq                      | sekwencja | lms
 public  | stats                              | tabela    | lms
 public  | supermasters                       | tabela    | lms
 public  | supermasters_id_seq                | sekwencja | lms
 public  | tariffassignments                  | tabela    | lms
 public  | tariffassignments_id_seq           | sekwencja | lms
 public  | tariffs                            | tabela    | lms
 public  | tariffs_id_seq                     | sekwencja | lms
 public  | tarifftags                         | tabela    | lms
 public  | tarifftags_id_seq                  | sekwencja | lms
 public  | taxes                              | tabela    | lms
 public  | taxes_id_seq                       | sekwencja | lms
 public  | templates                          | tabela    | lms
 public  | templates_id_seq                   | sekwencja | lms
 public  | teryt_simc                         | widok     | lms
 public  | teryt_terc                         | widok     | lms
 public  | teryt_ulic                         | widok     | lms
 public  | tsigkeys                           | tabela    | lms
 public  | tsigkeys_id_seq                    | sekwencja | lms
 public  | twofactorauthcodehistory           | tabela    | lms
 public  | twofactorauthcodehistory_id_seq    | sekwencja | lms
 public  | twofactorauthtrusteddevices        | tabela    | lms
 public  | twofactorauthtrusteddevices_id_seq | sekwencja | lms
 public  | uiconfig                           | tabela    | lms
 public  | uiconfig_id_seq                    | sekwencja | lms
 public  | up_customers                       | tabela    | lms
 public  | up_customers_id_seq                | sekwencja | lms
 public  | up_help                            | tabela    | lms
 public  | up_help_id_seq                     | sekwencja | lms
 public  | up_info_changes                    | tabela    | lms
public  | uiconfig                           | tabela    | lms
 public  | uiconfig_id_seq                    | sekwencja | lms
 public  | up_customers                       | tabela    | lms
 public  | up_customers_id_seq                | sekwencja | lms
 public  | up_help                            | tabela    | lms
 public  | up_help_id_seq                     | sekwencja | lms
 public  | up_info_changes                    | tabela    | lms
 public  | up_info_changes_id_seq             | sekwencja | lms
 public  | up_rights                          | tabela    | lms
 public  | up_rights_assignments              | tabela    | lms
 public  | up_rights_assignments_id_seq       | sekwencja | lms
 public  | up_rights_id_seq                   | sekwencja | lms
 public  | userassignments                    | tabela    | lms
 public  | userassignments_id_seq             | sekwencja | lms
 public  | userdivisions                      | tabela    | lms
 public  | userdivisions_id_seq               | sekwencja | lms
 public  | usergroups                         | tabela    | lms
 public  | usergroups_id_seq                  | sekwencja | lms
 public  | users                              | tabela    | lms
 public  | users_id_seq                       | sekwencja | lms
 public  | vaddresses                         | widok     | lms
 public  | vallusers                          | widok     | lms
 public  | vdivisions                         | widok     | lms
 public  | vmacs                              | widok     | lms
 public  | vnetworks                          | widok     | lms
 public  | vnodealltariffs                    | widok     | lms
 public  | vnodes                             | widok     | lms
 public  | vnodetariffs                       | widok     | lms
 public  | voip_cdr                           | tabela    | lms
 public  | voip_cdr_id_seq                    | sekwencja | lms
 public  | voip_emergency_numbers             | tabela    | lms
 public  | voip_number_assignments            | tabela    | lms
 public  | voip_number_assignments_id_seq     | sekwencja | lms
 public  | voip_numbers                       | tabela    | lms
 public  | voip_numbers_id_seq                | sekwencja | lms
 public  | voip_pool_numbers                  | tabela    | lms
 public  | voip_pool_numbers_id_seq           | sekwencja | lms
 public  | voip_prefix_groups                 | tabela    | lms
 public  | voip_prefix_groups_id_seq          | sekwencja | lms
 public  | voip_prefixes                      | tabela    | lms
 public  | voip_prefixes_id_seq               | sekwencja | lms
 public  | voip_price_groups                  | tabela    | lms
 public  | voip_price_groups_id_seq           | sekwencja | lms
 public  | voip_rule_groups                   | tabela    | lms
 public  | voip_rule_groups_id_seq            | sekwencja | lms
 public  | voip_rule_states                   | tabela    | lms
 public  | voip_rule_states_id_seq            | sekwencja | lms
 public  | voip_rules                         | tabela    | lms
 public  | voip_rules_id_seq                  | sekwencja | lms
 public  | voip_tariffs                       | tabela    | lms
 public  | voip_tariffs_id_seq                | sekwencja | lms
 public  | voipaccounts                       | tabela    | lms
 public  | voipaccounts_id_seq                | sekwencja | lms
 public  | vusers                             | widok     | lms
 public  | zipcodes                           | tabela    | lms
 public  | zipcodes_id_seq                    | sekwencja | lms
(278 wierszy)
Dobra chyba działa..

**Comment by batot1** [comment]
"Fatal error: cannot connect to database!"
Jednak to jeszcze trochę potrwa ;)

**Comment by zlyZwierz** [comment]
Do tego jest lista mailingowa,

https://lists.lms.org.pl/mailman/listinfo/lms

pt., 20 lis 2020 o 11:59 batot1 <notifications@github.com> napisał(a):

**Comment by batot1** [comment]
poddaje się
driver postgre zainstalowany w lms.ini wpisane, w phpinfo widać że enabled a lms twierdzi że nie enabled ;)
Jakieś sugestie?
`[Fri Nov 20 12:58:59.044758 2020] [php7:warn] [pid 7410] [client 10.60.1.12:38428] PHP Warning:  PHP Driver for "postgres" database doesn't seems to be loaded. in /var/www/html/lms-git26n/index.php on line 97, referer: http://10.60.1.232/lms-git26n/
`
To co im niby pomaga 
https://trzepak.pl/viewtopic.php?t=56100
czyli zmiana
local   all             postgres                                trust
czy
local   all             postgres                                md5
nic nie pomaga.
Jakieś pomysły?

Jak można recznie sprawdzić czy login i hasło pasuje do bazy aby mieć pewność?

**Comment by interduo** [comment]
Administracja postgresem i Twoim systemem nie jest w zakresie issues tego repozytorium!

**Comment by interduo** [comment]
Travis mieli prawie non-stop scenariusz wgrywania tego pliku do DB. Także na bank "się da".
