### ISSUE TITLE
Problem z fakturami wystawianymi ręcznie

### ISSUE THREAD

**Issue by mocakow** [lmsgit/lms#1857]
Wystawiając fakturę korygującą nie powstaje faktura do wydruku.
Dotyczy to faktur "usługowych", generowanych przez lms-payments.php.

**Comment by interduo** [comment]
Coś więcej?

**Comment by chilek** [comment]
Mistrzostwo świata tego typu zgłoszenia. Skrajny brak wyobraźni :D

**Comment by interduo** [comment]
A Ty na mnie narzekasz ;-))

**Comment by chilek** [comment]
@interduo Ty to jesteś świętoszek w stosunku do tego, ale na początku było z Tobą identycznie :D

**Comment by mocakow** [comment]
Tak to wygląda na koncie klienta . To trzecie to korekta. 
![screen-2020-11-26-06-31-03](https://user-images.githubusercontent.com/72433169/100311993-5e22fc00-2fb1-11eb-9e27-7dd3cd271b77.jpg)
Faktury są wystawiane jako PDF.

**Comment by mocakow** [comment]
Gdyby to dotyczyło tylko starych faktur (sprzed JPK7M) to ok. 
Niestety dotyczy to również tych „po JPK7M”.

**Comment by interduo** [comment]
SOA#1

Robiłeś:
$ composer update
?

**Comment by mocakow** [comment]
Po update 1.10.2020 tak mam.
composer update zrobiłem tak dla świętego spokoju.
Cache przeglądarki i i templates_c czyszczę prawie dziennie ;)
Efekt ten sam co na obrazku powyżej. 
Faktury są wystawiane jako pdf. Korekty generowane były jako html.
Był problem z poglądem korekt. Trzeba bylo invoices type w ustawieniach na domyślny (html)  aby zobaczyć podgląd Ale jako dokument, karekta widniała na koncie kienta.
Teraz nie.

**Comment by mocakow** [comment]
JSpoko … ja tak często updatów nie robię :)

**Comment by mocakow** [comment]
Spoko, ja tak często updatów nie robię. :)
Tylko jak muszę.

**Comment by mocakow** [comment]
Ja tak często updatów nie robię. :)
Najczęściej, dochodzi do tego  updatę całego systemu … więc mam jeszcze błędy composera.

**Comment by mocakow** [comment]
Ja tak często updatów nie robię. :)
Najczęściej, dochodzi do tego update całego systemu … więc mam jeszcze błędy composera. ;)

**Comment by mocakow** [comment]
Coś wiadomo w temacie korekt faktur ?

**Comment by interduo** [comment]
SOA#1 

Opisz jak odwzorować problem.

**Comment by mocakow** [comment]
Proba wystawienia korekry faktury, kończy się brakiem faktury korygującej do wydruku na koncie klienta. Co ciekawe wartość korekry jest brana pod uwagę. Na pewno to dotyczy faktur wystawianych przez skrypt ms-payments.php.
![image877](https://user-images.githubusercontent.com/72433169/103369485-8929cf80-4aca-11eb-8cad-7756493109c5.png)

**Comment by chilek** [comment]
@mocakow: na mysql coś wcześniej Ci poszło nie tak, a to co obserwujesz to opóźnione pozbawienie złudzeń, że na mysql nie bardzo się da sensownie korzystać z niego jeśli nie jesteś administratorem mysql.
Objaw wskazuje na to, że rekordy co cash dodają się, a rekordy do documents i invoicecontents niekoniecznie - błędy w schemacie bazy danych. Porównuj 1-do-1 tabele w Twojej bazie z tabelami z Twojego lokalnego pliku doc/lms.mysql. Bardzo prawdopodobne, że znajdziesz rozbieżności wynikające z wcześniej niezbyt udanych aktualizacji schematu.

Jest jeszcze inna możliwość - jeśli używasz wersji z gałęzi **master** to jest to wiecznie wersja rozwojowa, a 26.0 było chwilowo ustabilizowanych odrobinkę wydaniem rozwojowym. LMS to rozwiązanie w dużej mierze "self-care", a support ma społecznościowy i jeśli jest to akceptowalne i świadome to warto działać dalej ;-)

**Comment by chilek** [comment]
No i jest jeszcze co najmniej jedna rzecz porażająca mnie - nie chce się dla większość szukać historii problemów, które
są w wielu przypadkach zbieżne z własnymi. Odpowiedz mi na pytanie: dlaczego mam specjalnie dla Ciebie przeszukiwać historię zgłoszeń "issues" tutaj w github.com?

**Comment by mocakow** [comment]
Chilek dzięki za naprowadzenie, posprawdzam sobie. Co do drugiego wpisu nie wdaję się w takie utarczki. Powiem szczerze: nie miałem czasu sprawdzać bo mam wiele innej roboty. jeżeli był podobny problem to podai proszę tylko #numer Ja nie z tych, co czepiają się błędów w updatedb :)

**Comment by mocakow** [comment]
Faktycznie nie tworzy się dokument w tabeli. documents. Prześledzilem zmiany tabeli documents w updatedb od czasu poprzedniej aktualizacji (listopad 2019 po której wszystko działało). Przegrzebię jeszcze pliki w updatedb od czasu aktualizacji :) 
Potem pozostaje opcja awaryjna: zrobić sobie template  faktury korygującej. ;) 
Z innej beczki może da się wykorzystać ten gotowy.
Nie podoba mi się INSERT INTO documents ( …) w modules/invoicenote.php.  … Jeszcze, nie wiem dlaczego.

**Comment by mocakow** [comment]
Wygląda na to, że problem po ostatnich poprawkach rozwiązał się sam .

**Comment by interduo** [comment]
Stestowałem to przed chwilą na master - SOA#1.
Jeśli uważasz, że nie działa jak powinno opisz jak działa u Ciebie - a jak powinno.

Pozdrowionka :)

**Comment by mocakow** [comment]
Po wystawieniu faktury: Brak dokumentu do wydruku.  (faktury  w pdf).

![103369485-8929cf80-4aca-11eb-8cad-7756493109c5](https://user-images.githubusercontent.com/72433169/118387664-f5434500-b61f-11eb-81bb-f4e358f87509.png)

**Comment by interduo** [comment]
Jak wystawiłeś fv? Prze skrypt czy ręcznie?

**Comment by mocakow** [comment]
Ręcznie, „z klienta”.  Poprzez konto klienta /nowy dokument/faktura. To może być to samo co było z korektami. 
Może brakuje jakiegoś pola w insertach. Podejrzany: invoicenew.php.

**Comment by interduo** [comment]
Jak odwzorować problem na gałęzi master? 
Opisz krok po kroku.

**Comment by mocakow** [comment]
Wchodzisz na klienta.
![screen-2021-05-16-20-05-05](https://user-images.githubusercontent.com/72433169/118407780-84814480-b682-11eb-8f7a-a47042f0be4b.png)
Wybieram nowy dokument/faktura
![screen-2021-05-16-20-05-44](https://user-images.githubusercontent.com/72433169/118407793-9d89f580-b682-11eb-8e4d-1bd4bb4cf220.png)
Tworząc fakturę w danych podstawowych wybiram numer faktury, daty, inne pierdy  i zapisuję
![screen-2021-05-16-20-10-42](https://user-images.githubusercontent.com/72433169/118407870-0a04f480-b683-11eb-95a1-aa5a53e0278b.png)
Poniżej wybiram i wpisuję pozycje mające się znaleźć na fakturze. każdą zapisując
![screen-2021-05-16-20-13-37](https://user-images.githubusercontent.com/72433169/118407935-5819f800-b683-11eb-8a50-62ad0e544847.png)
Robię na koniec zapisz 
![screen-2021-05-16-20-15-43](https://user-images.githubusercontent.com/72433169/118407993-c959ab00-b683-11eb-8b51-e940518ff734.png)
I efekt końcowy na koncie klienta:
Wartość wchodzi do systemu ale dokumentu do wydruku brak.
![aaaaaaa](https://user-images.githubusercontent.com/72433169/118408162-83511700-b684-11eb-9453-78ef95a428c0.png)

**Comment by chilek** [comment]
W dniu 16.05.2021 20:24, mocakow napisał(a):

> [1]
> Tworząc fakturę w danych podstawowych wybiram numer faktury, daty, inne 
> pierdy i zapisuję

Dlaczego zakładasz, że te inne pierdy są dla nas nieistotne? ;-)



Links:
------
[1] 
https://user-images.githubusercontent.com/72433169/118407793-9d89f580-b682-11eb-8e4d-1bd4bb4cf220.png

**Comment by mocakow** [comment]
Uzupełniam: „pierdy” to „watości domyślne” ;-)
![screen-2021-05-17-15-35-23](https://user-images.githubusercontent.com/72433169/118497839-bbf4fd00-b725-11eb-9ffb-c30acbd17142.png)

**Comment by interduo** [comment]
@mocakow czy masz wersję aktualną mastera? Na czystej instancji tego nie mogę odwzorować.

**Comment by mocakow** [comment]
Nie napisałem, że baza MariaDB.

**Comment by mocakow** [comment]
@interduo Jak będę maił czas to postawię nowego lms.  Da się instalację jakoś zautomatyzować ?
W moim przypadku mam mały problem baza MariaDB jak wygląda konwersja na PostgreSQL? 
Narzędzia wiem że są, ale czy konwersja przechodzi bezproblemowo ?
