### ISSUE TITLE
Rejestr kasowy: nie można zrobić KP

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#1867]
**Wstępna weryfikacja**
W logach httpd i postgres cisza nic nie ma.

**Opis błędu**
Po wybraniu klienta znikają rejestry z litsty wyboru.

**Zrzuty ekranu**
Nagranie demonstruje problem: [lms-rejestr-kasowy-lms-git.zip](https://github.com/lmsgit/lms/files/5631673/lms-rejestr-kasowy-lms-git.zip)

**Środowisko - prosimy o uzupełnienie następującej informacji:**
Wersja LMS: | 26-git
-- | --
Wersja LMSDB: | 2020112800
Wersja PostgreSQL: | 10.14
Wersja PHP: | 7.2.24
Wersja Smarty: | 3.1.36

**Dodatkowe informacje**
Nigdy nie używałem tego modułu. Możliwe, że coś źle robię lub czegoś nie zrobiłem.

**Comment by kyob** [comment]
Jak sprawdzam w bazie zapytanie:
```sql
SELECT d.*,
       cc.name AS country,
       cd.name AS div_country,
       u.name AS USER,
       n.template,
       ds.name AS d_name,
       ds.address AS d_address,
       ds.zip AS d_zip,
       ds.city AS d_city,
       cds.name AS d_country
FROM documents d
LEFT JOIN countries cc ON cc.id = d.countryid
LEFT JOIN countries cd ON cd.id = d.div_countryid
LEFT JOIN vusers u ON (d.userid = u.id)
LEFT JOIN numberplans n ON (d.numberplanid = n.id)
LEFT JOIN customers c ON (d.customerid = c.id)
LEFT JOIN vdivisions ds ON (ds.id = c.divisionid)
LEFT JOIN countries cds ON cds.id = ds.countryid
WHERE d.type = 2
  AND d.id =1;
```
Otrzymuje komunikat: **ERROR:  unrecognized configuration parameter "lms.current_user"**

Dla pewności dodałem ponownie: 
```sql
CREATE OR REPLACE FUNCTION lms_current_user() RETURNS integer AS '
SELECT
CASE
    WHEN current_setting(''lms.current_user'') = ''''
    THEN 0
    ELSE current_setting(''lms.current_user'')::integer
END
' LANGUAGE SQL;
```
Nie pomogło. Jak tylko próbuję się zaprzyjaźnić z postgresem dostaję psikusa :)

**Comment by interduo** [comment]
@kyob https://github.com/chilek/lms-plus/issues/1499

**Comment by kyob** [comment]
### 1
```sql
 SELECT current_setting('lms.current_user', '0', 'false');
```
Error in query: ERROR: function current_setting(unknown, unknown, unknown) does not exist
LINE 1: SELECT current_setting('lms.current_user', '0', 'false')
HINT: No function matches the given name and argument types. You might need to add explicit type casts.

### 2
Po dodaniu:
```bash
# /var/lib/pgsql/data/postgresql.conf
# Add settings for extensions here
custom_variable_classes = 'lms'
```

`systemctl restart postgresql.service`
2020-12-02 22:08:37 CET <%> LOG:  received fast shutdown request
2020-12-02 22:08:37 CET <%> LOG:  aborting any active transactions
2020-12-02 22:08:37 CET <%> LOG:  worker process: logical replication launcher (PID 14041) exited with exit code 1
2020-12-02 22:08:37 CET <%> LOG:  shutting down
2020-12-02 22:08:37 CET <%> LOG:  database system is shut down

### 3
Pewnie znowu coś źle robię :)

**Comment by chilek** [comment]
>  SELECT current_setting('lms.current_user', '0', 'false');
> 
> Error in query: ERROR: function current_setting(unknown, unknown, unknown) does not exist
> 
> LINE 1: SELECT current_setting('lms.current_user', '0', 'false')
> 
> HINT: No function matches the given name and argument types. You might need to add explicit type casts.

Jak wskazuje podpowiedź - nie ma funkcji o prototypie, który próbujesz wykorzystać. Zrób:
```
SELECT current_setting('lms.current_user', '0', false);
```

**Comment by chilek** [comment]
> custom_variable_classes = 'lms'

Niepotrzebne od postgresql 9.1 (bodajże).

**Comment by chilek** [comment]
> Pewnie znowu coś źle robię :)

Zaraz się z kolei nasbiera na `posypanie popiołem` :D

**Comment by chilek** [comment]
> Po wybraniu klienta znikają rejestry z litsty wyboru.

Czy rejestry mają powiązania z firmami klientów poprzez niejawne dopisanie doń planów numeracyjnych?

**Comment by kyob** [comment]
### 1
> `SELECT current_setting('lms.current_user', '0', false);`

Error in query: ERROR: function current_setting(unknown, unknown, boolean) does not exist
LINE 1: SELECT current_setting('lms.current_user', '0', false)
HINT: No function matches the given name and argument types. You might need to add explicit type casts. 

### 2
Nie dokońca rozumiem 
> Czy rejestry mają powiązania z firmami klientów poprzez niejawne dopisanie doń planów numeracyjnych?
![Screenshot_2020-12-02 LMS Lista planów numeracyjnych](https://user-images.githubusercontent.com/689112/100933960-5eaa1e00-34ee-11eb-8ed1-3ecb4c5e5d9e.png)

**Comment by chilek** [comment]
W dniu 02.12.2020 22:33, kyob napisał(a):
> 1
> 
>> SELECT current_setting('lms.current_user', '0', false);
> 
> Error in query: ERROR: function current_setting(unknown, unknown,
> boolean) does not exist
> LINE 1: SELECT current_setting('lms.current_user', '0', false)
> HINT: No function matches the given name and argument types. You might
> need to add explicit type casts.

Zaraz, zaraz próbujesz ustawić czy odczytać?
Jeśli ustawić to gotowiec jest tu:
https://github.com/chilek/lms-plus/blob/dc90f32f264003e5a329b9a5bdc6eae546fd593e/lib/LMSDB_driver_postgres.class.php#L61

> 2
> 
> Nie dokońca rozumiem
> 
>> Czy rejestry mają powiązania z firmami klientów poprzez niejawne
>> dopisanie doń planów numeracyjnych?

1. Jakie masz przypisane plany numeracyjne dla dokumentów typu KP i KW w 
przykładowym
rejestrze kasowym, którego nie widzisz po wyborze klienta?
2. Czy te plany numeracyjne są przypisane do firmy do której należy 
testowy klient?

**Comment by interduo** [comment]
@kyob jeśli aktualne to otwórz.
