### ISSUE TITLE
Brak tytułu dokumentu w liście dokumentów w panelu klenta

### ISSUE THREAD

**Issue by mocakow** [lmsgit/lms#1884]
W userpanelu w liście dokumentów brak tytułu dokumentu.
Poniżej przykładowy klient
![screen-2020-12-14-22-36-51](https://user-images.githubusercontent.com/72433169/102138945-70c87c80-3e5d-11eb-95a9-3036fe0d770b.jpg)

Mam jeszcze problem z helpdeskiem dla klienta … gdzie ustawić domyślńa kolejkę dla klienta. ?
![screen-2020-12-14-22-38-16](https://user-images.githubusercontent.com/72433169/102139303-f64c2c80-3e5d-11eb-9379-fc26db2356d8.jpg)

**Comment by mocakow** [comment]
Znalazłem w tabeli uiconfig sekcję userpanel i wartości ale nie mam tej sekcji w konfiguracji panelu użytkownika
![photo_2020-12-15_18-36-35](https://user-images.githubusercontent.com/72433169/102251092-a3798000-3f04-11eb-959f-55504acac39b.jpg)

**Comment by interduo** [comment]
Lekkie OT: Przełącz sobie styl na bclean...

**Comment by mocakow** [comment]
Da się to lms.ini zrobić ?

**Comment by mocakow** [comment]
Da się to w lms.ini zrobić, czy trzeba grzebnąć w usepanelu w index.php ?

**Comment by chilek** [comment]
@mocakow jeśli jeszcze nie masz w swoim lms.ini wpisu:
```
userpanel_dir=/glowny/katalog/instalacji/lms/userpanel
```
to go dodaj i konfiguruj parametry userpanelu z poziomu menu "Panel klienta" z poziomu menu LMS po lewej ;-)

**Comment by mocakow** [comment]
Musi to być w sekcji [userpanel] w pliku ini ?

**Comment by mocakow** [comment]
W którym menu po lewej bo chyba oślepłem :)

**Comment by mocakow** [comment]
![screen-2020-12-15-19-23-23](https://user-images.githubusercontent.com/72433169/102255966-18e84f00-3f0b-11eb-8c9e-39dcaf033951.jpg)

**Comment by mocakow** [comment]
W  lms.ini nie dziala.
Dodałem w konfiguracji interfejsu użytkownika w sekcji directories i sie pojawił ;)

**Comment by mocakow** [comment]
Można by prosić jeszcze o tytuł dokumentu widoczny w panelu klienta w dokumentach :) Trochę to sam typ to trochę mało :)

**Comment by mocakow** [comment]
Można prosić jeszcze o tytuł dokumentu widoczny w panelu klienta w dokumentach.
Sam typ to trochę mało :)

**Comment by mocakow** [comment]
Może się komuś przyda: Dodany tytuł dokumentu (druga kolumna … po numerze) w dokumentach. w panelu klienta
/glowny/katalog/instalacji/lms/userpanel/modulesdocuments/templates/
[documents.tar.gz](https://github.com/lmsgit/lms/files/5703817/documents.tar.gz)

**Comment by mocakow** [comment]
Może się komuś przyda:  dodana pozycja tytuł w po numerze dokumentu w panelu użytkownika. w liście dokumentów
W sumie pierdoła… ale użyteczna.
/glowny/katalog/instalacji/lms/userpanel/modules/document/templates/
[documents.tar.gz](https://github.com/lmsgit/lms/files/5703927/documents.tar.gz)

**Comment by mocakow** [comment]
Utworzyłem sobie kolejkę „Zgłoszenia” na potrzeby helpdesku w userpanelu 
W konfiguracji modułu helpfesk chcę ją wybrać i zapisać. Niestety nie da się zapisać konfiguracji.
![screen-2020-12-17-07-22-26](https://user-images.githubusercontent.com/72433169/102451460-ce64f080-4038-11eb-90f7-3064eb3767bc.jpg)

Tak to wygląda po naciśnięciu zapisz:
![screen-2020-12-17-07-23-12](https://user-images.githubusercontent.com/72433169/102451527-f05e7300-4038-11eb-8e08-52f1c6e2923c.jpg)

**Comment by mocakow** [comment]
W panelu klienta wygląda to tak:
![screen-2020-12-17-07-38-22](https://user-images.githubusercontent.com/72433169/102452655-fce3cb00-403a-11eb-8324-55523a06bf68.jpg)
