### ISSUE TITLE
Composer Installer

### ISSUE THREAD

**Issue by Xanshara** [lmsgit/lms#1889]
Po wykonaniu composer install
Ukazuje się `composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating autoload files
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
`

Pliki są załadowane, ale niestety nie ma koncowej kompilacji.  Jak rozwiązać problem?

**Comment by chilek** [comment]
> Po wykonaniu composer install
> Ukazuje się `composer install Do not run Composer as root/super user! See https://getcomposer.org/root for details Continue as root/super user [yes]? yes Installing dependencies from lock file (including require-dev) Verifying lock file contents can be installed on current platform. Nothing to install, update or remove Generating autoload files 6 packages you are using are looking for funding. Use the `composer fund`command to find out more!`

i?

> Pliki są załadowane, ale niestety nie ma koncowej kompilacji. Jak rozwiązać problem?

O jaką kompilacją chodzi? Możesz dokładnie opisać?

**Comment by Xanshara** [comment]
Dokładnie robie z instrukcją i pierwszy raz coś takiego mi sie zdarza.
https://wiki.lms.org.pl/doku.php?id=instalacja_i_konfiguracja#instalacja_lms
Wpisuje komendę aby ściągnąć composera z git, następnie chce go zainstalować/uruchomić komenda `composer install` , pokazuje się to co wyżej napisałem, niestety za każdym razem na samym końcu "instalacji" ukazywało się `Compiling component files` i LMS ładnie działał. Niestety w tym wypadku tego nie ma i wchodząć na http://adresstrony.pl/lms pokazuje sie prosba o uruchomienie w folderze lms `composer install`.
Próbowałem na LMS 24, 25 i 26, za każdym razem to samo.
Ubuntu 16.06 server LTS, dodam, że nie był to mój wybór, i niestety tak musi być.

**Comment by interduo** [comment]
Może Twój problem jest wynikiem błędu w konfigu serwera www?

@Xanshara zerknij sobie https://github.com/chilek/lms-plus/blob/master/sample/lms-postgresql-debian10-install.sh tam masz krok po kroku co trzeba instalować. Przetestowane i działa. Na ubuntu zapewne będzie bardzo podobnie...
