### ISSUE TITLE
Powstaje nieprawidłowy typ dokumentu podczas wystawiania faktury w określonych okolicznościach.

### ISSUE THREAD

**Issue by darton** [lmsgit/lms#1891]
Wersja LMS: | 26.0 (2020-12-15T21:37:16+01:00)
-- | --
Wersja LMSDB: | 2020121400
Wersja MySQL: | 5.5.68-MariaDB
Wersja PHP: | 7.3.25
Wersja Smarty: | 3.1.36

Kroki:
Klienci --> lista -> Wybierz klienta -> Nowy dokument 'faktura' -> Adres odbiorcy [wybierz z listy] -> Zapisz -> Wybierz taryfę z listy -> Dodaj pozycję - Zapisz i drukuj

Taki ciąg czynności spowoduje wystawienie dokumentu, który nie jest fakturą.
Pominięcie kroku "Zapisz" po  kroku "Adres odbiorcy [wybierz z listy]" spowoduje, że faktura wystawi się prawidłowo.

**Comment by chilek** [comment]
Podejrzewam, że przy aktualizacji schematu MySQL miałeś błędy, które po prostu zignorowałeś.
Nie mam już siły 100x to samo w kółko tłumaczyć - przejrzyj historię zgłoszeń i popatrz jak sobie z tym radzić.

**Comment by darton** [comment]
OK dzięki.

**Comment by darton** [comment]
Wersja LMS: | 26.0 (2020-12-15T21:37:16+01:00)
-- | --
Wersja LMSDB: | 2020121400
Wersja MySQL: | 8.0.22-0ubuntu0.20.04.3
Wersja PHP: | 7.4.3
Wersja Smarty: | 3.1.36

Postawiłem system testowy od zera, lms od zera w najnowszej stabilnej wersji 26.
Dodałem ręcznie jednego klienta.

Wykonałem kroki:
Klienci --> lista -> Wybierz klienta -> Nowy dokument 'faktura' -> Adres odbiorcy [wybierz z listy] -> Zapisz -> Wybierz taryfę z listy -> Dodaj pozycję - Zapisz i drukuj

Dodaje dokument, który nie jest fakturą, jest w tabeli cash, ale nie zapisuje do tabel documents oraz invoicecontents.  

Pominięcie kroku "Zapisz" po kroku "Adres odbiorcy [wybierz z listy]" spowoduje, że faktura wystawi się prawidłowo. 

Będę wdzięczny za sugestie (za wyjątkiem migracji do postgresql bo to dopiero następny etap :-))

**Comment by chilek** [comment]
> Postawiłem system testowy od zera, lms od zera w najnowszej stabilnej wersji 26.

Nie istnieje coś takiego jak wersja stabilna 26.0 - to jest chwilowy zrzut developingu z master (fakt - troszeczkę ustabilizowany pod kątem synchronizacji z gałęzią `stable` z LMS+). Na bazie chwilowego `master` numerowanego 26.0 powstało `stable` z wersjami numerowanymi 26.x w LMS+.

> Będę wdzięczny za sugestie (za wyjątkiem migracji do postgresql bo to dopiero następny etap :-))

Błędnie zakładasz, że łatwiej najpierw zrobić aktualizację na mysql, a potem jak coś Ci trwale rozwali się będziesz próbował migrować na pgsql. W efekcie będziesz podwójnie robotę robił, ale Twoja sprawa.

Porównuj schematy tabel w bazie danych takie jak `documents`, `invoicecontents` i `cash` porównując stany bieżące schematu z tymi z biezącego doc/lms.mysql.

Był ten problem już wałkowany na mysql przez kilka osób w issues - przeszukaj i poczytaj.
