### ISSUE TITLE
Błąd w pliku https://github.com/lmsgit/lms/blob/master/lib/upgradedb/mysql.2018121200.php

### ISSUE THREAD

**Issue by darton** [lmsgit/lms#1892]
Błąd w pliku https://github.com/lmsgit/lms/blob/master/lib/upgradedb/mysql.2018121200.php

jest

$this->Execute("ALTER TABLE rtqueues ADD COLUMN verifierticketsubject varchar(255) NOT NULL DEFAULT ''");
$this->Execute("ALTER TABLE rttickets ADD COLUMN verifierticketbody text NOT NULL DEFAULT ''");

powinno być

$this->Execute("ALTER TABLE rtqueues ADD COLUMN verifierticketsubject varchar(255) NOT NULL DEFAULT ''");
$this->Execute("ALTER TABLE rtqueues ADD COLUMN verifierticketbody text NOT NULL DEFAULT ''");

I teraz pytanie w jaki sposób to poprawić:
Poprawić ten plik czy też zrobić kolejny  mysql.xxxx.php
który usunie kolumnę w jednej tabeli a doda w drugiej ?

**Comment by interduo** [comment]
Tak mi się wydaje, że idealnie by było, żebyś poprawił ten plik a w najnowszym schemacie napisał zapytanie z warunkiem "IF EXISTS".

**Comment by chilek** [comment]
@darton śliczne dzięki za eleganckie wskazanie problemu.
Poszła poprawka w master. Przeniosłem ją również do stable, stable-25 i stable-24.
