### ISSUE TITLE
Na świeżo zainstalowanym LMS dodanie faktury w specyficznych warunkach tworzy dokument, który nie jest fakturą, dane są w tabeli cash, ale nie w tabelach documents oraz invoicecontents.

### ISSUE THREAD

**Issue by darton** [lmsgit/lms#1895]
Wersja LMS: | 26.0 (2020-12-15T21:37:16+01:00)
-- | --
Wersja LMSDB: | 2020121400
Wersja MySQL: | 8.0.22-0ubuntu0.20.04.3
Wersja PHP: | 7.4.3
Wersja Smarty: | 3.1.36

Wykonałem kroki:

Postawiłem system testowy od zera, 

LMS od zera w najnowszej stabilnej wersji 26 na czystej bazie danych z zaimportowaną strukturą bazy z mysql.sql

Dodałem ręcznie jednego klienta.

Dodałem fakturę:
Klienci --> lista -> Wybierz klienta -> Nowy dokument 'faktura' -> Adres odbiorcy [wybierz z listy] -> Zapisz -> Wybierz taryfę z listy -> Dodaj pozycję - Zapisz i drukuj

Dodaje dokument, który nie jest fakturą, jest w tabeli cash, ale nie zapisuje do tabel documents oraz invoicecontents.  

Pominięcie kroku "Zapisz" po kroku "Adres odbiorcy [wybierz z listy]" spowoduje, że faktura wystawi się prawidłowo. 

Będę wdzięczny za sugestie (za wyjątkiem migracji do postgresql bo to dopiero następny etap :-))

Przywróciłem to zgłoszenie bo jak widać nie ma to nic wspólnego z aktualizacją LMS-a ani z Maria-DB

**Comment by mocakow** [comment]
Ten „zapisz” przed wybraniem taryfy z listy nie ma sensu. Wygląda, ze „Zapis” próbuje zapisać fakturę całościowo i nie pozwala zapisać faktury bez usługi/artykułu na fakturze.

**Comment by darton** [comment]
"Zapisz" to jest button w pierwszym panelu zaraz pod Adres odbiorcy i Komentarz.
Jak operator wystawiający fakturę zmienia adres to odruchowo na niego klika zakładając że po coś ten button "Zapisz" tam jest.
A skoro coś zmienił np wybrał z listy nowy adres a jest button "Zapisz" to w niego klienta.

Potem dodaje pozycje faktury i klienta "Zapisz" albo "Zapisz i drukuj" pod pozycjami faktury w efekcie faktura nie wystawia się.

**Comment by mocakow** [comment]
Ja mam identyczny problem z korektami faktur. 
Pozycja w cash jest, w documents… brak..
 Efekt na koncie klienta jest taki:
![image877](https://user-images.githubusercontent.com/72433169/103417062-79bd8b80-4b89-11eb-8f62-cb55ed2a630a.png)

**Comment by chilek** [comment]
https://github.com/lmsgit/lms/issues/1891#issuecomment-752994574

**Comment by chilek** [comment]
Sprawdziłem u siebie na czystej instalacji - prawdopodobnie nie zauważacie, że w pozycji faktury przy jej tworzeniu lista wyboru stawek jest pusta i to być może robi problem.
Gdy dodałem stawki VAT 23% i 8% i dodałem fakturę - bez problemu wystawiła się.
Testowałem na:

Wersja LMS: | 27-git
-- | --
Wersja LMSDB: | 2020122200
Wersja MySQL: | 5.5.5-10.4.17-MariaDB-log
Wersja PHP: | 7.3.25
Wersja Smarty: | 3.1.36

Tak czy inaczej testowanie czegokolwiek na 26.0 nie bardzo ma sens, bo od tej pory w master było już sporo poprawek i trzeba zawsze testować na bieżącym stanie gałęzi **master**.

**Comment by chilek** [comment]
Formularz nowej faktury tuż przed wciśnięciem ostatecznego "Zapisz" (ten na dole) wygląda u mnie następująco:

![Zrzut ekranu z 2020-12-31 17-16-51](https://user-images.githubusercontent.com/1457437/103417709-108b4780-4b8c-11eb-8415-30662abf77cd.png)

Faktura oczywiście bez problemu wystawia się.

**Comment by mocakow** [comment]
Nie dotyczy to korekt faktur … niestety. ;) 
Struktura tablic jest ok. Grzebię dalej.

**Comment by darton** [comment]
Faktura się wystawia u mnie tak samo bez problemu ale jak klikam tylko i wyłącznie dolny button "Zapisz"

Lista stawek Vat nie jest u mnie pusta. 
Dodałem wczesniej stawki vat i dodałem taryfę którą potem dodałem jako pozycję na fakturze.
Faktura się wystawia u mnie tak samo bez problemu ale jak klikam tylko i wyłącznie dolny button "Zapisz"

Weź wybierz adres z listy adresów a potem kliknij button "Zapisz" pod Komentarzem
a nastepnie dodaj pozycje na fakturze z listy i wtedy kliknij "dolny"  button "Zapisz" obok "Zapisz i drukuj"

**Comment by darton** [comment]
Przed chwilą przetestowałem to na wersji git, identycznie się zachowuje.


Wersja LMS: | 27-git
-- | --
Wersja LMSDB: | 2020122200
Wersja MySQL: | 8.0.22-0ubuntu0.20.04.3
Wersja PHP: | 7.4.3
Wersja Smarty: | 3.1.36

**Comment by darton** [comment]
> Formularz nowej faktury tuż przed wciśnięciem ostatecznego "Zapisz" (ten na dole) wygląda u mnie następująco:
> 
> ![Zrzut ekranu z 2020-12-31 17-16-51](https://user-images.githubusercontent.com/1457437/103417709-108b4780-4b8c-11eb-8415-30662abf77cd.png)
> 
> Faktura oczywiście bez problemu wystawia się.

Czy po wybraniu adresu z listy kliknąłeś na "Zapisz" pod komentarzem a dopiero potem dodawałeś pozycję na fakturze i kliknąłeś "Zapisz" pod pozycjami na fakturze ?
Samo wybranie adresu z listy nie powoduje problemów.

**Comment by chilek** [comment]
@darson gdybym tak nie zrobił to wybór adresu odbiorcy by "zginął"!
