### ISSUE TITLE
Wydrukuj formularz zapłaty 

### ISSUE THREAD

**Issue by dominoch** [lmsgit/lms#1896]
Nie jestem pewien czy błąd ale nie mogę zmienić na formularz przelewu/wpłaty w User Panel - sekcja finanse (przy zadłużeniu) "Wydrukuj formularz zapłaty" mimo zmian w IU w sekcji receipts z pdf na html 
Jak można wykorzystać /contrib/formularz_przelewu_wplaty
![obraz](https://user-images.githubusercontent.com/9640389/103533656-cb1d9180-4e8d-11eb-9ec9-2cca55556cba.png)

Próbowałem również na https://stable.lms.org.pl/userpanel/?m=finances&f=transferform
ciągle generowany jest pdf  a chciałbym przelew.png z wypełnionymi danymi 
Wydruk poprzez Finanse/Raporty/Formularze przelewu = również nie mogę zmienić - non stop szablon

LMS wersja 26-git
DB: 2020120800
Debian 10.7
https://stable.lms.org.pl/userpanel/?m=finances&f=transferform
![obraz](https://user-images.githubusercontent.com/9640389/103533628-bc36df00-4e8d-11eb-9553-c2586636702e.png)

**Comment by chilek** [comment]
Nie ma obsługi druczków png i nie będzie.
