### ISSUE TITLE
LMSD MariaDB issue

### ISSUE THREAD

**Issue by tudor-m234** [lmsgit/lms#1921]
Hello,

     I'm using the latest LMS git version, MariaDB 10.5.8, PHP 7.3. When using the "payments" LMSD module, i get this error:

Jan 19 17:03:00 lms lmsd[16597]: Configuration file '/etc/lms/lms.ini' loaded.
Jan 19 17:03:00 lms lmsd[16597]: Running module: payments
Jan 19 17:03:00 lms lmsd[16597]: ERROR: [db_exec] Query failed. You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' 2, 28, 'NUME prenume', 'oras', '', 'oras', '', '', 1611068580, 1611068580, 2...' at line 1

     Is there a maximum supported/tested/recommended version of MariaDB?

                  Thank you.

**Comment by interduo** [comment]
Using Postgres is recommended as DB engine. It's tested heavily and supported.

Why do You use lmsd? I think it's not maintained anymore (last change 2 years ago).

**Comment by tudor-m234** [comment]
The documentation said Mysql was the default, so...
As for LMSD, seemed advanced in the docs. I've gradually switched to
scripts, because different parts of LMSD started to fail or not work.

În vin., 19 mar. 2021 la 14:31, Interduo ***@***.***> a scris:

**Comment by tudor-m234** [comment]
I've switched to scripts and things work now. Maybe a "deprecated/please don't use LMSD" notice would help :)

              Thank you.
