### ISSUE TITLE
 Błąd daty końcowej przy wyborze bieżącego miesiąca w raportach finansowych (Finanse/Raporty) powtórnie.

### ISSUE THREAD

**Issue by mocakow** [lmsgit/lms#1947]
Przy wyborze bieżącego miesiąca (poprzez ikonę), w miesiącu lutym wygląda tak:
![screen-2021-02-01-06-27-26](https://user-images.githubusercontent.com/72433169/106419653-33de3680-6459-11eb-9857-2608ba09f9dd.jpg)
Na to wygląda, że może być problem z miesiącami mającymi mniej niż 31 dni.

**Comment by chilek** [comment]
Tak - faktycznie jest z tym problem - trzeba pewnie uzaleźnić kolejność wywołań metod js od bieżącego miesiąca.

**Comment by chilek** [comment]
Tym razem myślę, że ostateczny fix.
