### ISSUE TITLE
Zmienne do dokumenów/umów

### ISSUE THREAD

**Issue by dominoch** [lmsgit/lms#1968]
Czy uzyskam od was pomoc w namierzeniu zmiennych a może warto przygotować taką listę ;-)
a dokładnie do tworzenia dokumentu np typu umowa szukam zmiennej do wstawienia w dokument
maila i osoby reprezentującej
te nie działają
{$customerinfo.email}
{$customerinfo.name}
$customerinfo.customername
$customerinfo.customeremail

oraz jeżeli by się jeszcze udało żeby poprawnie pokazać numer konta ze spacjami
bo nie działa {$customerinfo.bankaccount|bankaccount_format}

kolega wystawił fajne umowy ale pod inet'a :/
https://ispforum.pl/index.php?topic=24844.msg137080#msg137080

**Comment by interduo** [comment]
Wrzuć sobie gdzieś w szablon dokumentu {debug} i wszystko stanie się jasne :)
