### ISSUE TITLE
Brak powiadomień o zmianach w zgłoszeniu helpdeska

### ISSUE THREAD

**Issue by Emers0** [lmsgit/lms#1977]
Przepisując zgłoszenie helpdeska innej osobie nie są wysyłane powiadomienia, mimo włączenia phpui.newticket_notify i phpui.ticket_property_change_notify. Wydaje mi się, że błąd jest w warunku sprawdzającym czy powiadomienie powinno być wysłane:
if (isset($ticketedit['notify'])
...

Zmienna $ticketedit['notify'] nie istnieje, jest za to $newticket_notify i wg mnie to ona powinna być w warunku. Po zmianie wysyłka działa.

```
--- rtticketedit.old.php        2021-03-23 13:06:22.156824157 +0100
+++ rtticketedit.php    2021-03-24 09:29:59.742267878 +0100
@@ -460,7 +460,7 @@
         // we notify about new ticket after queue change
         $newticket_notify = ConfigHelper::checkConfig('phpui.newticket_notify');
         $ticket_property_change_notify = ConfigHelper::checkConfig('phpui.ticket_property_change_notify');
-        if (isset($ticketedit['notify'])
+        if (isset($newticket_notify)
             && (($ticket_property_change_notify && ($ticket['state'] != $ticketedit['state']
                 || $ticket['owner'] != $ticketedit['owner']
                 || $ticket['deadline'] != $ticketedit['deadline']

```

**Comment by chilek** [comment]
Nie istnieje, bo nie zaznaczasz checkboksa "Powiadom użytkowników":

![Zrzut ekranu z 2021-03-24 12-55-14](https://user-images.githubusercontent.com/1457437/112306550-35312000-8ca0-11eb-9935-1bbbba06cb6b.png)

Mam na myśli **rtticketedit** i używany przezeń szablon html **rtticketmodify.html**.

**Comment by interduo** [comment]
@Emers0 aktualne?

**Comment by Emers0** [comment]
Nie.

W 18 maja 2021 14:57:15 Interduo ***@***.***> napisał:
