### ISSUE TITLE
Błędna data końcowa przy wyborze okresu w raportach.

### ISSUE THREAD

**Issue by mocakow** [lmsgit/lms#1979]
![screen-2021-03-31-16-07-01](https://user-images.githubusercontent.com/72433169/113157849-88c0e200-923b-11eb-8275-75dfb1636253.png)

**Comment by chilek** [comment]
Jeśli zamierzasz w ten sposób za każdym razem zgłaszać problem to po prostu tego nie rób, bo szkoda czasu wszystkich.

**Comment by interduo** [comment]
Przecież tutaj widać mankament. Może lekko się trzeba domyśleć.

**Comment by chilek** [comment]
> Przecież tutaj widać mankament. Może lekko się trzeba domyśleć. Ale fakt że można by to trochę było opisać precyzyjniej :-)

Naprawdę nie widzisz problemu w tego typu raporcie?

**Comment by interduo** [comment]
Widzę. Ale widzę też, mankament który zgłaszający chciał pokazać.

@mocakow nie potrafię odwzorować problemu siebie, daj więcej szczegółów

**Comment by chilek** [comment]
> Widzę. Ale widzę też, mankament który zgłaszający chciał pokazać.

Też widziałem ten mankament, tyle, że ten mankament poprawiałem osobiście już jakiś czas temu, a tu brak informacji kto jakiegoś środowiska używa. Bez sensu...

**Comment by mocakow** [comment]
Bo to tylko ostatniego wyskoczyło dzisiaj jest ok …
Wiem Chilek, że grzebałeś już w tym chyba w zeszłym miesiącu. Nie ma to raczej nic wspólnego ze środowiskiem pracy jak sugerujesz..

**Comment by mocakow** [comment]
Dzisiaj  ten problem nie wystąpił.
Mam jeszcze pytanie o composera: 
wrzucając najnowszego 
![screen-2021-04-30-13-43-17](https://user-images.githubusercontent.com/72433169/116690822-3dc0f880-a9ba-11eb-9097-11bb644e2678.png)
composer check-platform-reqs pokazuje:
![screen-2021-04-30-13-40-20](https://user-images.githubusercontent.com/72433169/116690853-4b767e00-a9ba-11eb-8141-70c3b648ddb3.png)
pomaga:
composer install --ignore-platform-reqs
Czy jest jakaś „dedykowana” wersja composera ?

**Comment by mocakow** [comment]
Juz w porządku okazało się ze modół php w apache stary. i teraz pytanie z tym zwiazane php7.1 czy php7.3 ?

**Comment by mocakow** [comment]
Wygląda na to, że problem się pojawia tylko 31.
![screen-2021-05-31-06-04-22](https://user-images.githubusercontent.com/72433169/120138609-15a20080-c1d7-11eb-8f64-dc00adb3b33f.png)

**Comment by chilek** [comment]
@mocakow chodzi o zakres dat pojawiający się po kliknięciu przycisku "bieżący miesiąc" dla miesięcy, które mają 31 dni?

**Comment by chilek** [comment]
Poprawione dla `current-month`.
