### ISSUE TITLE
Problem ze zmianą mac w urządzenia sieciowym.

### ISSUE THREAD

**Issue by mocakow** [lmsgit/lms#2052]
Nie da się zmienić i zapisać adresu mac w urządzeniu sieciowym. 
Pozostaje w trybie edycji
Można naciskać „zapisz” do woli.
Wydaje się, ze to ma związek ze zmianami  poczynionymi w modułach i temlaitach dotychacymi event'ów.
![screen-2021-06-24-16-11-03](https://user-images.githubusercontent.com/72433169/123279057-cade8480-d507-11eb-920c-0ae5f141f601.png)

**Comment by chilek** [comment]
Testowałem przed chwilą na bieżącej instalacji z gałęzi **master** - działa jak należy.
Spróbuj przeładować zawartość www z pominięciem mechanizmu cache przeglądarki www.

**Comment by mocakow** [comment]
wywalilem tymczasowe z templates_c i wywalilem historię przegladarki jest ok zamykam, probując na innej wszystko ok zamykam

**Comment by mocakow** [comment]
Z tym cache przeglądarek jest coraz większy problem. Chcą być zbyt mądre i szybkie. Zastanawiam się czy od strony www lms nie daloby się ustawić aby przeglądarka nie cache'owała strony. Nie chcę wyłaczać całkowicie cache'a przeglądarki. 
Ekstremalne rozwiazanie to logować się do lms „incognito” .:)

**Comment by interduo** [comment]
Musisz po prostu przy aktualizacji czyścić tu i tam i tyle :)

**Comment by mocakow** [comment]
Problem jest inny: jak edytuję paru klientów to cache przeglądarki cofając się pamięta te dane i zdarzyło się parę razy tak, że zmeniał dane nie tego klienta co trzeba.… ja na to zwracam uwagę ale niektórzy mają z tym problem .

**Comment by chilek** [comment]
W Google Chrome for Linux wystarczy wcisnąć SHIFT+F5 i po sprawie.

**Comment by mocakow** [comment]
Nie każdy o tym pamięta :)
