### ISSUE TITLE
[lms-notify] windykacja zadłużenie 100% i 200%

### ISSUE THREAD

**Issue by voytec69** [lmsgit/lms#2162]
W UI jest możliwość wylistowania klientów zadłużonych na 100 i 200%, pytanie czy da się to dorobić, lub ew. jak to osiągnąć na tym co jest z cli.

**Comment by chilek** [comment]
Nigdy nie będziemy dorabiać mało skalowalnych i podatnych na błędy zadłużeń typu N % miesięcznych zobowiązań.
Do tego służą liczby dni po przeterminowaniu należności i jest to obsługiwane od strony backendu w lms-notify.php:

https://github.com/chilek/lms-plus/wiki/Automatyzacja-czynno%C5%9Bci-na-klientach

**Comment by chilek** [comment]
Dyskusja związana z procenowymi zadłużeniami była już prowadzona wielokrotnie i szkoda czasu na dyskutowanie tego poraz setny :)
