### ISSUE TITLE
Brak możliwości modyfikowania adresu email w userpanelu

### ISSUE THREAD

**Issue by netarea** [lmsgit/lms#219]
Użytkownik, pomimo włączonej możliwości modyfikacji danych kontaktowych w userpanelu, nie może samodzielnie zaktualizować pola email - wpis nie dodaje się do bazy. Pole phone działa, pole email nie.

**Comment by interduo** [comment]
A patrzyłeś w https://lms/?m=userpanel&module=info&f=changes ? 

U mnie działa. Proponuję zamknąć zgłoszenie.
