### ISSUE TITLE
Przerobienie ładowania configów

### ISSUE THREAD

**Issue by maciejlew** [lmsgit/lms#228]
Chciałbym zrobić na nowo ładowanie configów. Zamiast globalnej tablicy $CONFIG dostępny byłby singleton LMSConfig. Byłaby możliwość ładowania ustawień z plików ini oraz bazy danych, z możliwością rozszerzenia na inne źródła w przyszłości.

Przykładowe użycie wyglądałoby następująco:

LMSConfig::getConfig()->getSection('directories')->getVariable('sys_dir');

LMSConfig::getConfig(array('lms_ini_path' => '/etc/lms/lms2.ini'))->getSection('directories')->getVariable('sys_dir');

LMSConfig::getIniConfig()->getSection('directories')->getVariable('sys_dir');

LMSConfig::getConfig()->getSection('jakas_sekcja_z_bazy')->getVariable('jakas_wartość_z_bazy');

LMSConfig::getDbConfig()->getSection('jakas_sekcja_z_bazy')->getVariable('jakas_wartość_z_bazy');

![lmsconfig](https://cloud.githubusercontent.com/assets/3950004/3281121/a8349aa0-f495-11e3-84a5-2b2f206804f5.png)

Zanim zacznę pisać to może ktoś ma jakieś spostrzeżenia do tego pomysłu?

**Comment by chilek** [comment]
Myślę, że można zamknąć już tą sprawę.
