### ISSUE TITLE
Nie mogę wyłączyć niepotrzebnych mi zakładek (modułow) w userpanel.

### ISSUE THREAD

**Issue by sq9mev** [lmsgit/lms#233]
Jedyną możliwość wyłączenia zakładek (modułów) w userpanel, to usunięcie lub wyłączenie dostępu do katalogów poszczególnych modułów w katalogu /userpanel/modules.

Oczywiście to powoduje rozsynchronizowanie mojej kopii roboczej z master i spowoduje problemy w przyszłości.

Jako workaround mógłbym skonfigurować ścieżkę do modułów, ale… nie mogę tego zrobić, ponieważ:
https://github.com/lmsgit/lms/blob/master/userpanel/index.php#L61

Wobec powyższego, kod używany w:
https://github.com/lmsgit/lms/blob/master/userpanel/index.php#L55 nie ma chyba najmniejszego sensu - wartość z $CONFIG, jeśli w ogóle jest gdzieś wykorzystywana, to moze być nieprzystajaca do zestawu modułów zczytanych w:
https://github.com/lmsgit/lms/blob/master/userpanel/index.php#L160

Pytania:
1. To jest błąd, czy jakieś celowe działanie?
2. Jak mam wyłączyć zakładki, których nie chcę nie modyfikując kodu źródłowego?

**Comment by chilek** [comment]
https://github.com/lmsgit/lms/blob/master/userpanel/index.php#L55 określa ścieżkę do modułów lms-a, a
w https://github.com/lmsgit/lms/blob/master/userpanel/index.php#L160 następuje rozpoczęcie czytania modułów userpanelu.

Myślę, że idealnym rozwiązaniem byłoby konfigurowanie dostępności poszczególnych modułów w menu userpanel lms-a.

**Comment by chilek** [comment]
Zrobione:
0e1b8c8cf0f40f9441b173c0ad1c2dc4ccbe6138
