### ISSUE TITLE
Próba aktualizacji do najnowszej wersji GIT

### ISSUE THREAD

**Issue by paszczus** [lmsgit/lms#239]
Kończy się takim błędem:

PHP Catchable fatal error:  Argument 1 passed to ConfigLoader::parseRawConfig() must be of the type array, null given, called in /usr/share/lmsgit/lib/LMSConfig/ConfigLoader.php on line 51 and defined in /usr/share/lmsgit/lib/LMSConfig/ConfigLoader.php on line 105

**Comment by cyberavis** [comment]
Coś jest jednak nie do końca tak jak powinno, bo po ponad 2 latach (LMS z gita wczoraj) na systemie openSUSE Leap z MariaDB 10.0.22, Apache 2.4.16 i PHP 5.5.14 wypluwa mi dokładnie ten sam błąd. Wydaje mi się, że to jakiś błąd z bazą danych, ale tylko wydaje mi się - bo nie mogę tego rozwiązać.

`PHP Catchable fatal error:  Argument 1 passed to ConfigLoader::parseRawConfig() must be of the type array, null given, called in /srv /www/lms/lib/LMSConfig/ConfigLoader.php on line 51 and defined in /srv/www/lms/lib/LMSConfig/ConfigLoader.php on line 105`
