### ISSUE TITLE
Userpanel 

### ISSUE THREAD

**Issue by dominoch** [lmsgit/lms#280]
Najświeższy LMS 1.11-git DB:DB: 2014090600 z dzisiaj 

Helpdesk - Nowe zgłoszenie  Kolejka: nie wyświetla się nic - brak listy rozwijanej. (oczywiście istnieje)

 Wystąpiły błędy w obsłudze bazy danych!
[ Błąd! ] 	Zapytanie: SELECT id FROM rtqueues WHERE id IN ()
Błąd: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 2

Zapytanie: SELECT id, name FROM rtqueues WHERE id IN ()
Błąd: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

Nie przypisuje do kategorii zgłoszenia.
Wszystko poprzypisywane poprawnie - wszystko działało prawdopodobnie do któregoś upgrade do GIT

**Comment by limer-org** [comment]
@dominoch zamykamy ??
