### ISSUE TITLE
ID i PIN na fakturze

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#309]
Pytanie dotyczy: https://github.com/lmsgit/lms/blob/master/modules/invoice_tcpdf.inc.php 
Nijak nie rozumiem zasadności umieszczenia jednocześnie ID i PIN na fakturach.

Myślę, że tego typu dane nie powinny znajdować się na fakturze, ale może jestem w błędzie?

**Comment by chilek** [comment]
Kwestia tego kto co lubi po prostu.

**Comment by paszczus** [comment]
Zgadza się, drukowanie PIN-u na fakturze, która często jest przekazywana do księgowych nie jest dobrym pomysłem. U nas to wyłączyliśmy.

**Comment by darton** [comment]
To jest luka, to oczywiste, ale trzeba traktować domyślny szablon jako
demonstrację możliwości, a nie produkcyjne zastosowanie.


W dniu 13 lutego 2015 15:04 użytkownik paszczus <notifications@github.com>
napisał:
