### ISSUE TITLE
zmiana właściwości połączenia

### ISSUE THREAD

**Issue by limer-org** [lmsgit/lms#331]
Gdy chcę zmienić rodzaj, szybkość etc. połączeń pomiędzy urządzeniami przy zapisie dostaję:
TypeError: form.elements.radiosector is undefined
Akurat nie mam jeszcze żadnego sektora dodanego do urządzenia.

**Comment by chilek** [comment]
https://github.com/lmsgit/lms/commit/8fbd58c948e6e2c9fa5aa4565b4c39e2e3b82ab5
Sprawdź czy pomogło.

**Comment by limer-org** [comment]
Tak, dziękuje.
