### ISSUE TITLE
rozciągniecie w poziomie strony

### ISSUE THREAD

**Issue by limer-org** [lmsgit/lms#351]
Czy to już tak ma być, że po dodaniu 'sektorów radiowych' strona będzie rozciągnięta w poziomie ?? czy mógłbym spróbować to przywrócić do poprzedniego zachowania ?

**Comment by chilek** [comment]
U mnie wygląda ok.

**Comment by chilek** [comment]
98247fc66d36acfe9a84e2c619e725f2553e82cf - trochę zwęziłem.

**Comment by limer-org** [comment]
trochę pomogło - a jakbym te opcje zrobił w dwóch rzędach ?? mam 1280x1024 - no chyba, że to za mało ;)

**Comment by chilek** [comment]
W dniu 21.04.2015 15:33, Krzysztof Labus napisał(a):
> trochę pomogło - a jakbym te opcje zrobił w dwóch rzędach ?? mam
> 1280x1024 - no chyba, że to za mało ;)

Ja mam 1920x1080 i pewnie dlatego styka ;-)
Można parami azymut i promień oraz wysokość i zasięg zrobić nad sobą.
Powinno wtedy wystarczyć.

-- 
Pozdrawiam
Tomasz Chiliński, Chilan

**Comment by limer-org** [comment]
w <thead> mogę <td> na <th> zamienić czy nie jest to wskazane ?

**Comment by nicraMarcin** [comment]
mam to samo. problem leży w długości pól i "nobr" :) przy mniejszym ekranie trzeba przewijać

**Comment by limer-org** [comment]
ja już zgrupowałem to jak @chilek zalecił - jest dobrze ;)

**Comment by nicraMarcin** [comment]
to może jakiś pull-request?

2015-04-22 9:19 GMT+02:00 Krzysztof Labus <notifications@github.com>:

> ja już zgrupowałem to jak @chilek <https://github.com/chilek> zalecił -
> jest dobrze ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lmsgit/lms/issues/351#issuecomment-95056475>.
>



-- 
Pozdrawiam
Marcin / nicraM

**Comment by limer-org** [comment]
robi się ;]

**Comment by limer-org** [comment]
@nicraMarcin pomogło ?

**Comment by nicraMarcin** [comment]
:) jeszcze nie robiłem fetcha, ale zapewnie pomoże :)

2015-04-22 10:31 GMT+02:00 Krzysztof Labus <notifications@github.com>:

> @nicraMarcin <https://github.com/nicraMarcin> pomogło ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lmsgit/lms/issues/351#issuecomment-95075533>.
>



-- 
Pozdrawiam
Marcin / nicraM

**Comment by limer-org** [comment]
Dalej przewijasz ?

**Comment by nicraMarcin** [comment]
tylko kilka pixeli, jest ok.

2015-04-22 10:44 GMT+02:00 Krzysztof Labus <notifications@github.com>:

> Dalej przewijasz ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lmsgit/lms/issues/351#issuecomment-95079597>.
>



-- 
Pozdrawiam
Marcin / nicraM

**Comment by limer-org** [comment]
Jaka przeglądarka i rozdzielczość ?

**Comment by nicraMarcin** [comment]
Firefox 1366x768

W dniu 22 kwietnia 2015 11:02 użytkownik Krzysztof Labus <
notifications@github.com> napisał:

> Jaka przeglądarka i rozdzielczość ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lmsgit/lms/issues/351#issuecomment-95083007>.
>



-- 
Pozdrawiam
Marcin / nicraM

**Comment by limer-org** [comment]
Firefox na Windzie i tej rozdzielczości nie każe mi przwwijać ;]

**Comment by nicraMarcin** [comment]
Ale to nie jest winda :)
Nie ma co się martwić jest ok. wystarczy Ctrl+- i działa bez przewijania.

W dniu 22 kwietnia 2015 11:15 użytkownik Krzysztof Labus <
notifications@github.com> napisał:

> Firefox na Windzie i tej rozdzielczości nie każe mi przwwijać ;]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lmsgit/lms/issues/351#issuecomment-95087075>.
>



-- 
Pozdrawiam
Marcin / nicraM

**Comment by limer-org** [comment]
No tak, sprawdzę to jeszcze jak będę przy jakimś linuksie ;]

**Comment by limer-org** [comment]
Teraz już wygląda dobrze.
