### ISSUE TITLE
problem z wyświetlaniem informacji o sektorach

### ISSUE THREAD

**Issue by limer-org** [lmsgit/lms#363]
Gdy dodaję sektor do połączenia:
![shot_150430_101739](https://cloud.githubusercontent.com/assets/2848202/7411037/9019eb9c-ef34-11e4-993c-236d7eefa763.png)

Po dodaniu:
![shot_150430_101856](https://cloud.githubusercontent.com/assets/2848202/7411036/901996ec-ef34-11e4-9dd3-ef661b7da259.png)

Gdy odświeżę stronę:
![shot_150430_101912](https://cloud.githubusercontent.com/assets/2848202/7411064/ca874dd8-ef34-11e4-962a-658d8ffa452b.png)

Czy ktoś wie dlaczego to się podmienia ??

**Comment by limer-org** [comment]
Jedyna różnica to zamiast 'żaden' mam '-' Tak dalej po odświeżeniu pozycje się podmieniają.

**Comment by chilek** [comment]
Zrób pełne odświeżenie zawartości w przeglądarce, bo pewnie czyta Ci z cache...

**Comment by limer-org** [comment]
naprawdę chciałbym by to było tylko to... zmieniłem przeglądarkę a na początku ją zupełnie zresetowałem. dalej to samo :(

**Comment by limer-org** [comment]
@chilek też masz coś takiego ?? mam tego patcha zaimplementowanego i też dalej zamienia. Może ja muszę na nowo coś dodać do bazy,m usunąć etc. ??

**Comment by chilek** [comment]
Po dwóch dzisiejszych commitach problem, który opisujesz nie istnieje.
Spróbuj jeszcze wyczyścić katalog ze skompilowanymi template-ami smarty.

**Comment by limer-org** [comment]
Od strony bazy. Mam urządzenie o ID 20, które jest połączone z urządzeniem 436. Urządzenie o 20 ma sektor o ID 6
6 | x   |  180.00 | 20.00 |       40 |    1000 |     20 | NULL    |   5.00000 |        101 |   0.04000 |       NULL 

połączenie to ma ID 1055
```
mysql> select * from netlinks where id = 1055;
+------+-----+-----+------+---------+---------+-------+------------+----------------+----------------+
| id   | src | dst | type | srcport | dstport | speed | technology | srcradiosector | dstradiosector |
+------+-----+-----+------+---------+---------+-------+------------+----------------+----------------+
| 1055 |  20 | 436 |    1 |       0 |       0 | 54000 |        101 |           NULL |              NULL |
+------+-----+-----+------+---------+---------+-------+------------+----------------+----------------+
1 row in set (0.00 sec)
```
Z poziomu 20 podłączam sektor do urządzenia 436 i otrzymuję:
```
mysql> select * from netlinks where id = 1055;
+------+-----+-----+------+---------+---------+-------+------------+----------------+----------------+
| id   | src | dst | type | srcport | dstport | speed | technology | srcradiosector | dstradiosector |
+------+-----+-----+------+---------+---------+-------+------------+----------------+----------------+
| 1055 |  20 | 436 |    1 |       0 |       0 | 54000 |        101 |           NULL |              6 |
+------+-----+-----+------+---------+---------+-------+------------+----------------+----------------+
1 row in set (0.00 sec)
```
co powoduje zamianę tych pól o czym pisałem wcześniej.

Jeżeli z poziomu 436 do połączenia dodaję ten sam sektor to otrzymuję:
```
mysql> select * from netlinks where id = 1055;
+------+-----+-----+------+---------+---------+-------+------------+----------------+----------------+
| id   | src | dst | type | srcport | dstport | speed | technology | srcradiosector | dstradiosector |
+------+-----+-----+------+---------+---------+-------+------------+----------------+----------------+
| 1055 |  20 | 436 |    1 |       0 |       0 | 54000 |        101 |              6 |           NULL |
+------+-----+-----+------+---------+---------+-------+------------+----------------+----------------+
1 row in set (0.00 sec)
```
i wszystko wygląda dobrze.

**Comment by chilek** [comment]
Może i tak, ale u mnie przed tą poprawką też występował dokładnie ten problem, a po poprawce działa jak należy.

**Comment by limer-org** [comment]
tak tylko, że poprawki nie zapisują TYLKO w jedno pole sektora, co powoduje, że ta wartość ID sektora Sobie wędruje w zależności, co gdzie ustawiamy.

**Comment by chilek** [comment]
To co pokazujesz w bazie wynika z błędnie u Ciebie działającego interfejsu użytkownika, więc to tu tkwi u Ciebie problem.

**Comment by chilek** [comment]
Już widzę, gdzie teraz leży problem.

**Comment by limer-org** [comment]
Wszystko działa już w porządku. Dziękuję za wysłuchanie.
