### ISSUE TITLE
Korekta faktur

### ISSUE THREAD

**Issue by nicraMarcin** [lmsgit/lms#364]
1. nie ma możliwości korekty faktury rozliczonej
2. korygując fakturę można tylko usunąć pozycje, nie można nic dodać

**Comment by chilek** [comment]
Punkt 2 to pomyłka - nigdy czegoś takiego nie było.

**Comment by nicraMarcin** [comment]
Tak, pomyłka. Pomyliła mi się edycja z korektą :/
