### ISSUE TITLE
Tworzenie zobowiązań z schematu promocji nie działa dla taryf z niezdefiniowanym okresem naliczania?

### ISSUE THREAD

**Issue by maciejlew** [lmsgit/lms#367]
Jeśli taryfa ma niezdefiniowany okres naliczania to podczas tworzenia zobowiązania zawsze będzie kopiowana. Czy to jest bug czy jest w tym jakiś głębszy sens?

Problem od strony technicznej jest w LMSFinanceManager::AddAssignment. Podczas sprawdzania czy taryfa istnieje należałoby dodać warnek "OR period IS NULL".

**Comment by maciejlew** [comment]
Powinno być tak moim zdaniem

                    // Find tariff with specified name+value+period...
                    $tariffid = null;
                    if ($tariff['period'] !== null) {
                        $tariffid = $this->db->GetOne('
                            SELECT id FROM tariffs
                            WHERE name = ? AND value = ? AND period = ?
                            LIMIT 1',
                            array(
                                $tariff['name'],
                                str_replace(',', '.', $value),
                                $tariff['period'],
                            )
                        );
                    } else {
                        $tariffid = $this->db->GetOne('
                            SELECT id FROM tariffs
                            WHERE name = ? AND value = ? AND period IS NULL
                            LIMIT 1', 
                            array(
                                $tariff['name'],
                                str_replace(',', '.', $value),
                            )
                        );
                    }

**Comment by chilek** [comment]
Możesz podesłać propozycję zmian w postaci pull request-a?

**Comment by maciejlew** [comment]
Podesłałem
