### ISSUE TITLE
userpanel: Unable to load template file 'userpanel/style/old/box.html' in 'login.html'

### ISSUE THREAD

**Issue by tm-poland** [lmsgit/lms#369]
Witam,
nowa instalacja z LMS_011116.zip. Wersja bazy 2015033000.

Po wejściu w userpanel mam następujący błąd:
Fatal error: Uncaught --> Smarty: Unable to load template file 'userpanel/style/old/box.html' in 'login.html' <-- thrown in /var/www/lms/lib/Smarty/sysplugins/smarty_internal_templatebase.php on line 129

Jakiś pomysł czym to może być spowodowane?
Oczywiście box.html jest na swoim miejscu, templates_c wyczyszczone.

**Comment by tm-poland** [comment]
ewidentnie coś jest namieszane ze ścieżkami 
będąc w katalogu userpanel odwołuje się do katalogu userpanel ponownie zamiast do 
style"
wystarczy przekopiować ponownie zawartosc userpanel do userpanel i wszystko działa

**Comment by tm-poland** [comment]
czemu zamknąłeś? jest jakiś commit do tego?

**Comment by chilek** [comment]
Przeczytaj to co sam napisałeś jeszcze raz:

> ewidentnie coś jest namieszane ze ścieżkami 
> będąc w katalogu userpanel odwołuje się do katalogu userpanel ponownie zamiast do 
> style"
> wystarczy przekopiować ponownie zawartosc userpanel do userpanel i wszystko działa

Z tego wynika, że już rozwiązałeś sam problem.

**Comment by tm-poland** [comment]
przepraszam, faktycznie nie wyraziłem się jasno

musiałem zdublować katalog userpanel żeby było ok

wygląda na to że problem jest gdy lms nie jest w katalogu głównym serwera www tylko w podkatalogu

u mnie np. jak do lmsa trzeba się dostać http://www/lms/ to problem występuje jak w pierwszym poście

**Comment by chilek** [comment]
Jak jest ustawione userpanel_dir ?

**Comment by tm-poland** [comment]
powiedz mi gdzie ta opcja jest do ustawienia bo w lms.ini jej nie widzę

**Comment by maciejlew** [comment]
Ale jak ją tam dopiszesz to zacznie działać ;) W sekcji directories.

W dniu 11.06.2015 o 18:53, tm-poland pisze:

**Comment by tm-poland** [comment]
userpanel_dir = /var/www/lms/userpanel/

bez zmian błąd jak w pierwszym poście

**Comment by tm-poland** [comment]
jak ustawiłem tą opcję w sekcji directories w lms.ini bez zmian

po ustawieniu w Konfiguracja -> interfejs użytkownika jest już dobrze

dziękuje

**Comment by maciejlew** [comment]
w userpanel.index.php, przed linia:

define('USERPANEL_DIR', $CONFIG['directories']['userpanel_dir']);

wpisz:

var_dump($CONFIG['directories']);die;

**Comment by maciejlew** [comment]
No to ok.
