### ISSUE TITLE
Problem z filtrowaniem Komputery -> Lista -> Status

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#373]
Zauważyłem problem (aktualny LMS z GIT oraz wcześniejsze) z filtrowaniem Komputery -> Lista.
Filtrowanie przestaje działać po np. jednym przebiegu tzn. filtrowanie po STATUS każdym po kolei i już od drugiej tury przestaje filtrować. Nie reaguje na zmiany i zawsze pokazuje komputery podłączone. Sprawdzałem na rożnych przeglądarkach, systemach i wersjach LMS. Problem występuje w każdym wariancie.

**Comment by chilek** [comment]
Sprawdziłem na demo - problemy nie występuje.

**Comment by kyob** [comment]
Problem jest z parametrami w robi mi się:
m=nodelist&page=1&s=2&n=0&ng=&g=&m=nodelist&s=1&o=name%2Casc&page=

zmiast:
m=nodelist&page=1&s=2&n=0&ng=&g=

Co ciekawsze problem jest na dwóch różnych maszynach, innych wersjach LMS, Apache/Nginx :)

**Comment by chilek** [comment]
Co po kolei klikać na demo, żeby uzyskać ten efekt?

**Comment by kyob** [comment]
Na demo jest OK u mnie mam problem.

**Comment by kyob** [comment]
Problem był w tabeli uiconfig. Wgranie wersji z git pomogło.

**Comment by maciejhiller** [comment]
Problem jest gdy ustawimy phpui.short_pagescroller = true
