### ISSUE TITLE
problem z tworzeniem dokumentów 

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#376]
LMS wersja aktualna z GIT.

PHP Fatal error:  Uncaught  --> Smarty: Unable to load template extendsall '/var/www/lms/documents//templates/default/plugin.html' <-- \n  thrown in /var/www/lms/lib/Smarty/sysplugins/smarty_internal_template.php on line 219, referer: http://localhost/?m=documentadd

**Comment by chilek** [comment]
1) Zrób dla pewności devel/smarty_install.sh
2) https://github.com/lmsgit/lms/tree/master/lib/SmartyPlugins
Sprawdź czy w tym katalogu masz plik resource.extendsall.php

**Comment by kyob** [comment]
Mam  plik resource.extendsall.php i smarty 3.1.27. 

Problem nadal występuje.

**Comment by chilek** [comment]
Na pewno katalogu <lms-path>/lib/SmartyPlugins ustawia Ci się jako katalog z pluginami Smarty?

**Comment by kyob** [comment]
Tak mam tylko czy tak ma być?

    [plugins_dir:Smarty:private] => Array
        (
            [0] => /var/www/localhost/lib/Smarty/plugins/
            [1] => /var/www/localhost/lib//SmartyPlugins/
        )
    [_is_file_cache] => Array
        (
            [/var/www/localhost/lib/Smarty/plugins/Resource.Extendsall.php] => 
            [/var/www/localhost/lib/Smarty/plugins/resource.extendsall.php] => 
            [/var/www/localhost/lib//SmartyPlugins/Resource.Extendsall.php] => 
            [/var/www/localhost/lib//SmartyPlugins/resource.extendsall.php] => 1
        )

**Comment by chilek** [comment]
Tak to jest ok.

**Comment by chilek** [comment]
Gdzie ten komunikat Ci się wyświetla: w przeglądarce www czy w logu serwera www?
Jeśli w przeglądarce www to wklej komunikat z logu serwera www, ewentualnie wybierz "Pokaź źródło" i wtedy wstaw to co tam masz.
