### ISSUE TITLE
Nie działa drukowanie formularza przelewu

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#377]
LMS GIT wersja z dziś
SMARTY 3.1.27

Po wybraniu klienta i [ Finanse => Raporty => Formularze przelewu ] strona przeglądarki jest pusta.

Generalnie co trzeba ustawić lub zmienić, aby generowało druki?

### Logi z przeglądarki

Po włączeniu [ const VERBOSE = true; ] w [ lib/ezpdf/include/TTF.php ] pokazuje tylko coś takiego: 

==== Table directory
Version: 1.0, number of tables: 23
DSIG     360332       6780
EF^#     357656        166
UBŐđÝĚ     357824       2474
m*i     360300         30
eú<       7288       1678
ß2k        504         86
{>C     357600         54
ő#       8968       4500
ŃÄ      53700       5994
       64160       1584
nga      59696       1646
gly     357584         16
xžťĂ      72444     255842
Î&      13468      40232
3˙        380         54
4X@        436         36
a96        592       6696
ai2     328288       5472
¨      65744       6700
Ŕ        472         32
A˙p     333760       6925
     340688      16895
      61344       2815

### Logi z apacha:

PHP Fatal error:  Uncaught exception 'Exception' with message 'Internal error - formatType is 0.0' in /var/www/localhost/lib/ezpdf/include/TTF.php:617\nStack trace:\n#0 /var/www/localhost/lib/ezpdf/include/TTFsubset.php(110): TTF->unmarshalPost()\n#1 /var/www/localhost/lib/ezpdf/include/TTFsubset.php(58): TTFsubset->unmarshal('/var/www/local...')\n#2 /var/www/localhost/lib/ezpdf/Cpdf.php(792): TTFsubset->doSubset('/var/www/local...', '?A?L?F?-?S?Y?T?...', NULL)\n#3 /var/www/localhost/lib/ezpdf/Cpdf.php(2608): Cpdf->o_font(8, 'out')\n#4 /var/www/localhost/lib/ezpdf/Cpdf.php(2651): Cpdf->output()\n#5 /var/www/localhost/lib/ezpdf/Cezpdf.php(1842): Cpdf->stream('')\n#6 /var/www/localhost/lib/ezpdf.php(166): Cezpdf->ezStream()\n#7 /var/www/localhost/modules/transferforms2.php(140): close_pdf(Object(Cezpdf))\n#8 /var/www/localhost/modules/print.php(480): require_once('/var/www/local...')\n#9 /var/www/localhost/index.php(289): includ in /var/www/localhost/lib/ezpdf/include/TTF.php on line 617, referer: http://localhost/?m=print

**Comment by chilek** [comment]
Nie potwierdzam problemu - przetestowałem pod bieżącą wersją ze Smarty 3.1.27.
