### ISSUE TITLE
Userpanel konfiguracja

### ISSUE THREAD

**Issue by askipl** [lmsgit/lms#380]
Bieżąca wersja lmsa (z gita, baza praktycznie pusta świeża instalacja). Próba kliknięcia w Userpanel/konfiguracja wyswietla pustą stronę, w logach apache:
PHP Fatal error:  Uncaught  --> Smarty: Unable to load template extendsall 'userpanel/templates/setup.html' <-- \n  thrown in /var/www/lms/lib/Smarty/sysplugins/smarty_internal_template.php on line 219
Jakieś propozycje ?
Pozdrawiam
Adam

**Comment by paszczus** [comment]
Musisz zaktualizować smarty: devel/smarty_install.sh

**Comment by askipl** [comment]
Z tego co pamiętam to uruamiałem..:
./smarty_install.sh 
Downloading Smarty sources... done.
Extracting... done.
Merging... done.
patching file sysplugins/smarty_internal_resource_file.php
Cleaning up... done
...
PHP Fatal error:  Uncaught  --> Smarty: Unable to load template extendsall 'userpanel/templates/setup.html' <-- \n  thrown in /var/www/lms/lib/Smarty/sysplugins/smarty_internal_template.php on line 219
...

**Comment by paszczus** [comment]
A cache wyczyszczony? (strzal)

**Comment by askipl** [comment]
hm... nie wiem o jaki cache chodzi ... ale w związku z tym, że to świerza testowaa instalacja....
rm -rf, drop database itp i od nowa, git clone, devel/smart... założenie admin'a i dalej to samo ...:(

**Comment by chilek** [comment]
Na pewno masz wskazane katalogi w sekcji directories poprawnie?
Komunikat wskazuje na to, że nie możliwe jest załadowanie userpanel/templates/setup.html
jako zasobu typu extendsall, a ten typ zasobu definiowany jest w lib/SmartyPlugins/resource.extendsall.php.
Jaka dystrybucja, w jakiej wersji, jaka wersja php, itd...
No i:
rm -f {userpanel/,}templates_c/* na dobry początek też nie zaszkodzi.

**Comment by askipl** [comment]
System CentOS 7 ,php 5.4.16-36.el7_1, cofnąłem się do lms-LMS_011117, Tutaj jest trochę lepiej, bo można wejśc w konfigurację ale "wBOK" (i tak już po za tematem, można się łatwiej upgradeować ze starej wersji 1.10.7) juz jest podobne zachowanie:
...
PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file 'userpanel/style/default/box.html' <-- \n  thrown in /var/www/lms-LMS_011117/lib/Smarty/sysplugins/smarty_internal_template.php on line 219
...
kasowanie:
/var/www/lms-LMS_011117/cache
/var/www/lms-LMS_011117/templates_c
/var/www/lms-LMS_011117/userpanel/templates_c
nic nie zmienia
...
[directories]
sys_dir =  /var/www/lms-LMS_011117
userpanel_dir = /var/www/lms-LMS_011117/userpanel
...
lms ot rozpakowane archiwum LMS_011117.zip
w root'cie lms:
#ls -l userpanel/style/default/box.html
-rw-r--r--. 1 root root 430 06-29 12:58 userpanel/style/default/box.html
# ls -l /var/www/lms-LMS_011117/lib/Smarty/sysplugins/smarty_internal_template.php
-rw-r--r--. 1 root root 35233 07-22 14:34 /var/www/lms-LMS_011117/lib/Smarty/sysplugins/smarty_internal_template.php
:(

**Comment by chilek** [comment]
Pokaż:
```shell
ls -alZ userpanel
ls -alZ userpanel/style
ls -alZ userpanel/style/default
ls -alZ userpanel/style/default/box.html
```

**Comment by maciejlew** [comment]
Jest mały bug w index.php, niepotrzebnie doklejane jest 'templates' po 
'default'. Poprawię wieczorem jak wrócę do domu. Możesz sprawdzić czy 
takie coś Ci pomoże?

W dniu 22.07.2015 o 15:19, Tomasz Chiliński pisze:

**Comment by chilek** [comment]
Prawdopodobnie nałożyły się 2 problemy, ale to będę wiedział po tym jak dostaniemy odpowiedź z wyjściem poleceń powyżej. Drugi problem poprawiłem ostatnim commitem - nieprawidłowe tworzenie stałych USERPANEL_* (weszło w ostatnich wcześniejszych commitach).

Doklejanie templates po templates/default jest potrzebne ze względu na zgodność ze starymi instalacjami lms. Kiedyś będzie można to wywalić.

**Comment by askipl** [comment]
co do ls -laZ to contexty selinuxa mogę być nieprawidłowe ... mam system w  "permissive" w tej chwili. Także w tej chwili wg mnie jest istotny:
...
unconfined_u:object_r:httpd_sys_content_t:s0
...

**Comment by chilek** [comment]
Jeśli wszystkie pliki mają takie etykiety to jest ok.
Wypróbuj lms-a z tego momentu. Poszła poprawka bbd4762f942ed247c495c0fb9f3c593ea30029ea

**Comment by askipl** [comment]
Potwierdzam, w tej chwili działa konfiguracja userpanelam, jednak nadal nie można uruchomić userpanela (logoowanie w wBOK). Efekt podobny jak w przypadku konfiguracji:
...
PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file 'userpanel/style/default/box.html' <-- \n  thrown in /var/www/lms/lib/Smarty/sysplugins/smarty_internal_template.php on line 219
...

**Comment by chilek** [comment]
Commit 0b1a9d31cdf1604975e9343171adf26028acb73c powinnien rozwiązać problem.

**Comment by askipl** [comment]
Potwierdzam, teraz jest OK.
