### ISSUE TITLE
lms-payments i "shortname"

### ISSUE THREAD

**Issue by askipl** [lmsgit/lms#382]
lms-payments nie wpisuje do tabeli documents "shortname".
O ile się nie pomyliłem (u mnie działa) to pomaga:
--- lms-payments.dist	2015-07-22 21:37:44.433895822 +0200
+++ lms-payments	2015-07-22 21:59:53.010947437 +0200
@@ -628,7 +628,7 @@
 				$udbq->execute($uid);
 				my $urow = $udbq->fetchrow_hashref();
 				
-				my $ddbq = $dbase->prepare("SELECT name, address, city, zip, countryid, ten, regon, account, inv_header, inv_footer, inv_author, inv_cplace
+				my $ddbq = $dbase->prepare("SELECT  shortname, name, address, city, zip, countryid, ten, regon, account, inv_header, inv_footer, inv_author, inv_cplace
 						FROM divisions WHERE id = ?");
 				$ddbq -> execute($urow->{'divisionid'});
 				my $drow = $ddbq->fetchrow_hashref();
@@ -640,15 +640,15 @@
 				my $idbq = $dbase->prepare("INSERT INTO documents (number, numberplanid, type, countryid, divisionid,
 						customerid, name, address, zip, city, ten, ssn, cdate, sdate, paytime, paytype,
 						div_name, div_address, div_city, div_zip, div_countryid, div_ten, div_regon, div_account, 
-						div_inv_header, div_inv_footer, div_inv_author, div_inv_cplace, fullnumber)
-						VALUES (?, ?, 1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
+						div_inv_header, div_inv_footer, div_inv_author, div_inv_cplace, div_shortname, fullnumber)
+						VALUES (?, ?, 1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
 
 				$idbq->execute($numbers{$plan}, $plan, $urow->{'countryid'}, $urow->{'divisionid'}, $uid,
 						$urow->{'lastname'}.' '.$urow->{'name'}, $urow->{'address'}, $urow->{'zip'},
 						$urow->{'city'}, $urow->{'ten'}, $urow->{'ssn'}, $currtime, $saledate, $paytime, $inv_paytype,
 						$drow->{'name'}, $drow->{'address'}, $drow->{'city'}, $drow->{'zip'}, $drow->{'countryid'},
 						$drow->{'ten'}, $drow->{'regon'}, $drow->{'account'}, $drow->{'inv_header'}, $drow->{'inv_footer'},
-						$drow->{'inv_author'}, $drow->{'inv_cplace'}, $fullnumber);
+						$drow->{'inv_author'}, $drow->{'inv_cplace'}, $drow->{'shortname'}, $fullnumber);
 
 				$idbq = $dbase->prepare("SELECT id FROM documents
 						WHERE cdate = ? AND number = ? AND type = 1 AND customerid = ?");

**Comment by chilek** [comment]
Podeślij pull requesta.

**Comment by askipl** [comment]
Trochę za mało wiedzy o gi mam:
http://www.ofpro.pl/lms-payments.shortname.patch

**Comment by misiek08** [comment]
Wejdź w plik, który chcesz edytować, daj Edit, wprowadź zmiany i ich opis.
Potem będzie przycisk w stylu "Send pull request"

Jedyne co, to nie pamiętam czy możesz to robić na tym repozytorium, czy
jednak musisz zrobić Fork i potem to co wyżej.

W dniu czwartek, 23 lipca 2015 askipl <notifications@github.com> napisał(a):

**Comment by chilek** [comment]
Dobra już założyłem patch i puściłem do repo. Dzięki.
