### ISSUE TITLE
Terminarz - "samoczynne" przenoszenie spraw na dzień następny

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#384]
Rejestrujemy losowe przemieszczanie się zgłoszeń o jeden dzień do przodu.

Problem występuje od czasu, kiedy została wprowadzona możliwość definiowania daty końca zgłoszenia.

Cechą wspólną problematycznych spraw jest puste pole "KONIEC" w sprawie.

Czy macie podobne problemy?

PS: Czy SYSLOG będzie w przyszłości rejestrował zmiany w terminarzu?

**Comment by chilek** [comment]
Potrzebnych więcej szczegółów na temat tego jak odtworzyć błąd.

PS. Jak czas pozwoli to będzie.

**Comment by kyob** [comment]
Problem sam ustąpił, więc brak danych do replikacji problemu.
