### ISSUE TITLE
Problem z upgrade bazy

### ISSUE THREAD

**Issue by prezeskk** [lmsgit/lms#386]
Jesli ustawimy w lms.ini w sekcji
[database]
type = mysqli
to mamy problem :(

https://github.com/lmsgit/lms/blob/master/lib/LMSDB_common.class.php#L693
chodzi o zmienna $this->_dbtype
wyszukujemy pliki w formacie mysqli-yyyymmddnn.php a takie nie istnieja

**Comment by chilek** [comment]
Poprawione przez f810304f73b42841ae27ddabdee429d170b806f9
