### ISSUE TITLE
Potrzebny przycisk oceniania kontrahenta

### ISSUE THREAD

**Issue by mys751** [lmsgit/lms#390]
Prosty system, jak na forach + oraz - Tak by można sortować kontrahentów po plusach bądź minusach. Powiedziało by to szybko z którym kontahentem jest najwięcej problemów.

**Comment by interduo** [comment]
A może ilość zgłoszeń danego klienta by sensowniej o tym mówiła? 

Może zamiast wartości np. Zgłoszenia (1)  w zakładce customerinfo warto byłoby umieścić wartość Zgłoszenia (A/W)

A - aktywne, W - wszystkie danego klienta

**Comment by interduo** [comment]
"kebaby" sprawdzają się w momencie gdy klient ma dużo interakcji. Na przestrzeni umowy 24 miesięcznej możesz mieć z klientem tylko 2-3 interakcje. Uważam, że takie staty nie mają sensu bo każdy może mieć zły dzień. To co wyżej napisałem zostało już  zrealizowane.
