### ISSUE TITLE
Just question on git :)

### ISSUE THREAD

**Issue by misoza** [lmsgit/lms#410]
Hi, i have realy old version on system,
LMS version 1.10.5 Neith (1.868.2.18/1.19.2.2)

I try to find this in git, becouse i want to find and upgrade my changes with git. 

Some advice how to find Neith in git ? LMS version 1.10.5 Neith (1.868.2.18/1.19.2.2)

Thanks a lot

**Comment by gacopl** [comment]
you will not find it, git was started not that long ago previously we used CVS.
So my idea to you is try to upgrade manually 1.10.x then 1.11.x where
x is the last minor version and then git pull the latest if you really
want cutting edge

Good Luck

2015-10-25 2:12 GMT+02:00, misoza <notifications@github.com>:

**Comment by chilek** [comment]
W dniu 25.10.2015 10:27, gacopl napisał(a):
> you will not find it, git was started not that long ago previously we
> used CVS.
> So my idea to you is try to upgrade manually 1.10.x then 1.11.x where
> x is the last minor version and then git pull the latest if you really
> want cutting edge

That's not right.
All braches from cvs have been imported to our git repository.
So you could try the following comands:
git checkout c9314dd5d1665cfa2a10addd833487caaf3d7334
git checkout -b old_master
This way you could compare original 1.10.5 code with your (probably
locally modified) 1.10.5 code.

> Good Luck
> 
> 2015-10-25 2:12 GMT+02:00, misoza <notifications@github.com>:
>> Hi, i have realy old version on system,
>> LMS version 1.10.5 Neith (1.868.2.18/1.19.2.2)
>> 
>> I try to find this in git, becouse i want to find and upgrade my
> changes
>> with git.
>> 
>> Some advice how to find Neith in git ? LMS version 1.10.5 Neith
>> (1.868.2.18/1.19.2.2)
>> 
>> Thanks a lot
>> 
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/lmsgit/lms/issues/410
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/lmsgit/lms/issues/410#issuecomment-150904897

-- 
Pozdrawiam
Tomasz Chiliński, Chilan

**Comment by misoza** [comment]
Thanks a lot!
i try it
