### ISSUE TITLE
phpui.big_networks

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#443]
lms/modules/eventadd.php 
```
if (!ConfigHelper::checkValue(ConfigHelper::getConfig('phpui.big_networks', false)))
{
	$SMARTY->assign('customerlist', $LMS->GetCustomerNames());
}
```

1. Ustawienie phpui.big_networks na true nie pokazuje listy klientów, która jest potrzebna do przypisywania lokalizacji do zgłoszeń w terminarzu.
2. Ile klientów trzeba mieć, żeby ustawić true dla big_networks?
3. Czy faktycznie jest potrzebny taki rozdział na małe i duże sieci w LMS?

**Comment by chilek** [comment]
Jest potrzebny. Wyobraź sobie, że masz 10 tys. klientów. Wtedy budowanie listy wyboru jest pozbawione sensu ze względu na obciążenie pamięci w przeglądarce i powolność działania takiej listy.
