### ISSUE TITLE
lms-payments.php

### ISSUE THREAD

**Issue by nicraMarcin** [lmsgit/lms#451]
Robi się coraz więcej pluginów. Niektóre z nich potrzebują wstawić coś "od siebie" co wiąże się nawet z kilkukrotnym przerabianiem.
Może dałoby się do tego kodu dorzucić hook'i?

**Comment by chilek** [comment]
Masz czas, żeby tym zająć się?

**Comment by nicraMarcin** [comment]
Na razie za mało mojej wiedzy :/

**Comment by chilek** [comment]
Jeden hook jakiś czas temu został dodany. Pozwala pluginom dodać swoje dodatkowe obciążenia.
