### ISSUE TITLE
Brak nr telefonu na karcie klienta

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#462]
Jesli po aktualizacji nie pokazuje się nr telefonu na karcie klienta to zapewne w tabeli customercontacts są wpisy z type=0

Szybki fix (na własną odpowiedzialność):
UPDATE customercontacts SET type=1 WHERE type=0

Zapewne problem pojawił się od czasu wprowadzenia w lib/definitions.php:
```
// Contact types
define('CONTACT_MOBILE', 1);
define('CONTACT_FAX', 2);
define('CONTACT_LANDLINE', 4);
define('CONTACT_EMAIL', 8);
define('CONTACT_INVOICES', 16);
define('CONTACT_NOTIFICATIONS', 32);
define('CONTACT_DISABLED', 64);
```

**Comment by chilek** [comment]
Dużo miałeś takich kontaktów?

**Comment by kyob** [comment]
Jak zrobiłem update to było coś około 2800 kontaktów.

**Comment by chilek** [comment]
To była dobra propozycja poprawki.
c76305807a4e530c50f5e151fb6ff2cdfe7920a3 rozwiązuje problem przy aktualizacji schematu bazy danych.

**Comment by chilek** [comment]
Oczywiście najlepiej wykonać zapytanie:
UPDATE customercontacts SET type = 4 WHERE type = 0;
bo z założenia kontakty wcześniej oznaczone przez 0 były kontaktami innymi niż komórkowe i faksy.
