### ISSUE TITLE
lms-teryt

### ISSUE THREAD

**Issue by nicraMarcin** [lmsgit/lms#469]
Witam
wcześniej tego nie zauważyłem, ale niektóre miejscowości wstawioane do bazy są dwukrotnie z innym cityid
SELECT * FROM location_cities WHERE name = 'Juliopol-Szosa'
lms=> select * from location_cities where name = 'Juliopol-Szosa';
  id   | ident  |      name      | cityid | boroughid 
-------+--------+----------------+--------+-----------
  5976 | 731880 | Juliopol-Szosa | 731850 |       315
 15062 | 731880 | Juliopol-Szosa |  15058 |       315
(2 wiersze)

lms=> select * from location_cities where ident = '731850';
  id   | ident  |   name   | cityid | boroughid 
-------+--------+----------+--------+-----------
 15058 | 731850 | Juliopol |        |       315
(1 wiersz)

lms=> select * from location_cities where ident = '15058';
 id | ident | name | cityid | boroughid 
----+-------+------+--------+-----------
(0 wierszy)

gdzie w pliku SIMC.xml występuje tylko raz
marcin@lms:_MLO-/tmp$ grep 'Juliopol-Szosa' SIMC.xml 
<col name="NAZWA">Juliopol-Szosa</col>

skąd w takim razie bierze się ten wpis?:
15062 | 731880 | Juliopol-Szosa |  15058 |       315

takich "zdublowanych" pozycji jest wiele, nie wszystkie ale jednak.

baza dla woj. mazowieckiego

**Comment by chilek** [comment]
#468 temporary fixes problem

**Comment by nicraMarcin** [comment]
ten request nie rozwiązuje podwójnego wstawiania do bazy
