### ISSUE TITLE
LMS Userpanel: rozdział finanse na finanse i taryfy

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#479]
Dla lepszej czytelności proponuje rozdział w userpanelu zakładki finanse na finanse oraz osobno taryfy.

Mogę przygotowac pull requesta.

PS: Jeśli przejdzie będzie mi łatwiej zrobić pulla dla nowej skórki.

**Comment by chilek** [comment]
Co na to inni?

**Comment by pjona** [comment]
Dla mnie ok.

**Comment by chilek** [comment]
Tylko czy konieczne jest rozbijanie na więcej zakładek, żeby wprowadzić nowy temat graficzny? Podaj jakieś racjonalne argumenty, które będą przekonywujące?

**Comment by kyob** [comment]
1. Mamy klientów z kilkunastoma, a nawet kilkudziesięcioma taryfami.
2. Aktualnie jest tak, że operacje finansowe są na jednej stronie. Co przy kilkuset lub więcej pozycji robi się dużo przewijania. Ostatecznie strona z finansami musi zakończyć się jakąś formą paginacji, bo pozycji co roku przybywa.

Można też rozważyć taki podział:
Informacje => dane osobowe + dokumenty
Taryfy => taryfy  + urządzenia
Finanse => operacja finansowe

Czasy jak było jedno urządzenie, jedna taryfa i 20 pozycji finansowych przy kliencie dawno mineły. Teraz tego jest dużo więcej i ciągle przybywa. Myślę, że warto rozważyć więcej pozycji w menu.

Poza tym nikt nie powiedział, że obecne menu nie możę być zmienione na coś praktyczniejszego, gdy przybędzie pozycji.

**Comment by chilek** [comment]
Ok brzmi rozsądnie. Poza tym łatwiej będzie modyfikować wydzielone listy w poszczególnych zakładkach userpanelu z poziomu pluginów.

**Comment by interduo** [comment]
+1

Dodatkowo boxa dokumenty i komputery też bym wyrzucił do swoich zakładek. Jeśli taryf jest dziesiątki to zapewne dlatego, że lokalizacji, usług i 'komputerów' jest dużo.

**Comment by kyob** [comment]
Pośrednio zrobione dla skórki BCLEAN.
