### ISSUE TITLE
Access level to LMSTcpdfBackend::Header() must be public (as in class TCPDF)

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#480]
Po zrobieniu pulla nie można otworzyć fv jako pdf.

``` PHP Fatal error:  Access level to LMSTcpdfBackend::Header() must be public (as in class TCPDF) in /var/www/lms/lib/LMSDocuments/LMSTcpdfBackend.php on line 35, referer: http://lms/?m=invoicelist ```

**Comment by chilek** [comment]
Czy commit e60f402a354ae25a919b1a10c97aff00eed2f932 poprawia to?

**Comment by kyob** [comment]
Zmiana z private na public dla LMSTcpdfBackend::Header() LMSTcpdfBackend::Footer() pomogła połowicznie. Teraz krzyczy 
``` PHP Fatal error:  Call to undefined method LMSTcpdfBackend::NewPage() in /var/www/lms/lib/LMSDocuments/LMSTcpdfBackend.php on line 57, referer: http://lms/?m=invoicelist ```

Sprawdzę dam znać.

**Comment by chilek** [comment]
Zobacz czy tym razem ten commit 11a7c647d89012f4895c8280cf4751fd44f34004 pomoże ;-) ?
Przy okazji: dzięki za testy backendu TCPDF!

**Comment by kyob** [comment]
Teraz działa.
