### ISSUE TITLE
ezpdf zamiast tcpdf

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#482]
Aktualnie korzystam z tcpdf, ale chciałem sprawdzić ezpdf, więc zmieniłem ```invoices.pdf_type``` na ```ezpdf```

**Czy to wystarczy, aby korzystać z ezpdf czy musze jeszcze coś zrobić?**

Teraz w logach mam takie coś:
```PHP Fatal error:  Uncaught exception 'Exception' with message 'Internal error - formatType is 0.0' in /var/www/lms/lib/ezpdf/include/TTF.php:617\nStack trace:\n#0 /var/www/lms/lib/ezpdf/include/TTFsubset.php(110): TTF->unmarshalPost()\n#1 /var/www/lms/lib/ezpdf/include/TTFsubset.php(58): TTFsubset->unmarshal('/var/www/lms')\n#2 /var/www/lms/lib/ezpdf/Cpdf.php(792): TTFsubset->doSubset('/var/www/lms', '?D?a?t? ?w?y?s?...', NULL)\n#3 /var/www/lms/lib/ezpdf/Cpdf.php(2608): Cpdf->o_font(8, 'out')\n#4 /var/www/lms/lib/ezpdf/Cpdf.php(2651): Cpdf->output()\n#5 /var/www/lms/lib/ezpdf/Cezpdf.php(1842): Cpdf->stream(Array)\n#6 /var/www/lms/lib/LMSDocuments/LMSEzpdfBackend.php(97): Cezpdf->ezStream(Array)\n#7 /var/www/lms/lib/LMSDocuments/LMSInvoice.php(64): LMSEzpdfBackend->WriteToBrowser('invoices.pdf')\n#8 /var/www/lms/modules/invoice.php(182): LMSInvoice->WriteToBrowser('inv in /var/www/lms/lib/ezpdf/include/TTF.php on line 617, referer: http://lms/?m=invoicelist```

**Comment by chilek** [comment]
Tak, działa w oparciu o backend ezpdf.
Na pewno masz najświeższą wersję z git?

Przy okazji: co pokazuje Ci:
ls -alR lib/ezpdf

Możliwe, że będzie jeszcze potrzebne dostawienie dla ezpdf gdzieś w którymś z plików:
https://github.com/lmsgit/lms/blob/master/lib/LMSDocuments/LMSEzpdfInvoice.php#L28

**Comment by kyob** [comment]
**ls -alR lib/ezpdf**
```
lib/ezpdf:
razem 268
drwxr-xr-x  4 www-data www-data   4096 paź 14 14:31 .
drwxr-xr-x 18 www-data www-data   4096 gru  9 13:08 ..
-rw-r--r--  1 www-data www-data  90266 paź 14 14:31 Cezpdf.php
-rw-r--r--  1 www-data www-data 159822 paź 14 14:31 Cpdf.php
drwxr-xr-x  2 www-data www-data   4096 paź 14 14:31 fonts
drwxr-xr-x  2 www-data www-data   4096 paź 14 14:31 include

lib/ezpdf/fonts:
razem 920
drwxr-xr-x 2 www-data www-data   4096 paź 14 14:31 .
drwxr-xr-x 4 www-data www-data   4096 paź 14 14:31 ..
-rw-r--r-- 1 www-data www-data 105008 paź 14 14:31 arial.afm
-rw-r--r-- 1 www-data www-data 105024 paź 14 14:31 arialbd.afm
-rw-r--r-- 1 www-data www-data 352224 paź 14 14:31 arialbd.ttf
-rw-r--r-- 1 www-data www-data 367112 paź 14 14:31 arial.ttf

lib/ezpdf/include:
razem 72
drwxr-xr-x 2 www-data www-data  4096 paź 14 14:31 .
drwxr-xr-x 4 www-data www-data  4096 paź 14 14:31 ..
-rw-r--r-- 1 www-data www-data 43088 paź 14 14:31 TTF.php
-rw-r--r-- 1 www-data www-data 17317 paź 14 14:31 TTFsubset.php```

**Comment by chilek** [comment]
Zawartości wyglądają ok.

**Comment by chilek** [comment]
Łukaszu, spróbuj jeszcze wyczyścić autoloader cache w katalogu cache lms-a. Może to pomóc.

**Comment by prezeskk** [comment]
U mnie tez ten sam blad w momencie uzycia ezpdf
System Slackware 12.2 (php 5.3.27)

**Comment by chilek** [comment]
Jesteście podesłać dokładny stack trace PHP bez zniekształcenia przez github?

**Comment by prezeskk** [comment]
[error.txt](https://github.com/lmsgit/lms/files/57209/error.txt)

**Comment by prezeskk** [comment]
[error.txt](https://github.com/lmsgit/lms/files/57212/error.txt)
Log php

**Comment by chilek** [comment]
[Wed Dec 09 18:42:33 2015] [error] PHP Fatal error:  Call to undefined function bcadd() in /usr/lms2/lib/ezpdf/include/TTF.php on line 1083, referer: https://lms2.drama.pl/?m=invoicelist
Doinstaluj/dokompiluj odpowiedni moduł php z obsługą bcadd().

**Comment by prezeskk** [comment]
Juz to zrobilem i wtedy pojawily sie bledy jak z pierwszego postu @kyob (ostatnie 2 linijki w zalaczonym pliku txt)

**Comment by chilek** [comment]
Czy problem występował przed ostatnimi aktualizacjami obsługi pdf?

**Comment by prezeskk** [comment]
Nie wiem :( musialbym sprawdzic ale to dopiero jutro

**Comment by kyob** [comment]
Ten sam problem miałem także tutaj: https://github.com/lmsgit/lms/issues/377

**Comment by chilek** [comment]
No to już wiemy, że to nie jest problem związany z ostatnimi dużymi zmianami w generowaniu dokumentów/faktur html/pdf.

**Comment by chilek** [comment]
Ciekawe z czego wynikają:
```
[Wed Dec 09 18:47:16 2015] [error] PHP Warning:  Division by zero in /usr/lms2/lib/ezpdf/Cpdf.php on line 1892
[Wed Dec 09 18:47:16 2015] [error] PHP Warning:  Division by zero in /usr/lms2/lib/ezpdf/Cpdf.php on line 1893
[Wed Dec 09 18:47:16 2015] [error] PHP Warning:  Division by zero in /usr/lms2/lib/ezpdf/Cpdf.php on line 1894
[Wed Dec 09 18:47:16 2015] [error] PHP Warning:  Division by zero in /usr/lms2/lib/ezpdf/Cpdf.php on line 1895
[Wed Dec 09 18:47:16 2015] [error] openFont: font file does not contain format 4 cmap
[Wed Dec 09 18:47:16 2015] [error] PHP Warning:  Division by zero in /usr/lms2/lib/ezpdf/Cpdf.php on line 1892
[Wed Dec 09 18:47:16 2015] [error] PHP Warning:  Division by zero in /usr/lms2/lib/ezpdf/Cpdf.php on line 1893
[Wed Dec 09 18:47:16 2015] [error] PHP Warning:  Division by zero in /usr/lms2/lib/ezpdf/Cpdf.php on line 1894
[Wed Dec 09 18:47:16 2015] [error] PHP Warning:  Division by zero in /usr/lms2/lib/ezpdf/Cpdf.php on line 1895
[Wed Dec 09 18:47:16 2015] [error] openFont: font file does not contain format 4 cmap
```

**Comment by chilek** [comment]
Może ktoś z Was jest w stanie dać mi dostęp ssh/http do maszyny na której występuje ten problem?

**Comment by prezeskk** [comment]
Jeszcze jeden test zrobilem i ustawilem w LMSEzpdfBackend.php $this->isUnicode = false;
Wygenerowalo pdf ale w srodku jest kaszana

**Comment by prezeskk** [comment]
Postawilem na szybko lms na debianie 8.2 i tu wszystko jest ok
Generuje sie faktura zarowno w ezpdf jak i w tcpdf
Bede drazyl dalej w czym jest problem

**Comment by chilek** [comment]
Czy czasem wszystkie opisywane problemy nie dotyczą Debiana? :)

**Comment by prezeskk** [comment]
Moze tak byc
Na slackware na konsoli mam znaki w iso-8859-2 a czy jest pelna obsluga utf-8 to nie wiem.
Zobacze na innej wersji slackware.
Natomiast na debianie 8.2 (z obsluga utf-8) nie ma problemow, wszystko dziala

**Comment by prezeskk** [comment]
Nowy slackware 14.1 tez dziala bez problemow

**Comment by chilek** [comment]
To wszystko wskazuje na upośledzoną obsługę UTF-8 w starszych dystrybucjach.
