### ISSUE TITLE
błąd w module ping.php

### ISSUE THREAD

**Issue by zajr** [lmsgit/lms#501]
Witam

W linii 44 pliku ping.php jest ustawiony moim zdaniem błędny parametr '-w':
$cmd = 'arping %i -c 1 -w 1.0';

Co daje 1ms - chyba że oczekujemy tak szybkich odpowiedzi ;)

Ustawienie '-W 1.0' załatwia sprawę.

Debian 8 3.16.0-4-amd64
ARPing 2.14, by Thomas Habets <thomas@habets.se>

**Comment by chilek** [comment]
Niestety używasz dystrybucji fabrycznie nie nadającej się na masową instalację na serwery bez zatrudnienia super fachowców. Pokazuję czym jest arping w normalnej dystrybucji:
RHEL/CentOS 6:
# arping -V
arping utility, iputils-sss20071127
RHEL/CentOS 7:
# arping -V
arping utility, iputils-s20121221
# arping -V
arping utility, iputils-s20140519

Tak, wiem że działa dystrybucja Debian na pralkach i lodówkach, tudzież żelazkach, ale to nie znaczy, że wszędzie zarządza się tym bez ciągłego "odkrywania koła na nowo" ;-)

**Comment by zajr** [comment]
Mówisz? ;)

4.0.5-gentoo:
arping utility, iputils-s20121221

"Gro i bucy" jak to mawiali starożytni jak i to że nie zawsze mamy to co lubimy... Co nie zmienia faktu że na Debianie się sypie, żadnego z nas wina że myśląc o żelazkach czy innych odkurzaczach zapomnieli o serwerach ;). Jedna linia kodu załatwia sprawę.

Ale z tą normalnością w przypadku Fedory to bym nie przesadzał :)

Pozdrawiam

**Comment by chilek** [comment]
E tam nic nie trzeba w kodzie zmieniać :)
https://github.com/lmsgit/lms/blob/master/modules/ping.php#L42
Widzisz? Tam jest uwzględniane ustawienie phpui.arping_helper, w którym możesz sobie zdefiniować dowolną komendę wykonującą arping...

**Comment by zajr** [comment]
No dokładnie ;). Hardcodowana komenda i wykluczający ją helper, dla którego config i tak trzeba sobie dodać ręcznie do phpui. Jedna linia i można by rozstrzał scalić tym bardziej że a. jak widać nie wszędzie działa b. część osób i tak ją będzie ozdabiać jakimś sudo czy innym zaklęciem ;)

**Comment by zajr** [comment]
Swoją drogą na Gentoo też wysyp:

arping: device (option -I) is required.

**Comment by zajr** [comment]
Tak to powinno wyglądać ;): 
arping %i -I %if -c 1 -w 1.0
