### ISSUE TITLE
 Fatal error: Call to undefined function bankaccount()

### ISSUE THREAD

**Issue by tudor2k3** [lmsgit/lms#518]
Hello,

   After upgrading today and clicking on a customer i get this error:

 Fatal error: Call to undefined function bankaccount() in /var/www/htdocs/lms/lib/LMSManagers/LMSCustomerManager.php on line 853

   Listing the invoices works, but trying to print one gives:

Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "/var/www/htdocs/lms/templates/default/invoice/invoice.html" on line 44 "{trans("Bank account:")} {format_bankaccount(bankaccount($invoice.customerid, $invoice.account))}" unknown function "bankaccount" <-- thrown in /var/www/htdocs/lms/lib/Smarty/sysplugins/smarty_internal_templatecompilerbase.php on line 44

   The old version of lms worked fine.
   I'm using gentoo linux with php 5.4 and apache 2.4

**Comment by chilek** [comment]
Hello, what does your phpui.lang set to?

**Comment by tudor2k3** [comment]
It was set to "ro-RO", which used to work before. I've deleted it and
now it works. Thanks. 

   But one more question: i want the interface to always be in romanian,
no matter the browser settings. In Firefox (linux and windows versions)
it's always in english, but in Chrome/Chromium it works correctly. What
am i missing? 

            Thank you. 

În 05.01.2016 19:08, Tomasz Chiliński a scris: 

> Hello, what does your phpui.lang set to? 
> 
> --
> Reply to this email directly or view it on GitHub [1].

  

Links:
------
[1] https://github.com/lmsgit/lms/issues/518#issuecomment-169084656

**Comment by chilek** [comment]
Try to set phpui.lang to:
ro

**Comment by tudor2k3** [comment]
Tried setting to "ro" or "pl", but only the currency changes. Everything
still in english. 

În 05.01.2016 21:10, Tomasz Chiliński a scris: 

> Try to set phpui.lang to:
> ro 
> 
> --
> Reply to this email directly or view it on GitHub [1].

  

Links:
------
[1] https://github.com/lmsgit/lms/issues/518#issuecomment-169117787

**Comment by chilek** [comment]
W dniu 05.01.2016 21:17, tudor2k3 napisał(a):
> Tried setting to "ro" or "pl", but only the currency changes.
> Everything
> still in english.

Set Romanian language as top preferred on in web browser. Then your user 
interface
should appear in your tongue-language ;-)

-- 
Pozdrawiam
Tomasz Chiliński, Chilan

**Comment by tudor2k3** [comment]
Alright, i've ALSO added "ro-RO' (first) to "intl.accept_languages" and it works now
