### ISSUE TITLE
Nie można zmieniać dni na liście w terminarzu

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#535]
Najnowszy LMS z git. Terminarz lista - nie działa zmiana dni nad filtrami.

Wstępnie wygląda na problem z GET i POST po ostatnich zmianch może nie wszystko zostało zmienione.

Problem jest tutaj linie 28-36: https://github.com/lmsgit/lms/blob/master/templates/default/event/eventlist.html

Zmiana dni leci jako GET, a reszta jako POST.

**Comment by chilek** [comment]
3201b1202e09f6f9e0276636b8e8199e0bc794d6 powinno rozwiązać problem.
Możesz potwierdzić?

**Comment by kyob** [comment]
Działa.
