### ISSUE TITLE
Terminarz: edycja powoduje wyzerowanie ID klienta

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#537]
Po zatwierdzeniu zmian w edycji zgłoszenia nie zapisuje się numer klienta i dostaje wartość 0.

Testowane na ostatniej wersji z git.

**Comment by chilek** [comment]
Chodzi o terminarz czy helpdesk?

**Comment by kyob** [comment]
Terminarz plik https://github.com/lmsgit/lms/blob/master/templates/default/event/eventedit.html linia 130 powinno czy tam nie powinno być: 
```
inputname="event[customerid]"
``` 
zamiast
```
inputname="event[custid]"
```

**Comment by chilek** [comment]
Czy c737a55cca4e731bcca540a5734893ff06090443 rozwiązuje problem?

**Comment by kyob** [comment]
Działa.
