### ISSUE TITLE
Terminarz zdarzenia otwarte/zamknięte

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#538]
Czy nie można było zostawić domyślnie pokaż wszystkie https://github.com/lmsgit/lms/commit/0fb35584fefe3db1ad2cf48edb13baf7501fd2fa?

 
U nas BOK i technicy twierdzą, że jak nie widzą wszystkiego to nie ma pełnego obrazu sytuacji.

**Comment by chilek** [comment]
Może warto opcję konf. wprowadzić, która będzie to określać?

**Comment by chilek** [comment]
Zmieniłem na rozwiązanie trójstanowe - powinno wszystkim odpowiadać ;-)
