### ISSUE TITLE
Problem z szablonami w LMS

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#547]
Przykładowo mam nowy katalog w ``templates/nowyszablon`` w nim jest:
``welcome/welcome.html`` wprowadzone zmiany są widoczne, ale wszystko co jest includowane w pliku ``welcome.html`` np.
```
{include file="welcome/welcome_links.html"}
```
nie działa i ładuje pliki z domyślnego szablonu ``default``

Mam ustawione: ``phpui.custom_templates_dir=nowyszablon``

UPDATE: Szablony działają, jeśli dodam przedrostek nazwy szablonu
```
{include file="nowyszablon/welcome/welcome_links.html"}
```

Tak to ma działać?

**Comment by chilek** [comment]
Dnia 17 stycznia 2016 00:01:26 CET, "Łukasz Kopiszka" <notifications@github.com> napisał(a):
>Przykładowo mam nowy katalog w ``templates/nowyszablon`` w nim jest:
>``welcome/welcomehtml`` wprowadzone zmiany są widoczne, ale wszystko co
>jest includowane w pliku ``welcomehtml`` np
>```
>{include file="welcome/welcome_linkshtml"}
>```
>nie działa i ładuje pliki z domyślnego szablonu ``default``
>
>Mam ustawione: ``phpuicustom_templates_dir=nowyszablon``
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/lmsgit/lms/issues/547

Jak wygląda struktura katalogów i plików w *nowyszablon*?
--
Pozdrawiam z Samsung Galaxy Note 4
Tomasz Chiliński, Chilan

**Comment by kyob** [comment]
```cp -pr templates/default templates/nowyszablon```

**Comment by chilek** [comment]
Możesz spróbować wykonać test z lms z gałęzi **smarty-3.1.29**?
Przed chwilą puściłem pierwszy commit:
https://github.com/lmsgit/lms/commit/145bc4fd54b3c49d94016500b4e585bb1ec34be0
w tej nowo utworzonej gałęzi i jest spora szansa, że 3.1.29 rozwiąże opisywany przez Ciebie problem, a na pewno rozwiąże problem z rozpoznawaniem zmian w szablonach spowodowanym przez zastosowanie ze smarty 3.1.27 prefiltru, który był konieczny, a w 3.1.29 nie powinien już być potrzebny.

**Comment by kyob** [comment]
Teraz domyślny dzablon nie ładuje podstron. Jakby to miało znaczenie testuje z PHP 5.5.9

**Comment by chilek** [comment]
1) Masz aktywne jakieś wtyczki? Jeśli tak to spróbuj tymczasowo wyłączyć.
2) Wyłącz własny katalog szablonów i wtedy zobacz co wyświetli domyślny szablon.

**Comment by prezeskk** [comment]
Potwierdzam ze tez pusta strona (znaczy sie jest tylko menu i naglowek bez srodka)
Najnowszy slackware 14.1 czysta testowa instalacja bez zadnych zmian

**Comment by chilek** [comment]
Sprawdzę dziś na wersji demo.

**Comment by kyob** [comment]
1) Brak wtyczek czyste repo.
2) Domyślny szablon nie działa tylko głowna strona (lewe menu, gorny toolbar i inputy do szukania). Nie ładuje żadnych includowanych podstron.
3) Brak błedów ```error_reporting = E_ALL```

**Comment by prezeskk** [comment]
To samo u mnie

**Comment by chilek** [comment]
@kyob: a Ty jakiej dystrybucji używasz? ;-)

**Comment by kyob** [comment]
Testuje na Ubuntu 14.04.3 LTS :-)

**Comment by chilek** [comment]
A nie pisałem wiele razy, że Slackware i wszelkie pochodne Debiana to nie dystrybucje? :D

**Comment by prezeskk** [comment]
Sprawdzam na 2gim systemie testowym
Debian 8.2
PHP: 5.6.14
Apache: 2.4.10
MySQL: 5.5.46

**Comment by prezeskk** [comment]
Nigdy wczesniej problemow nie bylo ze Slackware

**Comment by chilek** [comment]
Hehe, przecież żartuję - to nie problem z dystrybucją - na demo też jest problem i siedzę właśnie nad tym. Prawdopodobnie kolejny błąd w Smarty ;-)

**Comment by chilek** [comment]
Przygotowałem demonstrację problemu i wskazałem ją Uew Tews ze Smarty:
https://github.com/smarty-php/smarty/issues/123#issuecomment-172532910

**Comment by nicraMarcin** [comment]
Tomku, ten wątek w smarty jest zamknięty :/

**Comment by chilek** [comment]
WIem o tym - od dawna jest zamknięty, ale jak Uwe ma wolną chwilę to do niego zagląda.

**Comment by chilek** [comment]
Na wszelki wypadek utworzyłem nowe zgłoszenie:
https://github.com/smarty-php/smarty/issues/183

**Comment by chilek** [comment]
Wygląda na to, że problem rozwiązany. Można testować zmiany w gałęzi **smarty-3.1.29** (na demo działa). Jutro zaciągnę zmiany z tej gałęzi do **master**.

**Comment by prezeskk** [comment]
Potwierdzam dzialanie ;]
Co do czasow generowania musze porobic troche testow ale na pierwszy rzut oka wyglada na to ze dziala szybciej

**Comment by kyob** [comment]
`PHP Fatal error:  Class 'Smarty_Internal_Undefined' not found in /var/www/lms/lib/Smarty/sysplugins/smarty_internal_extension_handler.php on line 154 `

**Comment by pjona** [comment]
My też potwierdzamy działanie Smarty 3.1.29 z naszymi pluginami, po drobnych poprawkach.

**Comment by chilek** [comment]
Tak - w pluginach trzeba będzie usunąć wszystkie:
```smarty
{extends file="nazwa_pliku_z_szablonem"}
```
w przypadku, gdy **nazwa_pliku_z_szablonem** jest taka sama jak sam plik w którym to występuje.

**Comment by pjona** [comment]
Dokładnie.
