### ISSUE TITLE
Błędne obliczenia na fakturach

### ISSUE THREAD

**Issue by zajr** [lmsgit/lms#559]
Witam

Błąd polega na błędnych obliczeniach wartości netto przy dodawaniu pozycji do faktury jeżeli podawana ilość nie jest liczbą całkowitą.

Przykład:
ilość: 24948,04
cena jedn: 0,9 
rabat: brak
wynik:
wartość netto: 22407,04
a powinno być (po zaokrąglniu): 22453,24 

Błąd się pojawia na różnych wersjach LMSa

Pozdrawiam
Rafał Zając

**Comment by chilek** [comment]
Wykonuję test tego co opisujesz i jak widać na zrzucie ekranu:

![zrzut ekranu z 2016-01-22 14-11-31](https://cloud.githubusercontent.com/assets/1457437/12511531/396d5dbe-c112-11e5-9193-37fa0dc95560.png)

**Comment by zajr** [comment]
Jak pisałem wyżej - chodzi o stawki netto
cena jednostkowa netto - 0,90

![bug](https://cloud.githubusercontent.com/assets/10605009/12511796/734f7088-c114-11e5-9232-1d66ab63c3ea.png)

**Comment by chilek** [comment]
LMS przelicza najpierw cenę jednostkową na brutto, a potem przemnaża przez liczbę sztuk.

**Comment by zajr** [comment]
To czym w LMSie jest "Wartość netto"? Bo ta wartość jest ewidentnie błędna
24948,04*0,9 nie jest równe 22407,04

**Comment by chilek** [comment]
0.9 * 1.23 = 1.11
1.11 * 24948.04 = 27692.32

**Comment by chilek** [comment]
Czy Twoim zdaniem dla wyliczania sumy brutto na podstawie netto dla pozycji powinno być:
(cena_jedn_netto * ilość)  + VAT
bo w tej chwili jest:
(cena_jedn_netto + VAT) * ilość

**Comment by zajr** [comment]
Moim zdaniem
Cena jednostkowa netto * ilość = wartość netto

**Comment by zajr** [comment]
A wyliczenia dla sumy brutto (cena_jedn_netto + VAT) * ilość 

Ale nie o to mi chodzi...
Chodzi o to że na fakturach jest błędna wartość netto

**Comment by chilek** [comment]
Twoje problemy wynikają z tego, że próbujesz wpisywać przez netto, a LMS operuję na brutto.

**Comment by chilek** [comment]
Wpisz po prostu przez brutto towar.

**Comment by repcio** [comment]
Ten "błąd" występuje w LMS od zawsze. Przepisy MF dopuszczają obydwie formy wyliczania kwoty netto.
Trzeba poszukać, ale ten wątek AFAIR był już poruszany na liście mailingowej wieki temu.
IMHO (i zgodnie z przepisany) - nie ruszać :D

**Comment by zajr** [comment]
Przepisy dopuszczają obydwie formy - ok. Czyli wpisując tylko w 'valuenetto' cenę netto oraz wysokość podatku wszystkie kwoty na fakturze będą prawidłowe?

**Comment by zajr** [comment]
@chilek ja nie próbuję wpisywać przez netto. Po prostu wprowadzam konkretną dane do formularza, który umożliwia mi wprowadzenie tejże danej. Jeżeli na jej podstawie obliczenia wychodzą błędne tzn. że jest to Błąd a nie "błąd"

**Comment by zajr** [comment]
Witam.
Są jakieś szanse na to aby coś w tym temacie było ruszone?

**Comment by chilek** [comment]
Po co liczysz w oparciu o netto?
Naprawienie tego wymagałoby trzymanie nie cen jednostkowych w bazie danych, a cen sumarycznych (po wymnożeniu ceny jednostkowej przez liczbę sztuk)

**Comment by zajr** [comment]
Jak najbardziej cen jednostkowych tyle tylko że cen netto również a nie tak jak jest aktualnie (wyłącznie ceny brutto) i wykorzystanie ich do obliczeń zamiennie, na podstawie tego które pole zostanie wypełnione w formularzu.

Na ten błąd zwrócił mi uwagę klient, który ma w zwyczaju dogadywać się po cenach netto ze swoimi kontrahentami.

**Comment by chilek** [comment]
W samym formularzu faktury da się to poprawić, ale zmiana sposobu przechowywania operacji finansowych w bazie danych to potężna zmiana...

**Comment by zajr** [comment]
A gdyby tak dodać dodatkowe dwa pola (w invlocecontents lub cash): 1 - jednostkowa cena netto, 2 - int określający to która z cen powinna być brana pod uwagę podczas obliczen. Pozostała by kwestia modyfikacji funkcji które które obliczają vat, lub zastosowanie wbudowanych funkcji sql do tego celu.

**Comment by chilek** [comment]
To co jesteś chętny, żeby to zrobić wszędzie, gdzie to potrzebne w kodzie LMS i podeślesz pull requesta?

**Comment by zajr** [comment]
Jestem ale musiałbyś udostępnić mi dokumentację, w której znajdę szczegółowy schemat działania mechanizmu obsługi płatności w LMS, żebym mógł się skupić na zmianach a nie dochodzeniu do tego co gdzie i po co się znajduje.

**Comment by chilek** [comment]
Hehe no tak - jak by ktoś mnie za rączkę poprowadził to bym nie proponował przerobienia ;-)
Trzeba trochę poczytać o git + poszperać w kodzie źródłowymi. Znasz mysql/postgresql, PHP, Smarty, trochę html i css?

**Comment by chilek** [comment]
Wiesz co w sumie to mogę spróbować wykonać tą zmianę za 300 zł.

**Comment by zajr** [comment]
Uważasz że zapytanie o udostępnienie dokumentacji wolnej aplikacji jednego z jej głównych programistów jest próbą wymuszenia czegoś co pieszczotliwie nazywasz "prowadzenia za rączkę"? :) Jeżeli miałbym poświęcać swój czas na usuwanie istotnych błędów, na które przymykasz oko to wolałbym nie stawać przed koniecznością analizowania tego co autor miał na myśli w sytuacji gdy autor stoi obok mnie - to jest chyba oczywiste tym bardziej że sam twierdzisz że jest to potężna zmiana. 

Mówisz 300zł... To ja mam dla Ciebie inną propozycję - skoro nie jesteś chętny do tego aby kogokolwiek "prowadzić za rączkę" to sam wprowadzę dla Ciebie tą potężną zmianę ale za 3000zł co z punktu widzenia potężnych zmian jest kwotą optymalną. Z pewnością skorzysta na tym Twój komercyjny projekt, mój klient będzie zadowolony i wszyscy będziemy mogli dalej udawać że błąd w gicie to tylko urojenia :)

**Comment by chilek** [comment]
No tak i dochodzimy do poziomu dyskusji jaka w większości sytuacji ma miejsce wokół polskich projektów open source....

**Comment by zajr** [comment]
Czyli jakiej? Taki że osoby do których kierowane są te projekty mają wyłącznie teoretyczną możliwość zgłaszania uwag, a Ci którzy chcą coś dla projektu zrobić nie mają prawa wymagać jakiejkolwiek pomocy od jego opiekunów chyba że ich sobie wynajmą? Bo jeśli tak to w 100% się z Tobą zgadzam.

**Comment by chilek** [comment]
Słuchaj wymagać nigdy nie masz prawa, możesz jedynie prosić kogoś o coś i jak ten ktoś ma czas to może pomóc. Przeczytaj to co sam napisałeś za jakiś tydzień to może zrozumiesz o co chodzi.

Póki co napisz na listę mailingową - może ktoś znajdzie wolny czas lub ktoś już rozwiązał Twój problem (podkreślam Twój) i podzieli się z Tobą rozwiązaniem.

**Comment by zajr** [comment]
Sprowadziłeś moją prośbę o pomoc do rangi prowadzenia za rączkę więc jaki jest sens takich próśb? A co do wymagań to uważam że podejmując się jakiegokolwiek projektu, nie istotne czy komercyjnego czy opensourcowego, bierzesz za niego w pewnym sensie odpowiedzialność i powinieneś mieć na względzie to że nie tylko własne wymagania popychają te projekty do przodu  - to miałem na myśli i tego część osób  nie potrafi zrozumieć.

Wracając do tematu. Może by na czas wdrożenia rozwiązania uniemożliwić wprowadzanie danych w to konkretne pole ponieważ może one być powodem błędnych obliczeń na fakturach?

**Comment by misiek08** [comment]
Błędne wyniki w LMSie wywodzą się z zaokrąglania. Przy podanej cenie netto 0.9zł, cena brutto to z matematycznego punktu widzenia 0.972zł, co przemnożone przez ilość daje wynik o ok. 50zł wyższy niż na 2 screenie. 

Błędy wynikają tutaj zatem tylko z zaokrąglania i dlatego przeniosłem 2 firmy na własne rozwiązanie z takich powodów, gdzie po raz kolejny opiekun LMSa zamiast przyjąć "na klatę" swój błąd, twierdzi, że wszystko jest ok i to jest "błąd" konkretnego użytkownika. To właśnie są realia polskiego światka open source, a dyskusje powyżej to po prostu zlecenia i to jest zrozumiałe, że nikt za darmo nie będzie czegoś robił, bo musi. 

@chilek piękny projekt, kod trochę słabszy, ale podejście... Tutaj liczenie tych kwot to ewidentny błąd i w mojej opinii tak może zostać i nie musisz tego poprawiać (możesz, jeśli znajdziesz na to czas i chęci, ale nie musisz), musisz jedynie zrozumieć, że błąd jest i to konkretny. Przy większej ilości i dobrze dobranej cenie błędy są tak duże, że to już zakrawa o kabaret.

**Comment by chilek** [comment]
@misiek08: no widzisz - dzięki temu błędowi jest zapotrzebowanie na Twój produkt, którego nie robisz za darmo? A jest on chociaż na licencji GPL? :D

**Comment by misiek08** [comment]
No właśnie zapotrzebowanie nie, a raczej gwarancja, której musiałem udzielić za darmo. Wykorzystałem LMSa, a potem pisałem skrypty konwertujące dane na inną strukturę bazy danych, żeby jakoś się z tego wyplątać (pomijam pisanie we 2 całego nowego systemu...)

**Comment by chilek** [comment]
@misiek08: no to ładnie. To możesz jeszcze wskażesz, gdzie napisałem, że to "nie jest błąd i stwierdziłem, że wszystko jest ok, a to jest "błąd" konkretnego użytkownika."? Uwielbiam takich manipulantów :D

**Comment by chilek** [comment]
https://github.com/chilek/lms-plus/commit/eaf49b9334ab15c331cf636187f3a22206e686f9 rozwiązuje problem (na razie w tymczasowej gałęzi netto-to-brutto-fix ze względu na dużą inwazyjność zmiany).
