### ISSUE TITLE
Problem ze świeżą instalacją

### ISSUE THREAD

**Issue by barthekk** [lmsgit/lms#564]
Witajcie, mam spory problem a zaraz głowa mi eksploduje. Zainstalowałem z gita lms za pomocą git clone, skonfigurowałem bazę itd. Natomiast dostaję białą stronę za każdym razem po próbie odpalenia lms, tylko wersja 1.11.15 mi działa, wszystkie kolejne mają efekt białej strony. A logach apacza  mam:

PHP Catchable fatal error:  Argument 1 passed to ConfigLoader::parseRawConfig() must be of the type array, null given, called in /var/www/html/lms/lib/LMSConfig/ConfigLoader.php on line 51 and defined in /var/www/html/lms/lib/LMSConfig/ConfigLoader.php on line 105

Czy może mnie ktoś nakierować co zrobiłem źle ?
Linux localhost 3.16.0-4-586 #1 Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17)

**Comment by maciejlew** [comment]
Wygląda na złą ścieżkę do lms.ini

**Comment by barthekk** [comment]
Już ogarnąłem, ścieżka była poprawna natomiast po poprawie 3 linii w lms.mysql zaczęło wszystko działać. Bez dołożenia jednej kolumny nie chciało zadziałać.
('phpui', 'quicksearch_limit', '15', 0),
('mail', 'backend', 'pear', 9),
('mail', 'smtp_secure', 'ssl', 10),

**Comment by kyob** [comment]
https://github.com/lmsgit/lms/pull/596 rozwiązuje problem

**Comment by aporiapl** [comment]
Rozumie że ten problem został rozwiązany i w najnowszej wersji z git-a nie powinien wystąpić ?  Zrobiłem kopie z panelu, odtworzyłem dzień później i dostaje właśnie ten komunikat na każdej liście (faktur, klientów, itd ) : 
Catchable fatal error: Argument 1 passed to ConfigLoader::parseRawConfig() must be an array, null given, called in /var/www/lms/lib/LMSConfig/ConfigLoader.php on line 51 and defined in /var/www/lms/lib/LMSConfig/ConfigLoader.php on line 105
