### ISSUE TITLE
lms-sendinvoices.php bug?

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#569]
Ostatnia wersja z GIT klienci dostają na maila faktury swoje oraz od innych klientów.

Szybki test:
w lms.ini ustawic debug_mail oraz uruchomić skrypt u mnie w załącznika kilka faktur od różnych klientów

Jeszcze nie miałem czasu na głębszą diagnozę.

**Comment by pjona** [comment]
Poprawka już jest w masterze

**Comment by kyob** [comment]
Uff to dobrze, bo zbliżała się masowa wysyłka maili i bylby młyn :>

**Comment by chilek** [comment]
Hehe - jak się używa master to przynajmniej spać się nie chce ;-D

**Comment by kyob** [comment]
No risk no fun :)
