### ISSUE TITLE
Typy dokumentów

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#575]
Brakuje mi:
1. Promocja
2. Cennik
3. Gwarancja
4. Zawieszenie czasowe usługi

**Co jeszcze można dodać, bo jak znajdę czas zrobię commita?**

Czy dobrym pomysłem jest rozbicie `DOC_CONTRACT` na drobnicę np:
1. Umowa Internet
2. Umowa telewizja
3. Umowa telefon
4. Umowa monitoing
5. Umowa Internet z telewizja
6. Umowa Internet z telefonem
[...]

**Pytam mądrzejsze głowy czy takie zmiany mają rację bytu?**

**Comment by chilek** [comment]
Rozbicie DOC_CONTRACT moim zdaniem lepiej nie robić.
Co do brakujących typów - ogólnie ma to sens tylko czy Promocja to nie Regulamin usługi?

**Comment by kyob** [comment]
Pytanie jaką drogę wybrać, bo chciałbym móc listować umowy typu: internet, telefon, telewizja, internet z telewizją, itp.

**Comment by chilek** [comment]
'type' => DOC_CONTRACT
i w każdym szablonie inna nazwa umowy.

**Comment by kyob** [comment]
Ponawiam pytanie czy będzie zielone światło na zwiększenie ilości typów o m.in.:
1) promocja
2) cennik
3) gwarancja
4) regulamin

Przeglądanie długiej listy zaczyna być uciążliwe :)

**Comment by chilek** [comment]
Chodzi o dodatkowe typy dokumentów, żeby nie używać dla nich DOC_OTHER?

**Comment by kyob** [comment]
Tak.

**Comment by chilek** [comment]
Dodawaj - masz zielone światło.

**Comment by kyob** [comment]
https://github.com/lmsgit/lms/commit/568b4ab4f5a284b5210dd4222b0b6f401c0fb2a3
