### ISSUE TITLE
Problem po commicie 179ffdeee3f3e080240c7710fd5b301a90565fbc

### ISSUE THREAD

**Issue by prezeskk** [lmsgit/lms#583]
Po commicie 179ffdeee3f3e080240c7710fd5b301a90565fbc mam w logach taki blad:
PHP Fatal error:  Arrays are not allowed in class constants in /usr/lms2/lib/Session.class.php on line 30

**Comment by prezeskk** [comment]
Moze to tak poprawic zeby dzialalo z php 5.3 ?

[Session.class.php.diff.txt](https://github.com/lmsgit/lms/files/117017/Session.class.php.diff.txt)

**Comment by chilek** [comment]
W dniu 04.02.2016 08:51, Krzysztof Kulesza napisał(a):
> Moze to tak poprawic zeby dzialalo z php 5.3 ?
> 
> Session.class.php.diff.txt [1]

Już poprawione.
Sprawdź.

-- 
Pozdrawiam
Tomasz Chiliński, Chilan

**Comment by prezeskk** [comment]
W dniu 04-02-2016 o 12:45, Tomasz Chiliński pisze:
> W dniu 04.02.2016 08:51, Krzysztof Kulesza napisał(a):
> > Moze to tak poprawic zeby dzialalo z php 5.3 ?
> >
> > Session.class.php.diff.txt [1]
>
> Już poprawione.
> Sprawdź.
>
> -- 
> Pozdrawiam
> Tomasz Chiliński, Chilan
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/lmsgit/lms/issues/583#issuecomment-179785327>.
>
Dziala

-- 
Krzysztof Kulesza
