### ISSUE TITLE
heldesk - nie działają załączniki

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#594]
Najnowszy LMS z GIT. 

HELPDESK robię zgłoszenie i dodaję załączniki. Klikam zapisz i załącznika ni widu ni słychu.

W logach mam tylko: 
```
PHP Strict Standards:  Only variables should be assigned by reference in /var/www/lms/lib/LMS.class.php on line 1614, referer: http://192.168.12.2/userpanel/?m=helpdesk ```

**Comment by chilek** [comment]
Z tego co widzę powyżej chodzi o załączniki dodawane do zgłoszenia z userpanel?

**Comment by chilek** [comment]
Jaki temat graficzny używasz dla userpanel?

**Comment by kyob** [comment]
Tak  zgłoszenia z userpanel z domyślnym tematem graficznym.

**Comment by chilek** [comment]
Co prawda test wykonałem przed chwilą z 'blcean', ale działa, więc nie potwierdzam problemu.

**Comment by kyob** [comment]
OK w takim razie musze szukać problemu u siebie.

**Comment by kyob** [comment]
Co trzeba ustawić z opcji konfiguracyjnych, aby załączniki działały? 

Aktualnie maile wysyła i załączniki zapisuje na dysku. Jednakże maile przychodzą bez załącznika i w heldesku także brak odnośnika do załącznika. 

Chyba stoję pod latarnia i nic nie widzę.

**Comment by chilek** [comment]
**rt.mail_dir**

**Comment by kyob** [comment]
Na świeżutkiej instalacji załączniki działają poprawnie. Szukam dalej.

**Comment by kyob** [comment]
Plik: lms/userpanel/modules/helpdesk/functions.php 

Wstaiłem w linię [170](https://github.com/lmsgit/lms/blob/master/userpanel/modules/helpdesk/functions.php#L170)
```$testmsgid = $DB->GetLastInsertID('rtmessages');```

Następnie porównałem wynik z linią [176](https://github.com/lmsgit/lms/blob/master/userpanel/modules/helpdesk/functions.php#L176)

```$testmsgid != $msgid```
**$testmsgid** - wskazywał na lastinsertedid rtmessages, czyli poprawnie
**$msgid** - wskazywał na lastinsertedid rtticketcategories, czyli niepoprawnie

Pytanie czy [foreach](https://github.com/lmsgit/lms/blob/master/userpanel/modules/helpdesk/functions.php#L171) nie powienien być za [if](https://github.com/lmsgit/lms/blob/master/userpanel/modules/helpdesk/functions.php#L175)
