### ISSUE TITLE
problem z checkPrivalage

### ISSUE THREAD

**Issue by wawryk** [lmsgit/lms#604]
Będąc superuserem i mając zaznaczoe ukrywanie użytecznych linków one i tak nie znikają.
Czy w funkcji:
```php
public static function checkPrivilege($privilege, $checkIfSuperUser = true) {
		if ($checkIfSuperUser && self::checkConfig('privileges.superuser'))
			return preg_match('/^hide_/', $privilege) ? false : true;
		return self::checkConfig("privileges.$privilege");
	}
```
nie powinniśmy dodać jakieś opcji aby nawet superuserowi móc ukryć to ??

**Comment by wawryk** [comment]
Jak wywołuje tą funkcję z drugim parametrem false to działa dobrze, ale czy nie można by tego jakoś zrobić z configu ?

**Comment by chilek** [comment]
Hmmm trudno powiedzieć. Trzeba by zobaczyć co inni o tym myślą.

**Comment by pjona** [comment]
Potwierdzam, coś to nie działa.

@chilek: potwierdzasz to na demo? Musisz mieć pełne uprawnienia i zaznaczone "ukryte użyteczne linki".

Trzeba chyba dodać np. jak teraz mamy warunek:

`{if !ConfigHelper::checkPrivilege('hide_links')}`

to trzeba zmieniać na

`{if !ConfigHelper::checkPrivilege('hide_links', false)}`

rozwiązuje to problem, ale nie jestem pewny czy taki był pomysł na tą zmienną `$checkIfSuperUser`

**Comment by chilek** [comment]
Jeśli to ma wyłączać zakładki nawet dla superusera to oczywiście, że trzeba dać drugi parametr false, ale moim zdaniem podpinanie uprawnień w taki sposób, że dotyczą również superusera to nie jest dobry pomysł...

**Comment by pjona** [comment]
A jak to widzisz?

**Comment by chilek** [comment]
Jeśli to miałoby być ukrywane dla superusera to chyba boksy z planszy tytułowej poiwinny mieć obsługę "zwijalności/rozwijalności" podobnie jak inne karty we właściwościach poszczególnych zasobów w lms.
Jako, że obecnie zwijalność jest zapamiętywana we właściwościach użytkownika, a nie sesji to zwinięcia można uczynić stałymi.

**Comment by wawryk** [comment]
https://github.com/lmsgit/lms/pull/653
mój pull request dodaje opcje zwijalności/rozwijalności do 4 elementów ze strony głównej, które zajmują dużo miejsca, a mało kto z nich korzysta
