### ISSUE TITLE
Font-awesome zamiast ikonek gif?

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#617]
Co myślicie, aby zastąpić gify ikonami z font-awesome.

Można to wrzucić do composera `components/font-awesome`

**Comment by chilek** [comment]
Jaką mają licencję?

**Comment by kyob** [comment]
Jak to dołączyć - brutalnie czy jest inne lepsze rozwiązanie?
` <link rel="stylesheet" href="vendor/components/font-awesome/font-awesome.css">`

**Comment by chilek** [comment]
Zapewne w header.html.

**Comment by misiek08** [comment]
Licencja [tutaj](https://fortawesome.github.io/Font-Awesome/license/), darmowa do użytku komercyjnego. Dodatkowo od wersji 3 nie wymagają wspominania i ich używaniu:
```
Attribution is no longer required as of Font Awesome 3.0 but is much appreciated
```

**Comment by chilek** [comment]
@misiek08 już znalazłem wcześniej. A gdzie tam jest napisane, że darmowa? Możesz przytoczyć cytat?

**Comment by misiek08** [comment]
Na stronie głównej
```
Font Awesome is completely free for commercial use. Check out the license. 
```
ale sprawdziłem dokładnie, żeby nie wprowadzać błąd i kod jest na licencji MIT (totalnie darmowa, bez gwarancji, ale też bez ograniczeń, a same ikonki na [SIL OFL](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL), które ma w pierwszej linii
```
The SIL Open Font License (OFL) is a free, libre and open source license specifically designed for fonts and related software based 
```

**Comment by chilek** [comment]
@misiek08 Chłopie kiedy się przestaniesz się wymądrzać, a zaczniesz czytać co znaczy free w GPL? :)

**Comment by chilek** [comment]
@misiek08 na początek polecam: https://pl.wikipedia.org/wiki/GNU_General_Public_License (nota bene ani razu słowa darmowe/darmowy ;-))

**Comment by misiek08** [comment]
GPL? Gdzie przy Font-Awesome jest GPL?

Znowu docinki z wymądrzaniem się. Chyba naprawdę nie przestanie mnie to śmieszyć.

**Comment by chilek** [comment]
@misiek08 po co w ogóle tu piszesz, mądrzysz się przed każdym. Zamiast tracić czas na siedzenie na czatach typu randka.pl lepiej zrób coś konkretnego chłopie...

**Comment by chilek** [comment]
http://fotka.com/profil/Misiek08

co za "słit-focie". Coś kiepska średnia ocen ... Hehe...

**Comment by misiek08** [comment]
No przecież nie ma żadnego GPL przy FA....

Ufff, dobrze że to nie mój profil.

**Comment by nicraMarcin** [comment]
Wracając do tematu. Jestem za

**Comment by kyob** [comment]
https://github.com/lmsgit/lms/commit/e737fcf357517184bdf52c9a41bc79c6a8ec699e
