### ISSUE TITLE
LMS modyfikacja i instalacja

### ISSUE THREAD

**Issue by tomekbrydak** [lmsgit/lms#626]
Witam
Nie wiem czy do dobrej grupy piszę ale jednak spróbuję.

Zlecę instalację i wykonanie kilku modyfikacji w LMS.
Ogólnie chodzi o dodanie modułu odsetek oraz usunięciu kilku niepotrzebnych rzeczy i poukładania żeby jakoś ładnie wyglądało.

**Comment by gavron7** [comment]
Mogę się podjąć pisz na gavron@toya.net.pl
