### ISSUE TITLE
Problem z aktualizacją bazy postgress z LMS_011117 do master z 15.02.1016  

### ISSUE THREAD

**Issue by alkar1** [lmsgit/lms#630]
Przy pierwszym odpaleniu nowej wersji mam log postgres-sql-9.1:
`2016-02-15 16:34:33 CET DZIENNIK:  niekompletny pakiet uruchomieniowy
2016-02-15 22:37:15 CET BŁĄD:  błąd składni w lub blisko "=" przy znaku 23
2016-02-15 22:37:15 CET WYRAŻENIE:  UPDATE customers SET  = '373' WHERE id = NULL
2016-02-15 22:37:15 CET BŁĄD:  bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji
2016-02-15 22:37:15 CET WYRAŻENIE:  UPDATE customers SET street = 'ul. Wiślisko' WHERE id = '8'
2016-02-15 22:37:15 CET BŁĄD:  bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji
2016-02-15 22:37:15 CET WYRAŻENIE:  UPDATE customers SET street = 'ul. Marczyńskiego', building = '1', apartment = '33' WHERE id = '10'
2016-02-15 22:37:15 CET BŁĄD:  bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji
2016-02-15 22:37:15 CET WYRAŻENIE:  UPDATE customers SET street = 'ul. Czerwone Maki', building = '59', apartment = '34' WHERE id = '455'
2016-02-15 22:37:15 CET BŁĄD:  bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji
2016-02-15 22:37:15 CET WYRAŻENIE:  UPDATE customers SET street = 'ul. Pilotów', building = '81', apartment = '46' WHERE id = '324'
2016-02-15 22:37:15 CET BŁĄD:  bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji`
I tak dalej do końca bazy.
Jak najszybciej znaleźć błąd ?

Linux vdebian 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u2 x86_64 GNU/Linux
PHP Version 5.4.45-0+deb7u2

**Comment by chilek** [comment]
W dniu 18.02.2016 16:50, alkar napisał(a):
> Przy pierwszym odpaleniu nowej wersji mam log postgres-sql-9.1:
> 2016-02-15 16:34:33 CET DZIENNIK: niekompletny pakiet uruchomieniowy
> 2016-02-15 22:37:15 CET BŁĄD: błąd składni w lub blisko "=" przy
> znaku 23
> 2016-02-15 22:37:15 CET WYRAŻENIE: UPDATE customers SET = '373' WHERE
> id = NULL
> 2016-02-15 22:37:15 CET BŁĄD: bieżąca transakcja została
> przerwana, polecenia ignorowane do końca bloku transakcji
> 2016-02-15 22:37:15 CET WYRAŻENIE: UPDATE customers SET street = 'ul.
> Wiślisko' WHERE id = '8'
> 2016-02-15 22:37:15 CET BŁĄD: bieżąca transakcja została
> przerwana, polecenia ignorowane do końca bloku transakcji
> 2016-02-15 22:37:15 CET WYRAŻENIE: UPDATE customers SET street = 'ul.
> Marczyńskiego', building = '1', apartment = '33' WHERE id = '10'
> 2016-02-15 22:37:15 CET BŁĄD: bieżąca transakcja została
> przerwana, polecenia ignorowane do końca bloku transakcji
> 2016-02-15 22:37:15 CET WYRAŻENIE: UPDATE customers SET street = 'ul.
> Czerwone Maki', building = '59', apartment = '34' WHERE id = '455'
> 2016-02-15 22:37:15 CET BŁĄD: bieżąca transakcja została
> przerwana, polecenia ignorowane do końca bloku transakcji
> 2016-02-15 22:37:15 CET WYRAŻENIE: UPDATE customers SET street = 'ul.
> Pilotów', building = '81', apartment = '46' WHERE id = '324'
> 2016-02-15 22:37:15 CET BŁĄD: bieżąca transakcja została
> przerwana, polecenia ignorowane do końca bloku transakcji
> I tak dalej do końca bazy.
> Jak najszybciej znaleźć błąd ?
> 
> Linux vdebian 3.2.0-4-amd64 #1 [1] SMP Debian 3.2.73-2+deb7u2 x86_64
> GNU/Linux
> PHP Version 5.4.45-0+deb7u2

Za mocno wyrwane z kontekstu.
Jaki masz obecny stan:
SELECT * FROM dbinfo;
?

-- 
Pozdrawiam
Tomasz Chiliński, Chilan

**Comment by alkar1** [comment]
lms=# SELECT * FROM dbinfo;
             keytype              |                     keyvalue
----------------------------------+--------------------------------------------------
 unique_installation_id           | 32c78909eb0a82ed8851a81f160741ca045ce335d0271eb0
 dbversion                        | 2015080700
 last_check_for_updates_timestamp | 1455642932
 regdata_id                       | 3351
 regdata_name                     | Telnet Sp. z o.o.
 regdata_url                      |  http://www.telnet.krakow.pl
 regdata_hidden                   | 0
(7 wierszy)

Ale co dziwne po upgradzie lms nie pokazywał danych klientów a teraz po restarcie serwera są.
Zbadam to jeszcze dokładnie.

**Comment by chilek** [comment]
W dniu 18.02.2016 17:04, alkar napisał(a):
> lms=# SELECT * FROM dbinfo;
> keytype | keyvalue
> ----------------------------------+--------------------------------------------------
> unique_installation_id |
> 32c78909eb0a82ed8851a81f160741ca045ce335d0271eb0
> dbversion | 2015080700
> last_check_for_updates_timestamp | 1455642932
> regdata_id | 3351
> regdata_name | Telnet Sp. z o.o.
> regdata_url | http://www.telnet.krakow.pl
> regdata_hidden | 0
> (7 wierszy)
> 
> Ale co dziwne po upgradzie lms nie pokazywał danych klientów a teraz
> po restarcie serwera są.
> Zbadam to jeszcze dokładnie.

Czyli z poziomu interfejsu użytkownika LMS po lewej stronie
pod menu cały czas pokazuje Ci DB: 2015080700 i na dole każdej strony 
LMS-a
sypie błędami zapytań sql?

-- 
Pozdrawiam
Tomasz Chiliński, Chilan

**Comment by alkar1** [comment]
Po lewej mam DB: 2015091300 a błędy miałem tylko raz przy pierwszym uruchomieniu po rozpakowaniu nowej wersji.

**Comment by alkar1** [comment]
Po lewej mam 2015121800 i poniżej 
`Napotkano błędy w bazie danych!
Zapytanie: UPDATE customers SET = '462' WHERE id = NULL
Błąd: BŁĄD: błąd składni w lub blisko "=" LINE 1: UPDATE customers SET = '462' WHERE id = NULL ^
Zapytanie: UPDATE customers SET street = 'Zarzecze' WHERE id = '1941'
Błąd: BŁĄD: bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji
Zapytanie: UPDATE customers SET street = 'ul. Na Błonie', building = '9a', apartment = '414' WHERE id = '2039'
Błąd: BŁĄD: bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji
Zapytanie: UPDATE customers SET street = 'ul. Marczyńskiego', building = '6', apartment = '34' WHERE id = '704'
Błąd: BŁĄD: bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji`

**Comment by alkar1** [comment]
Jeden błąd naprawiony.
Skrypt postgres.2015122200.php nie radził sobie z upgradem klientów z pustym polem address.
Polecenie:
` update customers set address='brak' where address='';` 
załatwiło sprawę.

Drugiego błędu nie mogę znaleźć:
`Zapytanie: SELECT settings FROM users WHERE login = 'alfred'
Błąd: BŁĄD: kolumna "settings" nie istnieje LINE 1: SELECT settings FROM users WHERE login = 'alfred' ^`
