### ISSUE TITLE
Przejście na MariaDB 10.0.22 - błędy

### ISSUE THREAD

**Issue by cyberavis** [lmsgit/lms#674]
Załadowanie /doc/lms.mysql przy MariaDB 10.0.22 kończy się lawiną błędów:
[http://pastebin.com/SdY2DebL](http://pastebin.com/SdY2DebL)

Z tego co sprawdziłem pewne zmienne np. 'text' nie mogą mieć wartości DEFAULT ''.
Mam już poprawkę - zaraz wrzucę.

**Comment by chilek** [comment]
Co zwraca Ci w konsoli sql zapytanie:
```sql
show variables like 'sql_mode';
```
Prawdopodobne obejście problemu z nowym wersjach mysql znajduje się pod adresem:
http://bugs.mysql.com/bug.php?id=25520

**Comment by chilek** [comment]
Poprawka 0e4a4724b26b7bbd16383ccfcfb78c4ad4a0676d powinna rozwiązać problem.
Przeniesiona również do **LMS Plus** 1.11.19.x i 1.11.20.x.
