### ISSUE TITLE
Brak definicji dla tabeli passwdhistory w doc/lms.*sql

### ISSUE THREAD

**Issue by zlyZwierz** [lmsgit/lms#699]
Przypadkiem nadziałem się na to.

w upgradedb się tworzy cichaczem ;)

	CREATE SEQUENCE passwdhistory_id_seq;
	CREATE TABLE passwdhistory (
		id integer DEFAULT nextval('passwdhistory_id_seq'::text) NOT NULL,
		userid integer NOT NULL
		REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
		hash varchar(255) DEFAULT '' NOT NULL,
		PRIMARY KEY (id)
	)

Pozdraweiam.

**Comment by pjona** [comment]
https://github.com/lmsgit/lms/pull/700
