### ISSUE TITLE
Błąd świerzej instalacji

### ISSUE THREAD

**Issue by gavron7** [lmsgit/lms#708]
Witam!

Robię
`git clone github.com/lmsgit/lmsgit.git`
pobiera mi LMSa poprawnie, plik lms.ini łąduje w katalogu domowym www (ponieważ używam narazie innej wersji LMSa), stworzyłem nową bazę danych, nadałem uprawnienia do katalogów, zainstalowałem smarty. I wreszcie test....  http://192.168.1.51:8080/
i otrzymuję...
`Fatal error: Class 'LMSDB' not found in /var/www/lms/index.php on line 93`
jak w index.php zamienię

```
// Do some checks and load config defaults
require_once(LIB_DIR . DIRECTORY_SEPARATOR . 'checkdirs.php');
require_once(LIB_DIR . DIRECTORY_SEPARATOR . 'common.php');
require_once(LIB_DIR . DIRECTORY_SEPARATOR . 'Smarty' . DIRECTORY_SEPARATOR . 'Smarty.class.php');

```
na

```
// Do some checks and load config defaults
require_once(LIB_DIR . DIRECTORY_SEPARATOR . 'checkdirs.php');
require_once(LIB_DIR . DIRECTORY_SEPARATOR . 'LMSDB.php');
require_once(LIB_DIR . DIRECTORY_SEPARATOR . 'common.php');
require_once(LIB_DIR . DIRECTORY_SEPARATOR . 'Smarty' . DIRECTORY_SEPARATOR . 'Smarty.class.php');

```

idzie dalej ale wypluwa następny błąd

`Fatal error: Class 'LMSConfig' not found in /var/www/lms/lib/LMSDB.php on line 50`

Pytanie brzmi.. Jak to odpalić??

**Comment by maciejlew** [comment]
Wygenerowałeś pliki autoloadera? composer install / composer update?

W dniu 04.04.2016 o 21:47, Paweł Adamczewski pisze:

**Comment by gavron7** [comment]
tak jak najbardziej. na początku jak tego nie zrobiłem to LMS mówił żebym to zrobił

**Comment by maciejlew** [comment]
Zobacz czy w vendor/composer/autoload_classmap.php w zwracanej tablicy 
jest wskazana ścieżka do klasy LMSDB.

W dniu 04.04.2016 o 22:01, Paweł Adamczewski pisze:

**Comment by gavron7** [comment]
Dobra, chyba nie do końca :P 
Już działa. Miałeś rację, miałem błąd w composerze
