### ISSUE TITLE
Czasowe zawieszenie usług

### ISSUE THREAD

**Issue by gavron7** [lmsgit/lms#711]
Witam!
Czy jest możliwość (jak jest to jak) zrobić klientowi "czasowe zawieszenie usług" tj. właśnie się dowiedziałem że klienta przez 2 tygodnie nie będzie, w związku z czym chce zawiesić usługę na 2 tygodnie (zmniejszając abonament, proporcjonalnie do okresu zawieszenia). I teraz czy takie coś jest w  czy mam sobie sam doklepać?

**Comment by interduo** [comment]
Zobowiązania są miesięczne. Pozwalasz użytkownikom zawieszać usługę na określoną ilość dni?

Może po prostu dodaj sobie dwie takie same taryfy jedna DO druga OD. Luką jest okres zawieszenia. Korektę musisz i tak policzyć i wystawić ręcznie.
