### ISSUE TITLE
Dlaczego podanie VLAN ID jest obligatoryjne dla zdefiniowanej sieci?

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#714]
Dotyczy https://github.com/lmsgit/lms/commit/24ffaf4a04957bb4eb4b3bf4c76e9f084a726b78
u nas z uwagi, że używamy BRASA adresy z danej sieci mogą mieć różne VLAN ID.

**Comment by chilek** [comment]
b9f57635bac4fdb3bbe473dadbb4619bc11049cf to naprawia
