### ISSUE TITLE
phpui.quicksearch_autosubmit

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#715]
Dotyczy: https://github.com/lmsgit/lms/commit/b590eeb22c7cfe8fd472ff0912d62f954de91a62

Świeża instalacja nie zrobił się insert dla [phpui.quicksearch_autosubmit ](https://github.com/lmsgit/lms/blob/b590eeb22c7cfe8fd472ff0912d62f954de91a62/lib/upgradedb/mysql.2016031800.php 
)

Testowałem z mysql 5.6.28-76.1 (dokładniej percona xtradb cluster)

**Comment by chilek** [comment]
Patrzyłeś w logu zapytań mysql jak wyglądało zapytanie wysłane do mysqla?
