### ISSUE TITLE
lms-smstools - Use of uninitialized value $dest

### ISSUE THREAD

**Issue by piotrbaran2** [lmsgit/lms#725]
Próbowałem to poprawić ale jestem za słaby w te klocki :( skrypt nie poprawia statusów w zakładce wiadomości 

Use of uninitialized value $dest in substitution (s///) at ./lms-smstools line 146.
[sms sent] lms-7-48731100075

**Comment by piotrbaran2** [comment]
ktoś coś ?

**Comment by chilek** [comment]
Na mój gust brakowało tego:
https://github.com/lmsgit/lms/commit/e44557009d3bb130f0d581ec694f9afbb627f3a4
Poprawka poszła również do LMS Plus **stable** i **stable-1.11.19**.

**Comment by piotrbaran2** [comment]
potwierdzam, teraz wszystko działa. Dzięki za pomoc
