### ISSUE TITLE
Sektory radiowe

### ISSUE THREAD

**Issue by wawryk** [lmsgit/lms#728]
W osprzęt sieciowy informacje o urządzeniu nie działa podpowiadanie jednostek w momencie dodawania sektora radiowego

**Comment by chilek** [comment]
O który formularz konkretnie chodzi i jakie jednostki?
Masz jakieś błędy w **konsoli Javascript**?

**Comment by wawryk** [comment]
chodzi o ten formularz:
![image](https://cloud.githubusercontent.com/assets/15612188/15039539/2fb32770-12ae-11e6-84f6-526d9acb9978.png)

screen odrazu z consolą

**Comment by chilek** [comment]
A to żeś wyciął - nie wiadomo w jakim to kontekście...
No i o jakie jednostki chodzi?

**Comment by wawryk** [comment]
chodzi o to że niewiadomo czy zasięg w metrach czy w kilometrach ?, czy częstotliwość w hz  czy mhz ?, tak samo wysokość w metrach czy centymetrach ?,

**Comment by chilek** [comment]
@wawryk a w innym miejscu już to znalazłeś? To może i tu dorobisz i podeślesz pull requesta? ;-)

**Comment by chilek** [comment]
Naprawione.
