### ISSUE TITLE
layout.html vs header.html + footer.html

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#770]
To celowe działanie, że niektóre podstrony ładują **header.html** i **footer.html** zamiast **layout.html**?

**Comment by chilek** [comment]
Możliwe, że jakiś archaizm. Wskażesz konkretny przykład, żebym mógł sprawdzić przyczynę takiego stanu rzeczy?

**Comment by kyob** [comment]
1. https://github.com/lmsgit/lms/tree/master/templates/default/netnode
2. https://github.com/lmsgit/lms/blob/master/templates/default/event/eventnote.html

**Comment by chilek** [comment]
Archaizm - śmiało można przechodzić na **layout.html**!

**Comment by kyob** [comment]
https://github.com/lmsgit/lms/pull/772
