### ISSUE TITLE
przeniesienie bazy danych (2016->2005)

### ISSUE THREAD

**Issue by gavron7** [lmsgit/lms#771]
Nie mam w sumie gdzie napisać tego więc zapytuje w gronie najlepszych speców czyli tutaj :>

Używałem LMS z wersji np. z 2016 roku, ale większość bajerów mi nie potrzebna, w związku z czym postanowiłem DOWNGRADOWEować LMSa do np. 2005 roku. Backup bazy oczywiście nie importuje się gdyż w większości tabel pojawiły się dodatkowe pola.... Pytanie teraz - "Jak to zrobić aby zaimportował tylko konkretne pola, np. te które są wymagane". Czy muszę ręcznie zmodyfikować plik backupu czy jest jakiś automat może? Bardzo bym prosił o pomoc. :> Dziękuję :>

ps. mam nadzieję że nie namotałem :>

**Comment by chilek** [comment]
Nie rób ze głoszeń problemów listy dyskusyjnej.
