### ISSUE TITLE
Zapowiedź nowej skórki dla LMS 

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#776]
Bardzo wczesna wersja developerska:

https://lmsgit.alfa-system.pl/

l: demo
p: Demo1234

Można testować i wrzucać uwagi, a ja jadę na urlop :)

**Comment by paszczus** [comment]
Hosting>Konta oraz Helpdesk>Lista kolejek wyświetla stary wygląd.

**Comment by kyob** [comment]
Tak, bo jeszcze nie wszystkie strony są przerobione.

**Comment by paszczus** [comment]
A myślałeś może o Bootstrap Material Design? Wygląda IMO lepiej, ale w sumie jak już uda Ci się tą skrórkę przepchnąć to potem będzie z górki ;-)

**Comment by kyob** [comment]
Teraz chce się skupić na uporządkowaniu kodu i zwiększeniu ergonomii UI. Przejście na pochodną TWBS będzie już formalnością.

**Comment by chilek** [comment]
@kyob: zasadnicze pytanie: czy skórka działa po prostu jako odrębny katalog z szablonami?
Troszkę niepokoi mnie kwestia utrzymania w przyszłości dwóch równorzędnych systemów szablonów. Chyba, że stary się porzuci i "nakaże się" użytkownikom korzystanie z nowych szablonów...

**Comment by kyob** [comment]
@chilek 

> czy skórka działa po prostu jako odrębny katalog z szablonami?

Tak osobny katalog. Ja nikogo nie chce do niczego zmuszać. Zobaczymy co z tego będzie, bo jeszcze jest sporo pracy do wykonania.

**Comment by chilek** [comment]
Czy całość robisz w ten sposób, że szablony są niezależne od warstwy wizualnej, a sama warstwa wizualna to załadowanie odpowiedniego stylu w postaci javascript/css?

**Comment by chilek** [comment]
@kyob: skoro tu już jesteśmy wspólnie to może masz możliwość weryfikacji innego zgłoszenia
#674 (napisałem tam trochę o tym co można spróbować zrobić i jestem ciekaw czy to na nowych instalacjach mysql/mariadb/perconadb pomogłoby).

**Comment by kyob** [comment]
Prace trwają: **336** files changed, **42667** insertions(+), **852** deletions(-)

**Comment by interduo** [comment]
https://lmsgit.alfa-system.pl/ - nie działa :(

**Comment by chilek** [comment]
Może url zmienił się.
Istotne jest, żeby ewentualny nowy temat graficzny był responsywny i dostosowywał się sprawnie do rozdzielczości ekranu - wtedy byłoby wygodniej używać w telefonach i tabletach.

**Comment by kyob** [comment]
@interduo Poprawione.

**Comment by interduo** [comment]
Dziękuję. 

Czy w takim razie https://github.com/lmsgit/lms/issues/145 nie powinien zostać zamknięty?

**Comment by prezeskk** [comment]
https://lmsgit.alfa-system.pl/ - dzisiaj nie działa

**Comment by kyob** [comment]
Na szybko uruchomiłem, ale do dopieszczenia.

**Comment by chilek** [comment]
@kyob: kombinowałeś z ikonkami w kierunku tego, żeby ich wygląd realizowało się w LMS w oparciu o ustawienia atrybutu klasa dla elementu img? Każda klasa dla ikonki mogłaby mieć swoją unikalną nazwę w obrębie interfejsu użytkownika LMS, a plik mapujący klasy na obrazki załatwiałby całą "brudną robotę".

**Comment by kyob** [comment]
@chilek Jeszcze do tego nie ruszyłem.

**Comment by chilek** [comment]
@kyob fajnie byłoby przerobić wszystkie obrazki w LMS na elementy html ze wskazaniem przeznaczenia danej ikonki, a potem poprzez css (czy coś innego) dawać definicję odwzorowań znaczeń ikonek na konkretne obrazki.

**Comment by paszczus** [comment]
Dzisiaj przyszedł mail z informacją o nowej wersji iLMS i wygląd IMO jest dosyć sensowny (i responsywny). Wiem, że to "konkurencja" ale warto spojrzeć, mi się podoba.
![ilms](https://cloud.githubusercontent.com/assets/1582475/18668644/db62e07a-7f36-11e6-836a-22059a5b38ad.png)

**Comment by chilek** [comment]
W dniu 20.09.2016 13:34, paszczus napisał(a):
> Dzisiaj przyszedł mail z informacją o nowej wersji iLMS i wygląd
> IMO jest dosyć sensowny (i responsywny). Wiem, że to "konkurencja"
> ale warto spojrzeć, mi się podoba.

co rozumiesz przez "responsywny"?

**Comment by interduo** [comment]
Nie ma się czym zachwycać jeśli chodzi o wygląd, ma kilka fajnych elementów ale za to ma kilka wdrożonych funkcjonalności które zgłaszałem w issue :/

**Comment by chilek** [comment]
Ostatnio bardzo dużo w lms przybywa rzeczy dla kontrolek, które potem będzie można użyć w wielu miejscach (w kilku jest już używane). Obecny spis klas css lms-a:
https://github.com/chilek/lms-plus/wiki/Klasy-CSS-dostarczane-przez-LMS

**Comment by chilek** [comment]
No i zasadnicza sprawa: iLMS nie będzie responsywny - była krótka dyskusja na ten temat i kolega Daniel z inetLMS/iLMS stwierdził, że nie ma co się wysilać ;-)

**Comment by interduo** [comment]
Bardziej apka na telefon przydała z obsługą helpdesku i terminarza dla serwisantów niż responsywny wygląd.

**Comment by kyob** [comment]
Życie zweryfikowało teorię. Temat uważam za zamkniety.
