### ISSUE TITLE
LMS nie wyświetla "zawartości" stron. Nie da się dodać pierwszego użytkownika.

### ISSUE THREAD

**Issue by janix** [lmsgit/lms#778]
Witam,
zainstalowałem LMS-a stąd:
https://github.com/lmsgit/lms/releases/tag/LMS_011120

Po folder z lms-em dodałem do standardowej lokacji, na którą wskazuje apache.
Utworzyłem bazę, zaimportowałem i ogólnie zastosowałem się do instrukcji zawartych w dokumentacji:
http://lms.org.pl/doc/install.html
Jednak po uruchomieniu composer install i nadaniu praw dostępu do plików, nie pokazuje się ekran startowy z dodawaniem pierwszego użytkownika systemowego LMS-a.
Co dziwne, po lewej stronie jest menu, które wygląda na działające, ale po prawej stronie zawartość nie jest niestety wyświetlana.
Spotkał się ktoś z podobnym problemem?
Z góry dziękuję za poświęcony na odpowiedź czas.

Pozdrawiam.

**Comment by chilek** [comment]
1) Na pewno zainstalowałeś smarty skryptem **devel/smarty_install.sh**?
2) Co masz w logach błędów serwera www?

**Comment by janix** [comment]
Tak, to był brak uruchomienia smarty_install.sh
Ogólnie, to uruchamiałem ten skrypt, ale może w zbyt wczesnym kroku instalacji.

Dziękuję bardzo za odpowiedź.
Pozdrawiam serdecznie.
