### ISSUE TITLE
Update bazy danych

### ISSUE THREAD

**Issue by prezeskk** [lmsgit/lms#781]
Podczas aktualizacji LMS do master z gita dostałem takie błędy bazy danych:

Zapytanie: ALTER TABLE voip_tariffs CHANGE groupid groupid int(11) NOT NULL
Błąd: Cannot change column 'groupid': used in a foreign key constraint 'voip_tariffs_ibfk_2'
Zapytanie: ALTER TABLE voip_tariff_rules CHANGE groupid groupid int(11) NOT NULL
Błąd: Cannot change column 'groupid': used in a foreign key constraint 'voip_tariff_rules_ibfk_2'
Zapytanie: ALTER TABLE voip_tariffs CHANGE price price decimal(12,5) NOT NULL
Błąd: Unknown column 'price' in 'voip_tariffs'

**Comment by chilek** [comment]
Pewnie nie poszły Ci wcześniej zapytania:
```sql
ALTER TABLE voip_tariffs DROP FOREIGN KEY voip_tariffs_ibfk_1;
ALTER TABLE voip_tariff_rules DROP FOREIGN KEY voip_tariff_rules_ibfk_1;
```
Spróbuj w nich zastąpić ciąg **ibfk_1** poprzez **ibfk_2**.

**Comment by prezeskk** [comment]
Chyba w tym problem
Poradziłem sobie z tym dodając od nowa klucze obce

**Comment by chilek** [comment]
Zrobiłem porządek w ostatnich aktualizacjach schematu i mam nadzieję, że to rozwiąże trwale problem:
b330fab9cb5d03b5bc374e3979f57cbb37086f62
