### ISSUE TITLE
VOIP - rozwiązania

### ISSUE THREAD

**Issue by gavron7** [lmsgit/lms#788]
Witam!
Wiem że nie koniecznie temacik związany z LMSem, ale pomyślałem że znajdę tutaj całe kilo fachowców z tematu VoIP. 
Obecnie w mojej firmie jest normalna linia telefoniczna (chyba TPSA/Orange) i jakaś analogowa centralka telefoniczna. Chcę to zamienić na VoIP'a, tak aby można było w dowolnym miejscu wpiąć telefon VoIP ewentualnie używać jakiegoś komunikatora VoIP na komputerze. Co będzie mi potrzebne tak naprawdę i czego użyć? Coś czytałem o ASTERISKu ale w grę tak naprawdę chyba wchodzą jedynie rozwiązania sprzętowe, choć chętnie dowiem się czegoś o tym asterisku.

**Comment by chilek** [comment]
Nie rób ze głoszeń problemów listy dyskusyjnej.
