### ISSUE TITLE
Zdefiniowanie "custom_templates_dir" nie zmienia szablonu

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#797]
Przypisałem nazwę szablonu do **phpui.custom_templates_dir** i nie działa.

**Comment by chilek** [comment]
@kyob na pewno właściwie uprawnienia i właściciela tego katalogu?
Próbowałeś wyczyścić **templates_c**?

**Comment by kyob** [comment]
Łatka https://github.com/lmsgit/lms/pull/798

**Comment by kyob** [comment]
Działa prawidłowo jak wywalę 'default' z https://github.com/lmsgit/lms/blob/master/index.php#L181
i wpiszę swój szablon:
`SMARTY_TEMPLATES_DIR . DIRECTORY_SEPARATOR . 'moj_szablon',`

**Comment by chilek** [comment]
@kyob: wygląda na to, że dynamiczne zastępowanie szablonów w całej liście katalogów z szablonami powoduje opisywany przez Ciebie problem. Jeśli pliki w customer dir mają takie nazwy jak w default to wtedy i tak następuje niejawne rozszerzanie szablonów. Mimo wszystko, możesz tu wkleić przykładową zawartość Twojego szablonu, który nie działa?

**Comment by kyob** [comment]
Zrobiłem `cp -rp default/ moj_szablon/` i podmieniłem tylko jeden plik [login.html](http://pastebin.com/2z6FeX7G) 

Ładuje szablon **default** a mój ignoruje **moj_szablon**

**Comment by chilek** [comment]
Wygląda, więc na to, że jest tak jak napisałem wyżej. Nie da się w tym momencie obejść tego elegancko.

**Comment by kyob** [comment]
Jeśli chodzi o mnie innego szablonu nie będzie, bo utrzymywanie więcej niż jednego szablonu jest zbyt pracochłonne.
