### ISSUE TITLE
Osprzęt sieciowy -> wyszukiwanie po ssid

### ISSUE THREAD

**Issue by wawryk** [lmsgit/lms#806]
Wydaje mi się że przydała by się taka opcja w wyszukiwarce osprzętu sieciowego, mogę to dopisać i podesłac pull requesta, pytanie czy inni są też zainteresowani taką funkcjonalnością czy może jest już gdzieś coś takiego a ja nie widzę ?

**Comment by chilek** [comment]
Nie ma jeszcze czegoś takiego. Ciekawe czy brak odzewu oznacza brak zapotrzebowania, czy raczej brak świadomości, że na github issue można wejść i dyskutować ;-)

**Comment by frychlich** [comment]
Każda droga do znalezienia właściwego urządzenia sieciowego jest mile widziana.

**Comment by interduo** [comment]
Potrzebuję!

My dawniej (za czasów kiedy nie było jeszcze boxa "sektory radiowe") w nazwach sieci IP umieszczaliśmy SSID sieci ale to jest niewłaściwa droga ;-)

**Comment by interduo** [comment]
Zrobiliśmy to. @chilek proszę zamknij to.
