### ISSUE TITLE
Pinger live, nie zlicza strat pakietowych

### ISSUE THREAD

**Issue by iAdmin-PL** [lmsgit/lms#81]
Odpalony wątek, lecą "urządzenie sieciowe jest nieosiągalne" a w sekcji summary [razem] stoi w miejscu.
Podczas gdy urządzenie odpowiada, nie liczy przerw jak i pakietów na które nie odpowiedziało urządzenie.

**Comment by interduo** [comment]
Jeśli na stacji tą którą pingujemy zrobię:
iptables -A INPUT -p icmp -j REJECT, straty te zliczają się poprawnie jeśli 
iptables -A INPUT -p icmp -j DROP już nie.

**Comment by chilek** [comment]
State i nieaktualne.
