### ISSUE TITLE
nodeadd: przypisanie zamiast porównania

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#816]
https://github.com/lmsgit/lms/blob/master/modules/nodeadd.php#L269

`if($customerid = $nodedata['ownerid'])`

Co piszący miał na myśli?

PS: Ten sam problem z: https://github.com/lmsgit/lms/blob/master/modules/voipaccountadd.php#L152

**Comment by chilek** [comment]
Może chodzić o scenariusz w którym dodajesz komputerów dla niewybranego jeszcze klienta.

**Comment by kyob** [comment]
Według mnie to powinno być np. **==** a nie **=** lub wywalić **if**

**Comment by chilek** [comment]
Pewnie chodzi o to, żeby za jednym razem wykonać podstawienie pod $customerid i sprawdzenie jaki jest wynik przypisania, czyli czy $customerid w wyniku jest nie puste.

**Comment by kyob** [comment]
OK teraz  jasne :)
