### ISSUE TITLE
Problem z post_addresss na fakturach

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#825]
1. Czy jest opcja wyłączenia **post_address** z faktury?
2.  Dlaczego ustawienie **post_address** wyświetla się na "przeszłych" fakturach z przed czasu, gdy jeszcze nie było **post_address**? Według mnie jeśli już używać **post_address** to powinien wyświetlać się tylko na fakturach, od kiedy został ustawiony **post_address**?

**Comment by chilek** [comment]
1. Nie ma.
2. Co w tym złego. Chcesz wysłać stare faktury to masz łatwiej, a ogólnie US nie wymagają, żeby faktura co do literki była identyczna (w prawie tego nigdy nie było).

**Comment by kyob** [comment]
Obecne status quo zostało poparte silnymi argumentami. Zamykam :)

**Comment by chilek** [comment]
Hehe ;-)
