### ISSUE TITLE
Sprzęt sieciowy: Netdevinfo - Informacja o domyślnym adresie IP

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#837]
Brakuje informacji o tym, który z adresów IP jest domyślnym adresem urządzenia. Służącym do np logowania poprzez WWW lub SSH. 

Informacja jest o tyle krytyczna, że zalogować się na urządzenie dość często można tylko i wyłącznie poprzez jeden adres z wielu. Pisząc skrypty zewnętrzne biorące informacje bezpośrednio z bazy również byłoby prościej.

**Comment by chilek** [comment]
Dla urządzeń można przypisywać "adresy URL do zarządzania" i to jest lepsze rozwiązanie niż oznaczanie domyślnych ip...

**Comment by interduo** [comment]
OK

A pole "radius-secret" dla skryptu generującego automatycznie konfigi dla freeradiusa?

**Comment by chilek** [comment]
Dodać jako adres url:
**radius://secret@host**

**Comment by chilek** [comment]
Inny sposób - hosty IP przypisywane do urządzeń używane na potrzeby zarządzania dawać z sieci IP specjalnie dedykowanej do zarządzania.

**Comment by interduo** [comment]
Pododaję sobie więc wszystkie secrety radiusowe w pole "Adresy do zarządzania" i będę generował pliki dla Freeradiusa dzieląc link na części. Chociaż łatwiej byłoby mieć oddzielne pole na to bo czasami w secretach mam znaki specjalne i @. SNMP community ma również swoje pole mimo iż też może zostać wpisane do "adresy url do zarządzania" na podobnej zasadzie.

Idąc zaproponowanym przez Ciebie rozwiązaniem czy da sie dodać w jakiś sposób link np.:
ssh:$login_zalogowanego_uzytkownika@host:port ?
winbox:$login_zalogowanego_uzytkownika@host:port ?

Chcę, mieć do wpisania przy logowaniu tylko i wyłącznie hasło przy logowaniu.

Co do pakowania hostów w jedną sieć IP do zarządzania. Nie da się tak we wszystkich przypadkach. (adresy z poza naszych sieci)

**Comment by chilek** [comment]
Wpisujesz w adresach URL do zarządzania czy to ssh://... czy to winbox://... konfigurujesz w systemie lub przeglądarce www url protocol handler dla swoich protokołów i uruchomi Ci się co trzeba nawet od razu z wprowadzeniem loginu i hasła!

**Comment by interduo** [comment]
Użytkowników, którzy mają dostęp do sprzętu sieciowego mam kilku. Hasła dla nich są codziennie inne. Urządzenia sprawdzają czy para login/hasło jest właściwa za pomocą radiusa. Nie mogę ich więc wpisać na stałe do URLa.

Chcę by w logach urządzeń zostawała informacja kto się logował. Nie chcę za każdym razem gdy muszę coś zrobić na urządzeniu logować się na parę (użytkownik/hasło) do ratunkowego dostępu.
 
Dlatego pytam o tą zmienną, chciałbym przekazywać login aktualnie zalogowanego użytkownika lms przez URL. Tak by mieć do wpisania tylko hasło. 

Da się tak?

**Comment by chilek** [comment]
@interduo da się na 100%, ale to tak naprawdę od Ciebie zależy jako url protocol handlery w systemie lub przeglądarce skonfigurujesz.

**Comment by interduo** [comment]
Po kliknięciu w jakikolwiek adres IP znika BOX z "Adresy IP do zarządzania". Czy to celowe czy błąd?

Co do mojego pytania jeszcze raz:
mam w LMS trzech uzytkownikow o loginach user1, user2, user3.

Po zalogowaniu chcę żeby każdy z nich miał swój indywidualny URL w "adresy URL do zarządzania":
Loguje się 'user1" widzi link: winbox:user1@ip:port
Loguje się 'user2" widzi link: winbox:user2@ip:port
Loguje się 'user3" widzi link: winbox:user3@ip:port

Co mam wpisać w polach "Adresy URL do zarządzania" by każdy z tych użytkowników po zalogowaniu miał URL dedykowany dla siebie?

**Comment by chilek** [comment]
A nie możesz lokalnie podpiąć skryptu z obsługą winbox, gdzie każdy użytkownik wpisze w nim swój login i hasło?

Odnośnie braku adresów url do zarządzania po wybraniu hosta ip dla urządzenia - faktycznie - usprawnię to dzisiaj.

**Comment by chilek** [comment]
Poprawka w rozwojowym LMS:
https://github.com/lmsgit/lms/commit/de2d69b0d281b4b94574f429f90143922cae3b41
Przeniesiona również do bieżącej gałęzi stabilnej LMS Plus.

**Comment by interduo** [comment]
Mogę w ogóle nie podawać loginu/hasła w URLu.

Ale w takim razie gdzie mam zapisać parę ratunkową login/hasło skoro w sprzęcie nie ma pola "użytkownik", pole "hasło" jest ?

**Comment by chilek** [comment]
W skrypcie, który udostępnisz administratorom, a który będzie się wykonywał po kliknięciu w URL z protokołem winbox:// czy ssh:// możesz zrobić sprawdzanie czy udało się zalogować podaną w skrypcie kombinacją login i hasło, a jeśli nie udało się to próbować awaryjną.
Ewentualnie wpisać jako pierwszy url bez loginu i hasła, a drugi url z awaryjnym login i hasłem.

**Comment by chilek** [comment]
Jak będzie tym tematem większe zainteresowanie to przygotuję artykuł wiki projektu LMS Plus z dokumentacją jak można w windows i linuksie skonfigurować sobie własne protocol handlers (na przykładzie ssh:// i winbox://).

**Comment by interduo** [comment]
Zastanawiam się jak podejmujesz decyzję czy dana wartość powinna mieć swoje pole czy być w "Adresy URL do zarządzania". Mówię tutaj o takich informacjach jak: SNMP Community, Użytkownik, Hasło, RadiusSecret. 

Te informacje nie są wykorzystywane tylko i wyłacznie do logowania przez kliknięcie w URLa.

Co do manuala jest sporo tego w Internecie:
np. http://stackoverflow.com/questions/389204/how-do-i-create-my-own-url-protocol-e-g-so

**Comment by chilek** [comment]
@interduo: potwierdzam - jest tego dużo, choć większość nie działa tak jak trzeba (znając życie), a tylko bardzo wybrane pewnie działają ;-)

**Comment by alecpl** [comment]
@chilek, protocol handlers można zarządzać javascriptem. Nie wiem czy w tym przypadku to by się sprawdziło, nie czytałem dokładnie tego co piszecie. Pozdrawiam.

**Comment by chilek** [comment]
@alecpl tak, ale javascriptem nie uruchomisz lokalnego programu wykonywalnego - lokalnego w sensie takiego, który działa w systemie operacyjnym na którym uruchomiona jest przeglądarka.

**Comment by interduo** [comment]
OK, z radiusem i URL handlerami sobie poradzę.

Jak podejmujesz decyzję czy dana wartość powinna mieć swoje pole czy być w "Adresy URL do zarządzania" jako część URLa. Mówię tutaj o takich informacjach jak: SNMP Community, Użytkownik, Hasło, RadiusSecret ?

**Comment by interduo** [comment]
Co jest przeciw utworzeniu dodatkowych (opcjonalnych) pól?

**Comment by interduo** [comment]
Podejdę do sprawy bardziej globalnie:

Tomku, jak widzisz możliwość wprowadzenia funkcjonalności na zasadzie samodzielnej możliwości definiowania dodatkowych pól txt w każdym z modułów  (tj. customer, node, tariffs, net, netnode, document, event, rt). Da się to jakoś ogarnąć?

Chciałbym dojść do sytuacji gdy nie będę musiał ręcznie dodawać samodzielnie jakiegoś pola gdy zajdzie potrzeba ani takich brzydkich haków, na zasadzie jakichś tam znaczników w polu opis i późniejszego parsowania tego.

Skoro klient może mieć i 10 telefonów to dlaczego rzeczy/zdarzenia/taryfy/węzły nie mogą mieć 10 opisów?;)

**Comment by chilek** [comment]
Do wszelkiej maści autoryzacji możesz użyć adresów URL komputerów i urządzeń... URL-e są od tego, żeby opisywać lokalizacje dostępu i/lub zasobów sieciowych, ale mam wrażenie, że w tym temacie też już o czym innym piszesz... ;-)

**Comment by interduo** [comment]
Tak się stało ponieważ odpisałeś mi ponownie na pierwszy post zamiast na ostatni w tym wątku, zrozumiałem, że coś można zrobić innym sposobem i faktycznie sposób przewidziany przez autora jest lepszy.

Z radiusem sobie poradziłem. Teraz brakuje mi tylko możliwości zapisania 'ratunowego' loginu administratora - moim zdaniem jeśli hasło ma swoje pole to i login też powinien mieć.

**Comment by chilek** [comment]
W dniu 19.10.2016 18:25, Interduo napisał(a):
> Tak się stało ponieważ odpisałeś mi ponownie na pierwszy post
> zamiast na ostatni w tym wątku, zrozumiałem, że coś można zrobić
> innym sposobem i faktycznie sposób przewidziany przez autora jest
> lepszy.
> 
> Z radiusem sobie poradziłem. Teraz brakuje mi tylko możliwości
> zapisania 'ratunowego' loginu administratora - moim zdaniem jeśli
> hasło ma swoje pole to i login też powinien mieć.

To nie jest hasło radius jako użytkownika - to jest radius secret.
O którym haśle piszesz?

**Comment by interduo** [comment]
Każde urządzenie posiada u nas w systemie indywidualny secret radiusowy oraz parę do logowania awaryjnego (serwisanci mają codzienny dostęp przy użyciu innej indywidualnej pary z serwera radius która jest codziennie inna). Parę ratunkową chciałbym trzymać w bazie lms w polu hasło i login (tego pola nie ma) i pokazywać ją na żądanie po kliknięciu.

Natomiast w url przydałby się link np. ssh://$nazwazalogowanegouzytkownikalms@ip tak, żeby to potem ładnie ogarnąć potem za pomocą urlhandlera.

**Comment by interduo** [comment]
Gdyby był mechanizm o którym pisałem wcześniej mógłbym po prostu dodać sobie opisowe pole tekstowe zatytułowane loginuser o treści np adminuser2. Potrzeba powstała dlatego że na niektórych urządzeniach nie da się zmienić nazwy użytkownika głównego oraz tego że nazwa 'admin' jest na użytkownika z uprawnieniami administracyjnymi zbyt oczywista.

**Comment by chilek** [comment]
@interduo: a w czym widzisz problem, że dane do logowania wpisywać jako URL? Przecież po to postały URL-e, żeby ułatwić wszystkim życie...

**Comment by interduo** [comment]
Lubię jednoznaczność. Po co pole hasło więc?

**Comment by chilek** [comment]
Pole secret to wspólna fraza używana do komunikacji klient radius <-> serwer radius.

**Comment by interduo** [comment]
Czyli gdzie mam ją wpisywać w końcu? W postach wyżej kazałeś pakować tą frazę do urla o formacie radius://secret@host ?

**Comment by interduo** [comment]
W pole secret wpisuje frazę radiusa.
W URLe ssh://user:haslo@ip, winbox://user:haslo@ip.

Ta informacja jest zawarta tutaj. W skryptach backendowych sobie poprawię. Zamykam zgłoszenie.
