### ISSUE TITLE
Tytuły dokumentów w LMS

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#839]
Czy dałoby się dorobić listę wyboru w polu "Tytuł:" (opcjonalną) na początku ? 
Za każdym razem to trzeba wpisywać ręcznie. 

Jeśli wybierzesz coś z listy masz początek tytułu. A pozostały koniec możesz dopisać opcjonalnie.

U nas uzupełniamy tytuł dokumentów w formacie USŁUGA: Lokalizacja instalacji 
(jeśli klient ma dwie lub więcej).

Np. "Internet: 3-go Maja 1, Lubartów"
lub po prostu
Internet

**Comment by frychlich** [comment]
Jako, że każdy ma jakieś własne pomysły na nazwy dokumentów,
to może lepiej pójść w kierunku szablonów nazwy,
my na ten przykład nazywamy %DATA_%NAZWISKO_%ID_%typ-dokumentu_%typ-uslugi
i mamy finalnie 2016.08.18_KOWALSKI_3467_umowa_internet

**Comment by interduo** [comment]
Właśnie to nie jest ustandaryzowane. 

Uważam, że w tytule nie trzeba typ dokumentu umieszczać ponieważ masz do tego oddzielne pole.  A wpisywanie ręcznie nie podoba mi się bo można błąd.

**Comment by interduo** [comment]
Może coś bardziej ala: %typ-usługi_%lokalizacja-%nazwa/%nazwisko ?

**Comment by frychlich** [comment]
Dlatego najlepiej jakby można było na tyle uniwersalne szablony tytułów dokumentów tworzyć.
Jak mam kilka typów usług, to łatwiej nam się szuka umowy na liście dokumentów widząc w nazwie co to jest, czy umowa, czy protokół odbioru, czy serwisowy, czy przekazania sprzetu.

Najlepiej możliwość tworzenia na zasadzie jak plany numeracyjne

**Comment by interduo** [comment]
Ale przecież na liście masz wyświetlony typ dokumentu/datę, po co to dublować w tytule?

**Comment by frychlich** [comment]
Dlatego wg mnie, najlepiej nie definiować tego na sztywno jakimś schematem,
tylko każdy wg własnych potrzeb, definiowałby sobie szablon nazw,
jak na zasadzie opcji invoice.attachment_name

**Comment by chilek** [comment]
Zaimplementowane commitem https://github.com/lmsgit/lms/commit/59c7f97782e922dbe2cabfe91c5b49399844c693.
Definiuje się ten tekst właściwością _form_title_ lub (dotychczas istniejącą) _title_.

**Comment by interduo** [comment]
Ponawiam prośbę o spisanie wszystkich zmiennych i krótki ich opis.
