### ISSUE TITLE
Okres ważności taryfy

### ISSUE THREAD

**Issue by frychlich** [lmsgit/lms#840]
Witam,

może warto by było do taryf dodać pola "ważna od" oraz "ważna do”.
Podczas wybierania zobowiązania dla klienta nie było by takiego
„bałaganu” przy dużej historii różnych taryf (nazwy/ceny)

**Comment by chilek** [comment]
Czy wyłączenie taryfy "żarówką" nie załatwia problemu. Wtedy na liście wyboru taryf nie powinny się pojawiać taryfy wyłączone.

**Comment by frychlich** [comment]
Jeżeli wyłącze żarówką taryfę, to przy edycji zobowiązania, gdzie BOK chce zmienić datę końcową, nie można zapisać zmian ponieważ taryfa jest wyłączona z użycia.

**Comment by chilek** [comment]
@frychlich - a czy mimo wyłączenia taryfy powinna być możliwość edycji istniejących zobowiązań opartych o wyłączoną taryfę?

**Comment by frychlich** [comment]
Klient ma zrobione zobowiązanie na podstawie wyłączonej taryfy (skończył się okres np obowiązywania promocji, który trwał 3msc, umowa jest na 24msc), przychodzi podpisuje aneks na inną ofertę.

Jak mam zaznaczyć w zobowiązaniu kiedy kończy się naliczanie, jak nie mogę go zapisać, bo taryfa jest wyłączona?

**Comment by chilek** [comment]
Jeśli przychodzi podpisać nową umowę promocyjną to chyba nie w oparciu o starą, nieaktywną taryfę?

**Comment by frychlich** [comment]
Mam wrażenie, że konwersuje z ........

To może napisz mi proszę, jak wg Ciebie powinienem obsłużyć klienta, jak przychodzi zmienić taryfę?

**Comment by chilek** [comment]
@frychlich a ja zaczynam nie rozumieć co chcesz uzyskać. Absurdalne wydaje mi się uprzednie wyłącznie z użycia taryfy w oparciu o którą potem próbujesz tworzyć nowe umowy promocyjne. Po co ją wyłączasz skoro potem i tak przy podpisywaniu umów jej używasz?

**Comment by frychlich** [comment]
ja jebe nie ujebie

bę∂ę pisał powoli, aby łatwiej było zrozumieć mój przekaz myśli

1. w dniu 2015.12.24 organizuję promocję Internet do Karpia, promocja kończy się 31 grudnia. Klient w promocji podpisuje umowę na 24miesiące.

2. w dniu 2016.05.01 organizuję promocję Internet do grilla.

Przychodzi w dniu 5 maja, klient co ma podpisaną umowę na promocję z  pkt 1., ma przypisane odpowiednie zobowiązanie naliczane miesięcznie, które ma datę od 2015.12.24 do 2017.12.31

Więc jak mam teraz dodać mu nowe zobowiązanie aby naliczało mu się jedno?

**Comment by chilek** [comment]
Zawiesić dotychczasowe stare, dotychczasowe zobowiązanie i utworzyć nowe. Trochę inwencji wystarczy ;-)

**Comment by interduo** [comment]
Widzę tutaj dwa problemy:
1. Aneks prędkości z umowy promocyjnej (w okresie po promocji) czyli kiedy promocja się skończyła i nie można już podpisać nowej umowy z danej promocji, bo jest nowa.
2. Edycja błędnie zapisanej taryfy przez biuro i edycja jej np. dzień po skończonej promocji :) np. brak rabatu

**Comment by frychlich** [comment]
My nie zawieszamy starych zobowiązań, tylko zmieniamy im datę zakończenia.
Zawiesić to można sobie płaszcz na wieszaku albo internet klientowi na jego wniosek.

**Comment by chilek** [comment]
To po co w takim razie wyłączacie dostępność taryf?

**Comment by frychlich** [comment]
łoboshe, patrz pierwszy post

swoją drogą, działałeś na jakimś LMS, który żyje swoim życiem i abonentów dłużej niż dwa lata?

**Comment by chilek** [comment]
@frychlich: ehh jestem prawie pewień, że dłużej korzystam produkcyjnie z LMS-a niż Ty. I to pewnie parokrotnie dłużej ;-)

**Comment by interduo** [comment]
Wyłączamy je po to bo nie są już używane i żeby się nie myliły z innymi podczas dodawania nowych zobowiązań.

@frychlich co to pole wg Ciebie miałoby _DOKŁADNIE_ robić i jak byś je uzupełniał?

**Comment by chilek** [comment]
@frychlich: to może najrozsądniej będzie taryfę już wyłączoną pozwalać edytować, ale już nowej nie pozwolić po prostu dodać?

**Comment by interduo** [comment]
Która z opcji będzie lepsza?
A) Checkbox Pokaż wszystkie taryfy
B) po wybraniu pozycji z listy 'wszystkie taryfy' ładowana jest druga pełna lista

**Comment by chilek** [comment]
@interduo: ale to powoduje całkowite zniesienia wyłączania taryf...

**Comment by frychlich** [comment]
@chilek to by już jakoś rozwiązało problem, ale cały czas pozostaje problem ręcznego pilnowania wyłączania taryf

**Comment by frychlich** [comment]
@interduo nie pole a dwa pola, zakładam nową taryfę, np wiosna 2017 z polem ważne od = 2016.03.21 i polem ważne do = 2016.06.24 i w tym okresie taryfa ta pokazuje się do wyboru podczas dodawania nowego zobowiązania.
Oczywiście edycja takiego zobowiązania musi być możliwa aby po okresie obowiązywania danej promocji/taryfy można było skrócić zobowiązanie przypisane klientowi.

W pewnym sensie pozwoli to z pewnym wyprzedzeniem przygotowywać nowe taryfy, nie robiąc przy tym zamieszania dla biura obsługi klienta

**Comment by interduo** [comment]
Zrozumiałem już dokładnie o co Ci chodzi. Dobra opcja. Mi się osobiście nie podoba ogólna mnogość taryf dlatego zaproponowałem również https://github.com/chilek/lms-plus/issues/55.

**Comment by chilek** [comment]
@frychlich: jeszcze pytanko: używasz w ogóle promocji z lms?

**Comment by frychlich** [comment]
@chilek Nie używam, bo nie miałem do tej pory ani siły ani chęci dokładnego rozgryzania jak to w ogóle działa.

**Comment by chilek** [comment]
https://github.com/chilek/lms-plus/issues/173
