### ISSUE TITLE
change password

### ISSUE THREAD

**Issue by wawryk** [lmsgit/lms#841]
Dziwna sprawa
wymuszenie zmiany hasła nie działa (napewno na google chrome) 
motyw polega na tym ze wystarczy kliknąć w jakiś link albo odświeżyć stronę i przechodzimy dalej.
trzeba by to szybko ogarnąć

**Comment by chilek** [comment]
Nie potwierdzam problemu - przetestowałem u siebie na przeglądarce Google Chrome.

**Comment by wawryk** [comment]
Ściągnąłem najnowszy master, ale niestety nadal ten problem występuje, usunąłem również wszystkie ciasteczka i nadal to samo
powinienem mieć coś włączone dodatkowo w lms czy jak ?

**Comment by wawryk** [comment]
Świeża instalacja lms, zmiana hasła działa, lecz zmieniam je kilkukrotnie i dzieje się to samo. 
Testowane na różnych przeglądarkach w trybie incognito

**Comment by chilek** [comment]
@wawryk co mam zrobić po kolei, żeby odtworzyć problem?

**Comment by wawryk** [comment]
Ja zrobiłem tak: 
postawiłem nową instancję lms (czystą, gołą bez danych)
na koncie zmieniłem kilkukrotnie hasło (za każdym razem wymuszając zmianę bo hasło wygasło, aby tego dokonać usuwałem z tabeli users date ostatniej zmiany hasła) 
w pewnym momencie mogłem przejść dalej bez zmiany hasła

**Comment by chilek** [comment]
Zobacz czy commit 767a43c rozwiąże problem?

**Comment by wawryk** [comment]
Tak, to jest to ;) 
Dziękuję.
Zamykam

**Comment by chilek** [comment]
Przenoszę zatem poprawkę do LMS Plus stable.
