### ISSUE TITLE
Etykiety dla taryf

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#842]
Znalazłem kilka drobnostek do poprawy:
1. W 'tarifftaginfo' zmieniłbym 'Zapisz' na 'Dodaj' (w boxie obok jest 'usuń'). Funkcja submit dotyczy tylko jednego boxa.
2. Nie widać, które etykiety lub w ogóle czy są wybrane. Przydała by się taka informacja na pasku filtrowania.
3. W 'rtcategoryedit'  wydaje mi się, że coś nie gra w pliku html'u/css. 'Zaznacz Wszystkie' nie jest oznaczony jako odnośnik a wygląda jak zwykły tekst.

**Comment by chilek** [comment]
Ad 3. - bo to jest etykieta do checkboks-a, a nie link. Docelowo wszystkie etykiety powinny być html-owymi labelami, a nie anchorami.

**Comment by chilek** [comment]
Ad 2 - tylko jak tam upchnąć wizualnie listę wszystkich wybranych etykiet?

**Comment by interduo** [comment]
Ad 2 - Najprościej przycisk "Resetuj Etykiety" mógłby mieć wtedy inny kolor np zielony/czerwony gdy filtrowanie jest w użyciu a normalny gdy żadna z etykiet nie jest wybrana.
Ad 3 - Rozumiem. To idąc za ciosem przydała by się możliwość klikania w wiersz celem zaznaczenia checkbox'a jak w innych formularzach.

**Comment by chilek** [comment]
Ad 3:
https://github.com/lmsgit/lms/commit/c00d12098e47fb795a3d4221060417c5a008d6f5

To pozwoli na łatwe implementowanie tej funkcji przez dodanie klasy **row-all-check** dla wiersza tabeli.

**Comment by chilek** [comment]
Ad. 2: ale inny kolor nie ukaże Ci jakie etykiety są wybrane.
A może ten przyciski resetujący powinien mieć opis w środku:
"Resetuj: lista etykiet" i jeśli tego tekstu jest więcej niż np. 50 znaków to kończyłby się "...", a w chmurce byłaby pełna lista?

**Comment by interduo** [comment]
Ad 2: cokolwiek zrobisz będzie dobrze, tak jak proponujesz jest wystarczająco

**Comment by chilek** [comment]
A może coś takiego jak na zrzucie ekranu?
![zrzut ekranu z 2016-09-12 11-35-14](https://cloud.githubusercontent.com/assets/1457437/18431497/601ad01c-78dd-11e6-9902-4da0ead3e6f2.png)

**Comment by interduo** [comment]
Tak jak na zrzucie jest idealnie.

Ad 3:  Wrzuć jeszcze tą klasę w ?m=userpanel&f=rights oraz w ?m=userpanel&module=info&f=changes.

**Comment by chilek** [comment]
Czy w ogóle warto ten interfejs klikania przycisków z etykietami przy taryfach zostawiać?
W sumie wybór wielu etykiet z listy wyboru załatwi wszystko, a pola można zostawić jako linki do samych etykiet?

**Comment by interduo** [comment]
Jeśli mówisz o o 'tarifflist' to w pełni rację.

**Comment by chilek** [comment]
Commit https://github.com/lmsgit/lms/commit/58363812e3459f8a8ca18bb55d349d88cde8ec83 załatwi sprawę. Przy okazji - można będzie już w miarę sensownie używać pola multiwyboru w innych filtrach dla list zasobów.

**Comment by interduo** [comment]
Lista taryf przy rozwijaniu listy:
Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/lms/templates_c/8bbdaea7274e092a7d84d7c607eb987e72fdc032_1.extendsall.tarifflist.html.php on line 1102 >Etykieta1

Było "Composer update; rm templates_c/*.php"

Problem występuje tylko do czasu pierwszego wyboru.

**Comment by chilek** [comment]
Poprawione.

**Comment by interduo** [comment]
Ok to wszystko oprócz pkt 1 jest zamknięte. 

Kwestia etykiety "Zapisz" pojawia się też w innych formularzach tego typu.
np. usergroupedit, nodegroupedit, customergroupedit

Moim zdaniem powinno być tam dodaj ponieważ funkcja submit nie dotyczy całego formularza a poszczególnego boxa.

**Comment by chilek** [comment]
ad. 2: 162209a (klasa nazywa się multi-check w tym przypadku i pozwala z shiftem na zaznaczenie grupowo wierszy checkboksów).

**Comment by interduo** [comment]
ad 1: ?

**Comment by interduo** [comment]
Ad 1:
Jak wyżej napisałem Kwestia etykiety "Zapisz" pojawia się też w innych formularzach tego typu.
np. usergroupedit, nodegroupedit, customergroupedit.

Moim zdaniem powinno być tam dodaj ponieważ funkcja submit nie dotyczy całego formularza a poszczególnego boxa.

Jeśli nie chcesz tego zmieniać z jakiegoś powodu proszę zamknij to zgłoszenie bo pozostałe rzeczy zostały zrobione.
