### ISSUE TITLE
Helpdesk - rtmessageadd

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#843]
Do aktywnego zgłoszenia dodaję odpowiedź: 

Wpisuję treść odpowiedzi. 
Załączam plik, klikam zapisz. 

Treść odpowiedzi się dodaje niestety bez załącznika.

**Comment by chilek** [comment]
Zapewne brak ustawionego katalogu na załączniki helpdesku.
Katalog wskazuje ustawienie **rt.mail_dir**.

**Comment by interduo** [comment]
rtmessageview przydał by się podgląd załączników obrazkowych taki jak w rtticketview.

**Comment by interduo** [comment]
Ustawienie zmiennej mail_dir w lms.ini faktycznie pomogło.
