### ISSUE TITLE
Helpdesk - rtmessageview

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#844]
W 'rtmessageview' przydał by się podgląd załączników obrazkowych taki jak w 'rtticketview'. 

W przypadku kiedy wrzucamy do helpdeska zdjęciową dokumentację instalacji/serwisu i mamy 10 zdjęć za każdym razem trzeba klikać i otwierać poszczególne zdjęcia.

Przeglądać zdjęć bezpośrednio w 'rtmessageview' nie bardzo się da ponieważ jeśli mamy kilka odpowiedzi - wyjeżdzają za ekran.

**Comment by interduo** [comment]
![zrzut ekranu z 2016-08-23 13 54 32](https://cloud.githubusercontent.com/assets/17087236/17891002/a54a64da-6939-11e6-9f4c-9405dde3e766.png)

**Comment by chilek** [comment]
Ciekawe jak by to zachowało się w wersji rozwojowej, bo tam został zmieniony silnik napędzający podpowiedzi z miniaturkami obrazków. Sprawdzę w wolnej chwili na demo.

**Comment by chilek** [comment]
Zobacz tutaj:
http://demo.lms.org.pl/?m=rtticketview&id=5

**Comment by interduo** [comment]
A może w http://demo.lms.org.pl/?m=rtmessageview&id=24 obrazek mógłby się pokazywać automatycznie?

**Comment by interduo** [comment]
Na demo.lms.org.pl nie ma już tego problemu. Udało mi się go wywołać dosłownie dwa razy przez przypadek ale nie umiem tej sytuacji zwielokrotnić. Jeśli ten silnik napędzający podpowiedzi z miniaturkami wleci do lms-git zgłoszenie do zamknięcia ;)

**Comment by chilek** [comment]
Rzuć okiem teraz na demo i spróbuj kliknąć na obrazek.

**Comment by chilek** [comment]
Zamykam sprawę - będzie w następnej wersji stabilnej LMS Plus.
