### ISSUE TITLE
Filtry z możliwością wielokrotnego wyboru

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#845]
Przydałaby się możliwość dodania wielokrotnego wyboru w pasku filtrów w 'rtqueueview'.
A głównie chodzi mi o pola: 'Kolejka','Kategorie'. 

Mając dużo zgłoszeń i kilka kolejek ciężko raportować pracę serwisantów bez takiej możliwości.
Ciężko też pracować na zgłoszeniach na wielu kolejkach jednocześnie.

Kolejne miejsce z takim polem to: [customersearch] oraz GRUPY. Przydałaby się możliwość listowania klientów z więcej niż jednej 'Grupa', 'Grupa Komputerów', 'Status', 'Typ Taryfy'.

Chodzi mi o taką rozwijaną rozwijaną listę jak w 'eventadd' w polu 'wybierz użytkownika'.

**Comment by chilek** [comment]
To co tu piszesz wymagałoby bardzo dużego przebudowania systemu filtrów, bo specjalnie dla wybranych formularzy nie ma sensu coś takiego robić. Może kiedyś do tego wrócimy.

**Comment by interduo** [comment]
Przeniesiono do LMSplus.
