### ISSUE TITLE
Customerinfo - indywidualne pole do umowy

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#846]
Przydałby się checkbox czy klient:
"Klient wnosi o dostarczanie zmiany warunków Umów drogą elektroniczną na adres poczty elektronicznej lub za pośrednictwem ebok"

W umowie oczywiście pełna treść wniosku.

**Comment by chilek** [comment]
To raczej powinieneś dorobić we własnym zakresie, bo każdy to załatwia we własnym zakresie.
