### ISSUE TITLE
Integracja Terminarza i Helpdesku

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#847]
Na nasze potrzeby napisaliśmy sobie integrację terminarza z helpdeskiem. W strukturze organizacyjnej firmy równolegle działają dwie komórki:

Część zgłoszeń musi mieć określony dokładny czas wykonania a w szczególności mówimy tutaj o sprawach związanych z klientami: Instalacja, Serwis, Modernizacja. Przed integracją Terminarza z Helpdesk wklejaliśmy do terminarza numer id zgłoszenia z Helpdesk. 

Z powodu logiki obsługi zdarzeń i zgłoszeń w LMS oraz przyjętych w firmie procedur postępowania brak powiązania zgłoszenia w Helpdesk ze zdarzeniami w Terminarzu powodował: 
- Brak możliwości przejrzystego podglądu zgłoszenia wraz z powiązanymi zdarzeniami.
- Utrudnienia w kontroli tego jakie działania, kiedy, przez kogo i z jakim wynikiem zostały podjęte w celu rozwiązania problemu.
- Serwisantom łatwiej było „zapomnieć” o wiszących w terminarzu „rzeczach do zrobienia”, które nie mogły być w danym czasie wykonane a powinny być wykonane w najbliższym możliwym czasie.
- Pojawiały się problemy w komunikacji pomiędzy BOK i TOK.  

Wdrożony ficzer wygląda u nas tak:
![lms-formularz_dodawania_zgloszenia](https://cloud.githubusercontent.com/assets/17087236/17897186/911ef114-6953-11e6-8098-b33d75d35f52.png)
![lms-widok_zgloszenia](https://cloud.githubusercontent.com/assets/17087236/17897187/9120c80e-6953-11e6-83fc-a122800e6419.png)
![lms-terminarz](https://cloud.githubusercontent.com/assets/17087236/18316962/c8f7eaee-751c-11e6-8e97-2b63ef20a8b1.png)

Tomku, jak widzisz wdrożenie tego do LMSplusa? 
Podejrzewam, że trzeba będzie to napisać od podstaw ponieważ my nasz kod pisaliśmy na wersji z gita z końca 2013 roku.

**Comment by chilek** [comment]
Nie widzę przeciwwskazań, aby takie coś zintegrować z waniliowym lms nawet w ramach na bieżąco dostępnej wersji rozwojowej, a do stabilnej LMS Plus trafi po prostu z pewnym opóźnieniem.

**Comment by fhucomax** [comment]
+1
Także uważam, że taka funkcjonalność, którą zaproponował Jarek przydałaby się bardzo ;)
Jeśli nie w tej to, chociaż w następnej stable.
Chociaż skoro u Jarka to działa, to może wcale nie taki diabeł straszny Tomku?
Ryszard Tęcza

**Comment by interduo** [comment]
Przeniesione do LMSplus.
