### ISSUE TITLE
Indywidualna informacja na fakturze dla klienta

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#849]
Przydał by się komentarz umieszczany w treści faktury np w ramce "UWAGI:" lub "KOMENTARZ:"
np. 'Faktura dotyczy zamówienia XXX/2016' lub 'Dokument sporządzony zgodnie z umową ZXY/2016"

Treść komentarza powinna być definiowalna w zależności od klienta.

**Comment by chilek** [comment]
Wydaje mi się, że to tego można wykorzystać któreś z już istniejących pól klienta.

**Comment by fhucomax** [comment]
Broń Boże! ;)

Np. u nas już wszystkie obecne są wykorzystane do innych celów.

A osobne pole z uwagami do drukowania na fakturze – jak najbardziej popieram!

Może być np. w sekcji pod „Alternatywne rachunki bankowe” w tym samym układzie i z nazwą np.: „Uwagi do faktury”

 

Pozdrawiam.

Ryszard Tęcza

**Comment by chilek** [comment]
To trzeba byłoby gruntownie przemyśleć, bo coś takiego jak informacje na bazie czego jest generowana faktura można byłoby i zakodować w stopce faktury - trzeba byłoby chyba tylko dodać jakieś specjalne znaczniki/symbole, które byłyby podmieniane np. ostatnim co do daty dokumentem klienta (albo jakoś inaczej).

**Comment by interduo** [comment]
Ja bym dodał w bazie w tabeli 'invoices' kolumnę 'comment'. 
Uzupełniałbym ją w 'invoicenew' oraz w 'invoiceedit'.

Na szablonie umieściłbym tą informację raczej na samym dole pod 'UWAGI' najlepiej w czarnej,wycentrowanej poziomo ramce, żeby pokazać że ta informacja jest ważna.

**Comment by interduo** [comment]
Tak zauważyłem, że w szablonie faktury 'standard' w wydruku PDF nie ma również nagłówka i stopki, które są określone w 'divisionedit'.

**Comment by chilek** [comment]
@interduo nagłówek i stopka brane są z dokumentu-faktury, a nie z firmy. Nagłówek i stopka faktury z firmy są kopiowane do dokumentu-faktury z momentu jej wystawienia. Jak sens miałoby zmienienie stopki i faktury z jednoczesną zmianą we wszystkich fakturach wystawionych w przeszłości?

**Comment by interduo** [comment]
Nie miałoby to sensu ale:
Zmieniłem dane w 'Konfiguracja/Firmy'.
Utworzyłem nową fakturę w 'Finanse/Nowa Faktura'.
Na utworzonym dokumencie w szablonie html (invoice.html) oraz pdf (standard) nie widzę nagłówka ani stopki.

**Comment by chilek** [comment]
A klient jest przypisany do tej firmy? To co opisujesz wskazywałoby, że to w ogóle nie działa tak jak trzeba, a do tej pory nikt takiego problemu nie zgłosił...

**Comment by interduo** [comment]
OK, popełniłem błąd. Dodałem najpierw klienta później uzupełniłem pole 'Firma'. Po przypisaniu klienta do firmy i stworzeniu nowej faktury wyświetlają się te pola na szablonie. 

Niestety najeżdżają na siebie ale ok to nie problem poradzę sobie z tym przy poprawianiu szablonów. To zamykam ten podwątek i wróćmy do wątku głównego.

**Comment by interduo** [comment]
OK, skoro nagłówek i stopka są brane z dokumentów to gdzie się to ustawia?

Moim zdaniem brakuje w formularzu 'invoicenew' pola uwagi i kolumny w bazie danych.

**Comment by interduo** [comment]
Czy na formularzu: 
https://lms/?m=invoicenew 
dałoby radę dodać pole Uwagi/Komentarz ?

Pole wartość tego pola mogłaby być dodawana na koniec STOPKI i to najprościej zamknełoby zgłoszenie. Dałoby to super funkcjonalnośc bardzo niskim kosztem.

**Comment by interduo** [comment]
Rozwiązane.
