### ISSUE TITLE
 Helpdesk - rtticketprint

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#850]
Nie drukuje całej historii zgłoszenia. A przydałoby się, najlepiej razem z obrazkowymi załącznikami.

Trudniejsze zgłoszenia bardziej treściwe drukujemy bezpośrednio z przeglądarki przez co drukuje się wiele niepotrzebnych rzeczy.

**Comment by interduo** [comment]
1. Przydała by się też opcja drukuj bez notatek.
2. Brakuje dolnej kreski zamykającej okno notatki
3. Czy nie byłoby fajnie móc dodać kilka załączników do jednej notatki hurtem?
(My do niektórych typów zgłoszeń helpdeskowych przypisujemy średnio ~5 zdjęć).

**Comment by chilek** [comment]
> Czy nie byłoby fajnie móc dodać kilka załączników do jednej notatki hurtem? (My do niektórych typów zgłoszeń helpdeskowych przypisujemy średnio ~5 zdjęć).

od wczoraj w wersji rozwojowej pojawiła się możliwość (w ogóle) dodawania załączników do notatek, bo do wczoraj tego nie było, a i oczywiście wiele załączników można dodać. Nie wiem na podstawie jakiej wersji używanej przez Ciebie piszesz zgłoszenia, ale mam wrażenie, że na podstawie jakiejś archaicznej? ;-)

**Comment by chilek** [comment]
> Nie drukuje całej historii zgłoszenia.

Tu chyba powinna być jakaś opcja wyboru, czy drukuje tylko pierwszy komentarz, czy drukuje wszystko, czy drukuje tylko wszystkie wiadomości ze zgłoszenia bez notatek. Być może jakąś nową opcją konfiguracyjną.

> A przydałoby się, najlepiej razem z obrazkowymi załącznikami.

Drukowanie z obrazkowymi załącznikami jest bardzo dyskusyjne, bo może powodować duże zużycie tonera/tuszu...

**Comment by interduo** [comment]
Mam testing. Tylko git pull'a robiłem wczoraj :))) Wprowadzasz zmiany jak burza.

Co do drukowania zgłoszeń, ja to widzę tak:

rtticketprint:
bez obrazków, ze wszystkimi notatkami, ze wszystkimi odpowiedziami

rtmessageview:
pokazywanie od razu wszystkich obrazków w notatce (nie po najechaniu myszą)

**Comment by chilek** [comment]
> pokazywanie od razu wszystkich obrazków w notatce (nie po najechaniu myszą)
np. ?m=rtmessageview&id=7

to spowoduje rozjechanie się formatowania historii zgłoszenia z dużym prawdopodobieństwem.

**Comment by interduo** [comment]
Ok to może się wyświetlać miniaturkę o stałym rozmiarze np 150x150? 

Chodzi mi o to, żeby nie szukać zdjęcia myszą fotki jak masz ich 20 w zgłoszeniu tylko od razu najechać na właściwe.

**Comment by interduo** [comment]
4. Brak możliwości dodania notatki bez treści ale ze zdjęciami.

**Comment by chilek** [comment]
>  Brak możliwości dodania notatki bez treści ale ze zdjęciami.

i bardzo dobrze, tylko czy wtedy puste pole treści notatki wyświetla Ci na czerwono?

**Comment by interduo** [comment]
Tak wyświetla się na czerwono. 
Czasami jedyną 'treścią' notatki są zdjęcia.

**Comment by interduo** [comment]
5. Jeśli załączysz trzy pliki do notatek i nie wpiszesz treści zgłoszenia znikają załączone pliki i musisz je załączać kolejny raz (rtnoteadd).

**Comment by chilek** [comment]
Taka zmiana wymaga znacznych modyfikacji kodu, a najlepiej napisania uploadu plików zupełnie od zera...

**Comment by chilek** [comment]
Zrobione na wszystkich file uploaderów w helpdesku na całkowicie nowym uploaderze plików działającym w ajaksie, jquery nawet z oknem postępu uploadu.

**Comment by interduo** [comment]
Uploader działa spoko!
