### ISSUE TITLE
Terminarz

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#851]
Bardzo duży krok na przód jeśli chodzi o wygląd terminarza te typy zdarzeń aż się ucieszyłem je widząc :)
1. Przydałaby się jeszcze kolumna "Uruchomione usługi":
   z ikonkami Ziemi, Telefonu, Telewizji, Kamerki. Uzupełniona symbolem przypadku, gdy klient ma więcej niż jedną usługę.

Chciałbym przez to uczulić serwisantów, by dodatkowo sprawdzili po serwisie działanie reszty świadczonych usług. Czasami zachodzi potrzeba indywidualnej konfiguracji urządzenia, również w wydruku terminarza widziałbym taką informację. Ja trzymam takie informacje je w komputerach klienta w polu 'dodatkowe informacje'.

.2. Tekst w kolumnie "Typ" w wydruku również bym wyśrodkował w pionie.

.3. Zmienił bym ten czarny pasek z racji tego, że terminarz się drukuje - po co zużywać nadmiernie toner?:) Biały wygląda równie fajnie.

.4. Przydałaby się informacja czy:
- zdarzenie było przeniesione
- czy zdarzenie jest wpisane na podstawie zgłoszenia czy jest wolnym zgłoszeniem (trochę kontynuacja #847).

**Comment by interduo** [comment]
6. Brakuje spacji między calendar.gif a treścią wydarzenia.

**Comment by interduo** [comment]
.7 W 'eventlist' przyciski strzałek przy kolumnie "klient" nie powiększają i nie zmniejszają się.

**Comment by interduo** [comment]
.8. Rozbiłbym w 'eventprint' Klienta na dwie kolumny 'Klient' i 'Lokalizacja'
Klient - Imię, Naziwsko, Telefon, Telefon komórkowy 
Lokalizacja - Adres instalacji: ulica nrdomu/nr lokalu, miejscowość
Dzięki temu może wydruk terminarza by się skrócił.

**Comment by interduo** [comment]
.8 Zwiększyłbym o połowę rozmiar kolumn: "Użytkownik", "Klient".

**Comment by chilek** [comment]
Kwestia gustu...

**Comment by interduo** [comment]
A konkretnie o czym mówisz? Raczej kwestia czy chcemy długi wydruk czy krótki.

Np. 
![terminarz1](https://cloud.githubusercontent.com/assets/17087236/18385879/6ce67dc4-7693-11e6-8d94-72bd06eb33b1.png)

Dzięki takiemu rozbiciu podziałowi dałoby się w przyszłości zaznaczyć więcej niż jedną lokalizację do serwisu u danego klienta. W jednym wydarzeniu.

**Comment by interduo** [comment]
Gdy się to podzieli na: 1% 1% 70% 14% 14% całość wygląda tak:

![terminarz2](https://cloud.githubusercontent.com/assets/17087236/18390217/8e6a884e-76a9-11e6-8e21-bc303852ce92.png)

Jedno wydarzenie zajmuje sporo mniej linii.

**Comment by chilek** [comment]
https://github.com/lmsgit/lms/commit/0b12b8dd707545a22a57be95017fadebe27654f7
