### ISSUE TITLE
Różne szablony dla faktur 

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#852]
Przydała by się możliwość wyboru różnych szablonów dla faktur bo czasami trzeba dokonać zmiany w szablonie faktur:
np.
- zmiana wyglądu faktury, np. dodany motyw świąteczny na fakturach z grudnia,
- zmiana ułożenia, 
- zmiany treści,
- obecność druczka wpłat

Wszystkie stare faktury powinny być wyświetlane na szablonie obowiązującym w momencie ich tworzenia.

**Comment by interduo** [comment]
2. Czy da się ustawić nazwę pliku w 'attachment_name' w formacie nazwafirmy_numerfaktury ?

**Comment by chilek** [comment]
@interduo w jakim kontekście?

**Comment by frychlich** [comment]
Np tak faktura_nr_%number.pdf

**Comment by interduo** [comment]
Chodzi mi o nazwę pliku gdy generujemy fakturę PDF.

**Comment by interduo** [comment]
Użytkownik dostaje brzydko nazywający się plik 'invoices.pdf'.

**Comment by chilek** [comment]
@interduo: użytkownik, czy klient? Poza tym sugeruję nie tworzyć w danym wątku 10 różnych pod wątków, bo dzięki temu zwiększasz poważnie szansę, że ostatecznie danym tematem nikt nie zajmie się, bo nawet nie będzie wiedział czego dotyczy zgłoszenie...

Obecnie nazwy plików z fakturami są sterowalne dla plików pojedynczymi fakturami. Nie za bardzo jest jak sterować obecną metodą tworzenia szablonów nazw plików dla plików pdf, które zawierają wiele faktur. Poza tym po co na tym się koncentrować jak można to załatwić w prosty sposób zmieniająca nazwę pliku w lokalnie używanym systemie operacyjnym. Rzeczywiście tak wiele wykonujesz tę czynność miesięcznie, że warto dodawać złożony mechanizm, który będzie nadawał specyficzne nazwy plików przechowujących wiele faktur. Podejrzewam, że najczęściej ma to miejsce raz w miesiącu, a jest wiele innych elementów LMS i LMS Plus, gdzie czynności wykonywane są codziennie i tam coś lepiej optymalizować...

**Comment by interduo** [comment]
Ok, będę rozbijał to na najmniejsze możliwe sprawy.

Nie chcę zmieniać nazwy pliku gdy on zawiera wiele faktur PDF. 

Chodziło mi o dwie sytuacje:
- **klient** drukuje tylko **jedną** fakturę przez panel użytkownika 
- **użytkownik**  drukuje tylko **jedną** fakturę przez GUI LMSa

Nazwa pliku, który pobiera klient/użytkownik drukując fakturę mogłaby być inna dla każdej faktury:
np. ZXC-'nrfaktury'.pdf.

"Obecnie nazwy plików z fakturami są sterowalne dla plików pojedynczymi fakturami."
Jak tym sterować?

**Comment by chilek** [comment]
Zależy czy dla ręcznie pobranych czy wysyłanych automatycznie skryptem **bin/lms-sendinvoices.php**. Ustawienie nazywa się ....**.invoice_filename** - tylko nazwa sekcji zależy od tego jak generujesz fakturę (sendinvoices lub phpui). Obsługiwane symbole:
- %invoice - numer faktury,
- %docid - identyfikator dokumentu,
- %number - numer faktury,
Znaki specjalne (/[^[:alnum:]_\.]/i) zastępowane są znakiem '_'.

**Comment by interduo** [comment]
Tomku, czy da się dodać wszystkie te ustawienia z ustawieniami domyślnymi do GUI? Szukałem tam  oraz w dokumentacji tego przed zadaniem pytania.

**Comment by chilek** [comment]
@interduo: to nie jest dobry pomysł, ale wytłumaczenie dlaczego jest zbyt złożone, żeby tu opisywać. Pewnie bym się napisał, a nikt by nie zrozumiał (albo prawie nikt ;-)).
Raczej dokumentacja powinna być uzupełniania w miarę możliwości czasowych.
Aktualnie staram się całkowicie przebudować interfejs ładowania plików, żeby m.in. były zapamiętywane wybrane pliki pomiędzy kolejnymi zatwierdzeniami formularzy zakończonymi błędem.
Nie jest to, jak się okazuje, takie proste. Pewnie wyjdzie z 2 dni robocze...

**Comment by interduo** [comment]
![phpui](https://cloud.githubusercontent.com/assets/17087236/18201243/47742814-7109-11e6-963d-3c5ce998e556.png)

Ustawiam zmienną tak.
Dodaję nową fakturę.

Faktura ma nadal nazwę invoices.pdf w GUI po kliknięciu ikonki 'print.gif' w 'Konto klienta' w customerinfo.

**Comment by chilek** [comment]
Ahh przepraszam. W UI nazywa się to ustawienie:
**invoices.attachment_name**

**Comment by interduo** [comment]
OK to ustawienie działa to pozostała już tylko kwestia szablonów faktur.

**Comment by chilek** [comment]
Dla faktur PDF musiałoby być trzymanych tyle wersji kodów generujących faktury ile potencjalnych szablonów. Alternatywą mogłoby być konwertowanie faktur na stałe do plików PDF i nie martwienie się o szablony wykorzystywane w przeszłości.
Wg mnie obsługa wielu szablonów faktur PDF niesie niewiele potencjalnych korzyści w stosunku do potrzebnego nakładu pracy do realizacji tego.

**Comment by chilek** [comment]
Inny pomysł: rozwiązać motywy graficzne faktur jako faktury ze wskazaniem graficznego, półprzezroczystego tła, ale moim zdaniem wszelkie udziwnienia graficzne powodują niepotrzebne rozrastanie się faktur w sensie objętościowym i większe zużycie CPU serwera na potrzeby generowania...

**Comment by interduo** [comment]
Czy to jakiś duży techniczny problem mieć nawet 20 plikow z szablonami?

Ja to technicznie widzę tak: 
- do tabeli invoices dochodzi kolejna kolumna z nazwą szablonu
- faktura jest generowana zgodnie z tym polem, jeśli pole jest nieuzupełnione to generuje PDF z domyślnego szablonu

Ale czy to jakiś grubszy problem mieć np 2,4,5 a nawet 50 plików z szablonami faktur?

Ja to widzę tak że do tabeli invoices dochodzi kolejna kolumna z nazwą szablonu i faktura jest generowana zgodnie z tym polem.

Założe się, że większość z nas ma jakoś tam brandowane faktury na swój sposób/styl. Ten branding też ewoluje w czasie. Dzięki szablonom masz możliwość zmiany czegokolwiek co nie leży w bazie nie 'psując' poprzednich faktur.

**Comment by chilek** [comment]
Problem techniczny to nie jest, ale warto jeszcze zastanowić się nad tym, czy przychody firmy wzrosną od liczby różnych szablonów faktur...

Niech inni się jeszcze wypowiedzą w tym temacie.

**Comment by kyob** [comment]
Według mnie zbędny bajer :)

**Comment by interduo** [comment]
To może inaczej: 
Czy jest jakaś możliwość wyłączenia drukowania/wyświetlania starszych faktur niż rok w userpanelu lub możliwośc ustawienia drukowania/wyświetlania faktur tylko z roku ubiegłego?

**Comment by chilek** [comment]
> Większość commitów niepowoduje bezpośrednio wzrost przychodów.

Zapomniałem napisać, że najlepsze commity to te, które generują potencjalnie wzrost przychodów lub obniżają/optymalizują koszty firmy (a więc wpływają na dochód ;-)).

**Comment by chilek** [comment]
> Czy jest jakaś możliwość wyłączenia drukowania/wyświetlania starszych faktur niż rok w userpanelu lub możliwośc ustawienia drukowania/wyświetlania faktur tylko z roku bieżącego?

Chodzi o to, żeby wygląd starych faktur nie zmieniał się po zmianach w kodzie generującym faktury *pdf?

**Comment by interduo** [comment]
Dokładnie tak. 

Generujemy przez 12 miesięcy faktury zachodzi potrzeba zmian na stałe edytujemy szablon. Stare faktury chcemy wyświetlać po staremu.

**Comment by chilek** [comment]
A może tworzyć na dysku cache faktur pdf, który będzie wszystkie starsze niż jakiś tam okres przekształcał do pdf?

**Comment by interduo** [comment]
Uważasz, że szybsze jest to do wdrożenia niż zaproponowane przeze mnie rozwiązanie? Czy to co proponujesz rozwiązuje dodatkowo jakiś inny problem?

**Comment by chilek** [comment]
@interduo na pewno szybsze, bo sprowadza się do skryptu backendowego, który pobiera wszystkie faktury (identycznie jak lms-sendinvoices.php) i zamiast słać na maila zapisuje do wskazanego katalogu z cache.

**Comment by interduo** [comment]
Tak się nad tym zastanawiałem. Cache faktur starszych niż np miesiąc to w naszym przypadku kilka tysięcy miesięcznie. Trzeba by to jakoś sensownie wygenerować i magazynować ( to są już grube gigabajty ) i puchnie to zdrowo z każdym miesiącem,rokiem. Średnio dokument dwustronicowy w HTML zajmuje 20KB a w PDF zajmuje 10x tyle.

Co lepiej?
a) mieć te dokumenty zapisane w postaci plików
**b) generować przy każdym żądaniu**

Moim zdaniem tak jak jest teraz jest OK. Co do innych dokumentów w HTML. Też puchną sobie ale zużycie na poziomie:

$ du -sh ./documents/
152M	./documents/

Jest praktycznie pomijalne.

**Comment by interduo** [comment]
Dzisiaj wpadliśmy na inny sposób realizacji tego issue - pole w bazie PDFFILE. 

Funkcjonowałoby tak, że:
jeśli w bazie w polu PDFFILE jest nazwa pliku to zostaje on wczytany podczas podglądu. Jeśli natomiast polebyłoby puste - faktura generowała by się z danych w bazie.

Plan jest taki by zamknięte okresy rozliczeniowe archiwizować właśnie w taki sposób 
(np. skryptem lms-payments). Faktury wrzucone do PDF automatycznie zatwierdzałyby się czyli byłyby zblokowane finalnie do edycji.

Dzięki temu można by zmieniać szablon - co okres rozliczeniowy.

**Comment by chilek** [comment]
Zaimplementowane w rozwojowej - gałąź **master**. Będzie w LMS 24.0 i w LMS+ 24.x.

**Comment by interduo** [comment]
Według mnie nie wszystko zostało zaimplementowane:
Brakuje możliwości stworzenia  dwóch szablonów i wyboru przy tworzeniu FV.

Głównie chodzi o różnice:
- branding per firma (logo, kolory)
- druczek/bez druczka

**Comment by chilek** [comment]
Po co?

**Comment by interduo** [comment]
1. Masz dwie firmy w LMS chcesz, żeby FV inaczej wyglądały kolorystycznie.

2. Dla klientów biznesowych druczek jest zbędny i często tam jest tyle pozycji, że druczek generuje się na drugiej stronie co wygląda koszmarnie.

**Comment by chilek** [comment]
Moim zdaniem jak zwykle przesadzasz.

**Comment by interduo** [comment]
A jak to zrealizować inaczej?

**Comment by chilek** [comment]
Odpowiedź: jest dużo rzeczy do zrobienia bardziej przydatnych niż to co tu piszesz.

**Comment by interduo** [comment]
Co do nr 1:
Musisz pogadać z jakimś maretingowcem i zrozumieć dlaczego branding jest ważny i jak bardzo jest ważny w każdym z pism/dokumentów.

Co do nr 2:
https://github.com/lmsgit/lms/issues/952 - tutaj @frychlich wyjaśnił, że ten druczek nie jest potrzebny

Tak masz rację - priorytety zgłoszeń, każdy ma inne ;)
