### ISSUE TITLE
Domyślne drukowanie kopii dokumentu

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#853]
Przydałaby się opcja pozwalająca wyłaczyć domyślne drukowanie kopii dokumentu w:
- 'customerbalance',
- 'balancelist',
- 'receiptadd'

**Comment by chilek** [comment]
**invoices.default_printpage**

**Comment by interduo** [comment]
Przeoczyłem. Dzięki za pomoc.

**Comment by interduo** [comment]
Włączając bezpośrednio: https://lmsplus/?m=receipt&id=12 np poprzez kliknięcie ikonki 'printr' w 'balancelist' to nie ma zastosowania.

**Comment by interduo** [comment]
Tak samo jest w 'customerinfo' dla dokumentów KP. Dla faktur działa to prawidłowo.

**Comment by chilek** [comment]
Dla dokumentów kasowych obowiązuje po prostu inna zasada - jako, że i tak trafiają na jedną kartkę to zawsze drukuje się kopia i oryginał.
Zauważyłem za to chyba inny błąd - jak wciśnie się drukuj dla zaznaczonych dokumentów kasowych na dole to generuje się błędny kod pdf...

**Comment by interduo** [comment]
W tym momencie nie ma potrzeby oznaczania faktur jako orginał/kopia dlatego zamiast dwóch proponuję zatem wyświetlić domyślnie jeden i w razie ewentualnej potrzeby drukować dwie kopie za pomocą menagera wydruku. 

My drukujemy jeden egzemplarz KP dla klienta na A5.

**Comment by chilek** [comment]
Tymczasem poprawka błędu, który wcześniej znalazłem:
552da91bea66b08412486e459cf3037a432e5be6

**Comment by chilek** [comment]
> W tym momencie nie ma potrzeby oznaczania faktur jako orginał/kopia dlatego zamiast dwóch proponuję zatem wyświetlić domyślnie jeden i w razie ewentualnej potrzeby drukować dwie kopie za pomocą menagera wydruku.

Nie wiadomo czy w innych krajach to nie jest potrzebne, więc na razie zostanie jak jest (w końcu ustawieniem można to sobie wyregulować).

**Comment by chilek** [comment]
Commit 6d2c9db115dfce1cf7ac3a7b9cda4d78a3cc3e65 powinien załatwić sprawę ostatecznie tak, żeby "wszyscy byli zadowoleni".

**Comment by interduo** [comment]
Czy jest gdzieś w jakimś manualu spis wszystkich zmiennych konfiguracyjnych w LMS?
