### ISSUE TITLE
ezpdf - brak górnego odstępu w komórkach tabeli na fakturze

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#854]
![ezpdf-rozjazd](https://cloud.githubusercontent.com/assets/689112/17932010/50063b40-6a0e-11e6-93f9-baaffc46841b.png)

U Was też tak to wygląda?

Reszta jest OK, ale tabelka katastrofa.

**Comment by interduo** [comment]
Ja po zmianie zmiennej na 'invoice.type' na pdf mam białego PDF'a na testowym repo. Coś jeszcze muszę zrobić oprócz tego?

**Comment by kyob** [comment]
@interduo nie na temat :)

Dodam, iż z **tcpdf** faktura wygląda prawidłowo tzn. nie ma żadnych wizualnych baboli.

**Comment by interduo** [comment]
U mnie tylko tekst w kolumnie 'Nazwa produktu, towaru lub usługi'. Wszystkie inne kolumny są OK.

**Comment by kosaa** [comment]
nienaprawialne w krótkim czasie, trzeba poprawić bibliotekę ezPDF

p.s. gdyby ktoś znalazł czas to można podesłać zmianę autorowi
https://github.com/didaxRedux/php-ezPDF

**Comment by kyob** [comment]
Zamykam zostaje przy tcpdf.
