### ISSUE TITLE
ezpdf - brak salda oraz nr konta do wpłat

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#856]
Silnik **tcpdf** uwzględnia saldo i nr konta do wpłat, a **ezpdf** nie pokazuje tych informacji na fakturze.

Tak ma być czy to błąd?

**Comment by interduo** [comment]
U mnie to samo, brak tych elementów na wygenerowanej fakturze.

**Comment by chilek** [comment]
Raczej błąd w głowie ;-) Najlepiej zajrzeć do kodu i zobaczyć jakie ustawienia i symbole specjalne dla ezpdf odpowiadają za wyświetlanie rachunków.

**Comment by chilek** [comment]
No i poza tym w tym zakresie zaszły zmiany w wersji rozwojowej, żeby możliwości odnośnie numerów rachunków dla tcpdf i ezpdf były podobne.

**Comment by kyob** [comment]
Zamykam zostaje przy tcpdf mimo cięższych plików.
