### ISSUE TITLE
Podział: Komputery Klienta na 'Lokalizacje klienta', 'Urządzenia klienta'

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#864]
Tak się dzisiaj zastanawiam trochę czy nie warto by było podzielić 'Komputery Klienta' na:
- Lokalizacje klienta (tutaj trzymał bym tylko dane teleadresowe,geolokalizacyjne lokalizacji instalacji u danego klienta)
- Urządzenia sieciowe klienta (brakuje miejsca gdzie można trzymać indywidualne informacje/parametry co do urządzeń sieciowych, nie chcę tworzyć węzłów sieciowych i tych urządzeń wrzucać w 'Sprzęty sieciowe' bo robi się nieporządek)

Chodzi mi o takie informacje jak np.:
- kto konfigurował/instalował dane urządzenie (sytuacja: lokalizacja się nie zmienia, urządzenia w w lokalizacji klienta w sieci wewnętrznej się zmienia)
- siła sygnału PON/radiowego podczas instalacji,
- login/hasło do jakiegoś tunelu jeśli klient uruchomione inne usługi, 
- SSID/WPA2/hasło do zarządzania na router bezprzewodowy,
- komentarz dotyczący konkretnego urządzenia sieciowego w lokalizacji.

- dobywa tych urządzeń coraz to więcej: STB, kamery IP, rejestratory IP, aparaty/terminale VoIP, alarmy z zarządzaniem poprzez IP, NASy, centalki PBX...pojawia się tego coraz to więcej u klientów. Trzeba nad nimi panować.

- precyzyjnie wyglądałoby to w dzienniku zdarzeń.

W tym momencie 'Komputery' podłącza się bezpośrednio do sieci raczej tylko w sieciach firmowych, w domach większość ludzi ma routery wi-fi zamiast komputerów. Możemy dodać kilka komputerów ale w tym przypadku zajmujemy niepotrzebnie adres IP, który ma sprawdzanie czy się nie powtarza w naszej bazie co niewłaściwe (klasa prywatna abonenta) lub jest taki widząc urządzenie od strony operatora (np. gdy na urządzenie możemy się dostać tylko przez przekierowany jeden port).

Dzięki temu również można by np. pre-konfigurować 50 dowolnych urządzeń sieciowych dla klientów i je przerzucać z magazynu do danego klienta. I na podstawie tych danych później generować jakieś dokumenty.

Dzięki temu możnaby przypisywać również zobowiązania do lokalizacji zamiast do poszczególnych urządzeń.

Co wy o tym sądzicie?

**Comment by greenlms** [comment]
Dobry pomysł.
I w tym przypadku adres podany w "Lokalizacja klienta" powinien trafić do raportu UKE - jako punkt adresowy budynku.
Natomiast w "Urządzeniach klienta" byłby spis wszystkich urządzeń (AP, VoIPy, a jeśli ktoś chce to nawet komputery) klienta, którymi opiekuje się ISP.

**Comment by interduo** [comment]
Kwestia rodzaju informacji i ich powiązań:
1. Klient może mieć usługi w wielu lokalizacjach lub usługi nieprzypisane do lokalizacji np. hosting, ramowa umowa na np. usługi serwisowe. 
2. Do jednej lokalizacji możemy przypisać wiele urządzeń sieciowych lub nie przypisywać żadnego urządzenia. 
3. Urządzenia sieciowe mogą być nie przypisane do żadnej z lokalizacji np. FlyMobile ale być u klienta. Wymaga to przypisania klienta do lokalizacji głównej (tej rejestrowej z customerinfo).
4. Lokalizacje mogą istnieć bez klienta (np. to mogą być dodane miejsca gdzie mamy zasięg lub gdzie mieliśmy kiedyś klienta)
5. Umowa jest przypisana bezpośrednio do klienta ale zawiera lokalizacje jedną lub wiele
6. Urządzenie sieciowe może być przypisane do węzła lub klienta lub może być brak przypisania (plugin stock mógłby dodawać urządzenia sieciowe od razu tutaj)
7. Urządzenie sieciowe może posiadać adres IP lub wiele adresów lub go nie posiadać (parametr Urządzenie sieciowe abonenta)
8. Urządzenie sieciowe musi posiadać conajmniej jeden MAC adres
9. Do urządzeń sieciowych obsługujących VoIPa pozwoliłbym przypisywać konta VoIP tak by było wiadomo które urządzenie posiada, które konto
VoIP.
10. Tabela lokalizacje zawiera kod TERYT
11. Zobowiązania są przypisane do urządzeń (klient może mieć wiele usług w jednej lokalizacji, ale fajnie by było móc je wybrać jednym klikiem albo wybrać zobowiązanie INTERNET dla Lokalizacji X. I nie wybierać urządzeń)
12. Jedno zobowiązanie może być przypisane do jednego lub wielu urządzeń sieciowych lub lokalizacji
13. Dokumenty pozwoliłbym łączyć w grupy (nie można zadecydować który dokument jest główny w przypadku umów 3play, ponieważ użytkownik może rozwiązać jedną z nich, grupę oznaczyłbym ID klienta).

**Comment by chilek** [comment]
@interduo czy to jest opis powiązań miedzy informacjami, czy raczej chodzi o wyłapanie na obecnym etapie pewników? Swoją drogą ten ostatni komentarz warto chyba uczynić odrębnym zgłoszeniem w github issues projektu LMS Plus i zatytułować jakoś tak, żeby było wiadomo, że dyskusja ma na celu uporządkowanie powiązań między zasobami klienta.

**Comment by greenlms** [comment]
Większość opisałem już na https://github.com/chilek/lms-plus/issues/104

> 1. Klient może mieć usługi w wielu lokalizacjach lub usługi nieprzypisane do lokalizacji np. hosting, ramowa umowa na np. usługi serwisowe.

To już jest teraz w LMS i nie trzeba nic zmieniać – Hosting lub Serwis nie musi być przypisany do żadnej lokalizacji, bo tego nie raportuje się do SIIS. Wystarczy więc, że będzie zobowiązanie na koncie klienta (zobowiązanie utworzone ręcznie lub za pośrednictwem szablonu specjalnej Umowy, takiej w której nie wybiera się lokalizacji). A zobowiązanie możesz przypisać do dowolnej ilości Urządzeń abonenckich (obecnie do _nodes_, a wg mojej propozycji do _nodedevices_).
P.S. Dużo tego hostingu sprzedajesz w stosunku procentowym wszystkich zawieranych umów?

> 2. Do jednej lokalizacji możemy przypisać wiele urządzeń sieciowych lub nie przypisywać żadnego urządzenia.

Tak, lokalizacja zakończenia sieci może być pusta bez urządzeń oraz bez umów (jedynie zawsze powinna być przypisana do Klienta), patrz CTRL+F tablica nodeterminals w https://github.com/chilek/lms-plus/issues/104
Do Lokalizacji może być przypisanych wiele Urządzeń abonenckich (tych z warstwy L2/L3).
A kiedyś w przyszłości można by tak samo zrobić dla Sprzętu dzierżawionego ze STOCK (L0/L1).

> 3. Urządzenia sieciowe mogą być nie przypisane do żadnej z lokalizacji np. FlyMobile ale być u klienta. Wymaga to przypisania klienta do lokalizacji głównej (tej rejestrowej z customerinfo).

W sytuacji kiedy Klient kupuje tylko FlyMobile, to raczej powinieneś stworzyć Lokalizację zakończenia sieci (i wypełnić adres TERYT tożsamy jak ten w tabeli _customers_), tak by móc prawidłowo raportować adres TERYT tej usługi do SIIS. Czyli przynajmniej 1 Lokalizacja zawsze musi być, nawet z przepisanym zwykłym adresem podanym przez klienta do Umowy.

Jeśli jest coś co nie ma adresu IP,MAC to raczej bym to zaliczył do Sprzętu dzierżawionego (L0/L1), (tzn. dzierżawionego ze STOCK, ale to jest inny temat: https://github.com/chilek/lms-plus/issues/81 ), powinniśmy tutaj tego nie rozważać teraz, tylko w wątku związanym z magazynem oraz wypożyczaniem Sprzętu nie posiadającego IP (dowolnego Sprzętu dzierżawionego ze STOCK (L0/L1)).

> 4. Lokalizacje mogą istnieć bez klienta (np. to mogą być dodane miejsca gdzie mamy zasięg lub gdzie mieliśmy kiedyś klienta)

Lokalizacje gdzie mamy zasięg, ale nigdy klienta nie było(?), to raczej ciężki pomysł do zrobienia, bo je precyzujesz z dokładnością do lokalu w budynku, a zasięg sieci w SIIS opisujesz z dokładnością jedynie do budynku.
Ogólnie chwilowo proponuję nie realizować tego pomysłu, za dużo czasu by na to poszło.

Lokalizacje (tablica _nodeterminals_) gdzie mieliśmy kiedyś klienta (bo zrezygnował) zostaną na zawsze w bazie SQL w tablicy _nodeterminals_ z przypisanym _customerid_ do tego klienta. W razie gdy nie będzie już tam urządzeń, które mają aktywne zobowiązania, to dozwolone mogłoby być, aby _nodeterminalis.id_ edytować i przepisać do innego klienta zmieniając jedynie _customerid_ (a za tą zmianą podążą Urządzenia do nowego klienta, gdyż każdy _nodedevices_ jest przypisane do _nodeterminals.id_ czyli do Lokalizacji - wg mojej propozycji). Taka sytuacja wystąpi gdy klient sprzedaje/sprzedał swój dom, a Nowy Klient od razu podpisuje nową Umowę. Wtedy stara Umowa jest zrywana za porozumieniem stron (bez kar umownych), a ten Nowy Klient podpisuje nową Umowę na 2 lata. Następuje zmiana dla wybranych wpisów _nodeterminals.id_ na nowy _customerid_, i automatycznie od tego momentu wszystkie Urządzenia abonenckie które wskazują na ten _nodeterminalid_ już są u nowego klienta.

> 5. Umowa jest przypisana bezpośrednio do klienta ale zawiera lokalizacje jedną lub wiele

Wiele lokalizacji na jednej umowie? To błąd, przeanalizuj proszę jeszcze raz, ale dokładniej.
kontrahent->umowa->posesja <<-- to jest niekorzystna opcja, uzasadniłem to już
posesja->kontrahent->umowa <<-- o tym piszesz w pkt. 4., też nie jest dobre
**kontrahent->posesja->umowa <<-- to jest najlepsza opcja, dająca największe możliwości**

> 6. Urządzenie sieciowe może być przypisane do węzła lub klienta lub może być brak przypisania (plugin stock mógłby dodawać urządzenia sieciowe od razu tutaj)

To już jest wątek o samym STOCK i Sprzętu dzierżawionego (L0/L1) dla Klienta.
Tym proponuję zająć się nie teraz, a w przyszłości, jak już te podstawowe rzeczy będą zrobione.

> 7. Urządzenie sieciowe może posiadać adres IP lub wiele adresów lub go nie posiadać (parametr Urządzenie sieciowe abonenta)

Urządzenie sieciowe musi posiadać IP, a jeśli nie posiada, to jest jedynie Sprzętem dzierżawionym z magazynu (i taki Sprzęt powinien być już częścią STOCK, jako dzierżawiony dla Klienta).
Chyba że masz na myśli ten sprzęt, który jest za NATem i własnością Klienta? Do tego służy opcja Adresy URL do zarządzania w opcjach Komputera (po nowemu by było w opcjach "Urządzenia abonenckiego").

> 8. Urządzenie sieciowe musi posiadać conajmniej jeden MAC adres

Też tak uważam. A skoro ma MAC, to i powinno mieć jakiś IP.

> 9. Do urządzeń sieciowych obsługujących VoIPa pozwoliłbym przypisywać konta VoIP tak by było wiadomo które urządzenie posiada, które konto VoIP.

Nie mam zdania na ten temat.

> 10. Tabela lokalizacje zawiera kod TERYT

Też tak uważam.
P.S. To dlaczego chcesz sprzedawać FlyMobile bez lokalizacji TERYT? ;-)

> 11. Zobowiązania są przypisane do urządzeń (klient może mieć wiele usług w jednej lokalizacji, ale fajnie by było móc je wybrać jednym klikiem albo wybrać zobowiązanie INTERNET dla Lokalizacji X. I nie wybierać urządzeń)

Tak, zgadzam się.
Zobacz moją propozycję https://github.com/chilek/lms-plus/issues/104 - wybierz tam CTRL+F szukaj zdanie "Po tych zmianach w CONTRACT-PROMO moglibyśmy wybierać tylko nodeterminals(dawniej: nodes)"

> 12. Jedno zobowiązanie może być przypisane do jednego lub wielu urządzeń sieciowych lub lokalizacji

Jedno zobowiązanie może być przypisane do 1 lub wielu Urządzeń abonenckich (L2/L3), pod warunkiem, że te wybrane Urządzenia należą do jednej tej samej Lokalizacji.
Ponadto zobowiązanie powinno być przypisane tylko do 1 Umowy (propozycja tabeli _assigments.docid_).

> 13. Dokumenty pozwoliłbym łączyć w grupy (nie można zadecydować który dokument jest główny w przypadku umów 3play, ponieważ użytkownik może rozwiązać jedną z nich, grupę oznaczyłbym ID klienta).

W tym przypadku masz dwa główne dokumenty osobne:
umowę na internet i telefon,
umowę na telewizję.

**Comment by interduo** [comment]
AD1. Nie dużo. 

Musi być możliwośc przypisania zobowiązania również do lokalizacji. 
Np. Obsługa informatyczna za lokalizację Y. 
Administracja siecią firmową za lokalizację X.
Dzierżawa ciemnego włókna (LokalizacjaA, Lokalizacja B)
Transmisja danych L2 (LokalizacjaA, Lokalizacja B)
Wirtualna sieć prywatna (LokalizacjaA, LokalizacjaB, LokalizacjaC)


Ad2. 
Karta FlyMobile posiada IMEI, jak zlokalizujesz tą kartę?
Czy my jako operator musimy inwentaryzować FlyMobile czy zrobi to operator FlyMobile?

Ad3.
Lokalizacja powinna być oddzielnym tworem oddzielną tabelą, możesz sobie dodać lokalizacje i ich nie przypisywać a możesz je dodać i przypisać - Twój wybór. Puste lokalizacje to mogą być lokalizacje tam gdzie mamy gniazdka/mieliśmy klienta/łatwa instalacja tak by marketerzy wiedzieli gdzie pukać/dzwonić. Co do historii przypisać danej lokalizacji jestem za. 

Ad5.
Dlaczego nie mogę mieć ramowej umowy na wszystkie lokalizacje? Często jest tak że z niektórymi klientami podpisuje się umowę i aneksuje dodając tylko lokalizacje to wygodne.
Nadal nie zmienia to struktury o której piszesz. 

Jest Kontrachent --> Lokalizacja zakończenia sieciowego--> Sprzęt sieciowy

Umowa odnosi się do lokalizacji zamiast do kontrachenta.
Protokół uruchomienia usługi zawiera lokalizacje oraz sprzęt sieciowy.

Ad6
Chyba lepiej to od razu zmodyfikować ale na pewno wcześniej przegadać. 
Moim zdaniem obecny podział na: 'Komputery' i 'Sprzęt sieciowy' jest zdeaktualizowany i sztuczny. Komputerom potrzebne są właściwości urządzeń z sprzęt sieciowy. To nie jest wątek o samym stock.

Ad7
Możesz sprzedać abonentowi switcha zarządzalnego zbudować mu sieć i zapiąć do niego wkładkę SFP po za pomocą VLANów możesz wyrzucić swoje łącze na jego router. Fajnie mieć to w sprzętach klienta ponieważ jak będzie Ci port flapował to będziesz wiedział że na linku jest jeszcze jedno urządzenie.

Ad8
Urządzenie mając adres MAC nie musi mieć adresu IP. 

Przykład?
*Urządzenia L2 
*niezarządzalny terminal pon z jednym portem gigowym
*STB u klienta (w usłudze jambox: Ty znasz serial i mac, adres ip się zmienia i jest nadawany przez operatora usługi)

Ad9
Na jakiej podstawie określić TERYT Flymobile? Ja bym przypisywał takie usługi do danych rejestrowych firmy.

Ad 12
Nie prawda. Pamiętaj że kij dwa końce, proca ma trzy. 
Jeśli sprzedajesz usługę np. transmisji danych (tutaj masz dwa końce), VPN to końców będzie conajmniej dwa (więc może być trzy,cztery, 10).

Ad 13
Pamiętaj że nie zawsze klient ma usługi w pakiecie. 

Przykład klient biznesowy: 
Np. ma Internet symetryczny światłowodowy i indywidualną telefonię na XX numerów i terminali SIP. 

Tutaj nie zadecydujesz, która umowa jest główna bo klient jak rozwiąże Internet to nie zdemontujesz urządzeń transmisyjnych ponieważ służą również do usługi telefonii.

**Comment by interduo** [comment]
Przenoszę tą dyskusję do https://github.com/chilek/lms-plus/issues/118 oraz zamykam to zgłoszenie bo:
- zrobiła się z tego trochę grubsza sprawa, 
- nie chcę duplikować zgłoszeń,
- kilka rzeczy już się zmieniło od pierwotnego posta w trakcie dyskusji na mailliście/githubie.

**Comment by chilek** [comment]
Fajnie byłoby, żeby ktoś w wiki prowadził aktualny stan opisu, bo potem czytanie będzie trudne jak będzie się czytało długie wątki z wymianą opinii :(

**Comment by interduo** [comment]
Też dostrzegłem ten problem, może edytować pierwszego posta z założeniami, jeśli coś się zmieni?

**Comment by chilek** [comment]
@interduo a czemu nie w wiki trzymać w postaci artykułu - będzie i historia zmian i jednolita treść ;-)

**Comment by interduo** [comment]
Mam dostęp tutaj do wiki?

**Comment by interduo** [comment]
OK, wrzucę na wiki.
