### ISSUE TITLE
Czysta instalacja GIT, branch:master, import pliku schematu Postgres

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#865]
To tak:
$ psql
CREATE DATABASE lms ENCODING='UTF8';
\c lms
\i ./lms.pgsql

2016-08-29 18:41:31 CEST [3459-1] lms@lms BŁĄD:  relacja "tariffs" nie istnieje
2016-08-29 18:41:31 CEST [3459-2] lms@lms WYRAŻENIE:  CREATE TABLE voip_tariff_rules (
                id integer DEFAULT nextval('voip_tariff_rules_id_seq'::text) NOT NULL,
                tarifid integer NOT NULL
                        REFERENCES tariffs (id) ON DELETE CASCADE ON UPDATE CASCADE,
                ruleid integer NULL
                        REFERENCES voip_rules (id) ON DELETE CASCADE ON UPDATE CASCADE,
                PRIMARY KEY (id)
        );

Reszta dalej zostaje olana i przy każdym querry:
BŁĄD:  bieżąca transakcja została przerwana, polecenia ignorowane do końca bloku transakcji

**Comment by kosaa** [comment]
nowa instalacja czy update?

**Comment by kosaa** [comment]
patrzyłem pełny schemat, wszystko działa

zmieniałeś coś w schemacie?

**Comment by chilek** [comment]
W wierszu:
https://github.com/lmsgit/lms/blob/master/doc/lms.pgsql#L757
jest odwołanie do tablicy **tariffs**, a jej definicja występuje dopiero dalej:
https://github.com/lmsgit/lms/blob/master/doc/lms.pgsql#L834
!

**Comment by chilek** [comment]
Commit d0dcd3f powinien rozwiązać problem i dla mysql i postgresql.
