### ISSUE TITLE
userpanel force_ssl

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#866]
Czy tutaj jest błąd [L122](https://github.com/lmsgit/lms/blob/master/userpanel/index.php#L122
) ?
```php
$_FORCE_SSL` = ConfigHelper::checkConfig('userpanel.force_ssl', ConfigHelper::getConfig('phpui.force_ssl'));
```

Chyba wystarczy tak jak tutaj [L129](https://github.com/lmsgit/lms/blob/master/index.php#L129
) ?
```php
$_FORCE_SSL = ConfigHelper::checkConfig('phpui.force_ssl');
```

**Comment by chilek** [comment]
Nie no lepiej mieć chyba możliwość niezależnego forsowania ssl dla userpanelu?

**Comment by kyob** [comment]
OK teraz widzę tą opcję. Jakoś wcześniej nie zauważyłem checkboxa dla ssl w userpanel
