### ISSUE TITLE
Helpdesk - brak podglądu załączników w zgłoszeniach

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#870]
LMS aktualna wersja z git. Dodałem zgłoszenie w helpdesku i wgrałem załącznik. Następnie w zgłoszeniu szukam i szukam, ale nie mogę znaleźć tego załącznika. Gdzie można podejrzeć wgrane załączniki do zgłoszeń?

PS: Nowy uploader plików jest spoko :)

**Comment by chilek** [comment]
Powinny być widoczne przy wiadomościach lub notatkach jako listy załączników.
Zobacz czy w logach php/serwera www i audit.log nie masz błędów w czasie wgrywania załączników.

**Comment by kyob** [comment]
Gdzie powinny być zapisywane załączniki?

**Comment by interduo** [comment]
Tam gdzie kieruje zmienna z mail_dir z sekcji rt.

**Comment by kyob** [comment]
Bingo nie miałem potrzeby wcześniej tego ustawiać :)
