### ISSUE TITLE
cashregedit, rtqueueedit - brak opcji zaznacz wszystko dla danego użytkownika

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#880]
Gdy dodajemy użytkowników zawsze się oklikamy w checkboxy. Przydałoby się zaznaczać wszystkie checkboxy dla danego użytkownika (wszystkie checkboxy poziomo) po kliknięciu w podświetlony pasek z danym użytkownikiem.

Np. w documenttypesedit jest to ładnie zrobione poprzez kolejnego checkboxa "pełne prawa", który zaznacza pozostałe (ale nie ma tam już "zaznacz wszystko" które zaznacza pionowo chechboxy w danym typie dokumentów).

**Comment by chilek** [comment]
Takiej opcji nie będzie, ale za to 1670ed0c6c29ddc19531be62da96ecd9858982eb daje możliwość klikania na całym wierszu, żeby wszystkie uprawnienia zaznaczyć!
