### ISSUE TITLE
Filtr wyświetlania / drukowania faktur dla różnych firm.

### ISSUE THREAD

**Issue by toplek** [lmsgit/lms#884]
Przydałby się dodatkowy filtr 'Firmy (Oddziały)'  na liście LMSGUI->Finanse->Lista Faktur
(invoicelist) oraz LMSGUI->Finanse->Raporty->Faktury. Będzie to przydatne przy wydruku faktur np. na papierze firmowym dla różnych firm.

**Comment by chilek** [comment]
cff7bb07fe7dd58c31fccf905d786ef45f7a26f2 dodaje możliwość wyboru firmy w raportach finansowych dla faktur.
Dla listy faktur raczej to będzie mało praktyczne, bo jak trzeba wydrukować dużo faktur to niewygodnie jest przechodzić po kolejnych stronach z fakturami i drukować za każdym razem.
