### ISSUE TITLE
Feature: Users rozbicie <name> na <name/firstname> i <surname/lastname>

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#886]
Zgłaszam zapotrzebowanie na rozbicie **Imię i nazwisko** na dwa pola **Imię** i **Nazwisko**

Pozwoli to np. sortować alfabetycznie po nazwisku użytkowników, gdy dodajemy zgłoszenie.

Może ktoś ma wolne zasoby czasowe, bo ja aktualnie nie mam czasu, ale jeśli nikt się nie podejmie to w wolnych chwila naskrobie pulla.

**Comment by chilek** [comment]
@kyob w którym miejscu miałoby to być rozbite? ;-) W bazie danych od zawsze jest rozbite w customers na lastname i name ;-)

**Comment by kyob** [comment]
Nie **customers** a **users** :)

**Comment by chilek** [comment]
Aaaa, założyłem, że jak każdy mylisz customers z users, a to ja tym razem pomyliłem ;-)
Przyjąć zasadę przy dzieleniu dotychczasowych wpisów, że wszystkie podciągi tekstowe dzielone spacjami do przedostatniego włącznie to imiona, a ostatni to nazwisko?

**Comment by kyob** [comment]
Można tak przyjąć, ale bezpieczniej i przyszłościowo jest rozbić.

**Comment by chilek** [comment]
No tak, ale żeby rozbić to trzeba wiedzieć jak rozbić obecnie istniejące imiona i nazwiska ;-)

**Comment by kyob** [comment]
Aha :) w takim razie powinno być dobrze tak jak napisałeś.

**Comment by kyob** [comment]
OK coś tam już skrobię. Proponuje rozbić to na etapy.

1. Aktualizacja schematu bazy.
2. Skrypt migracyjny.
3. Ingerencja (całościowa lub moduł po module) w kod LMS zastąpienie users.name => users.firstname i users.lastname
4. Finał w chenglogu :)

Tak czy inaczej byś to @chilek byś widział?
