### ISSUE TITLE
voipaccountlist,voipaccountbillinglist - warningi

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#887]
Przy wyborze z głównego menu:
"Lista kont VoIP" lub "Lista Bilingów"

Warning: Invalid argument supplied for foreach() in /var/www/html/lms/lib/LMSManagers/LMSVoipAccountManager.php on line 103

Warning: Invalid argument supplied for foreach() in /var/www/html/lms/lib/LMSManagers/LMSVoipAccountManager.php on line 111

**Comment by chilek** [comment]
duplikat #890
