### ISSUE TITLE
Nodeadd - Brak błędu gdy niewybrany klient

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#888]
![nodeadd](https://cloud.githubusercontent.com/assets/17087236/18382160/195c8a94-7680-11e6-8e1d-bec63df6c92e.png)

Tak wypełniam. Klikam zapisz. Zero komunikatu, zero czerwonych pól. Czyściłem templates_c.
Proszę zerknijcie czy u was działa.

Czasami jak robię u siebie merg'a to wygląda to tak:
https://media.giphy.com/media/s4AxMEKhn5AfC/giphy.gif :D

**Comment by kyob** [comment]
Tak się dzieje, gdy nie wybierzesz klienta. Tutaj brakuje informacji zwrotnej w postaci komunikatu. Też się kiedyś na tym naciąłem.

**Comment by interduo** [comment]
Faktycznie, nie wyłapałem tego. 
Śpię dzisiaj coś :)

**Comment by chilek** [comment]
Co dokładnie trzeba wyklikać, że powtórzyć problem?

**Comment by interduo** [comment]
Dodać komputer z Komputery-->"Nowy Komputer", a w formularzu omyłkowo nie wybrać Klienta któremu przypisujemy komputer.

**Comment by interduo** [comment]
W najnowszym master problem już nie występuje. 
A chciałem naprawić bo już umiem :-)
