### ISSUE TITLE
Nodegrouplist - Dziwne radiobuttony

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#889]
Brak opisów do radio buttonów w tabeli z listą grup komputerów. 
Tak sobie trochę gram w te kropki przy piątku i widzę że kolejność grup się zmienia przez to.

U mnie wygląda to tak:
![nodegrouplist](https://cloud.githubusercontent.com/assets/17087236/18383796/741cbfc4-7687-11e6-89c1-bf7c7a025bab.png)

**Comment by chilek** [comment]
Tak - temu one służą, tj. zmianie kolejności grup komputerów. Kolejność grup komputerów można wykorzystać, np. do ustawienia kolejności sekcji generowania pliku konfiguracyjnego do narzędzi typu pinger. Kiedyś w przyszłości jak będzie na to w ogóle zapotrzebowanie będzie można przerobić te radio buttony na metodę wykorzystującą drag&drop do przeciągania nazw grup między sobą.

**Comment by interduo** [comment]
A może warto je jakoś opisać? Zamiast Razem w nagłówku (które jest też na dole), może "Kolejność" ?
