### ISSUE TITLE
voipaccountlist,voipaccountbillinglist - duże czcionki w menu

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#890]
Różne wielkości czcionek w paskach sortowania. Wygląda, że w HTML/CSS czegoś gdzieś nie ma.

Też trochę brak konsekwencji w tworzeniu, dla porównania:
"voipaccountbillinglist" (duża czcionka bez ikonek)
"rtqueueview" (mała czcionka, ikonki)
"documentlist" (mała czcionka, bez ikonek)

U mnie wygląda to tak:
![voipaccount](https://cloud.githubusercontent.com/assets/17087236/18383427/d255211e-7685-11e6-846e-b3f8f03fa328.png)

**Comment by chilek** [comment]
Pewnie wynika to z tego, że na górze masz warningi.

**Comment by chilek** [comment]
a03cd6a powinno rozwiązać problem.
