### ISSUE TITLE
eventinfo - warningi gdy dane zdarzenie nie ma podanych ram godzinowych

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#891]
m=eventinfo&id=1 gdy dane zdarzenie nie ma podanych ram godzinowych

Czas rozpoczęcia: 	
Warning: math: function call x not allowed in /var/www/html/lms/vendor/smarty/smarty/libs/plugins/function.math.php on line 66
:
Warning: math: function call x not allowed in /var/www/html/lms/vendor/smarty/smarty/libs/plugins/function.math.php on line 66

**Comment by chilek** [comment]
Wyłącz przede wszystkim warningi w php używanym produkcyjnie. To co opisujesz to ostrzeżenie podchodzące ze smarty, więc jeśli już to tam zgłoś ten problem.

**Comment by interduo** [comment]
OK, czyli nie meldować zgłoszeń z warningami?

**Comment by kyob** [comment]
Problemy ze **smarty** meldować do https://github.com/smarty-php/smarty :)

**Comment by interduo** [comment]
Błąd zgłoszony i naprawiony w smarty https://github.com/smarty-php/smarty/issues/288.

**Comment by chilek** [comment]
Jak wyjdzie smarty 3.1.31 z poprawką to po zmianie w composer.json odnośnie wymagań smarty:
```sh
composer update
```
podbije wersję na tą już poprawioną.
