### ISSUE TITLE
Smarty truncate a długości nazw

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#894]
Jest taki mały problemik np. z:
https://github.com/lmsgit/lms/blob/master/templates/default/customer/customerassignmentsedit.html#L98

U nas nazwy promocji są dość długie i 40 znaków to za mało. Początek nazw promocji jest identyczny, wiec wybierając promocję tak naprawdę nie wiemy co wymieramy.

Zwiększanie wartości **truncate** to może być zabawa w kotka i myszkę.

**Jak to można ugryźć, żeby można w pewnym zakresie tym sterować?**
1. Umożliwić dla każdego **truncate** sterowanie z poziomu **phpui**
2. Może globalne on/off **truncate**  w **phpui**
3. Wybrać tylko takie, które faktycznie mogą się rozrosnąć i tylko nimi sterować z **phpui**
4. Inne rozwiązanie?

**Comment by chilek** [comment]
Ale jak pozwolisz na dłuższe to Ci się zacznie w przeglądarce rozjeżdżać - nie mówiąc o telefonach i tabletach. Chyba ideałem byłoby pokazywanie w chmurce wybranej wartości.

**Comment by kyob** [comment]
Chmurka to jest dobry pomysł.

**Comment by chilek** [comment]
A jak pojawia się chmurka z podpowiedzią czego dotyczy pole to w efekcie skleić zawartość na zasadzie "nazwa_promocji" + "dotychczasowa_podpowiedź"?

**Comment by kyob** [comment]
Moja propozycja: https://github.com/lmsgit/lms/pull/939

**Comment by chilek** [comment]
To może być bardzo dobry pomysł. Niech jeszcze inni zrzucą okiem czy jest ok.

**Comment by kyob** [comment]
https://github.com/lmsgit/lms/pull/939 merged, więc zamykam.
