### ISSUE TITLE
Terminarz a aktualna data

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#895]
Jako, że terminarz nie otwiera się z aktualną datą często u nas dochodzi do pomyłek z wpisaniem sprawy z błędną datą. Problem zawsze się nasila w godzinach porannych, gdy terminarz zazwyczaj otwiera się z datą z dnia poprzedniego.

**Pomysły jak temu zaradzić, aby nie rozwalić obecnego status quo?**

Pomysły na szybko:
1. Zdefiniowanie w **phpui._nazwa-tego-ustrojstwa_** - otwieraj zawsze z dniem dzisiejszym po zalogowaniu do LMS
2. Informacją ostrzegająca, iż operujemy na innym dniu niż dzisiejszy.
3. Inne pomysły?

**Comment by interduo** [comment]
Terminarz otwiera się zawsze tam gdzie go ostatnio otwierałeś. U nas nie spotykamy się z tym problem często (może z raz przez te kilka lat się zdarzyło). To kwestia osoby, która wprowadza dane w formularz i nie zwraca uwagi na dane w formularzu.

4. Blokada dodawania zdarzeń w przeszłości dla użytkowników bez pełnego dostępu (?)
5. Możliwość włączenia 'przymusowego ręcznego wybierania daty w formularzy' dla pracowników, którym się zdarza błąd. (?)
6. Dzięki, https://github.com/lmsgit/lms/issues/847 - jest mniejsze prawdopodobieństwo że coś Ci zginie.
Serwisanci rozliczają u nas zdarzenia (Terminarz), a kierownik Zgłoszenia (Helpdesk).

**Comment by chilek** [comment]
@kyob https://github.com/lmsgit/lms/blob/master/doc/ChangeLog#L56

**Comment by kyob** [comment]
@chilek Tak to wystarczy. Zamykam.

Dla potomnych: `phpui.settings_timeout = 0`
