### ISSUE TITLE
eventedit, eventadd - radiobutton "Wszyscy użytkownicy"

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#896]
W formularzu m=eventedit i m=eventadd jest jedno małe niedopatrzenie, jest radiobutton "Wszyscy użytkownicy". Do czego On jest skoro lista wyboru użytkowników jest wyżej?

**Comment by chilek** [comment]
Pewnie jest po to, żeby nie trzeba było z listy wielowyboru wybierać poszczególnych użytkowników.

**Comment by interduo** [comment]
To w takim razie nie działa właściwie, bo nie da się go odznaczyć/zaznaczyć. 
Może opcja mogłaby być w liście z checkboxami ? Przy jej zaznaczeniu odznaczały by się inne lub przy jej zaznaczeniu nie przypisywałby po prostu nikogo mimo wybrania innych checkboxów?

**Comment by wawryk** [comment]
Jak nie masz zdefiniowanych grup użytkowników to ten przycisk nie służy do
niczego. A jak sobie telefonujesz grupy użytkowników np admini i serwisanci
to jest Ci łatwiej później szukać osoby na krótkiej liście zamiast na mega
dlugiej. Dodatkowo w phpui była jakąś opcja z tym związana

12 wrz 2016 13:09 "Interduo" <notifications@github.com> napisał(a):

**Comment by interduo** [comment]
OK, przespałem wprowadzenie "Grup użytkowników".
