### ISSUE TITLE
Automatyczne otwieranie Zakładek w customerinfo

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#899]
Automatycznie otworzyłbym zakładki w customerinfo w sytuacji gdy:
- klient ma niezatwierdzony dokument - zakładka "Dokumenty klienta"
- klient ma niezamknięte zadanie w terminarzu - zakładka "Terminarz"
- klient ma otwarte zgłoszenie w helpdesku (https://github.com/lmsgit/lms/issues/898) - Zakładka "Helpdesk"
- klient ma ujemne saldo - zakładka "Konto klienta"
- klient nie przeczytał wiadomości w userpanelu - zakładka "Wiadomości klienta"

**Comment by chilek** [comment]
A moim zdaniem jeśli już o czymś sygnalizować to w podobny sposób jak o zgłoszeniach w helpdesku - obok innych "przycisków" klienta.

**Comment by interduo** [comment]
No tak - ale mimo wszystko po otrzymaniu komunikatugdy będziemy chcieli wejść tam to mimo wszystko najszybszą droga będzie to zakładka na dole (w tym momencie zamknięta ).

**Comment by kyob** [comment]
Dorzucę swoje trzy grosze.

Można jeszcze rozważyć zastosowanie np. [tabs](http://v4-alpha.getbootstrap.com/components/navs/#tabs), bo po co przewijać tyle strony.

Coś takiego tylko to jest jeszcze mocno "niedorobione" :)
![screenshot from 2016-09-12 22-50-13](https://cloud.githubusercontent.com/assets/689112/18452608/ee01f35c-793b-11e6-92f7-10e07844d2f9.png)

**Comment by interduo** [comment]
Mamy szersze monitory niż wyższe tak, że jak najbardziej OK. Zakładki z otwartymi/niezatwierdzonymi rzeczami (zdarzenia,zgłoszenia,dokumenty,ujemne saldo) fajnie jak by było jak by były pogrubione.

**Comment by chilek** [comment]
a jak coś takiego zachowa się w telefonie/tablecie?

**Comment by interduo** [comment]
Liczę, że te tabsy ułóżą się po prostu pionowo.

**Comment by chilek** [comment]
@interduo: skoro ekrany teraz są panoramiczne to może na pc lepiej zakładki dawać w poziomie, a nie w pionie (choć wtedy ciężko pokazać więcej na raz rozwiniętych)?

**Comment by interduo** [comment]
Porównam oba jutro na różnych urządzeniach i się wypowiem szczegółowiej.

**Comment by interduo** [comment]
A może zamiast tabów/zakładek zrobić takie BOXy z dość sporym wymiarem (tzw. klaster)? 
Taki teraz trend na nowych stronach www trochę.

Na tabletach po prostu by się one układały jeden nad drugim. Na szerokich monitorach ustawiały by się jeden obok drugiego. Bo w tym momencie na szerokim monitorze w customerinfo przynajmniej połowa miejsca zajmuje pustka.

**Comment by chilek** [comment]
W wersji rozwojowej możesz już poukładać zakładki u klienta i w komputerze wg własnego uznania metodą drag&drop i układ pamiętany jest w ciastku dożywotnio.

**Comment by interduo** [comment]
Ale nie można ułożyć zakładek jednej obok drugiej.
