### ISSUE TITLE
lms-notify.php => Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#900]
Wywyłanie:
```bash
php lms-notify.php -d --type=timetable --channel=mail --section=mail
```

Efekt:
```php
Warning: Invalid argument supplied for foreach() in /var/www/html/lms/bin/lms-notify.php on line 421
```

**Comment by chilek** [comment]
https://github.com/lmsgit/lms/blob/master/bin/lms-notify.php#L421

Ten wiersz jest tu pusty. Możesz wskazać w github, której wersji lms-notify.php używasz?

**Comment by kyob** [comment]
https://github.com/chilek/lms-plus/issues/60

**Comment by chilek** [comment]
Jako, że to już martwy kod w wersji stabilnej 1.11.20.x i w 1.11.21.x będziesz miał całkiem przepisany na razie proponuję doraźnie dostawić:
```php
if (!empty($contacts))
  foreach (...)
```
