### ISSUE TITLE
Terminarz - brak możliwości edycji zdarzenia

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#901]
Złe działanie przycisku edycja z poziomu informacji o zdarzeniu. Jeśli jesteśmy lmsplus/?m=eventinfo&id=7, przycisk EDYTUJ nie posiada numeru zdarzenia (id) w linku.

**Comment by chilek** [comment]
W której wersji?

**Comment by interduo** [comment]
aktualna z git teraz, branch master

**Comment by chilek** [comment]
Sprawdziłem u siebie - problem nie występuje.

**Comment by interduo** [comment]
Możliwe że to przez ten warning ze smarty (math x function)?

**Comment by interduo** [comment]
Wyszło nowe smarty które rozwiązuje ten problem. Jesteś w stanie podbić smarty do nowej wersji?

**Comment by chilek** [comment]
Nie ma jeszcze smarty 3.1.31 w composerowym repo. Możesz sam próbować co jakiś czas modyfikując wiersz:
https://github.com/chilek/lms-plus/blob/master/composer.json#L26

**Comment by interduo** [comment]
Update paczki ze smarty do -dev jednak też nie pomaga na ten problem.

Co ciekawe problem występuje u mnie na dwóch instancjach LMS na Debianie Jessie.

**Comment by interduo** [comment]
@chilek pokaż proszę jaką masz wersję *pcre* na demo2

Czy jesteś w stanie zastąpić funkcję {math}:
https://github.com/lmsgit/lms/blob/master/templates/default/event/eventinfo.html#L35
oraz
https://github.com/lmsgit/lms/blob/master/templates/default/event/eventinfo.html#L52

Przez inną funkcję lub stosując gołe obliczenia ze smarty?

**Comment by chilek** [comment]
@interduo: nie prościej w środowisku produkcyjnym wyłączyć warningi php?

PCRE:
[I] dev-libs/libpcre
     Available versions:  (3) 8.38-r1 8.39
       {bzip2 +cxx +jit libedit pcre16 pcre32 +readline +recursion-limit static-libs unicode zlib ABI_MIPS="n32 n64 o32" ABI_PPC="32 64" ABI_S390="32 64" ABI_X86="32 64 x32"}
     Installed versions:  8.39(3)(12:10:04 PM 12/12/2016)(bzip2 cxx jit readline recursion-limit unicode zlib -libedit -pcre16 -pcre32 -static-libs ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="32 -64 -x32")
     Homepage:            http://www.pcre.org/
     Description:         Perl-compatible regular expression library

**Comment by interduo** [comment]
Tomku gdy nie wyświetla błędów nadal problem istnieje
Link pod przyciskiem edytuj nie ma wypełnionego ID.

**Comment by interduo** [comment]
@chilek gdy nie wyświetla błędów nadal problem istnieje
Link pod przyciskiem edytuj nie ma wypełnionego ID a pola nie mają wypełnionych danych.

**Comment by chilek** [comment]
@interduo: czy na demo2 problem też występuje? Jeśli tak to podaj kroki  jakie wykonać?

**Comment by interduo** [comment]
Na demo2 problem nie występuje. Szukam więc różnic.

**Comment by interduo** [comment]
Moje zgłoszenie na repo smarty https://github.com/smarty-php/smarty/issues/288 zostało zamkniętę i teoretycznie w '3.1.31-dev' (od 11.09.2016) powinno to działać. Composer nie ma tej gałęzi, nie ma też najnowszej wersji. 

@chilek U siebie na demo2 jaką masz wersję smarty?

**Comment by interduo** [comment]
Na forach smartowych sugerują zastąpienie wolnej funkcji math poprzez vaniliowe obliczenia.

**Comment by interduo** [comment]
Zrobiłem tak dodałem w kodzie:
<h1>EVENT.DATE {$event.date} EVENT.BEGINTIME {$event.begintime} EVENT.ENDTIME {$event.endtime}</h1>

Nic nie wyrzuca.

Jak tylko dodam w kodzie {$event.date="0"} wartość pola "Czas rozpoczęcia" wyświetla się prawidłowo.

**Comment by interduo** [comment]
Smarty nie dostaje wartości z bazy z jakiegoś powodu, niezależnie od tego czy w bazie siedzą zera czy inne dane - coś jest nie tego z eventinfo.php/eventprint.html bo w innych modułach (np. eventedit,eventprint) jak najbardziej te dane są dostępne.

@chilek masz pomysł gdzie może leżeć problem?

**Comment by interduo** [comment]
Znalazłem chwilę przejrzałem po kolei cały proces.
Błąd jest w zapytaniu SQL.

```
2016-12-19 14:26:08 CET [23391-2] lmsu@lmsdb WYRAŻENIE:  SELECT events.id AS id, title, description, note, userid, events.creationdate,
					customerid, date, begintime, enddate, endtime, private, closed, events.type, UPPER(c.lastname) || ' ' || c.name AS customername,
				    vusers.name AS username, events.moddate, events.moduserid, events.closeddate, events.closeduserid, nodes.location AS location, c.city || ', ' || c.address AS customerlocation,
				    (SELECT name FROM vusers WHERE id=events.moduserid) AS modusername,
				    (SELECT name FROM vusers WHERE id=events.closeduserid) AS closedusername
				    FROM events
				    LEFT JOIN nodes ON (nodeid = nodes.id)
				    LEFT JOIN customerview c ON (c.id = customerid)
				    LEFT JOIN vusers ON (vusers.id = userid)
				    WHERE events.id = '8'
```

**Comment by interduo** [comment]
2016-12-16 13:35:28 CET [2222-1] lmsu@lmsdb BŁĄD:  kolumna events.closeddate nie istnieje przy znaku 279

**Comment by interduo** [comment]
Na Postgresql 9.6 nie występuje problem.
