### ISSUE TITLE
Wyłączone taryfy w edycji zobowiązania

### ISSUE THREAD

**Issue by beskidmedia** [lmsgit/lms#902]
W czasie edycji zobowiązania z wyłączoną taryfą, nie ma jej na liście i nie można np. skorygować daty. Dobrze byłoby dołożyć aktualnie ustawioną taryfę do listy

**Comment by interduo** [comment]
Gdy taryfa wyłączona nie powinno być możliwości tworzenia nowego zobowiązania z tą taryfą ale jego edycja powinna być dozwolona.

**Comment by chilek** [comment]
To chyba duplikat innego zgłoszenia...

**Comment by frychlich** [comment]
#840

**Comment by interduo** [comment]
Do zamknięcia.
