### ISSUE TITLE
Taryfy - bez naliczeń

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#904]
Na potrzeby backendowych skryptów, które dzielą pasmo do Internetu przydała by się taryfa nie powodująca naliczenia kwot ani wystawienia faktur.

Proponuję w liście rozwijanej 'Naliczanie'  dodać pozycję 'Brak' i dodanie do skryptów lms-payments odpowiedniego warunku.

Np. Urządzenia własne używane na potrzeby świadczenia innych usług
Np. Taryfa testowa dla klientów

Jak wy rozwiązujecie tą kwestię?

**Comment by frychlich** [comment]
Mamy taryfy, które mają wartość 0 i niezdefiniowany okres naliczania

**Comment by interduo** [comment]
Da się niezdefiniować okresu? O extra! :)
