### ISSUE TITLE
Taryfy - różne parametry

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#905]
Np. taryfa z ustawionym typem telewizji ma:

Limit liczby domen:     bez ograniczeń
Limit liczby aliasów:  bez ograniczeń
Limit liczby kont e-mail:   bez ograniczeń
Limit liczby kont shellowych:   bez ograniczeń
Limit liczby kont www:  bez ograniczeń
Limit liczby kont ftp:  bez ograniczeń
Limit liczby kont sql:  bez ograniczeń
Limit rozmiaru konta e-mail:    bez ograniczeń
Limit rozmiaru konta shellowego:    bez ograniczeń
Limit rozmiaru konta www:   bez ograniczeń
Limit rozmiaru konta ftp:   bez ograniczeń
Limit rozmiaru konta sql:   bez ograniczeń 

Moim zdaniem te parametry powinny być widoczne tylko w przypadku wyboru typu taryfy 'hosting'.

**Comment by chilek** [comment]
Jest taki pomysł, żeby z czasem dostępne dla taryfy opcje były zależne od typu, np. jest już zaczątek tego dla taryf typu 'telefonia'.

**Comment by kosaa** [comment]
niepotrzebne pola podczas tworzenia edycji oraz przeglądania taryf nie będą się już pojawiały

można testować, jeśli wszystko ok to do zamknięcia

**Comment by interduo** [comment]
Formularz tariffadd:
jeśli wybiorę typ 'Internet' nadal mam definicję taryf z typu 'hosting'

**Comment by kosaa** [comment]
>1. Dla każdego typu taryfy (internet/hosting/telewizja/telefon/....) da się zadeklarować właściwości, które da się w nich zdefiniować.

nie rozumiem

>2. W formularzu doawania/edycji nowej taryfy wyświetlają się tylko określone w pkt 1 właściwości.

ani tego

>I nadal są te wartości wyświetlane w 'tariffinfo' więc robota nadal nie zrobiona do końca.

feel free to use git pull request option

**Comment by interduo** [comment]
![internet](https://cloud.githubusercontent.com/assets/17087236/19355656/68b7353e-916b-11e6-8dad-bfe729324c22.png)

**Comment by kosaa** [comment]
puściłem już pula - [link](https://github.com/lmsgit/lms/pull/965/commits/914d9b24f111174c40c027711f888effd7286755)

Ciebie interesowały by zmiany w tariffedit.html

**Comment by interduo** [comment]
Nie sprecyzowałem gdzie mnie interesowały zmiany. Miałem nadzieję w domyśle, że pojawią się wszędzie gdzie to wymagane. Natomiast Ty napisałeś 'niepotrzebne pola podczas tworzenia edycji oraz przeglądania taryf nie będą się już pojawiały'.

Czy jest miejsce w kodzie gdzie definiujemy co dana taryfa wyświetla (jakie właściwości) czy jest to zrobione tylko jakimiś warunkami "nie wyświetlaj sekcji hosting gdy taryfa = 'internet' lub taryfa="telewizja" ?

Bo np jeszcze:
- taryfa o typie 'usługa' może mieć parametry hostingu (o jakiej usłudze w tym typie mówimy? np. obsługa informatyczna czy np. usługa transmisji danych?) 
- taryfa o typie 'telewizja' może mieć zadeklarowane prędkości

**Comment by kosaa** [comment]
>taryfa o typie 'telewizja' może mieć zadeklarowane prędkości co jest bez sensu(?)

ma to bardzo wielki senes w przypadku gdy dostarczasz klientowi samą telewizję, wtedy masz możliwość regulowania przepustowości

>Czy jest miejsce w kodzie gdzie definiujemy co dana taryfa wyświetla

tu [link](https://github.com/lmsgit/lms/blob/master/templates/default/tariff/tariffadd.html#L349)

**Comment by interduo** [comment]
Skoro mu dostarczasz tylko telewizję to przepustowość czego chcesz deklarować?

**Comment by interduo** [comment]
I kolejna rzecz gdzie chcesz ten limit nałożyć.

Telewizję dostarcza się oddzielnym vlanem od pima/proxy do stb abonenta z pominięciem wszystkich możliwych routerów za pomocą multicastów (czasami też po L3 ale rzadko).

**Comment by chilek** [comment]
@interduo przepustowość dostępu unicastowego dla dekoderów tv. Niektóre iptv wymagają takiego dostępu.

**Comment by interduo** [comment]
Czy ktokolwiek tnie pasmo pod iptv?

**Comment by chilek** [comment]
@interduo a internet dla routerów/komputerów przycinasz? Po co? ;-)

**Comment by interduo** [comment]
Proszę pokaż mi usługę, która tego wymaga bo nie potrafię przykładu stworzyć.
IPTV leci po multicastach albo przez IP do lokalnego proxy.

**Comment by paszczus** [comment]
@interduo oj czepiasz się. Nie tniesz pasma pod TV tak jak wszyscy inni czytaj @chilek i nikt więcej? DUPA NIE ADMINISTRATOR z Ciebie w takim razie, nie znasz się! :)

**Comment by interduo** [comment]
@chilek przycinam i kolejkuję - po to by dać możliwośc kupna tańszego internetu i droższego. W przypadku telewizji jest rozróżnienie ilości kanałów tutaj ich nie definiujemy. STB nie potrzebuje Internetu.

Po co więc deklarować jakiekolwiek wartości dla usług, które wszędzie w tych usługach są takie same? Wskażcie mi miejsce gdzie używacie tych wartości.

**Comment by chilek** [comment]
@interduo: chcesz powiedzieć, że dla dostępu unicastowego do internetu dla dekoderów tv dajesz dostęp bez żadnych limitów? ;-)

@paszczus: w sumie nie potrzebnie próbuję drążyć wątki poza LMS Plus (typu administracyjne), bo przez to nie dosyć, że jednemu i drugiemu coś podpowiesz to jeszcze się obrazić potrafią...

**Comment by interduo** [comment]
@chilek Za darmo dajesz Internet do Telewizji? Czy to nie jest więc tak więc że sprzedajesz dwie usługi w pakiecie?

**Comment by chilek** [comment]
@interduo: to co chcesz sforsować jest niepraktyczne - ludzie będą narzekać, że aby z powodu bezpieczeństwa ograniczyć szybkość dostępu dla dekodera trzeba tworzyć dwa zobowiązania - typu tv i typu internet. Ja wiem, że w teorii jest wszystko piękne, ale praktyka zawsze weryfikuje teorię ;-)
Chcesz dać komuś tylko tv - i co? tworzysz 2 zobowiązania: internet i tv? Po co tak? Może ktoś chce mieć za jednym zobowiązaniem to zrealizowane, czyli dostęp tv, a przy okazji limitowanie szybkości (choćby ze względów bezpieczeństwa) do internetu.

**Comment by interduo** [comment]
Ok, założyłem po prostu że STB potrzebuje Internetu. Tyle.

A dla VoIPa? Dlaczego nie ma definicji prędkości? Analogicznie też powinny być.

**Comment by interduo** [comment]
To rozwiązałem sobie na poziomie traffic shapera.
