### ISSUE TITLE
Zakładka "Konta klienta" - "Konta VoIP" --> "Konta Klienta"

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#906]
"Konta VoIP" --> "Konta Klienta"

Moim zdaniem przydałoby się uogólnić tą zakładkę bardziej:

Widziałbym tam:
- konta VoIP,
- konta do sharedhostingu,
- konta do VPS,
- konta pocztowe,
- konta usług dodatkowych typu serwer plików, owncloud,
- konta administracyjne do CMS'ów,
- można przenieść szczegóły konta w userpanel'a ID/PIN
- PINy do kart SIM i ich numery PUK 

Żeby się nie myliły zakładki w GUI można by zamienić:
np. "Konto Klienta" --> "Bilans Finansowy Klienta" lub np. "Konto Klienta" --> "Bilans Klienta".

**Comment by chilek** [comment]
@interduo: ale to może część wizji już realizuje i podsyłaj pull requesty? ;-)

**Comment by interduo** [comment]
Fajnie, że na tą sprawę tak samo patrzymy. Na tą chwilę czuję się za miękki w uszach w PHP. 
Ogarnąłęm dopiero jakotako GIT'a. Popodsyłam na pewno trochę pulli do 'backend-scripts'.

Jak byś znalazł chwilę wolnego napisz jeszcze wszystkie swoje wizje w postaci issue z chęcią poczytam co Ci siedzi w głowie. Dzięki temu będzie ustalony jako taka ścieżka rozwoju i będziemy wiedzieli czego się spodziewać.

**Comment by chilek** [comment]
@interduo: za dużo tego jest - lepiej robić niż opisywać co po głowie chodzi. A w ramach LMS Plus obecnie przypisane issues czekają w pierwszej kolejności do realizacji.

Poza tym mam już praktycznie opracowany mechanizm własny do jqueryui pozwalający na drag&drop wierszy tabelek między kilkoma tabelkami. Przyda się przy wszelkiej maści zarządzanie wizualne choćby grupowe przerzucanie klientów do grupy klientów, etc.

**Comment by chilek** [comment]
Proponuję jeszcze zaimplementować w LMS odpowiedzi ownCloud/nextCloud ;-)

**Comment by interduo** [comment]
Jeśli chodzi o samą ewidencję tych kont - jak najbardziej się przyda.

Owncloud ma API, także pewnie dałoby radę ogarnąć dodawanie/usuwanie kont. Nie ma sensu wynajdywać koło od nowa, lepiej integrować z istniejącymi kołami.

**Comment by interduo** [comment]
W większości udało nam się zintegrować (mniej lub bardziej) z freeradiusem jeśli chodzi o logowania.
A ratunkowe konta klientów do różnych rzeczy trzymamy w management urls.
Minimum zrealizowane.
