### ISSUE TITLE
DOKUMENTACJA LMS

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#907]
Wtrące się, @frychlich napisał coś bardzo istotnego w https://github.com/lmsgit/lms/issues/840#issuecomment-247467083

> nie miałem do tej pory ani siły ani chęci dokładnego rozgryzania jak to w ogóle działa.

Dlatego według mnie największą bolączką LMS / LMS-PLUS jest brak dobrej dokumentacji takiej dla łopatologicznej. W co drugim zgłoszeniu jest:
- ja tego nie używam, bo nie ogaraniam
- ja nie wiedziałem, że tak to można zrobić
- ja tego nie ruszałem, bo nie wiem po co to jest
- ja tego nie używam, bo nie wiem jak skonfigurować

Oczywiście przesadzam, ale my do dzisiaj nie wykorzystujemy wszystkiego co jest w LMS, bo (tysiące  różnych powodów) ... a wystarczyła, by porządna dokumentacja :)

Ktoś w końcu musiał to napisać po raz setny i nie ostatni.

Zdaję sobie sprawę, że napisanie dokumentacji jest czasochłonne, ale ja nieograniam całego systemu. Trzeba zaczą od dokładnego wypunktowania i potem sukcesywnie uzupełniać. Tylko to musi w jakiś sposób lecieć przez GIT, bo inaczej umrze śmiercią naturalną jak obecne http://wiki.lms.org.pl/doku.php

Mając już tak wypunkowany zarys dokumentacji @chilek mógłby nie puszczać pulli bez dokumentacji, jeśli takowej wymagają.

Jakby zrobić dokumentację wewnątrz LMS przecież HTML do tego się świetnie nadaje ?

**Comment by frychlich** [comment]
Trzeba by nakreślić jakiś na początek prosty plan aby było od czego zacząć i rozbudowywać z biegiem czasu.
Na początek to by się przydała pełna lista zmiennych, jakie są w samym LMS, w skryptach.
Można by to potraktować jako zalążek do tworzenie dokumentacji do interfejsu LMS oraz skryptów.

**Comment by interduo** [comment]
A nie lepiej dokumentację na wiki tworzyć?

**Comment by kyob** [comment]
Może coś takiego przykład: 
1) LIBRENMS: http://docs.librenms.org/Installation/Installation-CentOS-7-Apache/
2) u góry odnośnik [Edit on GitHub](https://github.com/librenms/librenms/edit/master/doc/Installation/Installation-CentOS-7-Apache.md) klikamy i
3) edytujemy: https://github.com/librenms/librenms/edit/master/doc/Installation/Installation-CentOS-7-Apache.md
4) jeden system GIT i mamy historie zmian na tacy :)

**Comment by frychlich** [comment]
jestem ZA

**Comment by chilek** [comment]
Powtórzę po raz kolejny - wszystko odnośnie dokumentacji będzie tworzone głównie w ramach projektu LMS Plus w postaci artykułów wiki w github. Może ich system wiki nie jest idealny, ale używalny i dość wygodny i do tego spada obowiązek utrzymywania własnych aplikacji wiki.
A wiki z github z automatu ma obsługę historii edycji.

**Comment by chilek** [comment]
Zgodnie z obietnicą - dokumentacji w ramach LMS+ stale przybywa i będzie.
