### ISSUE TITLE
Autowylogowanie po każdym kliknięciu => aktualna wersja z git

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#910]
Po zalogowaniu pokazuje się:
```php
Warning: array_merge(): Argument #2 is not an array in /var/www/html/lms/lib/Session.class.php on line 89
```

Próba kliknięcia w cokolwiek powoduje wylogowanie.

PS: Musiałem także nanieść zmiany do bazy MySQL ręcznie, bo pluł się o brak kolumny _persistentsettings_

**Comment by chilek** [comment]
Automatyczny update schematu MySQL nie powiódł Ci się? Jeśli tak to może przyczepił się do nielegalnego wg najnowszych wersji MySQL ustawienia DEFAULT '' dla pola typu *text?
Robiłem już w sumie na to obejście w LMS, ale czyżby nie pomogło.

Jak wygląda u Ciebie $settings tuż przed nieszczęsnym wierszem. Wygląda na to jakby weszło w jakiś dziwny stan.

**Comment by kyob** [comment]
`var_dump($settings)`
```php
boolean false
```

**Comment by chilek** [comment]
Na 100% mówimy o wierszu:
https://github.com/lmsgit/lms/blob/master/lib/Session.class.php#L89
?

Co masz w polach **settings** i **persistentsettings** tabeli **users** dla użytkownika na którego się logujesz?

**Comment by kyob** [comment]
Zapytanie sql:
```sql
SELECT settings, persistentsettings FROM users WHERE login='admin'
```
settings => (pusto nic)
persistentsettings  => b:0;

**Comment by kyob** [comment]
Przed **introduced persistent settings** w tabeli **users** dla login **admin** pole **settings** => `a:1:{s:5:"mtime";i:1474459279;}	`

**Comment by chilek** [comment]
Może commit da81279 pomoże?

**Comment by kyob** [comment]
Pomogło! :)
