### ISSUE TITLE
Moduł: documentdel.php => wywala błąd przy usuwaniu więcej niż jednego dokumentu

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#911]
```php
Invalid argument supplied for foreach() in /var/www/html/lms/modules/documentdel.php on line 39

Cannot modify header information - headers already sent by (output started at /var/www/html/lms/modules/documentdel.php:39) in /var/www/html/lms/lib/Session.class.php on line 246
```

Testuję bieżącą wersję z GIT.

**Comment by chilek** [comment]
Masz dokumenty z zerową liczbą załączonych plików?
Możesz zobaczyć dla takowego dokumentu jak wyglądają rekordy w tabeli
**documentattachments**?

**Comment by kyob** [comment]
1. Tak bez załączników.
2. Np. tak:
```sql
id,docid,filename,contenttype,md5sum,main
95,10107,default.html,text/html,4c053f6943e22c3364fde3935f1e0d74,1
```
Dla formalności dokumentu się usuwają, ale wywala warninga.

**Comment by chilek** [comment]
Co ci pokaże:
```php
print_r($md5sums);
```
jak wstawisz przed:
https://github.com/lmsgit/lms/blob/master/modules/documentdel.php#L39
?

**Comment by kyob** [comment]
Nic nie pokazuje, ale teraz mam więcej informacji.

Warning pokazuje się tylko, gdy kliknę "Zaznacz wszystko", bo gdy ręczenie zaznaczę dokumenty do usunięcia problem nie występuje :)

**Comment by chilek** [comment]
To ja tu czegoś nie rozumiem...
Skoro:
```php
$md5sums = $DB->GetCol('SELECT md5sums FROM documentattachments
				WHERE docid = ?', array($id));
```
nic nie zwraca to jakim cudem usuwa Ci załączniki dokumentu?
Przecież usuwanie plików jest dopiero dalej.
Prawdopodobnie robisz coś czego nie opisałeś.

**Comment by kyob** [comment]
1. Tworzę dokumenty **bez załączników**.
2. Usuwając więcej niż jeden dokument wywala warningi.
3. 
```php
print_r($md5sums);
```
wstawione przed
https://github.com/lmsgit/lms/blob/master/modules/documentdel.php#L39

nic nie zwraca podczas usuwania

**Comment by kyob** [comment]
Dobra chyba widzę w czym problem za chwilę będzie pull.
