### ISSUE TITLE
Dodatkowe wartości dla taryf

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#912]
Przydało by się kilka pól w taryfach:
- Burst Limit 
- Burst Threshold
- Burst Time

na potrzeby generowania kolejek w skryptach backendowych

**Comment by chilek** [comment]
Można automatycznie wyliczać na podstawie rate i ceil - nie warto w takie coś bawić się.

**Comment by interduo** [comment]
W sumie jeśli określę je we wszystkich taryfach na tym samym poziomie % to masz rację.
