### ISSUE TITLE
Dodatkowa kolumna ID w customerassignmentpanel

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#913]
Jak w temacie, nie widać, np. która taryfa jest nowo dodana jeśli nie mamy zadeklarowanych dat/przypisań do komputerów. Analogicznie jak w 'nodespanel' lub w 'networkspanel'.

**Comment by interduo** [comment]
Może przy każdym boxie dałoby się zrobić coś na zasadzie wyboru tego co chce się pokazywać:

![entis](https://cloud.githubusercontent.com/assets/17087236/19440793/82ada5ca-9483-11e6-8ef4-e66109fcc506.png)

Np. dla części osób w firmie pewne pola nie są zupełnie potrzebne.

**Comment by chilek** [comment]
W danych tabelarycznych już takie coś jest zaimplementowane właśnie w stable 1.11.21,
ale mam wrażenie, że piszesz o czymś innymi niż dane tabelaryczne...

**Comment by interduo** [comment]
Chodzi mi o możliwość zdefiniowania wyświetlanych kolumn np w tych zakładkach:

![kolumny](https://cloud.githubusercontent.com/assets/17087236/19441617/8d0e76ea-9486-11e6-8958-8d2a4bee0952.png)

**Comment by chilek** [comment]
Aaaa te - pewnie wykonalne, ale nie myślę, żeby to było priorytetowe. Na razie nowe typy dynamicznych tabel osadzane są w miejscach interfejsu, gdzie faktycznie jest to bardzo przydatne.

**Comment by interduo** [comment]
A da radę chociaż dorzucić tą kolumnę ID tutaj? 
Jeśli mamy dwa identyczne nazywające się zobowiązania to nie da się ich odróżnić. Nie wiadomo które jest starsze.

**Comment by interduo** [comment]
na to puściłem wczoraj pulla
