### ISSUE TITLE
Błędy po aktualizacji

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#915]
Wystąpiły błędy w obsłudze bazy danych!
Zapytanie: SELECT settings, persistentsettings FROM users WHERE login = 'jkl'
Błąd: BŁĄD: kolumna "persistentsettings" nie istnieje LINE 1: SELECT settings, persistentsettings FROM users WHERE login =... ^
Zapytanie: SELECT settings, persistentsettings FROM users WHERE login = 'jkl'
Błąd: BŁĄD: kolumna "persistentsettings" nie istnieje LINE 1: SELECT settings, persistentsettings FROM users WHERE login =... ^

**Comment by chilek** [comment]
To jest efekt tego, że mysql wcześniej wykonał jakiegoś zapytania sql aktualizującego schemat i teraz zwija się z bólu...

**Comment by interduo** [comment]
Mam PostgreSQL'a. 
Chyba chodziło o: https://github.com/lmsgit/lms/commit/d401c7d1c741079ab84df365444ff7ba91e22f51  :)

Po tym commicie wszystko działa.
