### ISSUE TITLE
Customerinfo - grubelinie

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#916]
Występują chyba niezamierzone grube linie w niektórych miejscach:

![gruba_linia](https://cloud.githubusercontent.com/assets/17087236/18748103/155e1e16-80d1-11e6-84c4-0a9c0b91b10b.png)

to samo w panelu dokumentów w customerinfo, panelu terminarza i panelu zobowiązań w różnych miejscach

**Comment by chilek** [comment]
Nie dostrzegam na wersji demo opisywanego problem ani w Chrome, ani w Firefox.
Na pewno przeładowałeś wszystkie dokumenty witryny z lms-em z pominięciem cache przeglądarki.

**Comment by interduo** [comment]
Zrobiłem fullinstall.sh nadal problem występuje.

Udało mi się znaleźć przyczynę problemu. Zoomowanie w przeglądarce. Czy da się zrobić żeby ctrl+scroll nie rozwalał tak linii?

**Comment by interduo** [comment]
![powiekszenie](https://cloud.githubusercontent.com/assets/17087236/18752054/7b6de546-80e1-11e6-8e8e-843b68668930.png)

Powiększenie +50%. Otwarte mniejsze okno.

**Comment by kosaa** [comment]
Czy zgłoszenie aktualne?

**Comment by interduo** [comment]
Jedyny mankament który pozostał to to że na przeglądarce Chrome (wersja na telefon) zakładka saldo klienta jest rozjechana jak na zrzucie.
![chrome_mobile](https://cloud.githubusercontent.com/assets/17087236/20668912/9d6ad34c-b571-11e6-9bdb-ac352147336b.png)
