### ISSUE TITLE
RT nie wysyła maili jako "mail.phpmailer_from"

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#922]
> mail.backend = phpmailer
> mail.phpmailer_from = moj@mail.com

Odpowidając na zgłoszenia z RT LMS uparcie wstawia maila od zalogowanej osoby, a chyba powinien wstawić maila z **mail.phpmailer_from**

**Comment by chilek** [comment]
W dniu 27.09.2016 14:39, Łukasz Kopiszka napisał(a):
>> mail.backend = phpmailer
>> mail.phpmailer_from = moj@mail.com
> 
> Odpowidając na zgłoszenia z RT LMS uparcie wstawia maila od
> zalogowanej osoby, a chyba powinien wstawić maila z
> MAIL.PHPMAILER_FROM

Backend phpmailer w lms bierze ustawienia from z nagłówka 'From' 
przekazanego
do LMS::SendMail().

-- 
Pozdrawiam
Tomasz Chiliński, Chilan
opiekun projektu LMS - http://lms.org.pl
szef projektu LMS Plus / LMS+ - http://lms-plus.org

**Comment by kyob** [comment]
Czyli mowa o tym:
https://github.com/lmsgit/lms/blob/master/modules/rtmessageadd.php#L131

Jeśli user nie ma maila wstawia maila z kolejki.

W ustawieniach sekcji **mail** mam wpisane dane dla zewnętrznego SMTP dla konkretnego maila, a przez https://github.com/lmsgit/lms/blob/master/modules/rtmessageadd.php#L131 nie chce mnie autoryzować, bo jak się wstawi do from adres zalogowanego usera to jest zonk :)

Można to jakoś obejść nie dotykając zewnętrznego serwera SMTP?

**Comment by chilek** [comment]
@kyob tak - zmodyfikować wiersz kodu, który przytoczyłeś ;-)

**Comment by kyob** [comment]
Bez pulla nie rusz OK.

**Comment by kyob** [comment]
```php
   PHPMailer Object
(
    [Version] => 5.2.16
    [Priority] => 
    [CharSet] => UTF-8
    [ContentType] => text/plain
    [Encoding] => 8bit
    [ErrorInfo] => Invalid address:  (addAnAddress Reply-To): "Jan Słodowy" <moj@poprawny.mail>
```

Maile dochodzą, ale niby jeszcze wypluwa **[ErrorInfo] => Invalid address:  (addAnAddress Reply-To):**  olać to?

**Comment by chilek** [comment]
W jakim kontekście masz ten komunikat z błędem:
```
Invalid address:  (addAnAddress Reply-To): "Jan Słodowy" <moj@poprawny.mail>
```
Która dokładnie wysyłka maila go generuje?

Swoją drogą zauważyłem, że trzeba będzie wstawić AddReplyTo() przed setFrom(), bo inaczej dwa maile mogą zostać w wynikowym nagłówku Reply-To.

**Comment by kyob** [comment]
Jeśli dobrze pamiętam to błąd występuje jak odpowiadam na zgłoszenie w helpdesku i jest podany mail, na który ma zostać wysłane powiadomienie. 

Postaram się w przyszłym tygodniu zweryfikować ten problem, wtedy podam więcej szczegołów.

**Comment by kyob** [comment]
Literówka lub czeski błąd jak zwał tak zwał. Wszystko śmiga :)
