### ISSUE TITLE
Helpdesk: Informacja o źródle danego zgłoszenia

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#925]
Z racji tego, że zgłoszenia wpadają do nas różnymi drogami przydałoby się móc przypisywać źródło danego zgłoszenia.

Powód: Na zgłoszenie odpowiadamy tą samą drogą.
Można stosować prowizorki typu oddzielna kolejka...ale to nie tędy droga.
- Jeśli klient miałby ustawioną flagę typu: email odpowiedź na zgłoszenie mogłaby być automatycznie wysyłana emailem (w przeciwnym wypadku nie),
- Jeśli klient miałby wybraną inną drogę elektroniczną również jest możliwe automatyczne wysłanie odpowiedzi tą drogą.

**Comment by chilek** [comment]
Coś mi się wydaje, że w takim czymś weszłoby dużo różnych zależności, bo np. wypadałoby również uwzględnić jakie kanały komunikacyjne są zaakceptowane w umowie przez klienta.

**Comment by interduo** [comment]
Nie. Daj przykład.

Mówię o sytuacji w której jakiś klient do Ciebie dzwoni i mówisz, że oddzwonisz jak załatwisz jego sprawę. Czy w takiej sytuacji czytasz umowę przed wybraniem numeru do niego?

**Comment by chilek** [comment]
@interudo:

Co zatem rozumiesz przez to:
> Jeśli klient miałby ustawioną flagę typu: email odpowiedź na zgłoszenie mogłaby być automatycznie wysyłana emailem (w przeciwnym wypadku nie),
> Jeśli klient miałby wybraną inną drogę elektroniczną również jest możliwe automatyczne wysłanie odpowiedzi tą drogą.

**Comment by interduo** [comment]
Uważam, że jeśli klient zgłosi coś mailem/facebookiem/telefonem to masz prawo odpowiedzieć mu tą samą drogą i nie potrzebujesz do tego dodatkowych zgód w umowie. Klient pisząc do Ciebie oczekuje że mu odpowiesz tym samym kanałem komunikacji. 

W tym momencie jeśli nie wpiszesz tego w treść zgłoszenia nie wiadomo, którą drogą trafiło zgłoszenie.

Jeśli klient zgłasza coś telefonicznie (a ma dodanego maila w bazie):
- dodając zgłoszenie/odpowiadając na nie skrypt automatycznie sugeruje _niepotrzebnie_ wysłanie kopii odpowiedzi na maila do niego.

**Comment by interduo** [comment]
W GUI mogłoby to wyglądać tak:
https://github.com/interduo/lms-plus/commit/6b3ef40fae9d9b9b56144862b65054310cb7a862

**Comment by chilek** [comment]
cause w tabeli rttickets już jest od dość dawna.
Chodzi Ci o dodanie listy wyboru z pochodzeniem zgłoszenia (ja bym nazwał pole np. origin)?

**Comment by interduo** [comment]
Tak - poprawiłem nazwę. 
Mogłoby to tak wyglądać jak wkleiłem?

**Comment by chilek** [comment]
To raczej będzie zrobione w stylu:
https://github.com/lmsgit/lms/blob/master/lib/definitions.php#L115-L126
Dzięki temu łatwo będziesz się zarządzać z jednego miejsca wszystkich pochodzeniami zgłoszenia.

**Comment by interduo** [comment]
https://github.com/interduo/lms-plus/commit/510dba074ed5752b440bccdf487f8f80e57d3a4d

Co do poprawy? 
Funkcjonalność można używać.

**Comment by interduo** [comment]
A teraz?
https://github.com/interduo/lms-plus/commit/b7013247f80ec802723f07d005811beaf78f8520

**Comment by interduo** [comment]
Poprawiony origin--> source: 
https://github.com/interduo/lms-plus/commit/1a72ba8bae974b03cc30bb8d58f2cc93a80e81f8

**Comment by interduo** [comment]
Wdrożone: https://github.com/chilek/lms-plus/pull/300/commits/9f29ed9ee7b00843dafd4b780f0dc349283d72b4.
