### ISSUE TITLE
Helpdesk: Priorytet zgłoszeń

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#928]
Przydała by się możliwość priorytetyzowania zadań. Niektóre powinny zostać wykonane szybciej.
Mogłyby się wyświetlać na liście z innym tłem lub inną czcionką np rozmiar +1, bold lub cokolwiek.

Dzięki temu Pani z biura przy przyjęciu zgłoszenia mogłaby oznaczyć zadanie jako priorytet. I nie musiałaby pisać na komunikatorze/telefonicznie, że dana rzecz jest ważniejsza niż inne.

W tej chwili robimy to kategoriami ale nie ma to odzwierciedlenia już w samym interfejsie.
Może udałoby się chociaż różnie kolorować tło skategoryzowanych zgłoszeń?

**Comment by chilek** [comment]
Czyli możliwość przypisywania kolorów do kategorii i potem pokazywanie zgłoszeń z kategoriami w postaci kolorowych pasków?

**Comment by fhucomax** [comment]
Myślałem o kolorowych czcionkach, ale to zapewne bardziej skomplikowane do zrobienia niż paski z uwagi na konieczność zachowania rozróżnień nowy/ otwarty/ rozwiązany?

Sądzę, że definiowalne kolorowe paski tła także załatwią sprawę  ;)

**Comment by interduo** [comment]
Myślę, że kolorowe paski były by jak najbardziej wystarczające.

**Comment by interduo** [comment]
Wydaje mi się, że kolumna z priorytetem i kolorami podobna do kolumny 'TYP' w eventprint była by odpowiednia do tego typu.

Myślę, że 5 stopnii prioritetów będzie wystarczające:
0 - lowest,
1 - low,
2 - normal, 
3 - high,
4 - mission critical.

Proponowałbym przypisanie odpowiednio mocniejszej czerwieni/bolda do priorytetów.

**Comment by kosaa** [comment]
dodał bym kolumne _priorytet_ na prawo od typu zgloszenia i nie wypisywał zadnego tekstu w przypadku gdy priorytet zgloszenia ustawiony jest na normalny

wzrokowo bedzie mozna odfiltowac zgloszenia na ktore trzeba zwrocic uwage

**Comment by interduo** [comment]
Ja mówię o helpdesku Ty o terminarzu.
Zastanawiam się czy w helpdesku nie przydałoby się również określać typów zgłoszenia.

**Comment by kosaa** [comment]
nie wiem jaki problem masz u siebie, ale czy nie da sie go zalatwic tworzac rozne kolejki?

**Comment by interduo** [comment]
Niestety tworzenie kolejnych kolejek to utrudnienie pracy przy dużej ilości zgłoszeń.
(pisałem o tym np. tutaj: https://github.com/lmsgit/lms/issues/845)

Efekt: Zaburzona kolejność realizacji zadań.

**Comment by interduo** [comment]
z racji pull requesta, który umożliwia kolorowanie kategorii i wyświetlanie ich na liście ticketów zamykam zgłoszenie. Funkcjonalność jest wystarczająca.
