### ISSUE TITLE
Fakturowanie: Wydruk anulowanej faktury

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#930]
Anulowaną fakturę da się wydrukować, przydałoby się ją móc tylko podejrzeć lub przy drukowaniu oznaczać mega dużymi literami przez całą fakturą FAKTURA ANULOWANA a przedewszystkim zmienić nagłówek z Faktury VAT na "Faktura ANULOWANA". Tak żeby to potem po wydruku nie miało mocy prawnej.

Wrzucam to na Githuba, żeby nie uciekło bo jednak to ważna rzecz a wątek na liście mailingowej jest już długi.

**Comment by chilek** [comment]
Zrobione.
