### ISSUE TITLE
Helpdesk: szablony odpowiedzi

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#931]
Możliwość tworzenia gotowych szablonów odpowiedzi na typowe problemy klientów w celu optymalizacji pracy BOK.

Uwagi i popozycje?

**Comment by chilek** [comment]
Chodzi o coś podobnego jak w przypadku innych typów szablonów tj. mail, sms, userpanel, www i zbliżonego do tego co oferują systemy bugzilla (od razu masz listę rzeczy, które należy uzupełnić)?

**Comment by interduo** [comment]
Może bardzo prosto - pasek z rozwijanymi standardowymi odpowiedziami.
Po wyborze kopiuje się ten komunikat do treści zgłoszenia. Bo przeważnie trzeba tam coś jeszcze dopisać...

**Comment by kyob** [comment]
Opcja podana przez @interduo jest wystarczająca.

**Comment by chilek** [comment]
Zaimplementowane już jakiś czas temu.
