### ISSUE TITLE
Taryfy - ilość sztuk

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#937]
Mam klienta któremu naliczam dzierżawę za sprzęt w ilości 10sztuk.

Teraz:
1, Muszę dodać 10 pozycji z taryfą "Dzierżawa sprzętu" sztuk 1
2. Na fakturze każda dzierżawa to oddzielna pozycja

Preferowałbym:
1. Jedną taryfę z ilością sztuk w moim przypadku 10. 
2. Na fakturze - jedna pozycja, w kolumnie sztuk ilość "10".

**Comment by paszczus** [comment]
+1

**Comment by chilek** [comment]
Hmmm, tyle, żeby uzyskać to co piszesz nie trzeba robić nic w LMSie...

**Comment by interduo** [comment]
Jak dodać taryfę, żeby na fakturze w ilości sztuk pojawiła się odpowiednia ilość?

**Comment by chilek** [comment]
@interduo faktycznie nie jest coś takiego w tej chwili możliwe bez dodania po prostu 10x danej taryfy.

**Comment by interduo** [comment]
Jeśli dodasz 10x tą samą taryfę na fakturze będziesz miał 10 pozycji po 1 sztuce.
Więc w tej chwili nie jest możliwe w ogóle dodanie takiego zobowiązania.

**Comment by chilek** [comment]
Czym generujesz faktury?

**Comment by interduo** [comment]
1 roboczego dnia miesiąca - lms-payments, później ręcznie.

**Comment by chilek** [comment]
Skrypt lms-payments nie jest już rozwijany, a poprawiane są w nim wyłącznie poważne błędy.
Polecam migracją na lms-payments.php w którym jest:
https://github.com/lmsgit/lms/blob/master/bin/lms-payments.php#L575
(co oznacza próbę weryfikacji czy na wystawianej fakturze nie ma już danej pozycji i jeśli jest to następuje zwiększenie sztuk, zamiast dodawania kolejnych pozycji). Być może u Ciebie te 10 zobowiązań odróżnia coś więcej niż:
- tariffid,
- value,
- docid,
- description,
- pdiscount,
- vdiscount.
Na pewno wszystkie 10 zobowiązań mają te same właściwości co powyżej (oczywiście z wyjątkiem docid)?

**Comment by interduo** [comment]
Ok. Przemigruję więc na lms-payments.php.
