### ISSUE TITLE
Dokumenty - Osoba wystawiająca

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#938]
Nie doszukamy się przez GUI, która osoba wystawi dany dokument, jeśli:
- nie jest to dokument finansowy,
- nie mamy włączonego dziennika transakcji,
- w treści dokumentu nie występuje osoba wystawiająca.

W 'documentlist' widziałbym kolumnę "Czas wystawienia dokumentu", "Osoba wystawiająca".
oraz "Osoba zatwierdzająca dokument" oraz "Czas zatwierdzenia dokumentu".

**Comment by greenlms** [comment]
Dokładnie, super pomysł!

**Comment by greenlms** [comment]
A jak włączyć dziennik transakcji? Gdzie?

**Comment by interduo** [comment]
W konfiguracji phpui, opcja logging.

**Comment by greenlms** [comment]
Dzięki 👍 , działa. Widać teraz zdarzenia w /?m=archiveview , dobre

**Comment by interduo** [comment]
Heej halo... @kosaa dlaczego to zamykasz?

**Comment by interduo** [comment]
Ja tu widzę kolumnę "utworzony przez" w documentinfobox między utworzony a typ zawierającą informację który użytkownik wystawił dany dokument.
