### ISSUE TITLE
Dokumenty - jak wygenerować dokument, ale w PDF (nie HTML)?

### ISSUE THREAD

**Issue by greenlms** [lmsgit/lms#945]
Jak wygenerować jakiś dokument, **ale w PDF**? W tym również masowo jednym kliknięciem wygenerować taki sam dokument dla wielu klientów na raz.
Idąc dalej:
Jak zrobić, żeby później można było te wszystkie utworzone dokumenty wydrukować za jednym razem (czyli po kliknięciu "Drukuj" **scalić wszystkie zaznaczone do jednego pliku PDF wyjściowego**). Wiem, że ta opcja Drukuj scala pliki HTML w jeden duży, ale czy tak samo poprawnie scali pliki PDF, i czy sprawdził to ktoś?

P.S. Przy okazji zapytam: Czy szablony dokumentów w PDF mają dostępną opcję _html2pdf_? Bardzo by się taka przydała, żeby łatwo można było tworzyć PDF-y (wystarczyłaby znajomość kodu HTML).

**Comment by greenlms** [comment]
I jeszcze przy okazji zapytam: jak wybrane wysyłać dokumenty (mam na myśli raczej PDF, nie HTML) automatem na e-mail klienta? Czy jest do tego jakaś instrukcja jak to zrobić? Z góry dziękuję za wszelkie info.

**Comment by interduo** [comment]
Daj jakiś przykład z życia. 
Dokumenty trzymane są w plikach html tam gdzie LMS.

**Comment by greenlms** [comment]
Proszę bardzo, oto przykład:
Chciałbym massowo wygenerować wezwania do zapłaty dla dłużników. Najlepiej przy okazji również móc wysłać je jako załącznik do dłużników na e-mail (tylko jeśli podali swój e-mail do bazy LMS). Oprócz tego chcę wszystkie te utworzone wezwania wydrukować (czyli zapisać do jednego PDF na swój dysk).

Podsumowując: dłużnik dostanie wezwanie na e-mail oraz takie same pocztą do domu.

**Comment by chilek** [comment]
Ustawienie nazywa się **phpui.document_type**. Wprowadzasz wartość _pdf_.

**Comment by greenlms** [comment]
Dzięki Tomek, działa ta opcja. Teraz dokumenty HTML są wypluwane do PDF - OK.
a proszę podpowiedz mi gdzie **TCPDF** trzyma czcionki? Chciałbym dodać nowe czcionki.
_TCPDF ERROR: Could not include font definition file: times new roman_

**Comment by chilek** [comment]
W dniu 05.10.2016 16:23, Łukasz Hajdamowicz napisał(a):
> Dzięki Tomek, działa ta opcja. Teraz dokumenty HTML są wypluwane do
> PDF - OK.
> a proszę podpowiedz mi gdzie TCPDF trzyma czcionki? Chciałbym dodać
> nowe czcionki.
> _TCPDF ERROR: Could not include font definition file: times new roman_

Z grubsza tu:
https://github.com/lmsgit/lms/tree/master/lib/tcpdf/fonts

**Comment by greenlms** [comment]
Jest mały problem w /?m=documentlist. Wydruk via PDF nie umożliwia wydruku wielu (zaznaczonych) dokumentów na raz.

- Gdy opcja **phpui.document_type = pdf** - to jest problem, bo wypluwa tylko jeden (pierwszy z góry) zaznaczony dokument do wydruku, zamiast wszystkie.

- Gdy opcja **phpui.document_type = html** - wtedy jest OK, bo wszystkie zaznaczone prawidłowo scala je do jednego, więc daje możliwość hurtowego wydruku wszystkich dokumentów.

Tylko ja chciałbym to w PDF, nie w HTML. Czy da się to poprawić? :)

**Comment by greenlms** [comment]
Rozwiązanie problemów:

**Ad. 1)**
Opcja html2pdf jednak działa.
_"Currently you can only print many documents of type text/html!"_
Innych plików (np. skanów PDF) nie scala, ale nie jest to potrzebne.

**Ad. 2)**
Jeszcze powinny nastąpić zmiany kodu w pliku _/modules/documentview-mode.php_:
`$ctype != 'pdf'`
na
`$ctype == 'text/html'`
#lub na
`preg_match('/html/i', $ctype`
wg uznania.
> Bo bez takiego wykluczenia wszystko chce iść via html2pdf() czyli nie można otworzyć innych plików nie HTMLowych.

Pozostawienie `$ctype != 'pdf'` powoduje, że nie można otwierać plików JPG i innych nie-tekstowych kiedy skonfigurowana jest konwersja _html2pdf_ w locie (czyli wtedy gdy jest wartość: `phpui.document_type`='pdf').

**Comment by chilek** [comment]
@greenlms okazuje się, że obsługa sklejania pdfów (czyli możliwość drukowania wielu pdf-ów jako pojedynczy dokument pdf) jest dostępna poprzez zewnętrzny patch. Postaram się go wkrótce integrować z w wersji rozwojowej.

**Comment by chilek** [comment]
Ad. 2) O coś takiego chodzi:
https://github.com/lmsgit/lms/commit/df9e40207ca09f7b246573bf57fceafaac01fc94
?

**Comment by chilek** [comment]
Ad. 1) Zważywszy na to, że do dokumentów można dołączać już wiele załączników to sprawa z ich sklejeniem do pdf wydaje się dużo bardziej złożona i nie wiem czy nie wygeneruje nieoczekiwanych przez użytkownika rezultatów...

**Comment by chilek** [comment]
Skleić do jednego pdf-a można byłoby jedynie wtedy, gdy wszystkie dokumenty i ich załączniki, które zostały wybrane byłyby pdf-ami, a coś mi się wydaje, że to będzie bardzo rzadko scenariusz...

**Comment by greenlms** [comment]
> Ad. 2) O coś takiego chodzi: df9e402?

Tak, teraz jest OK!

> Skleić do jednego pdf-a można byłoby jedynie wtedy, gdy wszystkie dokumenty i ich załączniki, które zostały wybrane byłyby pdf-ami, a coś mi się wydaje, że to będzie bardzo rzadko scenariusz...

Właśnie jakbyś takie coś wprowadził to by było cool :-)
U nas trzymamy wszystkie dokumenty w .pdf (nawet te z html2pdf (są generowane za pomocą bogatszego _mpdf60/mpdf.php_ a nie defaultowego _tcpdf_, ale to raczej nie ma znaczenia). I jakby te wszystkie zaznaczone istniejące fizycznie pliki .pdf mogłoby się dać łączyć w jeden duży wyjściowy .pdf to by było dobre, a nawet bardzo dobre 👍

**Comment by chilek** [comment]
@greenlms wiesz, że obecnie do pojedynczych dokumentów można dołączać wiele plików? Z kolei z tego faktu wynika, że jeśli byś zaznaczył wiele dokumentów z których każdy zawierałby wiele załączników  pdf to otrzymywałbyś dokument pdf w którym byłby wiele razy zduplikowany plik o tej samej zawartości?

**Comment by greenlms** [comment]
@chilek Wow, tego nie zauważyłem. Czyli od teraz do umów (zawierającą umowę, regulamin, cenniki itp.) można dodawać również zdjęcia .jpg powykonawcze, bardzo dobrze :-)

P.S. A co oznacza wartość 0 lub 1 w kolumnie "_main_" w tablicy _lms.documentattachments_?

Co do łączenia dokumentów .pdf (np. skanów) w jeden duży wyjściowy .pdf, to może to jednak odłóżmy to w czasie, do czasu aż faktycznie będzie większa potrzeba ich scalania.

**Comment by chilek** [comment]
@greenlms a w liście zmian jest. 1 dla pola main oznacz czy dany załącznik jest głównym załącznikiem dokumentu, czyli czy podlegał generowaniu przez kod szablonu dokumentu. Te które dołączasz jako pliki mają wartość 0.

**Comment by chilek** [comment]
https://github.com/lmsgit/lms/commit/c58224a8a0b93668ea811f9f3877b0423728ce37 dodaje w wersji rozwojowej obsługę "sklejania" pdf-ów jeśli wybierze się tylko dokumenty z załącznikami w postaci PDF.
