### ISSUE TITLE
Błąd w schemacie aktualizacji bazy danych postgres 2016100500

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#946]
Warning: Invalid argument supplied for foreach() in /var/www/html/lms/lib/upgradedb/postgres.2016100500.php on line 31

Po dzisiejszym commicie po kliknięciu w 'Nowe konto'. Błąd widać było tylko jeden raz.

**Comment by kosaa** [comment]
poprawka już wysłana, problem występował przy przeindeksowywaniu numerów w momencie gdy żaden numer nie był zdefiniowany

linki do commitów dla dociekliwych
d545757
665d696

**Comment by interduo** [comment]
potwierdzam działa :)
