### ISSUE TITLE
Drukowanie faktury bez druczka przelewu

### ISSUE THREAD

**Issue by frychlich** [lmsgit/lms#952]
Proponuję dorobić do LMS-UI dwie opcje:
1. globalna - drukowanie/nie drukowanie druku przelewu dla Firm
2. per klient - zaznaczana w karcie klienta czy ma drukować druczek danemu klientowi

**Comment by interduo** [comment]
A może inne podejście:

Różne szablony dla faktur:
https://github.com/lmsgit/lms/issues/852

Robisz dwa szablony jeden z druczkiem drugi bez, przy wystawieniu faktury decydujesz którego szablonu użyć. Dzięki temu możesz jeszcze głebiej personalizować fakturę. (zmienić logo, np. dodać reklamy na odwrocie faktury i takie tam).

Ad 1. Domyślny szablon 'bez druczka'
Ad 2. Dodał warunek, żeby przy drukowaniu rozliczonej faktury nie drukować druczka wpłaty - szablon 'bez druczka'.

**Comment by chilek** [comment]
Czy możecie mi wyjaśnić jaki to w ogóle ma cel poza dodawaniem sobie dodatkowej roboty? :)

**Comment by frychlich** [comment]
Nam firmy marudzą, że nie chcą tego druczka na fakturze, bo wolą tam sobie robić dekretację.
Jak mam firmę, która ma na fakturze więcej pozycji to druczek i tak ląduje na drugiej stronie,
którą możemy wyrzucić do kosza, a po co ja drukować.

**Comment by interduo** [comment]
Ja po prostu nie chcę marnować kolorowego toneru.

**Comment by interduo** [comment]
Po wrzuceniu kodu: https://github.com/chilek/lms-plus/issues/279 zamykam (można już definiować zgodami per klient).
