### ISSUE TITLE
Błąd przy wyświetlaniu KP

### ISSUE THREAD

**Issue by interduo** [lmsgit/lms#953]
Warning: file(/img/style_print.css): failed to open stream: No such file or directory in /var/www/html/lms/lib/LMSDocuments/LMSHtmlDocument.php on line 45

$ ls -la /var/www/html/lms/lib/LMSDocuments/LMSHtmlDocument.php
-rw-r--r-- 1 root root 1955 paź 3 13:21 /var/www/html/lms/lib/LMSDocuments/LMSHtmlDocument.php

$ wget https://lmsplus/img/style_print.css --no-check-certificate--2016-10-07 11:59:42--  https://lmsplus/img/style_print.css
Translacja lmsplus (lmsplus)... 10.100.0.107
Łączenie się z lmsplus (lmsplus)|10.100.0.107|:443... połączono.
UWAGA: Żaden certyfikat nie został przedstawiony przez `lmsplus'.
UWAGA: Certyfikat `lmsplus' nie ma znanego wystawcy.
Właściciel certyfikatu nie pasuje do nazwy hosta `lmsplus'
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 200 OK
Długość: 2931 (2,9K) [text/css]
Zapis do: `style_print.css'

style_print.css     100%[=====================>]   2,86K  --.-KB/s   w  0s

**Comment by chilek** [comment]
Spróbuj w wierszu:
https://github.com/lmsgit/lms/blob/master/lib/LMSDocuments/LMSHtmlDocument.php#L44
zastapić:
```php
ConfigHelper::getConfig('directories.sys_dir', '', true)
```
przez:
```php
SYS_DIR
```

**Comment by interduo** [comment]
Tak zrobiłem, trzeba było jeszcze usunąć ")" w linijce niżej. 
Błąd się nie wyświetla już. 

Niestety w samym już HTMLu jest:
<title>::: LMS : Dokument kasowy nr 0003/10/2016 :::</title>
<style type="text/css"></style>
</head>

**Comment by chilek** [comment]
A możesz pokazać wiersz kodu po modyfikacji?

**Comment by interduo** [comment]
$this->smarty->assign('css', file(SYS_DIR)
                        . DIRECTORY_SEPARATOR . 'img' . DIRECTORY_SEPARATOR . 'style_print.css');

**Comment by chilek** [comment]
Tak myślałem, że źle zrobiłeś.
Przecież to cały plik z pełną ścieżką musi być parametrem wywołania file()...

**Comment by interduo** [comment]
Kazałeś tak zrobić to tak zrobiłem.

To jest świeża instalacja LMS, da się zrobić żeby to działało od razu po instalacji?

**Comment by chilek** [comment]
> Kazałeś tak zrobić - to tak zrobiłem ;)

No niestety nie zrobiłeś tak jak napisałem, ale zakładam, że teraz już poprawiłeś jak należy i działa?
Jeśli działa to mogę to puścić commitem do master...

**Comment by interduo** [comment]
Możesz puszczać. Działa.

**Comment by interduo** [comment]
Puścisz commita i zamkniesz zgłoszenie?:)

**Comment by interduo** [comment]
Puścisz commita i zamkniesz zgłoszenie?:)
