### ISSUE TITLE
cannot connect to database

### ISSUE THREAD

**Issue by cyberavis** [lmsgit/lms#955]
Przy ładowaniu LMS w przeglądarce dostaje błąd
`Fatal error: cannot connect to database!`
apache2 error.log:
`[date] [:error] [pid 13110] [client x.x.x.x] PHP Warning:  Unknown config variable "type" in section "database"! in /var/www/lms/index.php on line 94`

To jest najnowsza wersja z git.
Czy czegoś nie doinstalowałem czy gdzieś jest błąd?

**Comment by prezeskk** [comment]
A co masz ustawione w lms.ini w sekcji database?
type może być mysql/mysqli lub postgres

**Comment by interduo** [comment]
Na czystej instalacji nie mam tego błędu (postgres).

**Comment by cyberavis** [comment]
Database driver type
`type Default: mysql`
więc nic nie ustawiałem - bo używam właśnie mysql

podobnie z localhost
`host Default: localhost`

Ale o dziwo dopiero po wpisaniu tych dwóch wartości
```
type = mysql
host = localhost
```
zaczyna działać.
Więc coś jest nie tak z wartością default.
Dziękuję za sugestie.
