### ISSUE TITLE
Wcięcia w kodzie - spacja czy tabulator? 

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#962]
Zajawka:
https://www.youtube.com/watch?v=SsoOG6ZeyUI

Słowem wstępu:
http://programmers.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e

**Jaki standard jest/będzie preferowany w LMS?**

**Comment by chilek** [comment]
Ja używałem, używam i będę używał tabulatorów. Nie wiem po co ktoś wymyśla koło na nowo
jak już dawno grupa ludzi opracowała standardy kodowania.
Niech mnie ktoś przekona, że stosowanie wcięć w postaci spacji jest szybsze, wydajniejsze, etc.
Znam PSR-*, który mówi, że tak powinno się dla php robić, ale mi akurat podoba się formatowanie kodu z kernela linuksowego ;-)

**Comment by kyob** [comment]
Ja także jestem za tabulatorem. Tymbardziej, że tabulator można dostosować pod siebie.

**Comment by interduo** [comment]
Dobra rozgrzewka brzucha z rana :)

**Comment by noyo-pl** [comment]
Przykre bo finał tego związku w serialu nie był happy end.
Ja jestem za tym i za tym zależy od potrzeby.
Choć przyznam, że spacja jest bardziej uniwersalna.

**Comment by kyob** [comment]
Ja używam głównie [NetBeans IDE](https://netbeans.org/) i tam można dowolnie zdefiniować długość wcięcia i czy ma być w formie spacji lub tabulatora. Także jak będzie coś ustalone wprowadzam dane i cała robotę robi IDE.

Generalnie jest problem z typu mało istotny, ale może warto przyjąć jakiś standard :)

**Comment by interduo** [comment]
Ja wolę tabulatory:
- niższy filesize
- ładniej to wygląda

**Comment by chilek** [comment]
@interduo: a jak mniejszy filesize to i kompilacja szybsza w tym przypadku ;-)

**Comment by interduo** [comment]
Chyba wybór jest tak mało ważny, że na prawdę ten issue nadaje się po to by pośmiać się tylko z rana.

**Comment by kyob** [comment]
Reasumując do wcięć stosujemy tabulator, albo **dopłata** do abonamentu miesięcznego.
Tutaj proponuję prosty przelicznik **1 zł za** każdą zbędną **spację** wprowadzoną do projektu.
Tym samym można zamknąć problem wcięć :)

**Comment by interduo** [comment]
Issue zamyka zgłaszający lub admin.

**Comment by kyob** [comment]
Zamykam, ale pamiętać o tabulacji :)
