### ISSUE TITLE
Pytanie o generowanie faktur

### ISSUE THREAD

**Issue by noyo-pl** [lmsgit/lms#963]
Do generowana faktur są dwa pliki lms-payments i lms-payments.php, którego używać? Jest jakaś różnica w wyniku uruchomienia skryptu?
Do tej pory używałem lms-payments.
Jaki jest sens dodawania wpisu cash przy generowaniu faktur gdy klient ma status ustawiony na podłączony oraz odznaczone w zobowiązaniu "z fakturą" ?

**Comment by chilek** [comment]
lms-payments.php

**Comment by interduo** [comment]
Klientowi może zmienić się saldo bez dokumentu finansowego (kp/kw/faktura/paragon), więc jest sens.

**Comment by noyo-pl** [comment]
A jest jakaś możliwość bez modyfikacji skryptu generującego, aby nic nie dodawało?
Można zmienić klientowi status na oczekujący i wtedy nie bierze go pod uwagę, ale to nie do końca to.

@chilek a co w skrypcie php jest rewolucyjnego? czy po prost perlowy nie jest rozwijany

**Comment by chilek** [comment]
perlowy nie jest rozwijany - jedynie poprawki. w php dochodzą nowe rzeczy, np. z ostatnich - związane z generowaniem obciążeń za  rozmowy telefoniczne.

**Comment by noyo-pl** [comment]
ok dzięki wielkie za odpowiedź
