### ISSUE TITLE
Moduł "/?m=documentadd"

### ISSUE THREAD

**Issue by greenlms** [lmsgit/lms#971]
**1)**
Czy możecie potwierdzić, czy u Was też występuje taki problem.

Wejście na "Dodaj nowy dokument" (_**/?m=documentadd**_).
Przy wybieraniu klienta z listy przewijanej, nie przenosi wybranego na liście numeru ID klienta do pola "ID klienta: ".

---

**2)**
Przy okazji: Tomku, czy w tym formularzu mógłbyś dodać coś na wzór:
`'form_title' => 'Umowa abonencka',`
tylko o dodatkowych nazwach, np.
`'document_fromdate' => date("Y/m/d", mktime(0, 0, 0, date("m")+1, 1, date("Y"))),`
`'document_todate' => '',`
`# powyżej każdy sobie wstawi wg jakich zasad tworzy umowy lub inne dokumenty`
i automatycznie wstawiać to do pola _fromdate_ i _todate_? Była by to super pomocna rzecz (i myślę b. łatwa do wdrożenia dla Ciebie).

---

**3)**
Proponowałbym inną kolejność wprowadzania danych:
1. Klient: lub ID klienta:  Szukaj »»»
2. Typ:  
3. Szablon: -zmienić nazwę "..wybierz szablon.." na "..wybierz szablon lub wyślij dokument.."
4. Wyślij do LMS gotowy dokument bez szablonu:
5. Tytuł:   - tutaj już wprowadza się samo na podstawie wybranego szablonu z możliwością edycji
6. Okres: od: - tutaj mogłoby wprowadzać się samo na podstawie wybranego szablonu z możliwością edycji, tak samo Okres: do:
7. Opis: - zwykle pole puste, ale można by też coś zaciągać z szablonu j.w.
8. Numer: - zwykle pole puste
9. Zatwierdzony:

**Comment by chilek** [comment]
> Czy możecie potwierdzić, czy u Was też występuje taki problem.
>
> Wejście na "Dodaj nowy dokument" (/?m=documentadd).
> Przy wybieraniu klienta z listy przewijanej, nie przenosi wybranego na liście numeru ID klienta do pola  "ID klienta: ".

Poprawione w **master** i **stable**.

**Comment by chilek** [comment]
> Przy okazji: Tomku, czy w tym formularzu mógłbyś dodać coś na wzór:
> 'form_title' => 'Umowa abonencka z dnia '.date("Y/m/d"),
> tylko o dodatkowych nazwach, np.
> 'document_fromdate' => date("Y/m/d", mktime(0, 0, 0, date("m")+1, 1, date("Y"))),
> 'document_todate' => '',
> i automatycznie wstawiać to do pola fromdate i todate? Była by to super pomocna rzecz (i myślę b. łatwa do wdrożenia dla Ciebie).

Nie w wersji stable, ale w rozwojowej mogłoby być coś takiego. Tylko co to miałoby dokładnie robić, bo jakoś nie widzę, żeby wszystkim odpowiadało wstawianie bieżącej daty w tytule umowy...

**Comment by chilek** [comment]
> Proponowałbym inną kolejność wprowadzania danych:
> 
> Klient: lub ID klienta: Szukaj »»»
> Typ:
> Szablon: -zmienić nazwę "..wybierz szablon.." na "..wybierz szablon lub wyślij dokument.."
> Wyślij do LMS gotowy dokument bez szablonu:
> Okres: od: - tutaj mogłoby wprowadzać się samo na podstawie wybranego szablonu z możliwością edycji, tak samo Okres: do:
> Tytuł: - tutaj już wprowadza się samo na podstawie wybranego szablonu z możliwością edycji
> Opis: - zwykle pole puste, ale można by też coś zaciągać z szablonu j.w.
> Numer: - zwykle pole puste
> Zatwierdzony:

Coś mi się wydaje, że część proponowanych zmian mogłaby być uniwersalna dla wszystkich, ale niektóre byłyby niepożądane w niektórych sieciach. Niech się inni wypowiedzą. Oczywiście zmiany pod tym kątem nie pójdą na pewno do stable.

**Comment by greenlms** [comment]
> > 'document_fromdate' => date("Y/m/d", mktime(0, 0, 0, date("m")+1, 1, date("Y"))),
> > 'document_todate' => '',

> Nie w wersji stable, ale w rozwojowej mogłoby być coś takiego. Tylko co to miałoby dokładnie robić, bo jakoś nie widzę, żeby wszystkim odpowiadało wstawianie bieżącej daty w tytule umowy...

Każdy ISP mógłby skonfigurować swoją datę, wg swoich potrzeb albo pozostawić pola puste ''.
Np. dla "protokołów uruchomienia usługi" będę akurat wpisywał datę jak w przykładzie po to, aby monter mógł szybciej wystawić taki dokument, czyli żeby nie musiał wpisywać tej daty ręcznie.

**Comment by interduo** [comment]
AD2: 
Uważam, za dobry scenariusz gdy:
pola 'from' i 'to', zostają uzupełniane w [CONTRACT-PROMO] już po wybraniu szablonu promocji oraz okresu obowiązywania umowy - tutaj powinno zostać jak jest czyli opcjonalnie. 

Nie mam nic przeciwko możliwości, żeby to było uzupełniane opcjonalnie z zaproponowanych przez Ciebie nagłówków.

AD3 :
Z tą kolejnością to aż tak bym nie mieszał. Jak przeniesiesz Tytuł dokumentu gdzieś na dół jak to będzie wyglądać? ...tak jest naturalnie

@greenlms : Proponuję w zamian. Czy gdyby podświetlć na ŻÓŁTO komórki pól, które są obowiązkowe do uzupełnienia i wstawił w środek napis "Wymagane do uzupełnienia". Czy byłoby to  wystarczające? 

Rozumiem, że chcesz pokazać Pani w biurze które pola ma po kolei wypełniać - ja jej bym powiedział wtedy w takim scenariuszu żółte.

**Comment by chilek** [comment]
> Uważam, za dobry scenariusz gdy:
> pola 'from' i 'to', zostają uzupełniane w [CONTRACT-PROMO] już po wybraniu szablonu promocji oraz > okresu obowiązywania umowy - tutaj powinno zostać jak jest czyli opcjonalnie.
>
> Nie mam nic przeciwko możliwości, żeby to było uzupełniane opcjonalnie z zaproponowanych przez > Ciebie nagłówków danego szablonu dokumentu.

**Comment by greenlms** [comment]
> AD2:
> Uważam, za dobry scenariusz gdy:
> pola 'from' i 'to', zostają uzupełniane w [CONTRACT-PROMO] już po wybraniu szablonu promocji > oraz okresu obowiązywania umowy - tutaj powinno zostać jak jest czyli opcjonalnie.

Ok, a są też inne dokumenty niż Contract-Promo. I właśnie do tych innych szablony najbardziej by przydała by się opcja z góry ustawionego _datefrom/dateto_.

> Nie mam nic przeciwko możliwości, żeby to było uzupełniane opcjonalnie z zaproponowanych przez Ciebie nagłówków danego szablonu dokumentu.

Ok, dzięki! 👍 

> AD3:
>  Z tą kolejnością to aż tak bym nie mieszał. Jak przeniesiesz Tytuł dokumentu gdzieś na dół jak to będzie wyglądać? ...tak jest naturalnie

A właśnie ta kolejność co jest obecnie to się nie sprawdza gdy wypełniasz od góry do dołu. No bo gdy klikasz "Nowy dokument" wypełniasz pierwsze pole z góry czyli **Tytuł**, po czym niestety jest on **nadpisywany** podczas wybrania szablonu. Czyli lepiej jakby Tytuł był wypełniany przez użytkownika dopiero PO wyborze szablonu (i przysłowiowa Pani w BOK też zobaczy, że już nie musi nic dopisywać, albo że właśnie może coś dodać od siebie).

Z uwagi na to, że są też inne dokumenty niż Contract-Promo - na przykład dokumenty o nazwie "wypowiedzenie umowy", "aneks", "zawieszenie usługi", "wezwanie do usunięcia ... w terminie ..."  - proponuję, aby daty _datefrom/dateto_ były skonfigurowane w template w pliku _info.php_.

> @greenlms : Proponuję w zamian: Podświetlenie na ŻÓŁTO komórki pól, które są obowiązkowe do uzupełnienia i wstawienie w środek napisu "Wymagane do uzupełnienia". Czy byłoby to wystarczające?

Naprawdę tylko zmiana kolejności będzie OK. To nikomu nie zaszkodzi a jedynie może pomóc: **czyli najpierw wybranie klienta, później szablonu, a dopiero Tytuł i Daty po wybraniu szablonu**. Proszę o poparcie tej zmiany.

**Comment by greenlms** [comment]
> Nie mam nic przeciwko możliwości, żeby to było uzupełniane opcjonalnie z zaproponowanych przez Ciebie nagłówków danego szablonu dokumentu.

@chilek: Ok, poproszę! dzięki :)

**Comment by interduo** [comment]
Gdybyś miał pola na żółto nie domyśliłbyś się które trzeba najpierw wypełnić?:)

**Comment by chilek** [comment]
A jeśli już mowa o takich rzeczach to chyba uniwersalny projekt wizualny byłby przydatny, który pola formularzy z atrybutem 'required' nieco inaczej by oznaczał wizualnie.

**Comment by interduo** [comment]
@greenlms nie wypełniasz kreatora pierwszy raz w życiu, znasz jego zachowania na pamięć. Myślę, że podświetlenie pół i automatyczna data na starcie sprawi, że wybierzesz to do trzeba bez pudła.

Pamiętaj proszę, że nie wszystkie dokumenty są z kreatorów.
