### ISSUE TITLE
Odsetki ustawowe

### ISSUE THREAD

**Issue by sq9mev** [lmsgit/lms#98]
Sugestia: Implementacja naliczania odsetek ustawowych.
- jak zamodelować?
- które z istniejących elementów LMS można wykorzystać
- integracja z Userpanel
- czyhające pułapki/zagrożenia
- aspekty prawne/formalne

Jeśli macie jakieś sugestie w tym temacie - z chęcią wysłucham, przymierzam się do jakiejś implementacji tego tematu, ale to moje początki w LMS, więc sugestie developerów będą b. mile widziane.

**Comment by marcinn** [comment]
> jak zamodelować?

zgodnie ze sztuką :)

> które z istniejących elementów LMS można wykorzystać

żadnych.

> integracja z Userpanel

js api np. via http+json

>  czyhające pułapki/zagrożenia

...

> aspekty prawne/formalne

można pogadać z naszymi księgowymi lub znaleźć innego eksperta dziedzinowego.

> Jeśli macie jakieś sugestie

dokumenty przenieść na zewnętrzny (pod)system z obsługą kont/sald, zintegrować z nim faktury, odsetki liczyć w nowym (pod)systemie, wyłączyć wszelakie automaty wysyłki faktur w lms.

**Comment by sq9mev** [comment]
@marcinn frappant.
